### ISSUE TITLE
Add support for $replaceRoot aggregation stage

### ISSUE THREAD

**Issue by evanchooly** [MorphiaOrg/morphia#1000]
[JAVA-2287](https://jira.mongodb.org/browse/JAVA-2287)

**Comment by harrisonlingren** [comment]
+1

**Comment by nanangarsyad-mt** [comment]
Hi, is this feature got implemented yet?

**Comment by evanchooly** [comment]
Not yet.  I'm focusing on getting 1.5.0 out which is meant to both fix bugs and be a bridge to migrate to 2.0.0.  2.0.0 will move morphia on to modern driver artifacts and revamp the mapping code to be much more robust.  Once that's done, my plan is to focus on the aggregation API in 2.1.0.  I'll try to put up a `RoadMap.md` detailing all this.
