### ISSUE TITLE
Add options to $unwind 

### ISSUE THREAD

**Issue by evanchooly** [MorphiaOrg/morphia#1003]
[JAVA-1995](https://jira.mongodb.org/browse/JAVA-1995) 
[JAVA-1957](https://jira.mongodb.org/browse/JAVA-1957)

**Comment by daibertdiego** [comment]
Any news in this feature?

**Comment by evanchooly** [comment]
I'm still gathering up the threads after the handover and starting to work through the backlog.

**Comment by mweiczorek** [comment]
Any ETA on this? I found a workaround, but it would be nice if this were available.

**Comment by evanchooly** [comment]
I don't have an ETA at the moment.  I'm trying to wrap up 1.5 (which is all but done) so I can merge in the mapper updates/fixes for 2.0.  Then the plan is to focus on the aggregation API for a bit.  Right now 2.1 is looking to be largely driven by aggregation work.
