### ISSUE TITLE
add support for $sample

### ISSUE THREAD

**Issue by evanchooly** [MorphiaOrg/morphia#1006]
[JAVA-1937](https://jira.mongodb.org/browse/JAVA-1937)

**Comment by ankita-dhyani** [comment]
+1 any plans on releasing this feature ?

**Comment by r3tina** [comment]
Hi, any update on when this will be included in a release? That would save me updating my own fork :-)

**Comment by evanchooly** [comment]
I'm trying to clarify the plan with Mongo, myself...

**Comment by evanchooly** [comment]
fixed by #1081
