### ISSUE TITLE
Aggregation pipeline stages

### ISSUE THREAD

**Issue by evanchooly** [MorphiaOrg/morphia#1022]
1. $project
2. $match
3. $redact
4. $limit
5. $skip
6. $unwind
7. $group
8. $sample
9. $sort
10. $geoNear
11. $lookup
12. $out
13. $indexStats

**Comment by bigggjimmm** [comment]
Hi !
Have a real trouble executing a pipeline 
class person{
private ObjectId id;
private String name;
}
class book{
private ObjectId id;
private String title;
}
class person_ownership{
private ObjectId id;
@Reference private person p; ( stored has DBREF )
@Reference private List<book> books; ( stored has list of  DBREFs )
}

AggregationPipeline aggr = DS.createAggregation(person.class);
Query<person> personFilter = DS.find(person.class);
personFilter.field("name").equal("james");

aggr.match(personFilter);

aggr.lookup("person_ownership", "id", "p.id", "ownership");
aggr.unwind("ownership");
aggr.unwind("ownership.books");

List<ObjectId> BOOKs = new ArrayList<ObjectId>();
BOOKs.add(ID_book1);BOOKs.add(ID_book2);BOOKs.add(ID_book3);

Query<book> queryBook = DS.createQuery(book.class) ;
queryBook.field("id").in(BOOKs);

Query<Object> query = DS.getQueryFactory().createQuery(DS);
query.field("ownership.books").elemMatch(queryBook );

aggr.match(query);
AggregationOptions opts = builder().outputMode(OutputMode.CURSOR).build();
Iterator<person> aggregate = aggr.aggregate(person.class, opts);

How (USING MORPHIA )to create a lookup and filter on fields found on the lookup collection?
Is aggr.lookup("person_ownership", "id", "p.id", "ownership"); correct ?
Do i need to output this using aggr.out(out_person.class, opts); ?
If so what about concurrent requests ? 

Please deliver me from this abyss !!!
