### ISSUE TITLE
Seems that Converters.getEncoder could be cached better?

### ISSUE THREAD

**Issue by niccottrell** [MorphiaOrg/morphia#1024]
Almost half the cpu time of `Mapper.toDBObject` in one of my batch functions is taken by `CustomConverers.getEncoder`. Since this batch is working with just a single class of Entity, it seems like this shouldn't need to be calculated each time. I only have a single subclass on TypeConverter in my code and it's not related to this entity. 

I see `tc.isSupported` called on every call of Converters.getEncoder(Object,MappedField). Couldn't tc be saved into tcMap prior to returning inside 

```
       for (final TypeConverter tc : untypedTypeEncoders) {
            if (tc.canHandle(mf) || (val != null && tc.isSupported(val.getClass(), mf))) {
                return tc;
            }
        }
```

Here's my JProfiler output:
<img width="896" alt="screen shot 2016-09-18 at 15 54 52" src="https://cloud.githubusercontent.com/assets/850094/18616336/4c4a0a30-7dba-11e6-9ac7-137ee865f1df.png">

This is as of Morphia 1.2.1

**Comment by evanchooly** [comment]
It actually gets worse:  `tc.canHandle(mf)` ends up calling `isSupported(mf.getType(), mf)` so it's essentially checking twice.  It's obvious there's a fair bit of clean up to do here.  :/

**Comment by evanchooly** [comment]
I'm not seeing anything super obvious to tackle at the moment but it occurs to me that much of this will be obviated by 2.0 which completely revamps how all this is done.  So for the moment, I'm going to kick this can down the road and see if it's still an issue post-2.0.  I think this issue will magically vanish for us with that transition.

**Comment by evanchooly** [comment]
This is all redone in 2.0 so I'm going to close this for now.
