### ISSUE TITLE
Asynchronous ensureIndexes() support

### ISSUE THREAD

**Issue by DigitalSmile** [MorphiaOrg/morphia#1035]
I have an application, which is connected to MongoDB and uses Indexes. I have added the ensureIndexes() call at application startup and it takes a lot of time (due to network latency) to send the command to MongoDB. My datastorage is not changing frequently, but I still want to be sure indexes are created inside (in case of DB failure or failover to another instance). So I cannot just remove this to speed up.

My question is - could we have an option to send the command in asynchronous way and not wait the operation to be completed in client side? This will affect the application startup significantly and provide more reliable way to operate the ensuring command.

**Comment by evanchooly** [comment]
can't you just call `datastore.ensureIndexes(true)` and build them in the background?

**Comment by DigitalSmile** [comment]
@evanchooly no, I can't. It forces me to wrap the call with threads (because current implementation just send the call to the server synchronously and all async work is in mongo side). That is not appropriate with my current configuration, as It is located inside the Guice module.
I believe, to be in sync with library architecture, the special async method should be available to start the process. Basically, I don't care about results, I assume the operation will succeed. If it fails, the log message could appear, but anyway it is not critical operation.

**Comment by evanchooly** [comment]
async operations might come someday but not today.
