### ISSUE TITLE
@PrePersist Called twice

### ISSUE THREAD

**Issue by Belkacem** [MorphiaOrg/morphia#1047]
This occurs when the annotated method is public in an inherited entity.

@Entity
abstract class BaseEntity {
    @PrePersist
    public void prePersist() {
        Logger.getAnonymousLogger().log(Level.INFO, "CALLING UPDATE TIME TWICE");
    }
}

Cheers,
B.R

**Comment by evanchooly** [comment]
Could not reproduce on `master`.  Perhaps this got cleaned up somewhere along the way.
