### ISSUE TITLE
Create an IteratorFactory similar to QueryFactory

### ISSUE THREAD

**Issue by rlodge** [MorphiaOrg/morphia#1075]
Similar to how Query is an interface and the QueryImpl class is basically only internal implementation and there is a factory on the Datastore for creating Query instances, it would be great to have MorphiaIterator and MorphiaKeyIterator to be interfaces with internal implementations with a factory interface on the Datastore to create them.  This would give users the option of adding functionality to the iterators without having to override and copy/paste a bunch of internal code.  (Our use case is gathering metrics from the iterators and sending them to graphite, but one could imagine other use cases).

**Comment by rlodge** [comment]
I'm fine with closing the PR in favor of waiting until after a major refactor, but I'd like this sort of thing kept in mind.  In the version we were previously using, we ended up extending a lot of private implementations to make things work the way we needed, and it would be really helpful to have some more extensibility in the whole framework so that it's more flexible.

For this specifically, I'm aware that the MorphiaIterator class has some methods for reading the performance.  We're using that data, but we want to automatically pass those pieces of data to an external metrics system when the iterator is closed or exhausted.  To do that I want to wrap the iterator and use the delegate pattern, and I want my datastore to use my new "wrapper" class whenever an iterator is created.  But iterators are created in a number of places, and to be able to wrap them globally we need to do something like extend QueryImpl (which is internal API we don't want to extend), and then extend MorphiaIterator, which has some private methods that we end up copy-pasting into the new class.  I wanted a way where I could build a delegate without having to extend the implementation class, and the only way to really do that without making a mess was to introduce a clean interface.

**Comment by evanchooly** [comment]
You should look in to the [monitoring](http://mongodb.github.io/mongo-java-driver/3.4/driver/reference/monitoring/) API in the driver.  I think it will simplify what you're trying to do.

**Comment by rlodge** [comment]
Not really.  It gives me the ability to register a global listener, which is useful, but doesn't give me the ability to summarize the statistics for each query in a particular call tree, which is something we do now.  Nor is monitoring the only use case; we have iterator implementations that ignore mapper errors for missing data, for instance.

**Comment by evanchooly** [comment]
I know this request has a long history.  But looking at how and what the iterator is now vs when this was filed, I'm not quite sure how to tackle it.  Morphia's iterator (`MorphiaCursor`) now is just an implementation of `MongoCursor` and there's just not that much there.  Most of the work is done by classes created by the driver.  Short of providing an explicit creator for this, subclassing, say, `DefaultQueryFactory` and providing an implementation that perhaps does some magic in the `iterator()` method on the `Query` it creates, I'm not sure what facilities Morphia could offer to help here.

I'm not opposed to the idea by any means.  It sounds like it could be terribly useful in certain scenarios.  I'm just not seeing the path from here to there just now.

**Comment by rlodge** [comment]
Given the changes, I don't feel like this is useful anymore.

**Comment by evanchooly** [comment]
Similar requests come up from time to time so if you run into something please let me know and we'll see if we can't work out a solution together.
