### ISSUE TITLE
Backport #961 to 1.2.x

### ISSUE THREAD

**Issue by d4nirod** [MorphiaOrg/morphia#1112]
@evanchooly: we're getting hit by #961 on 1.2.2, any chance to backport the fix?
See also #941

Thanks

**Comment by d4nirod** [comment]
ping @evanchooly

**Comment by d4nirod** [comment]
@evanchooly: so no love for this one?

**Comment by evanchooly** [comment]
Well, I've left MongoDB so my access isn't quite what it was.  While I'm still planning on contributing, etc. some of those decisions are no longer mine to make.

**Comment by jyemin** [comment]
Generally we don't backport bug fixes to previous minor releases.  What's preventing you from upgrading to 1.3.0?

**Comment by d4nirod** [comment]
The root cause it's actually a change in the driver API introduced in `r3.0.0`: [`ObjectId` was made final](https://github.com/mongodb/mongo-java-driver/commit/6fb1830a3dd42997efc4ed8068ec267c20a247be#diff-f7f229538ce532517ba2202d8aa1b244).

We're stuck with **Morphia `1.2.x` + MongoDB Java Driver `2.14.x`** until we can dedicate time and resources to refactor. It´s really non-trivial for us since we make extensive use of our own type-safe object ID class: `class EntityId<T> extends ObjectId` which we wouldn't be able to do after `r3.0.0`. More details including code samples in [in our Google groups discussion from a while ago](https://groups.google.com/d/msg/morphia/isndCXKISTQ/nvll2FMpAAAJ).

So as for the backporting request I know it might be a pain in the royal but, short of bypassing Morphia altogether and replacing the offending code with equivalent raw Java Driver statements, I´m running out of ideas.
