### ISSUE TITLE
Deprecate uses of MorphiaIterator and MorphiaKeyIterator

### ISSUE THREAD

**Issue by evanchooly** [MorphiaOrg/morphia#1142]
This mechanism will be much different in 2.x.  This issue will deprecate the two types themselves as well as all methods in the public API that expose them.  new methods will be introduced that return more appropriate driver types instead.

**Comment by amanchoudhary** [comment]
@evanchooly i have made changes where MorphiaIterator & MorphiaKeyIterator return types are removed from public APIs, and I have replaced it with Iterator<T> types in this pull request: https://github.com/mongodb/morphia/pull/1163/files

Please review this and let me know if any improvements are required in it.
Thanks in advance,
Aman
