### ISSUE TITLE
multi is not consistently set in DatastoreImpl update methods

### ISSUE THREAD

**Issue by ymmark0** [MorphiaOrg/morphia#1154]
In DatastoreImpl there are a number of update methods that support the createIfMissing argument.
I find that most of these methods leave multi=false (after updating to v 1.3.2), while one:

```
public <T> UpdateResults update(final Query<T> query, final UpdateOperations<T> operations, final boolean createIfMissing,
                                    final WriteConcern wc) {
```

sets multi to true.  
This behaviour (leaving multi=false by default) broke our code (although may not be specific to 1.3.2).  
I can update our code to pass an empty write concern, setting multi=true, and fix the problem, but I'm wondering if this is the correct behaviour?

**Comment by PhilJay** [comment]
I can confirm this issue.

`UpdateResults results = getDatastore().update(q, operations, false, null);`
Updates all documents matching the query.

`UpdateResults results = getDatastore().update(q, operations, false);`
Updates only the first document matching the query.

This does not seem like wanted behaviour. Is there any method / way to set the "multi = true" flag separately?

**Comment by mridang** [comment]
I've confirmed this too. This is a fairly serious issue as it changes the behaviour of the update ops.
