### ISSUE TITLE
Add nullable annotation for Kotlin 

### ISSUE THREAD

**Issue by MiguelAngelLV** [MorphiaOrg/morphia#1155]
Add nullable annotations will be very useful for Kotlin developers.

**Comment by evanchooly** [comment]
I applied `@NonNull` (from the driver) at the package level and then tweaked various methods as needed.  All looks relatively ok from the Java side of the world but I'm certainly open to refinement with feedback from a kotlin project.  I have one of my own that I'll try it out with as well.
