### ISSUE TITLE
@Property annotation fields could not support by Morphia order(String sort) method

### ISSUE THREAD

**Issue by leeaee** [MorphiaOrg/morphia#1158]
Bean entity with org.mongodb.morphia.annotations.Property like:
```java
    @Property("login_name")
    public String loginName;
```
Input order string "loginName", the sort not effect. and input order string "login_name", it worked.
I think morphia need to recognize the input string "loginName" and mapping to "login_name"

**Comment by thuglnx** [comment]
Hi @leeaee! 
I think different, if field is annotated, it recognize only annotation's value.

**Comment by evanchooly** [comment]
Works as intended.
