### ISSUE TITLE
Huge amounts of "Found more than one class mapped to collection" logging

### ISSUE THREAD

**Issue by plaa** [MorphiaOrg/morphia#1164]
I just upgraded our Morphia version from 1.2.1 to 1.3.2 and am seeing huge amounts of log created by Morphia.

The excess log lines are:

    2017-05-10 13:11:10.435 | INFO  | org.mongodb.morphia.mapping.Mapper       |Found more than one class mapped to collection 'Profile'[MappedClass - kind:Profile for com...domain.Profile fields:[], MappedClass - kind:Profile for com...domain.ProfileImpl fields:[ ... 3kB of stuff ... ]]

What it reports is that it found two classes for the collection: The first is an interface, the other the only implementation for that interface.  By looking at the source (Mapper.getClassFromCollection) I would assume that the method shouldn't return the interface, so it looks like a bug to me.

It may be related to the fact that Profile is a lazy-loaded reference from another entity.  I haven't seen the output with any other entity types.  Maybe the interface is the proxy class?

The code itself seems to work correctly, even though to my understanding the getClassFromCollection currently returns the interface class (since it's listed first in the log output).

As each log line is about 3kB of stuff, this adds hugely to our server log.  I can disable INFO logging for Morphia, but this seems to indicate a bug in the Mapper logic itself.

**Comment by zebgun** [comment]
Experiencing the same thing when using a lazy reference on an abstract class.  I've been using 1.3.2 for a while and only started getting error when I added an `@Embedded` class with a property with `@Reference(lazy=true)`.  Setting `@Reference(lazy=false)` fixes the problem however I would like to keep it lazy.


```
// Morphia v1.3.2 - fails when lazy=true resulting in
// error 'Found more than one class mapped to collection...'
@Embedded
public class A {
  @Reference(lazy=true)
  private B b;
}

@Entity("b")
public abstract class B {}

@Entity("b")
public class B1 extends B {}

@Entity("b")
public class B2 extends B {}

```

**Comment by evanchooly** [comment]
There's not much to be done about how often that gets logged.  At least not at this stage in 1.x's life but I reduced the amount that gets logged at least.  You're right.  That's an insane amount to log.  I already reduced the log level to `warn` so that might make it easier for you to filter/configure away.
