### ISSUE TITLE
Get distance on geo queries?

### ISSUE THREAD

**Issue by heyarny** [MorphiaOrg/morphia#1166]
Is there a way to get the distance from the returning results when using $near and similar?
I don't see a way right now.

**Comment by danielreuterwall** [comment]
Hey @heyarny,

Have you found a solution on this yet? I've got the same issue.

**Comment by heyarny** [comment]
@danielreuterwall no, I did it with the mongodb driver and QueryBuilder.
Then converted the results to my own Java objects with jackson.

**Comment by danielreuterwall** [comment]
Cool, I'll give it a go! Thanks for the update.

**Comment by evanchooly** [comment]
I know this is way late but it's one of the last remaining items I'm trying to clear out before 2.0.  I'm not sure I'm understanding what you're wanting much less how to consider making it available.  Could you explain your problem and the workaround you used?  Thanks.

**Comment by evanchooly** [comment]
Ok.  I'm unsure what's actually being asked here so if new information comes to light we can take a look at it then.
