### ISSUE TITLE
NoSuchMethodError on createDatastore

### ISSUE THREAD

**Issue by scottbert** [MorphiaOrg/morphia#1168]
I just upgraded from an old morphia (0.107) to 1.3.2 - everything compiles OK but the code which was previously working fine is now failing with:
```Caused by: javax.ejb.CreateException: Initialization failed for Singleton DatastoreProvider
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:483)
	at com.sun.ejb.containers.AbstractSingletonContainer.access$000(AbstractSingletonContainer.java:81)
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:654)
	... 89 more
Caused by: java.lang.Exception: java.lang.NoSuchMethodError: org.mongodb.morphia.Morphia.createDatastore(Lcom/mongodb/MongoClient;Ljava/lang/String;)Lorg/mongodb/morphia/Datastore;
```
and I'm at a loss. I'm also pretty new to Java so apologies if there's something obvious that I've missed, but as far as I can see from the docs, this is the correct signature for that method?

Using `mongo-java-driver` v `3.4.2` and the latest mongodb

Code is roughly:

```java
import config;
import com.mongodb.MongoClient;
import org.mongodb.morphia.Datastore;
import org.mongodb.morphia.Morphia;

String dbHost = config.getMongoDbHost();
int dbPort = config.getMongoDbPort();
MongoClient mongoClient = new MongoClient(dbHost, dbPort);
Morphia morphia = new Morphia();
String database = config.getMongoDbName();
Datastore datastore = morphia.createDatastore(mongoClient, database);
```

**Comment by scottbert** [comment]
Having investigated a bit further, the change that breaks my code is introduced between 0.107 and 0.108 which are both really old versions (I inherited this API from someone else and am trying to bring it up to date) - I saw https://github.com/mongodb/morphia/issues/579 which I thought could be a candidate for what's up but I'm using a MongoClient not an instance of Mongo so I'm still a little confused

**Comment by evanchooly** [comment]
I'm afraid this question has aged out of a useful answer.  Hopefully it's been adequately resolved but I'm happy to help otherwise.  I apologize for the gap in activity.  I had been away for a while but came back to the project last year.
