### ISSUE TITLE
removeAll (pullAll) broken due to object mapping producing different order for the properties

### ISSUE THREAD

**Issue by agiannone** [MorphiaOrg/morphia#1170]
Objects no longer seem to be mapped with the properties in the same order in the new Morphia release so all instances of pullAll are now broken.

Any idea what changed the order in which the properties are mapped? Is there any way to roll this back?

**Comment by evanchooly** [comment]
I'm probably way too late for this but could you expand on the problem you're seeing?  I'm not sure I understand.
