### ISSUE TITLE
Add Projection $elemMatch support.

### ISSUE THREAD

**Issue by vknysh-axon** [MorphiaOrg/morphia#1171]
Projection's $elemMatch: 
https://docs.mongodb.com/manual/reference/operator/projection/elemMatch/
isn't supported by Morphia 1.3.2 version.

**Comment by sergey-alekseichenko-axon** [comment]
Yeeah! We **need** this!

**Comment by evanchooly** [comment]
This method already exists in 1.3:  org.mongodb.morphia.query.FieldEnd#elemMatch
