### ISSUE TITLE
Custom TypeConversion of non-iterable object to BasicDBList fails with ClassCastException

### ISSUE THREAD

**Issue by thimmwork** [MorphiaOrg/morphia#1177]
Hi everyone,
my entity is composed of a Map that uses a tuple as key, much similiar to a Map<Pair<String, String>, Object>.

I wrote a custom TypeConverter that maps the object to a mongodb data structure like this:
`[ {
    leftKey: x,
    rightKey: y,
    value: z
} ]`
where x and y are the Strings that are used as key to identify an entry in the Map.
Note that the mongodb data structure comes down to a list of entries which btw turns out to be a useful pattern when dealing with data that has multi-attribute keys.
In my particular use case, the Object z that represents the value is a complex object itself, but this is not relevant to the issue.

My problem is that Morphia tries to cast the Map to Iterable when mapping to a DBObject. This occurs when it's trying to figure out whether or not to remove the class indicator. The issue only occurs when mapping to a list.
`java.lang.ClassCastException: net.thimmwork.test.MasterCodeMap cannot be cast to java.lang.Iterable
    at org.mongodb.morphia.mapping.Mapper.extractFirstElement(Mapper.java:797)`

I'll add a full test case soon.

**Comment by evanchooly** [comment]
Missing reproduction details.  If this is still a problem please file an issue with a reproducer and I'll see what I can do.  Thanks.
