### ISSUE TITLE
mapPackage("path.to.models") fails with Play2 framework (class not found)

### ISSUE THREAD

**Issue by StanislavLapitsky** [MorphiaOrg/morphia#1182]
final Morphia morphia = new Morphia();
morphia.mapPackage("path.to.models"); //<--- class not found here

The problem is internal call line #243

    public synchronized Morphia mapPackage(final String packageName, final boolean ignoreInvalidClasses) {
        try {
            for (final Class clazz : ReflectionUtils.getClasses(packageName, mapper.getOptions().isMapSubPackages())) {
                try {

because ReflectionUtils.getClasses uses current thread's class loader

    public static Set<Class<?>> getClasses(final String packageName, final boolean mapSubPackages) throws IOException,
            ClassNotFoundException {
        final ClassLoader loader = Thread.currentThread().getContextClassLoader(); //<---------
        return getClasses(loader, packageName, mapSubPackages);
    }

But Play2 framework loads classes on fly and thread's class loader is wrong in this case.

Added a fix locally

        final Morphia morphia = new Morphia() {
            //The method overrides default one because of default uses Thread class loader and therefore cannot find
            //entities (mapPackage failed).
            @Override
            public synchronized Morphia mapPackage(final String packageName, final boolean ignoreInvalidClasses) {
                try {
                    for (final Class clazz : ReflectionUtils.getClasses(this.getClass().getClassLoader(), packageName, false)) {
                        try {
                            final Embedded embeddedAnn = ReflectionUtils.getClassEmbeddedAnnotation(clazz);
                            final Entity entityAnn = ReflectionUtils.getClassEntityAnnotation(clazz);
                            final boolean isAbstract = Modifier.isAbstract(clazz.getModifiers());
                            if ((entityAnn != null || embeddedAnn != null) && !isAbstract) {
                                map(clazz);
                            }
                        } catch (final MappingException ex) {
                            if (!ignoreInvalidClasses) {
                                throw ex;
                            }
                        }
                    }
                    return this;
                } catch (IOException | ClassNotFoundException e) {
                    throw new MappingException("Could not get map classes from package " + packageName, e);
                }
            }
        };

So it seems reasonable to change the call  with passing current class' ClassLoader

**Comment by niccottrell** [comment]
It doesn't look like there's a great way to do this without requiring a big external library (See [StackOverflow](https://stackoverflow.com/questions/520328/can-you-find-all-classes-in-a-package-using-reflection))

You can manually list your classes. It's more explicit and performant anyway:
```
     morphia = new Morphia();
     morphia.map(Example1.class)
          .map(Example2.class)
          .map(Example3.class);
```

**Comment by StanislavLapitsky** [comment]
Actually the fix is to pass proper ClassLoader. All the rest remains. 
public synchronized Morphia mapPackage method already uses ReflectionUtils.getClasses(...) as it was stated above. Just pass classloader of current class to suppress default thread's classloader.

**Comment by niccottrell** [comment]
When you say "current class" you mean any class from your project/application? It doesn't need to be one of the annotated Morphia classes?

**Comment by StanislavLapitsky** [comment]
No. No need to use annotated class. In the code above
ReflectionUtils.getClasses(**this.getClass().getClassLoader()**, packageName, false))

**Comment by neon-dev** [comment]
The same issue (class not found) happens if you use Morphia in a [Wildfly Swarm](http://wildfly-swarm.io/) environment.
When starting the project via `mvn wildfly-swarm:run` you can achieve successful mapping by passing the parent classloader of the current classes classloader to ReflectionUtils and then load the found class by the current classloader, like so:
```
Collection<Class<?>> classes = ReflectionUtils.getClasses(getClass().getClassLoader().getParent(), packageName, morphia.getMapper().getOptions().isMapSubPackages());
for (Class clazz : classes) {
  Class<?> classLoadedByCurrentClassLoader = classLoader.loadClass(clazz.getName()); // otherwise annotations cannot be found
  Embedded embeddedAnn = ReflectionUtils.getClassEmbeddedAnnotation(classLoadedByCurrentClassLoader);
  Entity entityAnn = ReflectionUtils.getClassEntityAnnotation(classLoadedByCurrentClassLoader);
  boolean isAbstract = Modifier.isAbstract(classLoadedByCurrentClassLoader.getModifiers());
  if ((entityAnn != null || embeddedAnn != null) && !isAbstract) {
    morphia.map(classLoadedByCurrentClassLoader);
  }
}
```

Unfortunately, this only works when running via the maven goal. Starting a fat jar generated by `mvn wildfly-swarm:run` via `java -jar project-swarm.jar`, I could not find a way to make it work. No classloader in the getParent() chain seems to know the package. Or at least ReflectionUtils cannot find anything in there. I did not debug it so I cannot say which one is the case.

**Comment by neon-dev** [comment]
I've debugged a bit and found this out:
When running a swarm.jar, ReflectionUtils.getClasses searches for classes on a `filePath` called `/content/project.war/WEB-INF/lib/project_commons-1.0-20180413.133035-185.jar/com/example/model/mongo/entity/`.
As you can see, the entitiy classes are inside a .jar inside the .war, which should be located inside the project-swarm.jar (fat jar). I have no idea where to find `/content` to begin with. It shouldn't even be a system path.
There is `/_bootstrap/project.war`inside the fat jar, containing what is searched for, so a working `filePath` would most likely look something like `/wherever/project-swarm.jar!/_bootstrap/project.war/WEB-INF/lib/project_commons-1.0-20180413.133035-185.jar/com/example/model/mongo/entity/`.
I don't know the inner workings of the swarm ecosystem, so I hope the limited info I found out is enough to help you finding a solution.
