### ISSUE TITLE
Mapping ArrayList<ArrayList<Integer>> fails

### ISSUE THREAD

**Issue by nimrodgans** [MorphiaOrg/morphia#1183]
The Java Driver perfectly maps this into Array of Array of ints but Morphia fails doing so...
Adding the exception:

> Exception in thread "main" org.mongodb.morphia.mapping.MappingException: Error mapping field:nimrodpasha.cinema.objects.Screening.Seats
> 	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:984)
> 	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:593)
> 	at org.mongodb.morphia.DatastoreImpl.entityToDBObj(DatastoreImpl.java:1362)
> 	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1282)
> 	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:775)
> 	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:758)
> 	at nimrodpasha.cinema.dao.DataAccessObject.CreateOne(DataAccessObject.java:31)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
> 	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> Caused by: java.lang.IllegalArgumentException: BasicBSONList can only work with numeric keys, not: [className]
> 	at org.bson.types.BasicBSONList._getInt(BasicBSONList.java:168)
> 	at org.bson.types.BasicBSONList._getInt(BasicBSONList.java:160)
> 	at org.bson.types.BasicBSONList.removeField(BasicBSONList.java:117)
> 	at org.mongodb.morphia.mapping.EmbeddedMapper.writeCollection(EmbeddedMapper.java:243)
> 	at org.mongodb.morphia.mapping.EmbeddedMapper.toDBObject(EmbeddedMapper.java:90)
> 	at org.mongodb.morphia.mapping.Mapper.writeMappedField(Mapper.java:876)
> 	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:982)
> 	... 15 more

my "Screening.Seats" is ArrayList<ArrayList<Integer> as said the in headline

**Comment by nimrodgans** [comment]
Ok, for future knowledge, after marking the ArrayList<ArrayList<Integer>> as @Property it worked!!!!
I was about to give up!

**Comment by nimrodgans** [comment]
So I've tried updating a document with an ArrayList<ArrayList<Integer> item, but the mapper fails!
The arraylist of arraylist is being converted to BasicDBList<BasicDBList<Integer>> and then the Mapper tries to remove the ClassName field from each of the first List items! BUT, each of the inner items is a list itself. Since BasicDBList extends DBObject it tried to remove the field but he uses the key "ClassName" which isn't int (the required field type for removing item from BasicDBList).
Boom, IllegualArgumentException.
Code snipped from the problematic part:
`} else {
            mappedValue = toMongoObject(value, EmbeddedMapper.shouldSaveClassName(value, mappedValue, mf));
            if (mappedValue instanceof BasicDBList) {
                final BasicDBList list = (BasicDBList) mappedValue;
                if (list.size() != 0) {
                    if (!EmbeddedMapper.shouldSaveClassName(extractFirstElement(value), list.get(0), mf)) {
                        for (Object o : list) {
                            if (o instanceof DBObject) {
                                ((DBObject) o).removeField(CLASS_NAME_FIELDNAME);
                            }
                        }
                    }
                }`

As a fix id suggest iterating on the list children, and if the child is a list itself keep iterating! and dont remove nonexisting field :(



As a solution (I dont have the t

Line

**Comment by evanchooly** [comment]
This might not matter now but this works as far as I can tell.  see  [this test](https://github.com/MorphiaOrg/morphia/blob/b35fb2d7c7802d4fe0bf1f82c45b5022f57166bc/morphia/src/test/java/dev/morphia/mapping/NestedMapsAndListsTest.java#L27) as an example.

If that test doesn't cover your case, please open a new issue with your sample entity or, better yet, publish a [reproducer](https://github.com/MorphiaOrg/reproducer) so I can run it directly and I'll see what I can track down for you.
