### ISSUE TITLE
find.near(point) query throws NPE in Kotlin

### ISSUE THREAD

**Issue by mohammadrafigh** [MorphiaOrg/morphia#1185]
it seems Morphia uses the references of the passed "Point" parameter to the near function (and other similar functions), but in Kotlin all function parameters are passed by value not reference so there is no way to use it in Kotlin. Kotlin forces this behaviour to prevent changes on function parameters (which is generally a bad practice).

so for now I used DBObject to handle my query but it would be great to see a fix on this.

**Comment by niccottrell** [comment]
Sorry - I don't know Kotlin but my understanding is that parameters are the equivalent of `final` in Java. Morphia doesn't modify the `Point` object, so I don't see why this would be a problem. Can you include an example? Also, did you try it? Did you get an error?

**Comment by mohammadrafigh** [comment]
sorry I'm not working on that part of project anymore so I can't provide an example right now. but as I mentioned in title yes I got NPE.
