### ISSUE TITLE
Stream support

### ISSUE THREAD

**Issue by heruan** [MorphiaOrg/morphia#1189]
It would be great to be able to get a `java.util.Stream` of a collection and being able to filter, sort, skip, limit, map and collect automatically with optimized queries.

I understand this is huge but it's being accomplished in other frameworks, e.g. [Speedment](https://www.speedment.com/developers/) and I'd love to have this in Morphia.

**Comment by chenchenyangll** [comment]
upvote

**Comment by evanchooly** [comment]
I'm not promising anything but I'll schedule it for investigation in 2.2.

**Comment by pioorg** [comment]
Hi!
Actually I've been using Morphia with Streams for quite a while. It requires one extra line, but this goes back to Java 'why `Iterable` has no `stream()` method'.
Here it comes:
`Query<Example> query = datastore.find(Example.class);
Stream<Example> stream = StreamSupport.stream(query.spliterator(), false);`
Therefore I'm not sure if this really worth the effort. I mean: there are reasons why e.g. we have to call a `stream()` on a list...

**Comment by evanchooly** [comment]
On the other, that's a very simple, convenient, and useful method to add.  It would mirror `iterator()` on `Query`.  And I'm looking for quick and easy tonight.  :)
