### ISSUE TITLE
Query : not able to get existing options & modify them for maxTime and readPreference

### ISSUE THREAD

**Issue by nmayakuntla** [MorphiaOrg/morphia#1190]
We have a library which takes in org.mongodb.morphia.query.Query as the input parameter.

1. In the application, they set following on query object

query.order(sortyBy)

2. Library gets the query object and internally based on configuration needs to set
    maxTime
    readPreference

    Query itself does not have setters for this, which means have to create new options object in step 2 and the values set in step 1 is lost. 

Instead if i get the options from step 1 and then add other options in step 2, that would work.

But how do i get the options from query object?

Thanks in advance.

**Comment by nmayakuntla** [comment]
When methods which take options as a parameter get called ( such as public List<T> asList(final FindOptions options) { )
shouldn't it merge the options already set in its private member variable (options) with the method parameter options
Or
provide a getter to access options member variable

**Comment by evanchooly** [comment]
2.0 cleans up this API (because I agree it's terribly awkward) so I'm going to close this one.  I'm hoping for 2.0 alpha/beta releases soon.  If that API still needs some work, please file an issue against 2.0.
