### ISSUE TITLE
Tracking changed state of object to avoid unnecessary round trips?

### ISSUE THREAD

**Issue by niccottrell** [MorphiaOrg/morphia#1192]
Is there any tracking of an objects state once it is loaded from Morphia? I.e. do we keep the initial BSON data so that we could do a diff on the current fields vs the loaded state with some sort of `isChanged(obj)` call? In my use case that would be useful to check before calling `coll.save(obj)` to avoid the full round trip to the server.

**Comment by evanchooly** [comment]
I know this is an old question, but no there isn't support for dirty state tracking in morphia.  Hibernate has something like this and it's terribly complicated to do.  There aren't any plans currently to support it in Morphia.
