### ISSUE TITLE
Missing compatibility table with mongo-driver versions

### ISSUE THREAD

**Issue by niccottrell** [MorphiaOrg/morphia#1196]
Maybe the installation guide page should contain a note on which version of the mongo-driver is required? I realise that maven should take care of it, but for those downloading jar files manually it might be useful to quickly see which version of Morphia works with which drivers.

**Comment by pcompieta** [comment]
I also think that Projects' description should briefly report when a change in the driver version will be introduces (i.e. when support for MongoDB 3.6 will be introduces..)

**Comment by evanchooly** [comment]
I'm actually working on that integration now and rebuilding the mapping on top of the pojo codec code in the driver.  You can follow my progress [here](https://github.com/evanchooly/morphia/tree/driver36).  It's rather large changeset at the moment...

**Comment by evanchooly** [comment]
I want to completely revamp how the docs are done in 2.0 and will try to incorporate these details there.  in the meantime, you can see what versions are being tested on [travis](https://github.com/MorphiaOrg/morphia/blob/master/.travis.yml#L13).
