### ISSUE TITLE
Projection Morphia

### ISSUE THREAD

**Issue by ronoel** [MorphiaOrg/morphia#1198]
Hey guys!

Is there a simple way to map which fields I want to project in MongoDB?

I looked for it, as I haven't found I created my own solution.
https://github.com/ronoel/morphiaprojection

If there is no issue to use this solution, is it possible to add in the Motphia's project?

Thanks!

**Comment by evanchooly** [comment]
org.mongodb.morphia.query.Query#project(java.lang.String, boolean)

**Comment by ronoel** [comment]
Hi evanchooly, I used it, but I was looking for something like an annotation to map the fields. There are situations that I would like to create a view for users with specific permissions or for a report, but I would like to have a easy way to refactor.

I used the following approach:

```
public class Foo {
    @ProjectView(name = {"View1","View2"})
    @Id
    private Long id;

    @ProjectView(name = "View1")
    private String name;
    
    private Integer age;
    ...
```

**Comment by evanchooly** [comment]
I know this is super old but I'm trying to clear out the back log and resolve what I can.  Are the views in the recent versions of mongodb suitable for what you need?

**Comment by ronoel** [comment]
The approach that I described above was good enough to solve my problem. I wanted to load only a few fields of my collection instead load the whole document. I was wondering if my aproach could be a good feature to add to Morphia.

**Comment by evanchooly** [comment]
I have been giving it some thought lately.  I know JPA supports such a
notion.  I'm curious if it would just easier to use views though as they'd,
hopefully, require no code changes.

**Comment by ronoel** [comment]
Views require more code, you need to create and map it. For my needs at that time, the approach above fit better because I just needed to choose which projection that user has permission to see. But if any other user needed this feature, maybe its not so useful to add to the code.
