### ISSUE TITLE
Add support for array filters for update

### ISSUE THREAD

**Issue by niccottrell** [MorphiaOrg/morphia#1209]
See related [Java issue](https://jira.mongodb.org/browse/JAVA-2552) in JIRA and [use cases from core server](https://jira.mongodb.org/browse/SERVER-1243).

**Comment by niccottrell** [comment]
I'm thinking a new method to UpdateOperations called 

```
    arraySet(String pattern, Object newValue, ArrayFilter filters...)`
```

giving something like:

```
UpdateOperations<Root> op = ds.createUpdateOperations(Root.class)
                .arraySet("a.$[i]", newValue, new ArrayFilter("i", position);
```

or

```
UpdateOperations<Root> op = ds.createUpdateOperations(Root.class)
                .arraySet("a.$[i].c.$[j].d", 2, new ArrayFilter("i.b", 0), new ArrayFilter("j.d", 0));
```

but I'm a bit stuck on how to elegeantly handle

```
db.coll.update({}, {$set: {“a.$[i]”: 2}}, {arrayFilters: [{$or: [{i: 0}, {i: 3}]}]})
```

Maybe a helper ```ArrayFilter.or(new ArrayFilter(i,0), new ArrayFilter(i,3))``` ?

**Comment by niccottrell** [comment]
Note to self: add tests for {multi:true} and not.

**Comment by niccottrell** [comment]
Also need support for stuff with more complex conditions from [the docs](https://docs.mongodb.com/master/reference/operator/update/positional-filtered/index.html#position-nested-arrays-filtered) like
```
db.students2.update(
   { },
   { $set: { "grades.$[elem].mean" : 100 } },
   {
     multi: true,
     arrayFilters: [ { "elem.grade": { $gte: 85 } } ]
   }
)
```

**Comment by fa-at-pulsit** [comment]
any news about this issue ?

**Comment by evanchooly** [comment]
I've picked this one up three times now only to set it back down.  I'm not exactly sure how that API should look (especially when trying to be consistent with the 2.0 CRUD API changes).  I think i'll bump this to 2.1 because I want to pull all the agg stuff from 2.1 here instead.

**Comment by Javabien** [comment]
Looking forward to this feature!
