### ISSUE TITLE
update in DatastoreImpl is not multi anymore

### ISSUE THREAD

**Issue by gaspardpetit** [MorphiaOrg/morphia#1210]
I commented on https://github.com/mongodb/morphia/commit/00143b8d3164b14d4e1c31aa520b1f9955cafd35

The changelist changed `<T> UpdateResults update(Query<T> query, UpdateOperations<T> operations, boolean createIfMissing);` while similar update method use a multi update, this one does not. I do not believe this is intentional since one could use updateFirst to do a non-multi update.

**Comment by Chatom** [comment]
Issue duplicates this one #1154
