### ISSUE TITLE
Query using elemMatch fails when elemMatch-query does specify some restrictions

### ISSUE THREAD

**Issue by RovoMe** [MorphiaOrg/morphia#1213]
We have a scenario where we have 2 collections, i.e. `documenttype` and `custom-script-action` where a custom-script references a respective document and we want to retrieve the container collection (`custom-script-action`) based on a given sample of one of its contained entities (`documenttype`). 

The `documenttype` collection contains only two entries: 

```
/* 1 */
{
    "_id": ObjectId("5a1701e5df011141f5a0031e"),
    "documentId": "1",
    "mimetype": "XML",
    ...
},
/* 2 */
{
    "_id": ObjectId("5a1701e5df011141f5a0031f"),
    "documentId": "2",
    "mimetype": "XML",
    ...
}
```

The `custom-script-action` collection references `documenttypes` like this:

```
/* 1 */
{
    "_id" : ObjectId("5a1701e5df011141f5a00320"),
    "uuid": "4fd05d4a-6671-42b9-80b8-ee27d2c66414",
    "documents" : [ 
        {
            "$ref" : "documenttype",
            "$id" : ObjectId("5a1701e5df011141f5a0031e")
        }
    ],
    "sender": {
        "$ref" : "company",
        "$id" : ObjectId("5a1701e5df011141f5a00317")
    },
    ...
},
/* 2 */
{
    "_id" : ObjectId("5a1701e5df011141f5a00321"),
    "uuid": "fc5f0ee7-13f7-40b9-baf8-c0325c3ffe10",
    "documents" : [ 
        {
            "$ref" : "documenttype",
            "$id" : ObjectId("5a1701e5df011141f5a0031f")
        }
    ],
    "sender": {
        "$ref" : "company",
        "$id" : ObjectId("5a1701e5df011141f5a00318")
    },
    ...
},
/* 3 */
{
    "_id" : ObjectId("5a1701e5df011141f5a00322"),
    "uuid": "d70c1655-04e3-42a3-838b-a0625d30b9d6",
    "documents" : [ 
        {
            "$ref" : "documenttype",
            "$id" : ObjectId("5a1701e5df011141f5a0031e")
        }, 
        {
            "$ref" : "documenttype",
            "$id" : ObjectId("5a1701e5df011141f5a0031f")
        }
    ],
    "sender": {
        "$ref" : "company",
        "$id" : ObjectId("5a1701e5df011141f5a00319")
    },
    ...
},
/* 4 */
{
    "_id" : ObjectId("5a1701e5df011141f5a00323"),
    "uuid": "2b5070ec-11e2-4ddf-9bb5-0de70d935723",
    "documents" : [ 
        {
            "$ref" : "documenttype",
            "$id" : ObjectId("5a1701e5df011141f5a0031e")
        }
    ],
    "sender": {
        "$ref" : "company",
        "$id" : ObjectId("5a1701e5df011141f5a00319")
    },
    ...
},
/* 5 */
{
    "_id" : ObjectId("5a1701e5df011141f5a00324"),
    "uuid": "a0dae760-dde6-48df-bf69-aaf4b66e9515",
    "sender": {
        "$ref" : "company",
        "$id" : ObjectId("5a1701e5df011141f5a0031c")
    },
    ...
}
```

On querying `documenttype`'s via 

```
Query<DocumentTypeEntity> docTypeQuery = mongoDataStore.createQuery(DocumentTypeEntity.class);
docTypeQuery.asList();
```

the query does return both documenttype entries as entity representation, while a query like

```
Query<DocumentTypeEntity> docTypeQuery = mongoDataStore.createQuery(DocumentTypeEntity.class);
docTypeQuery.field("documentId").equal("1");
docTypeQuery.asList();
```

does return only one item, as expected. We've also tried to used `.criteria(...)` instead of `.field(...)` without any differences.

If this query, however, is used as input to an `.elemMatch(query)` method invocation, similar to the sample below, the primer query does return results while the latter one, however, does not. I'd expect at least 2 entries being returned in this case. Note that no further restrictions were defined. Is this behavior intended?

```
Query<CustomScriptActionEntity> query = dataStore.createQuery(CustomScriptActionEntity.class);
query.criteria("documents").elemMatch(docTypeQuery);
query.asList();
```

Note that we had a query that used `.hasThisElement(object)` before, where we passed that respective object directly to the query, though since we upgraded from Morphia 1.2.2 to 1.3.2 this method throws a NullPointerException for us which we tried to counter by changing to its replacement function `elemMatch(...)`. The NPE reads like this:

```
java.lang.NullPointerException: null
	at org.mongodb.morphia.mapping.Mapper.toMongoObject(Mapper.java:634)
	at org.mongodb.morphia.query.FieldCriteria.<init>(FieldCriteria.java:64)
	at org.mongodb.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:295)
	at org.mongodb.morphia.query.FieldEndImpl.hasThisElement(FieldEndImpl.java:140)
	at org.mongodb.morphia.query.FieldEndImpl.hasThisElement(FieldEndImpl.java:26)
        at some.of.our.Test
```

We are also in the process of upgrading the MongoDB driver from 3.2.2 to 3.4.3 in the same process so we are not sure if the problem might eventually be caused by the driver update.

**Comment by RovoMe** [comment]
OK, today I had time to proceed on this issue and it seems that the elemMatch query has to explicitely lookup the `$id` field. If I change the query lookup to something like the example below the lookup works.

```
// Lookup the entity from the datastore
DocumentTypeEntity docType = 
        dataStore.createQuery(DocumentTypeEntity.class)
            .field("documentId").equal(documentId)
            .get();
// Create the match query for via the ObjectId returned in the previous query
Query<DocumentTypeEntity> elemMatchQuery = 
        dataStore.createQuery(DocumentTypeEntity.class)
            .field("$id").equal(docType.getId());
// Append the match query to the actual query for script actions on that document
Query<CustomScriptActionEntity> query = 
        dataStore.createQuery(CustomScriptActionEntity.class)
        ...
        .field("documents").elemMatch(elemMatchQuery);
query.asList();
```

Compared to the previous `hasThisElement(Obj)` method this is notably more code and also has a repetitive smell to it somehow.

**Comment by evanchooly** [comment]
This may be coming far too late but I realized finally, after reconstructing it all here, why you're getting results you don't expect.  You can't use `$elemMatch` on a reference like that.  `$elemMatch` matches the structure of nested elements not remote documents in another collection.  So when you run your query with elemMatch, nothing matches.

This is old enough now that i'm going to close this but certainly if you have more questions, I'm here to answer them in hopefully a much more timely manner going forward.
