### ISSUE TITLE
Aggregation on date problems

### ISSUE THREAD

**Issue by SparkosisNR** [MorphiaOrg/morphia#1220]
Hey guys, i don't know what im doing wrong, but i need help. 

I have to do a count on a date for stats, i have a mongo model and a dto.

i did that:

`Query<myModel> query = this.createQuery();
		Date dFin = new Date();

		
		 DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		 Calendar cal = Calendar.getInstance();
		 cal.add(Calendar.YEAR, -1);
		 String toto = dateFormat.format(cal.getTime());
		 Date ddebut = null;
		try {
			ddebut = dateFormat.parse(toto);
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
     
	

		AggregationPipeline pipeline = getDs().createAggregation(myModel.class);
		query.and(query.criteria("date_ajout").lessThanOrEq(dFin));
		query.and(query.criteria("date_ajout").greaterThanOrEq(ddebut));
		

		
		
			
		
		
		
		
		Iterator<myDto> iterator = pipeline.match(query)
				.group
			    (
			    		"annee",
			    		
			    		grouping("nb", new Accumulator("$sum", 1 ))
			    		
			  
			   )
			    
			    .project(
		
			    		   projection("nb", "nb"),
			    		   projection("annee", "_id")
                       
                       )
			    .aggregate(myDto.class) ;`

I would like to have month, year and count stored in my dto, for now i have only the year and the count, i need the month.

In model i have 1 iso date (date_ajout) and 1 field month, 1 field year and 1 field day

Thanks

**Comment by evanchooly** [comment]
I'm afraid this question is probably too old deal with *now*.  My apologies for the delay.  I'm trying to get on top of the back log and manage it more efficiently.  At any rate, if you're still fighting this (hopefully not!) please open a new ticket with sample code and any errors or better yet use a [reproducer](https://github.com/MorphiaOrg/reproducer).
