### ISSUE TITLE
FindAndModify Default Behaviour

### ISSUE THREAD

**Issue by tarunguptapec** [MorphiaOrg/morphia#1230]
findAndModify(Query<T> query, UpdateOperations<T> operations) method's default behaviour is to return the modified document in morphia. **Shouldn't this be consistent with how mongoDB defines its collection method and return unmodified document by default?**
```
/**
 * Find the first Entity from the Query, and modify it.
 *
 * @param query      the query to use when finding entities to update
 * @param operations the updates to apply to the matched documents
 * @param <T>        the type to query
 * @return The modified Entity (the result of the update)
 */
 <T> T findAndModify(Query<T> query, UpdateOperations<T> operations);
```

```
db.collection.findAndModify(document)
```
Modifies and returns a single document. **By default, the returned document does not include the modifications made on the update**. To return the document with the modifications made on the update, use the new option. The findAndModify() method is a shell helper around the findAndModify command.

**Comment by evanchooly** [comment]
The default should have perhaps matched the server but it didn't.  It's well documented what the default behavior is now and changing that would likely break existing users.  I'll bump this to consideration 2.0 where the options scheme will be changing anyway and such a change would be more obvious to users.

**Comment by evanchooly** [comment]
the default on the new method(s) is to return the "before" state.
