### ISSUE TITLE
Can not support generics type

### ISSUE THREAD

**Issue by yemingfeng** [MorphiaOrg/morphia#1233]
Hi, I meet some problems.
`class Value<T> {
    private T value;
    private double rating;
}`

`class Table {
    List<Value<Integer>> values;
}`
and throw some exceptions: java.lang.ClassCastException: java.lang.Integer cannot be cast to com.mongodb.DBObject

**Comment by gursahibsahni** [comment]
hello @yemingfeng could you please elaborate your concern and post some test cases around this?
