### ISSUE TITLE
Clarification on Datastore.merge() on versioned item.

### ISSUE THREAD

**Issue by PlatanoBailando** [MorphiaOrg/morphia#1235]
I must be confused on the functionality of merge with versioned items.  According to the javadoc, merge is supposed to do a $set on the fields in the passed in entity.  However, after reading the source code it appears that if the entity is versioned, then merge is functionally equivalent to Datastore.save().  Is this intentional?  If so, what is the rationale?

Here's a test illustrating the result:

	@Entity(value="test", noClassnameStored = true)
	static class Test1
	{
		@Id
		ObjectId id;
		String name;
		@Version
		long version;
	}

	@Entity(value="test", noClassnameStored = true)
	static class Test2
	{
		@Id
		ObjectId id;
		String blarg;
		@Version
		long version;
	}

	@Test
	public void merge()
	{
		Test1 test1 = new Test1();
		test1.name = "foobar";
		Datastore ds = getDatastore();
		ds.save(test1);
		Test2 test2 = ds.createQuery(Test2.class).get();
		assertNotNull(test2.id);
		test2.blarg = "barfoo";
		ds.save(test2);
		test1 = ds.createQuery(Test1.class).field("_id").equal(test1.id).get();
		assertNotNull(test1.name);//fails
	}

	private static Datastore ds;
	private static Morphia morphia;

	public static Datastore getDatastore()
	{
		if (morphia == null)
		{
			morphia = new Morphia();
			MapperOptions options = new MapperOptions();
			options.setStoreNulls(false);
			options.setStoreEmpties(false);
			morphia.getMapper().setOptions(options);
			morphia.map(Test1.class);
			morphia.map(Test2.class);
		}
		if (ds == null)
		{
			initDatastore();
		}
		return ds;
	}

	private static void initDatastore()
	{
		ds = morphia.createDatastore(...);//DB init code
		ds.ensureIndexes();
	}
`

**Comment by evanchooly** [comment]
Sounds like a bug to me.  I'm trying to fix the longstanding mapping deficiencies but I'll take a look.  I think save(), even, should always use `$set` if the ID is set.  There have been a number of questions over the years about `save()` "losing" fields not mapped by morphia and using `$set` more often would fix that.  We'll see, though.

**Comment by evanchooly** [comment]
The wheels of progress turn slowly it seems.  I'm trying to catch up...
