### ISSUE TITLE
Custom IterableConverter is not used inside maps

### ISSUE THREAD

**Issue by norvan** [MorphiaOrg/morphia#1241]
I created an IterableConverter for java.util.PriorityQueue.

It is being used properly if my persisted entity has a PriorityQueue field.

However, if I have a field containing a Map of PriorityQueue, morphia fails to use my converter, and uses the default IterableConverter instead.

I believe the issue lies in the EphemeralMappedField:

`@Override
public Class getType() {
    if (pType == null) {
        return super.getType();
    } else if (isMap()) {
        return Map.class;
    } else {
        return List.class;
    }
}`

So in my case, the toString representation of my EphemeralMappedField is: "EphemeralMappedField for  ( type:PriorityQueue, multiple:true, subtype:class java.lang.Integer); {}"

However, getType() returns java.util.List instead of java.util.PriorityQueue. This prevents my custom converter to be called, and uses the IterableConverter instead.

**Comment by evanchooly** [comment]
I know this is terribly old and i apologize for the delay.  I'm almost done grooming the backlog and hopefully bugs won't age so disgracefully going forward.  If you're still fighting this, can you show me your model class and i'll see what i can track down.  Thanks.
