### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by cleciusjm** [MorphiaOrg/morphia#1242]
I use Morphia in production with my Saas and for me it is the best option of Java interaction with MongoDB, but it is since 4 months without commits and incompatible with latest drivers.

There are pending pull requests without revision.

Is sad to see this project dying.

How to we could revert this scenario??

**Comment by ctmay4** [comment]
I have been using Morphia for while and just updated to the latest Java drivers.  I haven't seen any issues yet.  What have you found to be incompatible?

**Comment by evanchooly** [comment]
It's not a question of compatibility so much as improved mapping functionality as supplied by the driver.

**Comment by ctmay4** [comment]
Ah makes sense.  Thanks for the update.

**Comment by jyemin** [comment]
Hi @cleciusjm 

Yes, MongoDB engineers are in communication with @evanchooly and are working with him to ensure that this PR goes through.

**Comment by ctmay4** [comment]
Sorry to keep commenting on this, but I didn't realize POJO support was added to the base Java driver.

http://mongodb.github.io/mongo-java-driver/3.6/bson/pojos/

That seems to have a lot of overlap with Morphia.  I wonder if that is future path for ORMs.  I'm sure it is not complete, but it may explain why MongoDB has not been maintaining this project much anymore.

**Comment by evanchooly** [comment]
My goal is to get morphia working on top of the POJO support and then maintain the query and aggregation, etc. APIs.  I'm aiming to clean up and the modernize the API on top of that.

**Comment by ctmay4** [comment]
That would be awesome.  Thanks for responding and for all your work on the project.

**Comment by evanchooly** [comment]
I'm not planning on abandoning it, personally.  I like the fluent query API in Morphia more than what's in the driver.  So my expectation is that Morphia becomes a thinner layer on top of the driver than it has been but still provides higher level APIs and features than perhaps what is reasonable in the driver.  I'm still working on reconciling how Morphia works with how the PojoCodec works but it's coming along reasonably nicely.

**Comment by patrickliangli** [comment]
Any updates on how the new updates are coming along?

**Comment by evanchooly** [comment]
I'm reworking the docs a little bit (I never liked the brown/green Mongo theme) and updating the build infrastructure so that I can publish the beta docs for the 2.0 update i've been working on.  I'm still trying to figure out a decent package name for #1264.  (Suggestions welcome there!)  

And then I need to triage all the recent issues and PRs and see which ones should be fixed *now* vs which ones have been obviated by the 2.0 changes.

I'm traveling a lot over the next month or so speaking at conferences (I'm in Stockholm now!) so my time for making changes will be spotty but it's as big a priority as I can afford to make it.

**Comment by patrickliangli** [comment]
@evanchooly, good to hear. We have been very happy with using Morphia (moved from Hibernate OGM). Wrt to the package name change, I have not been keeping up to date on all this, what is this with moving out of under MongoDB umbrella? Was morphia directly under MongoDB before?
