### ISSUE TITLE
BasicDAO.update() does not allow for specifying writeconcern

### ISSUE THREAD

**Issue by kalexmills** [MorphiaOrg/morphia#1253]
Presently, the only way to specify the WriteConcern for an update via BasicDAO is via a @WriteConcern annotation on the entity class. However, datastore exposes UpdateOptions.  Why not expose the UpdateOptions via an overloaded method?

**Comment by evanchooly** [comment]
The DAO types are being deprecated in 1.5.  They poorly track Datastore's API providing only a subset of its functionality.  Maintaining both APIs is not the best of use of time and resources.  Users should either use Datastore directly or build custom DAOs.
