### ISSUE TITLE
MapKeyDifferentFromString when map has a String key

### ISSUE THREAD

**Issue by ITarrio** [MorphiaOrg/morphia#1254]
Hi, I have a class that extends from HashMap<String, T>, so my class end with ThisClass<SomeOtherClass>. The MapKeyDifferentFromString is checking the first parameterized class, in my case is "SomeOtherClass" but the key of the map is String. 

I am using v1.3.2

**Comment by evanchooly** [comment]
What exactly is your question/problem?  Is Morphia complaining?
