### ISSUE TITLE
Multi Document transaction support with Morphia

### ISSUE THREAD

**Issue by jayprakashsm** [MorphiaOrg/morphia#1256]
I am really looking forward to Morphia providing multiple document transaction support which comes with Java driver 3.8 for Mongo DB

**Comment by mazen-khalil** [comment]
@evanchooly  I would love to see this feature coming as part of 2.0.0 release. The scope of work shouldn't be much as transactions (sessions) are natively supported now as part of MongoDB driver.

**Comment by evanchooly** [comment]
I'm glad you reminded me.  This isn't *currently* listed as 2.0 but probably will be.  I'm rapidly getting to the end of the current list and I'm starting to pull items in.  I'm just trying to keep that list short and manageable at the moment to try and wrap up the current bits underway.  e.g., i'll probably redo all the aggregation APIs to make them more fluent like I've done for the CRUD operations.  So more is coming I'm just trying to keep things a bit focused at the moment.

**Comment by yizhangy** [comment]
@evanchooly when are you planing release this feature? If this release is not far, my project can wait for it. I am not going to introduce my own transaction.

**Comment by yizhangy** [comment]
@evanchooly  I workaround the morphia with 4.0 transaction like following

my version of update entity like this. so I can start session and use it to update multiple documents entities. if fail,  abortTransaction and rollback. tested working fine. Is this ok to workaround like this.
```
public <E extends BaseEntity> E txUpdate(ClientSession session, E entity, String collectionName) {
		Validate.notNull(entity);
		Validate.notNull(session);
		Validate.notBlank(entity.getId());
		E e = ProxyHelper.unwrap(entity);
		final LinkedHashMap<Object, DBObject> involvedObjects = new LinkedHashMap<Object, DBObject>();
		final DBObject dbObject = entityToDBObj(e, involvedObjects);
		Document document = new Document(dbObject.toMap());
		Document filter = new Document();
		filter.put("_id", entity.getEntityId());
		this.getMongoDatabase().getCollection(collectionName).replaceOne(session, filter, document);
		ObjectId obId = (ObjectId) dbObject.get("_id");
		entity.setEntityId(obId);
		return entity;
	}
```
