### ISSUE TITLE
https://mongodb.github.io/morphia/ appears to be down

### ISSUE THREAD

**Issue by Ertai87** [MorphiaOrg/morphia#1262]
The main source for this documentation appears to have been down since Friday (Sept 7, 2018).  Is there an alternate source for the documentation online, and/or when is this going to be back up?

**Comment by evanchooly** [comment]
Check the README on the main repo page.  It has the correct, updated link to http://morphiaorg.github.io/morphia/

**Comment by Ertai87** [comment]
Thanks!  Now we wait until Google correctly indexes the new site...can you set a redirect maybe?

**Comment by evanchooly** [comment]
That's a github thing afaik.  I don't think anyone outside github could do such a thing.
