### ISSUE TITLE
Morphia's Criteriacontainer overwrites previously set "$or" statement

### ISSUE THREAD

**Issue by tungnduong** [MorphiaOrg/morphia#1278]
I am using Morphia's Query api, and found that my "or" expression is getting overwritten when the expression takes a certain shape.  The full expression that I tried to craft was:

````
$and: [ 
    { $or: [ { fieldA: "a"}, { fieldB: "b"} ] } ,    // fieldA == a OR fieldB == b
    { $and: [ 
        { fieldC: "c" },                                        // fieldC == c AND (fieldD = d OR fieldE = e)
        { $or: [ { fieldD: "d" }, { fieldE: "e" } ] }
 ]
````
Here's how I'm building the query:
````
 query.and(
         query.or(
                 query.criteria("fieldA").equal("A"),
                 query.criteria("fieldB").equal("B")
         ),
         query.and(
                 query.criteria("fieldC").equal("C"),
                 query.or(
                         query.criteria("fieldD").equal("D"),
                         query.criteria("fieldE").equal("E")
                  )
         )
);
````
The resultant query's toString() form :
`  { query: { "$or" : [{ "fieldD" : "D" }, { "fieldE" : "E" }], "fieldC" : "C" }   `

It's missing the section, "$or: [ {fieldA: A}, { fieldB: B} ]".

I understand that the api modifies the internal state of the query object, and so I suspect that perhaps I'm not using the API correctly.  If so, could you please provide some guidance on how my original expression could be built programmatically using the Query object?  

I digged into Morphia's CriteriaContainerImpl.java, and saw that the addTo(final DBObject obj) method descends into the nested expression and passes the running DBObject:
````
} else {
     // no dup field names, don't use $and
     for (final Criteria child : children) {
          child.addTo(obj);  <--- this is the running DBObject
     }
}
````
Then, when it starts evaluating the child "$or" expression, it replaces the pre-existing "$or" stored in the propagated DBObject:
````
final BasicDBList or = new BasicDBList();
for (final Criteria child : children) {
    final BasicDBObject container = new BasicDBObject();
    child.addTo(container);
     or.add(container);
}

obj.put("$or", or);
````

Thanks for your time.  If this is not the proper place to be posting this, then please kindly direct me to where I should go for these type of questions.

**Comment by evanchooly** [comment]
Update:  I have *your* bug fixed but it broke a few other tests.  I'm investigating.

**Comment by evanchooly** [comment]
I've fixed this bug but the actual shape of the document is different than you're expecting.  Because the default "join" operation on document elements is an `and`, they are often dropped from the generated structure.  This makes them less noisy and easier to read.  To see the shape generated, for your reference if you're interested,  you can check out the unit test [here](https://github.com/MorphiaOrg/morphia/blob/fd212f0d97f112be38a1f2496801c9cd0be65d8d/morphia/src/test/java/xyz/morphia/query/TestQuery.java#L1626) and I've included it below as well since the unit test version is condensed.

```json
{
  "$or": [
    {
      "fieldA": "a"
    },
    {
      "fieldB": "b"
    }
  ],
  "fieldC": "c",
  "$or": [
    {
      "fieldD": "d"
    },
    {
      "fieldE": "e"
    }
  ]
}
```

**Comment by tungnduong** [comment]
Thank you!

**Comment by evanchooly** [comment]
Of, course!  Apologies for the delay.

**Comment by arivazhagan-jeganathan** [comment]
@evanchooly , the response from the above query is
{ query: { "$or" : [{ "fieldD" : "d" }, { "fieldE" : "e" }], "fieldC" : "c" }  }
It still skips the first $or block. can you please explain is this still an open issue?
posted related question here:
https://stackoverflow.com/questions/56327859/issues-in-generating-mongo-query-using-morphia-with-nested-and-and-or-criteria

**Comment by evanchooly** [comment]
Are you on 1.5.2?

**Comment by arivazhagan-jeganathan** [comment]
@evanchooly  1.3.2

**Comment by arivazhagan-jeganathan** [comment]
@tungnduong , can you please share if this issue is resolved for you? what is the morphia version you are using?

**Comment by evanchooly** [comment]
Well, the is marked as fixed in 1.5.0 so if you're not on at least that version, you're not going to have the fix.

**Comment by arivazhagan-jeganathan** [comment]
Thanks @evanchooly .. But i see only 1.3.2 is the latest on Maven.
https://mvnrepository.com/artifact/org.mongodb.morphia/morphia/1.3.2.
Can you please let me know if there is a different link for that?

**Comment by evanchooly** [comment]
https://morphia.dev/

**Comment by arivazhagan-jeganathan** [comment]
@evanchooly  thank you so much. That helps!
