### ISSUE TITLE
Order of LinkedHashMap is lost during update operation

### ISSUE THREAD

**Issue by shrey-garg** [MorphiaOrg/morphia#1280]
When calling DAO<T, U>.update(query, operation) and setting a LinkedHashMap in an attribute would result in ordering of that Map being lost due to the usage of HashMap.

**Comment by shrey-garg** [comment]
This is for version 1.3.2

**Comment by shrey-garg** [comment]
I have attempted a fix in https://github.com/MorphiaOrg/morphia/pull/1279

**Comment by evanchooly** [comment]
Merged in to 1.3.2.  need to forward port to the 1.4 and master branches

**Comment by shrey-garg** [comment]
Thanks for merging. :)

PRs for forward porting the fix:
[1.4.x] https://github.com/MorphiaOrg/morphia/pull/1281
[1.5.x] https://github.com/MorphiaOrg/morphia/pull/1282

**Comment by shrey-garg** [comment]
Also, would you r

**Comment by evanchooly** [comment]
PR merged.  Thanks again.
