### ISSUE TITLE
Morphia-Validation: Is there a support for JSR380(Hibernate Vadliator 6)?

### ISSUE THREAD

**Issue by challarao** [MorphiaOrg/morphia#1283]
I'm trying to find a version of morphia which supports Bean Validation 2.0.

**Comment by dupski** [comment]
Hi @challarao 

I was just looking for this myself - I don't think you get this out of the box, but It looks like it is very easy to add custom validation via an "EntityInterceptor" hook.

See example here:
https://github.com/MorphiaOrg/morphia/blob/master/validation/src/main/java/xyz/morphia/ValidationExtension.java

Once you've created your custom validator, you register it with Morphia using:

```java
morphia.getMapper().addInterceptor(new MyCustomValidationInterceptor())
```

Then it will be executed every time you use `Datastore.save()` on an entity

**Comment by evanchooly** [comment]
Bean validation is not supported in Morphia, no.  The solution above looks promising and it's something that might be considered in the 2.x timeframe if there's sufficient interest.
