### ISSUE TITLE
Deprecate Datastore.getCollection()

### ISSUE THREAD

**Issue by evanchooly** [MorphiaOrg/morphia#1285]
This method will be removed in 2.0 and replaced with an updated version using more modern driver types.

**Comment by evanchooly** [comment]
Also marking up all the related methods.  All of them will return new types in 2.0.

**Comment by williamgosse** [comment]
So there's no alternative for the getCollection method at this time? I'm currently using it for stuff like this:
				DBCollection dBCollection = dataStore.getCollection(RuleEntity.class);
				BasicDBObject query = new BasicDBObject();
				query.put(AGENTS, new BasicDBObject(NOT_EQUALS, EMPTY));
				agents = dBCollection.distinct(AGENTS, query);

**Comment by evanchooly** [comment]
It still exists in 2.0.  It's just that the return type is changing.  The deprecation is there to get your attention so you know it's coming.  In 2.0 it returns a `MongoCollection` rather than a `DBCollection`.
