### ISSUE TITLE
Question: why does IterableConverter exist while EmbeddedMapper implements the logic for collections?

### ISSUE THREAD

**Issue by sinsemellan** [MorphiaOrg/morphia#1287]
I wonder what the IterableConverter is for, because when I use a field of type list inside an entity, EmbeddedMapper.writeCollection handles collections without IterableConverter.

```
@org.mongodb.morphia.annotations.Entity
public class MorphiaTest {
    @org.mongodb.morphia.annotations.Id
    public UUID Id;

    public List<Item> ListA;

    public static class Item {
        public int B;
    }
}
```

**Comment by evanchooly** [comment]
The code paths getting to such things are varied and complex.  The "why" of this is probably lost to history at this point.  I'd take the time to investigate and maybe clean it up, but the 2.x code completely revamps all of this anyway so we'll get that for free "soon."
