### ISSUE TITLE
Possibility of better interoperability between Morphia and Mongo Java Driver

### ISSUE THREAD

**Issue by slisaasquatch** [MorphiaOrg/morphia#1289]
I assumed that the Morphia project was dead so I never bothered to post this. And since things are starting to happen here again, here I am.

We've been using Morphia since the Mongo 2 days. We just upgraded to Mongo Java Reactive Streams Driver, and we are using the Driver to do non-blocking IO, and using Morphia to do object/document mapping and query building to keep the existing code functional with Morphia annotations and stuff.

Things are working well for us now, although Morphia is not particularly friendly in terms of interoperation with Mongo Java Driver. We have to create a fake Datastore instance that we never actually use to do IO, and we have to use the deprecated methods, such as Query.getQueryObject() and Query.getSortObject(), to turn Morphia types into Bson to feed into Driver types.

I don't know if we are alone on this, but is there any possibility of improving interoperability between Mophia types and Driver types? Some of my suggestions would be adding the option of creating Query, UpdateOperation, etc. without an instance of Datastore, and making it easier to turn Morphia types into Bson.

Thanks!

**Comment by evanchooly** [comment]
It depends on what you mean exactly.  I have a branch mostly ready for a 2.0 of Morphia that's built on `Document` and such rather than `DBObject`, etc. that aims to be a much more modernized layer on top of the Driver.  I'm not sure what you  mean by "a fake Datastore instance that we never actually use to do IO."

**Comment by slisaasquatch** [comment]
Thanks for your quick reply!

What I mean is that we are using `com.mongodb.reactivestreams.client.MongoClient` and `com.mongodb.reactivestreams.client.MongoCollection` to get non-blocking IO, but we are still using Morphia to build queries and do object/document mapping. Our workflow to do a query basically goes like this:

1. Create Morphia `Query`/`UpdateOperations` objects.
2. Turn them into Bson by calling `Query.getQueryObject()`, `UpdateOperations.getOps()`, etc.
3. Feed the Bson into `com.mongodb.reactivestreams.client.MongoCollection` and get a `Publisher<Document>`.
4. Turn the `Document`s into POJOs with Morphia annotations with Morphia `Mapper`.

And here are the problems:

1. To create a `Query`, you need an instance of `Datastore`. So we are creating a `Datastore` that we never use for anything other than creating `Query` objects. And to create a `Datastore`, we also need an instance of `com.mongodb.MongoClient` that we never use, and an instance of `com.mongodb.DBCollection` that we never use.
2. `Query.getQueryObject()` and `Query.getSortObject()` are deprecated, so I'm afraid that they are going to be removed in the future. I obviously don't want them removed.
3. Turning Bson into Morphia entities is not super straightforward, since Morphia casts things into `DBObject` internally, so we have to recursively reconstruct `BasicDBObject`s with `BasicDBList`s from `Document`s. But maybe that's fixed already on your branch?

And here's what I would love to see (I don't know if it's too much to ask TBH):

1. The option to create `Query` instances without `Datastore`, and throw `RuntimeException`s if the `Query` is being used to do IO (`count()`, `iterator()`, etc.). Or, add the option to create a `Datastore` with `com.mongodb.client.MongoClient`, `com.mongodb.async.client.MongoClient`, and especially `com.mongodb.reactivestreams.client.MongoClient` so we don't have to create fake instances.
2. Un-deprecate `Query.getQueryObject()` and `Query.getSortObject()` and make them return `Bson` or `Document`.
3. More extensive use of `Bson` and `Document` in general to replace `DBObject`.

**Comment by evanchooly** [comment]
Well, the `mapper` branch makes use of `Document` everywhere it can.  There are no more `DBObject`s or `BasicDBObject`s in the mix anywhere.  I'd rather not expose `Bson` types (directly) as that API is rather quite odd.  As for creating `Query` instances, `Datastore` just delegates to a `QueryFactory` instance.

There are methods in the branch to go to/from `Document` instances and your entity types.  They *are* internal methods (as the current methods were supposed to be) that aren't really intended for external use as the APIs may shift over time.  Using them, you'd assume any responsibility should an API change break your app.

The way the `getQueryObject()` and `getSortObject()` are used and exposed vary a bit in the new branch.  You can still get at them, for the most part, it's just the semantics and API have shifted a bit.  The deprecations are there now as a heads up that those are changing.  Again, apply the "internal method" warning here as well.

The API, in general, is getting reworked to smooth over some of the `Morphia`/`Datastore`/`MongoClient` awkwardness that has crept in to the API over the years.  Hopefully the new API is much saner in that regard but I'll try to solicit some feedback via `alpha` releases when things get closer to usable.

Also, it *is* on my radar to look at better, native integration with the async clients such that you needn't go through all the gymnastics you're doing now to leverage both Morphia and async programming.

I'm trying to get a 1.5.0 release done and polished so I can focus solely on that new release without having to bounce back and forth and continually forward port changes and bug fixes in to the 2.x branch.  It's a fair bit of work for sure but I have the build/release infrastructure mostly stabilized so I hope to be able to move forward much more quickly now.  Also, there *are* 2.0.0-SNAPSHOT builds available (and built/released automatically with every successful jenkins build) if you're feeling especially adventurous.  And, of course, the API docs are already published at the main documentation site.

**Comment by slisaasquatch** [comment]
Thanks! I'll close the ticket.
