### ISSUE TITLE
Mongodb saving null instead of empty list

### ISSUE THREAD

**Issue by zaid2130** [MorphiaOrg/morphia#1292]
I am getting null fields whereas I have declared them as emptyList. I have also added `morphia.getMapper().getOptions().setStoreEmpties(true)` just after server starts. After adding this with it's dependency my mongo is saving same null fields. Any solution?
I am using MongoSession instead of MongoCodecSession in grails 3.1

**Comment by zaid2130** [comment]
Not getting this issue resolved through this issue  https://github.com/MorphiaOrg/morphia/issues/626

**Comment by evanchooly** [comment]
can you post your model and a test case.  it would also be extremely helpful to see the document as as stored in the database.

**Comment by zaid2130** [comment]
While saving my instance, it was saving null. Not only here, in every save it was saving null fields. I am using MongoSession instead of MongoCodecSession in grails 3.1. here region is null so it is saving it as null. And then I got problem whille pushing on instance.region in another flow
Sample.withNewTransaction { status ->
                    try {
                        Validator<Sample> validator = ValidatorFactory.instance.getValidator(Sample)
                        def instance = createNewInstance(clonedParams)
                            instance.name = getName()
                            instance.region = null
                            if (!(instance.hasErrors())) {
                                if (instanceCommitted) {    //if true, then save the instance
                                       instance.save(flush: true)
                                }
                    }
}

**Comment by evanchooly** [comment]
I've never used Grails so I can't help you there.  I don't see anything morphia related here.

**Comment by zaid2130** [comment]
I have used this line when my server starts. As discussed here https://github.com/MorphiaOrg/morphia/issues/626 
`morphia.getMapper().getOptions().setStoreEmpties(true)`
I have also added the dependency.

**Comment by evanchooly** [comment]
Right.  But I don't see where you're using *morphia*.  I'm not sure exactly what `MongoCodecSession` is but I'm guessing it's a persistence unit using the `ObjectCodec` from the Java driver.  That is *not* morphia and so settings on morphia classes will have no effect on `ObjectCodec`'s behavior.
