### ISSUE TITLE
Generic Entity

### ISSUE THREAD

**Issue by pbl7** [MorphiaOrg/morphia#1293]
Is saving a generic entity still not supported?

> @Entity("entries")
public class Entry \<T> implements Comparable<Entry<?>> {
...
}

Results in:
`java.lang.RuntimeException: Generic TypeVariable not supported!`

**Comment by evanchooly** [comment]
the support in the branch for 2.x is greatly enhanced.  1.x had not been updated in that regard.

**Comment by evanchooly** [comment]
Short answer now:  Yes.

However, there's a lot of grey area here and you should test accordingly and file issues if you find anything that breaks.
