### ISSUE TITLE
What's the reason behind the warning log: Parameterized types are treated as untyped Objects

### ISSUE THREAD

**Issue by slisaasquatch** [MorphiaOrg/morphia#1296]
Since we upgraded to a recent version of Morphia, we've been getting a lot of warning logs complaining about fields like this:
```java
	@Embedded("rl")
	private Map<String, Object> rules;
```

I found [this](https://github.com/MorphiaOrg/morphia/blob/master/morphia/src/main/java/xyz/morphia/mapping/MappedField.java#L581) in the source code.

So why is this a warning? Is this not the recommended way of storing arbitrary BSON?

**Comment by evanchooly** [comment]
From which version did you upgrade?  1.4.0 is essentially just 1.3.2 so there should be no change in behavior in that case.

**Comment by slisaasquatch** [comment]
From a really REALLY old forked version...

The code still works as expected. What I want to know is the purpose of the warning and what the recommended way of storing arbitrary embedded BSON is.

**Comment by slisaasquatch** [comment]
Ah OK then. I do have some additional questions about `@Embedded`... 🙈

So about `@Embedded` in 2.x, are you saying `ElementType.FIELD` will be removed? Is `@Property` the replacement for annotating fields? And what is the current behavior in 1.4.0? Can I replace `@Embedded` with `@Property` today? The only documentation I found is [this](https://github.com/jmkgreen/morphia/wiki/Embedded-Annotation). Maybe it's outdated?

**Comment by evanchooly** [comment]
That link is to an old fork.  It hasn't been updated in 6 years.  In 1.4.0, you can use `@Embedded` on fields but it doesn't really serve much if any purpose.  `@Property` would be more appropriate or you could even just leave off all annotations and Morphia will map those just fine.

And, yes, in 2.0.0 `ElementType.FIELD` will be removed from that [annotation](https://github.com/MorphiaOrg/morphia/blob/mapper/morphia/src/main/java/xyz/morphia/annotations/Embedded.java).

**Comment by slisaasquatch** [comment]
Thanks! I'll close the ticket.

**Comment by evanchooly** [comment]
Any time.  I hope it helped.

**Comment by slisaasquatch** [comment]
Hi, sorry to bother you again, but I just ran into another problem with `@Embedded`.

Here's the suspect:
```java
import com.mongodb.BasicDBObject;

import xyz.morphia.Morphia;
import xyz.morphia.annotations.Entity;
import xyz.morphia.annotations.Property;

@Entity("collection_name")
public class FakeMorphiaEntity {

	@Property("field1Renamed")
	public FakeMorphiaEmbedded field1 = new FakeMorphiaEmbedded();

	public static class FakeMorphiaEmbedded {
		@Property("field2Renamed")
		public String field2 = "field2Default";
	}

	public static void main(String[] args) {
		Morphia morphia = new Morphia();
		FakeMorphiaEntity fakeMorphiaEntity = new FakeMorphiaEntity();
		BasicDBObject dbObject = (BasicDBObject) morphia.toDBObject(fakeMorphiaEntity);
		System.out.println(dbObject);
	}

}
```
The line with `toDBObject` will cause this error:
```
Exception in thread "main" org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class FakeMorphiaEntity$FakeMorphiaEmbedded.
	at org.bson.codecs.configuration.CodecCache.getOrThrow(CodecCache.java:46)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:63)
	at org.bson.codecs.configuration.ChildCodecRegistry.get(ChildCodecRegistry.java:51)
	at com.mongodb.DBObjectCodec.writeValue(DBObjectCodec.java:230)
	at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:148)
	at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:64)
	at com.mongodb.BasicDBObject.toJson(BasicDBObject.java:194)
	at com.mongodb.BasicDBObject.toJson(BasicDBObject.java:167)
	at com.mongodb.BasicDBObject.toJson(BasicDBObject.java:154)
	at com.mongodb.BasicDBObject.toString(BasicDBObject.java:238)
	at java.lang.String.valueOf(Unknown Source)
	at java.io.PrintStream.println(Unknown Source)
	at FakeMorphiaEntity.main(FakeMorphiaEntity.java:22)
```

And as soon I change `@Property("field1Renamed")` to `@Embedded("field1Renamed")`, the error goes away.

So looks like `@Embedded` in 1.4.0 does make a difference.

**Comment by evanchooly** [comment]
I don't *think* it's necessary when you use Morphia properly.  You're calling an internal(ish) method so much of the normal code paths are not followed.
