### ISSUE TITLE
mapPackage fail to load class from jar (by maven pacakge which with some module)

### ISSUE THREAD

**Issue by em14Vito** [MorphiaOrg/morphia#1314]
Hello. here is my config:
```
morphia: 1.4.0.
bson: 3.4.0.
spring boot: 1.5.16 
mongodb: 4.0
maven: 3.2.5
```
I use maven to package my project as a jar file( use maven-plugin:```spring-boot-maven-plugin```). project struct likes:
-parent(manage dependecy only.)
--web(contain spring-web)
---repository(contain @Entity.class and @Embeded.class)
---service
when I start project by ``` java -jar project.jar```. Morphia can not load my class. (but In _IntelliJ IDEA_  work well).
***
When I debug I found that method
```
ReflectionUtils.getFromJARFile(final ClassLoader loader, final String jar, final String packageName, final boolean mapSubPackages)
``` 
can not load @Entity.class because It did not parse repository.jar.

**Comment by evanchooly** [comment]
I'm not entirely sure I understand your statement there.  Are you seeing a stacktrace at all or is it just not finding your entity type?

**Comment by evanchooly** [comment]
I don't understand what you mean by "didn't scaner sub module but project which run with intellij idea".  Could you post the actual stack trace?

**Comment by em14Vito** [comment]
> I don't understand what you mean by "didn't scaner sub module but project which run with intellij idea". Could you post the actual stack trace?

Hi evanchooly, I mean that, when I use ```morphia.mapPackage()```, it didn't work when I start project by command ```java -jar project.jar```,  the project.jar was package by _spring-boot-maven-plugin_ .  I will  show the error project if you need. thx : )

**Comment by evanchooly** [comment]
That'd be great.  I can build/run it locally with a `master` build and see what's going on.

**Comment by em14Vito** [comment]
> That'd be great. I can build/run it locally with a `master` build and see what's going on.

Hi @evanchooly . I put my demo into [github](https://github.com/em14Vito/morphia-demo-project/tree/master). If you any puzzled, please feel free to contact me. Thx.  😄

**Comment by evanchooly** [comment]
Great, thanks.  I'll see what I can find out.  I'm heading to DevNexus in the next few days so it might be a bit before I have the bandwidth but I'll do my best.

**Comment by em14Vito** [comment]
> Great, thanks. I'll see what I can find out. I'm heading to DevNexus in the next few days so it might be a bit before I have the bandwidth but I'll do my best.

**Comment by evanchooly** [comment]
I think I have it.  My local test works and your demo app shows the class as being mapped.  if you want to give a 1.5.0-SNAPSHOT a test run, I'd love to verify the fix in a full application.  You might run in to the package change from `xyz` to `dev`.  If you're not on 1.4.1, do that upgrade and you'll get the package change and nothing else.  Then switching between 1.4.1 and 1.5.0-SNAPSHOT is just a simple pom change.
