### ISSUE TITLE
Upgrade to Mongo 4

### ISSUE THREAD

**Issue by redkhalil** [MorphiaOrg/morphia#1315]
We're currently using Morphia 1.0.1 and connecting to Mongo v3.
What would it take to move to Mongo v4 (or even just v3.4)? I notice that the latest version of morphia has a new package name and we're hoping to avoid to make such a big change.
I'm interested in the 'least effort' option as we have several projects using Morphia.

**Comment by evanchooly** [comment]
Morphia is currently tested against MongoDB versions 3.4 through 4.0.  Apart from the package name changes, it should just be a drop in replacement.
