### ISSUE TITLE
Support higher JDK versions

### ISSUE THREAD

**Issue by gurkerl83** [MorphiaOrg/morphia#1317]
It seems the version from master supports JDK 8. The build for JDK 9 and higher is broken because of several dependencies such as java/tools or activation. What will be the amount of work necessary to migrate morphia to support > JDK 8 versions?

**Comment by evanchooly** [comment]
1.5.0 will java 6 compatible for historical reasons but 2.0.0 will require at least 8 but be built with java 11/12.  There are some issues on the build side with some of the javadoc taglets to get cleaned up before it can build cleanly on anything 8+.

**Comment by evanchooly** [comment]
That said, it should *run* on any JVM version greater than 6.

**Comment by evanchooly** [comment]
If there's nothing else on the subject, i'll close this for now.

**Comment by grossws** [comment]
`r1.5.2` fails to build on openjdk 11.0.4 because it can't resolve `java:tools:jar:11.0.4`. But it builds on openjdk 1.8.0_222.

I guess, dependency on java tools should be in profile activated by jdk version.

**Comment by evanchooly** [comment]
`master` is still building for 1.6.  The `2.0-dev` branch has moved to jdk11.
