### ISSUE TITLE
How to change the collection name before save and load

### ISSUE THREAD

**Issue by chenchuxin** [MorphiaOrg/morphia#1318]
I want to sharding by a field. 
For example：
```
@Entity("info")
public class Info {
    private long id = 1L;
    private long activityId = 2L;
    private long userId = 3L;
}
datastore.save(new Info());
```
I expect to the info save to the collection named **info_2** . How to do?
Please forgive my poor English~

**Comment by evanchooly** [comment]
You've mapped it to store in `info`.  Why would you expect a collection named `info_2`?

**Comment by chenchuxin** [comment]
> You've mapped it to store in `info`. Why would you expect a collection named `info_2`?

I want to sharding by `activityId`

**Comment by evanchooly** [comment]
sharding is unrelated to storing entities in a collection.  See [here](https://docs.mongodb.com/manual/sharding/) for help on setting up sharding.

**Comment by chenchuxin** [comment]
I just want to sharding by business, not the cluster sharding.
Sharding by activityId, I can easily delete when the activity is useless

**Comment by evanchooly** [comment]
Oh, you're looking for multitenancy not sharding.  You'll have to layer that on yourself.  With a custom DAO that's business-aware you can use the overloads on `AdvancedDatastore` to redirect to specific collections based on which business/customer you're dealing with.

**Comment by chenchuxin** [comment]
thank you very match

**Comment by evanchooly** [comment]
No problem.  I'll close this one for now, then.  Happy coding!
