### ISSUE TITLE
documentation link broken

### ISSUE THREAD

**Issue by RubenPirotte** [MorphiaOrg/morphia#1326]
the documentation link seems to be broken: http://morphiaorg.github.io/morphia/

**Comment by evanchooly** [comment]
What are you seeing?  It works for me here?

**Comment by RubenPirotte** [comment]
seems to be a firewall issue on our end, my bad. I should have done some more research before creating an issue.

**Comment by evanchooly** [comment]
no worries.  glad it's working for you.
