### ISSUE TITLE
Illegal access on LocalDateTime.date

### ISSUE THREAD

**Issue by jottinger** [MorphiaOrg/morphia#1329]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by xyz.morphia.mapping.MappedClass (file:/Users/me/.m2/repository/xyz/morphia/morphia/core/1.4.0/core-1.4.0.jar) to field java.time.LocalDateTime.date
WARNING: Please consider reporting this to the maintainers of xyz.morphia.mapping.MappedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by evanchooly** [comment]
works on 2.0
