### ISSUE TITLE
Morphia version recommendation

### ISSUE THREAD

**Issue by tL295** [MorphiaOrg/morphia#1335]
** Please ask your question and provide whatever background or supporting information you think might be relevant: **
Trying to use Morphia with Mongo 4

** Please complete the following information: **
    Server Version: 4.0.8
    Driver Version: 3.10.0
    Morphia Version: 1.4.1 or 1.5

I'm trying to upgrade a legacy system from Mongo 2.6 and Mongo Driver 3.2 and Morphia 0.111 to something that can talk to Mongo 4.  

When I try to run the integration tests in Morphia 1.4.1 with a 3.10 driver I get a lot of errors (most seem to report a warning coming back from the Mongo Driver.) . Is this something you think I can ignore -OR- should I just wait for 1.5 to be released.  If the answer is the 1.5 do you have an approximate release date?

PS: The code that I inherited is doing some pretty low level stuff so I am not sure 2.0.x will work if that is also recommended.

Thanks Justin,

Tom

**Comment by evanchooly** [comment]
it depends on what those errors are.  I believe Mongo 4.x is being tested on Travis so it should all work.
