### ISSUE TITLE
Lifecycle events on Update/upsert

### ISSUE THREAD

**Issue by sirajka** [MorphiaOrg/morphia#1338]
We are encrypting/decrypting fields using preSave and preLoad

However on upserts, using findAndModify (1.3) or update (1.5), I see the entity is persisted with no call to lifecycle methods.
So data is persisted unencrypted. 
I added prePersist and that is not called either.  

Is this correct behavior for update and if so, what is the approach to mimic save functionality which calls preSave?

**Comment by evanchooly** [comment]
can you share your code/project that shows this behavior?
