### ISSUE TITLE
Search issues with 1.5

### ISSUE THREAD

**Issue by ctmay4** [MorphiaOrg/morphia#1339]
**Describe the bug**
The expected behavior building searches has changed in 1.5

**To Reproduce**

In this code I start with a search on "version".  Optionally, I add an "or" criteria.  If I add the "or", then the previous "version" search is removed.  This code worked correctly in 1.3 and stopped working in 1.5.

```java
Query<C> q = getDatastore().createQuery(_changelogClass);

q.field("version").equal(version);

// POINT A

// id searching
if (param.getDisplayId() != null) {
    List<Criteria> orCriteria = new ArrayList<>();

    orCriteria.add(q.criteria("adds.id").equal(param.getDisplayId()));
    orCriteria.add(q.criteria("deletes.id").equal(param.getDisplayId()));
    orCriteria.add(q.criteria("mods.id").equal(param.getDisplayId()));

    q.or(orCriteria.toArray(new Criteria[orCriteria.size()]));
}

// POINT B
```

In the code I am optionally adding an "or" block.  I put the string representation of the query object below at two points in both versions

In 1.3.x:

POINT A:

```js
{ query: { "version" : "latest" }  }
```

POINT B:

```js
{
    query: {
        "version": "latest",
        "$or": [{
            "adds.id": "5cb5fa6f8d7bd65e8276cd48"
        }, {
            "deletes.id": "5cb5fa6f8d7bd65e8276cd48"
        }, {
            "mods.id": "5cb5fa6f8d7bd65e8276cd48"
        }]
    }
}
```

In 1.5.0:

POINT A:

```js
{ query: { "version" : "latest" }  }
```

POINT B:

```js
{
    {
        "$or": [{
            "adds.id": "5cb5fa6f8d7bd65e8276cd48"
        }, {
            "deletes.id": "5cb5fa6f8d7bd65e8276cd48"
        }, {
            "mods.id": "5cb5fa6f8d7bd65e8276cd48"
        }]
    }
}
```

In the new version the "or" overwrites what is in the query, whereas under 1.3 it added an "or" criteria.  Is this a known change?  I could write this in different ways, but I wanted to highlight that it now produces different results.

I can fix my code by changing it to look like this:

```java
Query<C> q = getDatastore().createQuery(_changelogClass);

List<Criteria> andCriteria = new ArrayList<>();

andCriteria.add(q.criteria("version").equal(version));

// id searching
if (param.getDisplayId() != null) {
    andCriteria.add(q.or(
            q.criteria("adds.id").equal(param.getDisplayId()),
            q.criteria("deletes.id").equal(param.getDisplayId()),
            q.criteria("mods.id").equal(param.getDisplayId())
    ));
}

q.and(andCriteria.toArray(new Criteria[0]));
```

**Comment by evanchooly** [comment]
@ctmay4 i think i've finally untangled that code.  can you try the snapshot build (either wait a few hours for it to show up once jenkins pushes it or build locally from `master`)?

**Comment by ctmay4** [comment]
Awesome.  I'll wait until tomorrow and test the snapshot.  Thanks again!

**Comment by evanchooly** [comment]
Sounds good.  They should be live now in addition to the `asList()` -> `toList()` update.

**Comment by ctmay4** [comment]
Just did some testing.  The snapshot definitely fixed some things.  I did find one thing that still produces different results.  I was able to work around it, but it makes me wonder if there are still differences my unit tests are not hitting.

Here is some code that takes a defined search criteria and sometimes adds additional criteria.

```java
@Override
protected Query<RxBean> buildSearchCriteria(RxSearchParam param) {
    Query<RxBean> q = super.buildSearchCriteria(param);

    // BEFORE

    q.and(q.criteria("type").equal(param.getType()));

    // AFTER

    return q;
}
```

For both versions the value of `q` is the same for BEFORE:

```json
{
    "version": "latest",
    "hidden": {
        "$ne": true
    },
    "$or": [{
        "name": {
            "$regex": "\\Qterm_a\\E",
            "$options": "i"
        }
    }, {
        "alternateName": {
            "$regex": "\\Qterm_a\\E",
            "$options": "i"
        }
    }]
}
```

The AFTER is different.  

In the old versions (1.3.x) the `type` is correctly added to the existing query:

```json
{
    "type": "REGIMEN",
    "version": "latest",
    "hidden": {
        "$ne": true
    },
    "$or": [{
        "name": {
            "$regex": "\\Qterm_a\\E",
            "$options": "i"
        }
    }, {
        "alternateName": {
            "$regex": "\\Qterm_a\\E",
            "$options": "i"
        }
    }]
}
```

However under 1.5.x, the query is dropping the existing criteria and ends up with only the new criteria::

```json
{
    "type": "REGIMEN"
}
```

Interestingly enough, if I switch the code from using `and` to using `field`:

```java
@Override
protected Query<RxBean> buildSearchCriteria(RxSearchParam param) {
    Query<RxBean> q = super.buildSearchCriteria(param);

    // BEFORE

    q.field("type").equal(param.getType());

    // AFTER

    return q;
}
```

Then the value of `q` is correct for AFTER.

Does that make sense?

**Comment by evanchooly** [comment]
it does and I think I know why...

**Comment by evanchooly** [comment]
ok.  all cleaned up.

**Comment by evanchooly** [comment]
I just pushed 1.5.1.

**Comment by ctmay4** [comment]
I did some testing and looks good.  Thanks again.

**Comment by evanchooly** [comment]
Any time!  Thanks for your help and patience running down that fix.
