### ISSUE TITLE
Validation artifact missing from Maven central

### ISSUE THREAD

**Issue by Chatom** [MorphiaOrg/morphia#1342]
Hi,
In your 1.5 guide you provide such info to use morphia validation dependency :
https://morphia.dev/1.5/guides/validationextension/

Yet, I do not see any `dev.morphia` version of the validation artifact.
Is it known ? I also suppose the previous org.mongodb 1.3.2 validation might not work with the current core ?

Thank you !

** Please complete the following information: **
    Server Version:
    Driver Version:
    Morphia Version: 1.5.1

**Comment by evanchooly** [comment]
Curious.  that entire module has been missing since the switch to maven.  I will correct that and try to publish just a 1.5.1 of that module.

**Comment by evanchooly** [comment]
ended up just pushing a 1.5.2 since doing the one module was increasingly more of a hassle
