### ISSUE TITLE
findAndModify Logging lots of stacktraces

### ISSUE THREAD

**Issue by larslorenzen** [MorphiaOrg/morphia#1344]
Hi, we are in the process of updating from old morphia 1.3.2 to 1.5.2 and findAndModify is now logging the following exception:
```
  A null reference was passed in for the dbObject
java.lang.Throwable
	at dev.morphia.mapping.Mapper.fromDBObject(Mapper.java:202)
	at dev.morphia.DatastoreImpl.findAndModify(DatastoreImpl.java:381)
	at dev.morphia.DatastoreImpl.findAndModify(DatastoreImpl.java:403)
```

It is called from our side using:
`datastore.findAndModify(query, updateOperations, false, false);`

Prerequisite: there are no entries in the collection.

Got this exception from morphia 1.5.2

**Comment by evanchooly** [comment]
Are either `query` or `updateOperations` null there?  What happens if you update to the recommended replacement?

**Comment by evanchooly** [comment]
Nevermind.  I found the issue and will fix it promptly.

**Comment by evanchooly** [comment]
1.5.3 is available on maven central now
