### ISSUE TITLE
QueryImpl.first(FindOptions) return null

### ISSUE THREAD

**Issue by chenchenyangll** [MorphiaOrg/morphia#1345]
see [here](https://github.com/MorphiaOrg/morphia/blob/master/morphia/src/main/java/dev/morphia/query/QueryImpl.java#L231)

**Comment by NoOneOfConsequence** [comment]
This is really egregiously bad code. If a method is being left for later implementation, have it throw UnsupportedOperationException or something. To simply return a bogus value without comment is an invitation to all kind of client problems if it leaks out into a release (as this did).

This **one** bug (which we stepped in on our own) has so lowered our confidence in Morphia that it's caused my team to put off adopting 1.5

**Comment by evanchooly** [comment]
@chenchenyangll, my apologies.  that should've been replaced with the implementation of `get()` and clearly the unit tests aren't robust enough to have caught that up.  I'll clean that up ASAP.  I'm at a conference so it might take a few days to get it done and released, though.

**Comment by evanchooly** [comment]
1.5.3 is available on maven central now
