### ISSUE TITLE
source code's link in guides all error

### ISSUE THREAD

**Issue by fdcmessenger** [MorphiaOrg/morphia#1347]
hi
when I read Morphia's guides I find add source's link address odd.
like this:
https://github.com/MorphiaOrg/morphia/blob/(HEAD/morphia/src/test/java/dev/morphia/TestIndexCollections.java
a parenthesis.right!
hope correct it.

**Comment by evanchooly** [comment]
Yep.  a bug in the docs push.  it shouldn't have pushed from a non-master workspace.  Give mea

**Comment by evanchooly** [comment]
All cleaned up.  Apologies for the blip.

**Comment by fdcmessenger** [comment]
thanks your work.
