### ISSUE TITLE
Memory bug with caching

### ISSUE THREAD

**Issue by ctmay4** [MorphiaOrg/morphia#1348]
I recently updated to the latest version of Morphia and have started to get out of memory exceptions.  This service it is used in has been running for many years using Morphia on 1GB of JVM memory, but I just had to bump it up to 2GB.  I did a heap dump and Morphia is using more memory than I would have expected.  I didn't think it was doing any caching so I wasn't sure why it would hold so much.  This is a dump on "live" objects so it excludes any objects already marked for GC.

![image](https://user-images.githubusercontent.com/444345/58182301-5deac780-7c7b-11e9-8d24-63fe3dc402db.png)

Filtering on `dev.morphia`:

![image](https://user-images.githubusercontent.com/444345/58182478-ad30f800-7c7b-11e9-9274-85e978586477.png)

Here is one of the objects expanded:

![image](https://user-images.githubusercontent.com/444345/58183046-a1920100-7c7c-11e9-8a5a-c0eeb23d0600.png)

Does this usage seem normal?  963,167 instances of `EphemeralMappedField` seems high.  Did this behavior change in version 1.5?

**Comment by ctmay4** [comment]
I've done some more research on this and I think I know the problem.  This looks like it was introduced in #1222.  Two caches were added:

In `Converter`

```java
private final Map<MappedField, TypeConverter> mfConverterCache = new HashMap<MappedField, TypeConverter>();
```

In `Mapper`

```java
private final IdentityHashMap<MappedField, CustomMapper> mapperCache = new IdentityHashMap<MappedField, CustomMapper>();
```

The issue I have is the longer my application runs, the larger these caches grow.  Eventually they take all the memory in the JVM.  Here is a heap dump for a process that was running for about a day.

![image](https://user-images.githubusercontent.com/444345/58633668-200f2400-82b7-11e9-9df3-4d823d1069c1.png)

There are close to 1 million entries in the cache and it just continues to rise.

I see a few issues:

- The key in both maps is `MappedField`.  That field does not define `equals` or `hashCode`.  I suppose that doesn't matter for the `IdentityHashMap` but is since it is growing I assume the objects are beaing created fresh.  In the converter it is just using a regular `Hashmap` so since there is no equals/hashCode it will default to object reference equality.  Either way, it is not working as expected since it grows out of control.
- In `Converter`, the other private maps are `ConcurrentHashMap` for thread safety.  These two new maps are not thread safe.  I'm not sure if that was an oversight, but its worth considering.

Let me know if you want me to do any more testing.  I am going to roll back to version 1.4.x since this a major issue for us.  

@evanchooly Any thoughts on this?

**Comment by evanchooly** [comment]
Two caches seems a tad redundant.  I'll definitely dig in to that.

**Comment by evanchooly** [comment]
If i can get a 1.5.3-SNAPSHOT build published could you try it?

**Comment by ctmay4** [comment]
Sure.  I can test it.  How did you fix it?  Did you add equals/hashCode?  Just curious since I've been debugging this.

**Comment by evanchooly** [comment]
I think i'm actually just going to roll most of that back, to be honest.  neither seem to provide much value and morphia's worked for years with out it.  And considering that most of this code is almost certainly getting deleted in the next version, the breakage just isn't worth it.  But we'll see you how fare in a few minutes.

**Comment by evanchooly** [comment]
My jenkins server just pushed new snapshots.  i don't know how long they take to sync but the file names should look something like core-1.5.3-20190530.172921-12.jar

**Comment by ctmay4** [comment]
I have some meetings but will try to give this a test this afternoon.  Thanks for looking into it.

**Comment by ctmay4** [comment]
I did some testing on a development server.  I can't replicate the load from production, but after looking at a heap dump everything seems stable.  I think the fix looks good from my end.

**Comment by evanchooly** [comment]
Excellent.  Currently boarding a plane but i'll try to do a release this weekend.  Thanks for your help.

**Comment by evanchooly** [comment]
1.5.3 is available on maven central now

**Comment by ctmay4** [comment]
Thanks!  I just tested locally and looked good.  I will deploy to production today.  Appreciate looking into this so quickly.

**Comment by evanchooly** [comment]
Of course!  If anything else comes up don't hesitate to file a bug.
