### ISSUE TITLE
Update to use Codecs instead of current mapping code

### ISSUE THREAD

**Issue by evanchooly** [MorphiaOrg/morphia#1353]
The newer drivers support custom PojoCodec code which is much more robust than the current mapping code.  The current code will be updated/replaced/removed as needed to accommodate this new mapping code wherever necessary

**Comment by richarddd** [comment]
Could you add functionality to add custom mapper from json like kotlinx.serialization, gson or Jackson? If we dont do magic with references this should be very convenient and separate mapper from the library.

Would be great if we could have pluggable mappers such as JacksonMapper GsonMapper etc
