### ISSUE TITLE
When I try to connect 4.X  replicaset "com.mongodb.MongoSocketReadException: Prematurely reached end of stream"

### ISSUE THREAD

**Issue by AaronLiang** [MorphiaOrg/morphia#1357]
**Describe the bug**
When I try to connect 4.X  replicaset "com.mongodb.MongoSocketReadException: Prematurely reached end of stream"

**Comment by evanchooly** [comment]
This is an issue with the driver itself and not with Morphia.  You should post to the users list with details of your issue and they can set you straight.
