### ISSUE TITLE
Query on DBref isn't working anymore on Morphia 1.5

### ISSUE THREAD

**Issue by Piskel** [MorphiaOrg/morphia#1361]
Hi,

I have a problem with upgrading to Morphia 1.5.3

The java version I'm using is 1.8, and hte Mongo version is 4.0.3

So I have an object with a @Reference to an other class (MyClass)

Favorite.java :
```java
@Entity("favorite")
public class Favorite {
    @Reference
    private MyClass myClass;
}
```

And I have a query on this class : 

```java
public Favorite findByMyClass(String favoriteId, String  myClassId) {
        Query<Favorite> query = datastore.createQuery(Favorite.class);
        return query.field("id").equal(new ObjectId(favoriteId))
                .disableValidation()
                .field("myClass.$id").equal(new ObjectId(myClassId)))
                .find().tryNext();
    }
```

The error is : 

```
Exception in thread "main" dev.morphia.query.ValidationException: Could not resolve path 'myClass.$id' against 'testMorphia.bean.Favorite'.
at dev.morphia.internal.PathTarget.failValidation(PathTarget.java:147)
	at dev.morphia.internal.PathTarget.resolve(PathTarget.java:130)
	at dev.morphia.internal.PathTarget.getTarget(PathTarget.java:104)
	at dev.morphia.query.FieldCriteria.<init>(FieldCriteria.java:41)
	at dev.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:338)
	at dev.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:334)
	at dev.morphia.query.FieldEndImpl.equal(FieldEndImpl.java:96)
	at dev.morphia.query.FieldEndImpl.equal(FieldEndImpl.java:44)
```

I was using this code with 1.4 (the .find().tryNext() was a .get()) and it was working fine. I don't have any idea on why this isn't working anymore.

Thanks for reading, have a nice day !

**Comment by evanchooly** [comment]
try this query:

```java
  return query.field("id").equal(new ObjectId(favoriteId))
                .disableValidation()
                .field("myClass").equal(new ObjectId(myClassId)))
                .find().tryNext();
```

**Comment by Piskel** [comment]
Thank you for the quick reply !

So your solution did remove the stacktrace but the query doesn't seem to return the object.
I even tried with an hard-coded ID that existed in mongodb but it didn't return anything

```java
.field("myClass").equal(new ObjectId("5d0a4d9d30175f68cbe990d5")))
```

Do you have any idea about what's happening ? Thanks.

**Comment by evanchooly** [comment]
yes.  use the `idOnly` option on your `@Reference` annotation.  It's storing a `DBRef` in the database but you're passing in only an `ObjectId` which doesn't match in the query.

**Comment by Piskel** [comment]
Ah sorry I forgot to mention that MyClass is actually -- despite its name -- an Interface, and I can't put the `idOnly` parameter (I really need the DBRef late in the code).

So is there a way to do it without the idOnly ? That would be handy. Thanks !

**Comment by evanchooly** [comment]
Try this:  
```java
.field("myClass").equal(new DbRef("collection name", new ObjectId(myClassId))))
```

**Comment by Piskel** [comment]
Hi!

So this works fine in my test project, but the problem is that in the actual project, I don't have access to the collection name.

The only information I have access to are String favoriteId, and String  myClassId.

**Comment by evanchooly** [comment]
Sorry for the late reply.  There is a way to get the collection for a given class on ...  `Mapper`?  i think.  Now, it's deprecated and will change/go away in 2.0.  If you use `Key` references rather than `String`s this would be much simpler.

**Comment by Piskel** [comment]
No problem!

So I did solve the problem by using this query :
 ```java
query.field("id").equal(new ObjectId(favoriteId))
                .disableValidation()
                .field("myClass").equal(new Key<>(MyClass.class, collection, new ObjectId(myClassId)))
                .find().tryNext();
```

Now I'm not sure it was what you meant by using `Key`s but I couldn't refactor the way the data is stored so easily, so I went with this solution (now I managed to pass `collection` to the function).

Thanks for your help and have a great day !

**Comment by SOCRATESZZ** [comment]
I am facing similar issue. I am using 2.4 
I cannot use Key since it is deprecated. How do I query using only reference id
