### ISSUE TITLE
Morphia gives: 'Generic TypeVariable not supported', when trying to serialize Set<Employee<O>> but works fine for Employee<O>

### ISSUE THREAD

**Issue by shashank2apr** [MorphiaOrg/morphia#1363]
I have an Entity which I want to save in MongoDb using Morphia.

In this class I use a Generic type Object that Morphia easily resolves but, when I use Set/List of same generic object, Morphia gives below error :

`'java.lang.RuntimeException: Generic TypeVariable not supported!'`
When trying to save this to MongoDB using Morphia, I am able to successfully save 'Employee employeeOrder' but 'Set> orderDetails' gives error.

When I try to save same Set of Generic object as below then Morphia can easily resolve it while saving and fetching:
```
`
Set<Employee<? extends IOrder>>`
```
I looked at 'MappedField.java' of Morphia which throws this error and it seems the cause of error is that Morphia recognises 'type' of each member variable of my Entity class correctly except when its Set>.

It neither recognises it as 'instanceof ParameterizedType' nor 'instanceof WildcardType'.

I am using Morphia 1.5.3 currently. I am not sure if this error is fixed in newer versions or I am doing something incorrectly.

My Entity class:
```

@Entity
class Employee<O extends IOrder> {
.
.
@org.mongodb.morphia.annotations.Embedded
private Employee<O> employeeOrder;
.
.
@org.mongodb.morphia.annotations.Embedded
private Set<Employee<O>> orderDetails = Sets.newHashSet();
}
```
To summarize: Morphia is able to resolve type of 'O' in Employee but not able to understand the type of same 'O' in Set> and throws below error:
```
java.lang.RuntimeException: Generic TypeVariable not supported!
	at dev.morphia.mapping.MappedField.toClass(MappedField.java:656)
	at dev.morphia.mapping.EphemeralMappedField.getSubClass(EphemeralMappedField.java:84)
	at dev.morphia.mapping.EphemeralMappedField.<init>(EphemeralMappedField.java:39)
	at dev.morphia.mapping.MappedField.collectTypeParameters(MappedField.java:579)
	at dev.morphia.mapping.MappedField.discoverType(MappedField.java:540)
	at dev.morphia.mapping.MappedField.discover(MappedField.java:509)
	at dev.morphia.mapping.MappedField.<init>(MappedField.java:115)
	at dev.morphia.mapping.MappedClass.discover(MappedClass.java:574)
	at dev.morphia.mapping.MappedClass.<init>(MappedClass.java:142)
	at dev.morphia.mapping.Mapper.getMappedClass(Mapper.java:512)
	at dev.morphia.mapping.MappedClass.discover(MappedClass.java:535)
	at dev.morphia.mapping.MappedClass.<init>(MappedClass.java:142)
	at dev.morphia.mapping.Mapper.getMappedClass(Mapper.java:512)
	at dev.morphia.DatastoreImpl.getWriteConcern(DatastoreImpl.java:1592)
	at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:1123)
```

### Version information: 
    Server Version: 3.0.15
    Driver Version: 3.8.2
    Morphia Version: 1.5.3

**Comment by evanchooly** [comment]
At the top you say you're on 1.3.2 but at the bottom you list 1.5.3.  Can you clarify which version you're on?  From the stack trace, my guess is 1.3.2.  If you could try it on 1.5.3, that would help, too.

**Comment by shashank2apr** [comment]
I have updated my question. I am using 1.5.3 now. Earlier it was 1.3.2.

Can you please check now?

**Comment by shashank2apr** [comment]
@evanchooly I made this change in code and it worked correctly for me.

Can you verify if it looks correct then I will create a PR.


Class: MappingField.java 
```
    protected Class toClass(final Type t) {
        if (t == null) {
            return null;
        } else if (t instanceof Class) {
            return (Class) t;
        } else if (t instanceof GenericArrayType) {
            final Type type = ((GenericArrayType) t).getGenericComponentType();
            Class aClass;
            if (type instanceof ParameterizedType) {
                aClass = (Class) ((ParameterizedType) type).getRawType();
            } else if (type instanceof TypeVariable) {
                aClass = ReflectionUtils.getTypeArgument(persistedClass, (TypeVariable<?>) type);
                if (aClass == null) {
                    aClass = Object.class;
                }
            } else {
                aClass = (Class) type;
            }
            return Array.newInstance(aClass, 0).getClass();
        } else if (t instanceof ParameterizedType) {
            return (Class) ((ParameterizedType) t).getRawType();
        }



      //Added below code to make it work
         else if (t instanceof WildcardType) {
            return (Class) ((WildcardType) t).getUpperBounds()[0];
        }
//End of newly added code




        throw new RuntimeException("Generic TypeVariable not supported!");

    }

```

**Comment by shashank2apr** [comment]
Please let me know your suggestion/comments soon as we need this to be done for a critical task ASAP in production.

**Comment by shashank2apr** [comment]
Can you please have a look at this? This is important for a production release.

**Comment by evanchooly** [comment]
I'm cleaning out the backlog so I can see what's still active and what's not.  This one seems to have gone inactive.  If that's not the case, please let me know.
