### ISSUE TITLE
1.5.3 uses slf4j version 1.8.0-beta2

### ISSUE THREAD

**Issue by slisaasquatch** [MorphiaOrg/morphia#1365]
**Describe the bug**
I was trying to upgrade my Morphia version, and the new version broke my logging. It turns out that [1.5.3 is using slf4j 1.8.0-beta2](https://mvnrepository.com/artifact/dev.morphia.morphia/core/1.5.3) for some reason.
I've excluded slf4j from Morphia in my build and things are working now, but I don't really know why the beta version was used in the first place.

**To Reproduce**
N/A

**Expected behavior**
The version should probably be a stable version like 1.7.26.

 - Server Version: 3.6
 - Driver Version: 3.10.1
 - Morphia Version: 1.5.3

**Additional context**
N/A

**Comment by evanchooly** [comment]
looks like an errant version instead of taking advantage of the dependencies management

**Comment by evanchooly** [comment]
fixed in 9beebbfad5e9b5a9d932a622d72a8fbbb5e038eb
