### ISSUE TITLE
Iterate over all documents in a collection

### ISSUE THREAD

**Issue by Plebo13** [MorphiaOrg/morphia#1380]
Hi,
I have a collection of documents and try to iterate over all documents in that collection. But I got following error stacktrace:

```
Exception in thread "main" java.lang.IllegalArgumentException: call loop instead
	at dev.morphia.utils.IterHelper.loopMap(IterHelper.java:33)
	at dev.morphia.converters.MapOfValuesConverter.decode(MapOfValuesConverter.java:24)
	at dev.morphia.converters.Converters.fromDBObject(Converters.java:125)
	at dev.morphia.mapping.ValueMapper.fromDBObject(ValueMapper.java:19)
	at dev.morphia.mapping.Mapper.readMappedField(Mapper.java:889)
	at dev.morphia.mapping.Mapper.fromDb(Mapper.java:295)
	at dev.morphia.mapping.Mapper.fromDBObject(Mapper.java:202)
	at dev.morphia.query.MorphiaIterator.convertItem(MorphiaIterator.java:137)
	at dev.morphia.query.MorphiaIterator.processItem(MorphiaIterator.java:149)
	at dev.morphia.query.MorphiaIterator.next(MorphiaIterator.java:120)
	at DatabaseUpdater.update(DatabaseUpdater.java:34)
	at DatabaseUpdater.main(DatabaseUpdater.java:88)
```

Here is my code in _Databaseupdater.update()_:
```java
Query<Index> qI = datastore.createQuery(Index.class);
    Iterable<Index> indices = qI.fetch();
    for (Index index : indices) {
      System.out.println(index);
    }
```

And here is the beginning of my "Index" class:
```java
@Entity("indices")
public class Index {

  private static final Logger log = Logger.getLogger(Index.class.getName());
  @Id
  private String isin;
  private String name;
  private double[] performanceMedian = new double[2];
  private double[] performanceOffset = new double[2];
  private HashMap<Integer, Double> kgvMedian = new HashMap<>();
  private HashMap<Integer, Double> dividendReturnMedian = new HashMap<>();
  private HashMap<Integer, Double> dividendDifferenceMedian = new HashMap<>();
  private HashMap<Integer, Double> dividendDifferenceOffset = new HashMap<>();
  private Set<Integer> years = new HashSet<>(Arrays.asList(2020, 2019, 2018, 2017));
  private Date lastUpdate;
  @Reference
  private Set<Share> shares = new HashSet<>();
```

As I can see _fetch()_ is deprecated but so is _asList()_. What is the recommended way to achieve an iteration over the documents?

Thanks in advance!

Server Version: 4.2.0
Driver Version: 2.12.3
Morphia Version: 1.5.3

**Comment by evanchooly** [comment]
Using the [reproducer](https://github.com/MorphiaOrg/reproducer) project, this works for me using the code as is.  It's possible that it's stumbling over some of your data but I can't recreate that here.  Can you try creating a reproducer for me and we can take a look together?  And you really using 2.12.3 of the driver?  Because that's *really* outdated and morphia doesn't test against versions that old.  If I add

```xml
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>2.12.3</version>
        </dependency>
```
 to my pom, the project won't even build anymore.

**Comment by Plebo13** [comment]
I cleared my Database and changed to _asList()_. Now it is working :) Don't know exactly what the problem was.
Thank you!

**Comment by evanchooly** [comment]
THat's pretty bizarre.  I would have loved to isolate the cause but so long as it's working for you.  I'm sure it was probably wonky data in your db so there's *probably* a fix to be made in there.
