### ISSUE TITLE
Is Morphia 1.0.1 compatible with MongoDB 4?

### ISSUE THREAD

**Issue by redkhalil** [MorphiaOrg/morphia#1383]
** Please ask your question and provide whatever background or supporting information you think might be relevant: **
We're in the process of upgrading from MongoDB 3 to 4 and I would like to find out if morphia 1.0.1 is compatible with MongoDB 4.
If not, what's the latest version of MongoDB that is compatible with this Morphia 1.0.1? We could consider upgrading Morphia as long as we can avoid having to deal with the package name changes. What options do we have?

** Please complete the following information: **
    Server Version: 3
    Driver Version: Not Specified
    Morphia Version: 1.0.1

**Comment by evanchooly** [comment]
*probably* but it's not tested that far back.  The oldest version supported 1.3.2.  The biggest risk is that morphia might try to use a server feature that's been removed but there aren't too many of those.

**Comment by redkhalil** [comment]
I've checked v1.3.2 and it's prior the package name change, so it's something we can consider. However I would also want to know what are my options should we stick with Morphia v1.0.1.
Is the compatibility between Morphia and MongoDB documented somewhere?

**Comment by evanchooly** [comment]
It is not documented, per se, but if you look at the travis.yml file you can see the matrix of versions currently being tested.  1.0.1 is well outdated, though, and there are no plans for further updates to it.
