### ISSUE TITLE
DefaultCreator default constructor causing NPE on 1.5.x

### ISSUE THREAD

**Issue by slisaasquatch** [MorphiaOrg/morphia#1387]
The default constructor of `DefaultCreator` will leave `options` null. In 1.4.x, the `getClass` method in `DefaultCreator` checks `options` nullness ([see code here](https://github.com/MorphiaOrg/morphia/blob/1.4.x/morphia/src/main/java/dev/morphia/mapping/DefaultCreator.java)), but for some reason that's changed in 1.5.x.
I know this can be fixed by passing in a `MapperOptions`, but it's still a problem that the public default constructor can create a broken instance of `DefaultCreator`. Also IMO this makes creating a `MapperOptions` with `DefaultCreator` very awkward, because I have to do this now:
```java
final MapperOptions baseMapperOptions = MapperOptions.builder().storeEmpties(true).build();
final MapperOptions mapperOptions = MapperOptions.builder(baseMapperOptions)
		.objectFactory(new DefaultCreator(baseMapperOptions) {
			@Override
			protected ClassLoader getClassLoaderForClass() {
				return myClassLoader;
			}
		})
		.build();
```

 - Server Version: 3.6.8
 - Driver Version: 3.11.0
 - Morphia Version: 1.5.5

**Comment by jonahseguin** [comment]
Encountered this issue too, took a lot of digging to find an easy fix, similar to yours:
```java
MapperOptions options = morphia.getMapper().getOptions();
        morphia.getMapper().setOptions(MapperOptions.builder(options)
                .objectFactory(new DefaultCreator(options) {
                    @Override
                    protected ClassLoader getClassLoaderForClass() {
                        return classLoader;
                    }
                })
                .build());
```

**Comment by evanchooly** [comment]
OK.  I see what broke there.  I removed the null checking thinking that `DefaultCreator` would "never" be created without an options instance.  It, in fact, *needs* one now since the discriminator configuration has been moved there.  You can't *do* anything with those values, yet, but 2.0 will open that up.  I'll default that field to have a valid instance and that should clean it up.
