### ISSUE TITLE
How to print mongo sql to console ? 

### ISSUE THREAD

**Issue by july-young** [MorphiaOrg/morphia#1389]
Hi I'm a java programmer,I have a question that how to print mongo sql to console ,just like mybatis.

    Server Version:     java 1.8 . spring boot
    Driver Version:      org.mongodb.mongo-java-driver    3.4.2
    Morphia Version:  1.3.2

**Comment by evanchooly** [comment]
If you print out the query you should see the generated query structure.  In 2.0, i've added a method to capture information as the server sees it but 2.0 isn't quite out yet.
