### ISSUE TITLE
Query size of embedded list

### ISSUE THREAD

**Issue by mweiczorek** [MorphiaOrg/morphia#1392]
Hi,
It would be nice to be able to query the size of an embedded list. Your documentation alludes to 'filter' and '$size' and '$gt', but offers no inkling on how to combine this into 'list size > 0'. Right now, I filter after the query is returned, but would be nice to delegate this to mongo

**Comment by evanchooly** [comment]
Is that kind of query even expressable in the query language in the shell?  If you can show me what *that* looks like, we can take a look at a morphia equivalent.

**Comment by chenchenyangll** [comment]
check [this](https://stackoverflow.com/a/15224544/4673919)

**Comment by evanchooly** [comment]
oh, right.  I forgot about that one.  Let me play with this and see.  might end up needing a new method.
