### ISSUE TITLE
Broken validation of fields in 1.5.x

### ISSUE THREAD

**Issue by pthum** [MorphiaOrg/morphia#1401]
**Describe the bug**
When using types and subtypes in one collection and querying the parent type with a field of the child, then no ValidationException is thrown (anymore). 
Morphia versions up to 1.4.1 (including) had thrown a ValidationException in that case, when validation was enabled.

**To Reproduce**
- have a class "Tire" with some attributes
- have a class "SpikeTire" which extends "Tire" and is stored to the "Tire" collection, and an attribute "spikeLength" 
- store some objects (esp. of SpikeTire, containing the attribute)
- do a query on "Tire" class mentioning the "spikeLength" attribute (see additional context below)

**Expected behavior**
I would expect a ValidationException to be thrown (like before), as i explicitly enable the validation within the query and i do a query on the parent class and the field doesn't exist on the parent class. Or at least a possibility to enable some kind of "strict check"

** Please complete the following information: **
 - Morphia Version: starting from 1.5.0

**Additional context**
Any example models, queries, and executable test cases you can supply will greatly help debugging your issue:

```java
@Entity
public class Tire
{
	@Id
	public ObjectId id;
	public String test;
}
```
```java
@Entity( value = "Tire" )
public class SpikeTire extends Tire
{
	public double spikeLength;
}
```
```java
	public static void main( final String[ ] args )
	{
		try (final MongoClient mongoClient = new MongoClient( new MongoClientURI( "mongodb://localhost:27017" ) ))
		{
			final Morphia m = new Morphia( );
			final SpikeTire st = new SpikeTire( );
			st.test = "abc";
			st.spikeLength = 2.2d;
			final SpikeTire st2 = new SpikeTire( );
			st2.test = "cde";
			st2.spikeLength = 1.1d;
			final Datastore ds = m.createDatastore( mongoClient, "Test0815" );
			ds.save( st );
			ds.save( st2 );

			final Query<Tire> qry = ds.createQuery( Tire.class );
			qry.enableValidation( ).criteria( "spikeLength" ).greaterThan( 1.5d );
			final List<Tire> cursor = qry.asList( ); // throws a validation exception when using versions before 1.5.0
			// ...
		}
	}
```

**Comment by evanchooly** [comment]
OK.  Here's what's happened here.  In 1.4 there were two different code bases used for evaluating path elements:  the older one used in the query code and newer used ... elsewhere.  Changes were made to shift everything to newer code since it was much more robust in many ways.  One of those ways, was more support for polymorphic queries.  In essence, the new code is smart enough to check subtypes when it finds an unknown field.  This makes polymorphic queries possible.  This is why you're not seeing the validation error anymore.  Because morphia got a tiny bit smarter.

**Comment by evanchooly** [comment]
In short, this isn't actually a bug it's what we want.  But it's definitely a change in behavior.
