### ISSUE TITLE
Cloned Query is affecting the query from which it got cloned

### ISSUE THREAD

**Issue by stephandischer** [MorphiaOrg/morphia#1405]
**Description**
If I am not mistaken, a query instance created by using query.cloneQuery() is suppose to be independant of this query. Adding new filter criterias however does affect both, the cloned query, as well as the query from which the instance was cloned from.

We were using the method with morphias version 1.3.2 with the expected behaviour, but after migrating to 1.5.7 found that the behaviour changed in that regard.

**Simplified example (written in scala)**
```
val query = datastore.createQuery(classOf[Transaction])
        .disableValidation()
        .field("field1").equal("value1")
System.out.println(query.toString)
val query2 = query.cloneQuery()
query2.field("field2").equal("value2")
System.out.println(query.toString)
System.out.println(query2.toString)
```
**Prints out**
{ {"field1": "value1"}  }
{ {"field1": "value1", "field2": "value2"}  }
{ {"field1": "value1", "field2": "value2"}  }

**Versions**
Morphia Version: 1.5.7
Java Version: OpenJDK 8
MongoDB Version: 3.4

**Comment by evanchooly** [comment]
Can you tell me a bit about what you're using it for?  This is an internal method so I'm a little hesitant to promote it's usage too much.

**Comment by stephandischer** [comment]
We have some more complex search implementations in which we build the query based on wether results can be found for parts of this query. 
So something like 
if (q.cloneQuery().field("field1").equal("value").count() > 0) q.field("field1").equal("value");
if (q.cloneQuery()...)

I am aware that its not a good design practice and working with proper aggregations would certainly allow us to achieve the same and more performant result, but I was wondering how the method is suppose to work instead. I am sure having a way of cloning a complex query to be used independantly can be of use in a lot of scenarios. 
E.g. database consistency checks while unit testing.

**Comment by evanchooly** [comment]
wow. i  really dropped the ball on this one.  I apologize.  Is this still an issue for you?  2.0 has actually dropped that method altogether and relies, internally, on other approaches.

**Comment by stephandischer** [comment]
thanks for getting back to me. I found some workarounds for my existing use cases and avoid using that approach for new implementations, so I am good for now. Will close this issue then.
