### ISSUE TITLE
UpdateOperations.dec can change field type

### ISSUE THREAD

**Issue by sdalichampt** [MorphiaOrg/morphia#1406]
**Description**
When using dec(String, Number) method of org.mongodb.morphia.query.UpdateOpsImpl whit a int ou float value, the type of the field is change to long and double in the database.

This is probably due to the inner call of UpdateOpsImpl.inc(String, Number) which assume long and int are equals and can be passed by longValue (and double and fload passing by doubleValue)

**Sample**
// assmuming solde is stored as int32

int decValue = 5;
ds.findAndModify(
                ds.createQuery(MyType.class).field("_id").equal(id),
                ds.createUpdateOperations(MyType.class).dec("solde", decValue)
);

// solde is now stored as int64

**Versions**
Morphia version : 1.3.2 -> 1.5.9-SNAPSHOT

**Comment by evanchooly** [comment]
I'm having a hard time recreating this.  I'm tweaking dev.morphia.TestUpdateOps#testIncDec trying to recreate it and coming up empty handed.  Do you think you could work up a [reproducer](https://github.com/MorphiaOrg/reproducer) I could take a look at?

**Comment by sdalichampt** [comment]
Yes I can, you can take a look at https://github.com/sdalichampt/reproducer

**Comment by evanchooly** [comment]
Lovely.  I'll try to take a look at it later today.  thanks for doing that.

**Comment by evanchooly** [comment]
My apologies to taking so long.  The world got weird and super busy.  I actually can't recreate it even with the reproducer using either 1.5.2 or 1.6.0-SNAPSHOT.

**Comment by sdalichampt** [comment]
Hi

I just retested with the reproducer and the version 1.5.2 of morphia with the official docker image of mongo.

I added a new test case in the reproducer which fails line 243 because the type of the field "number" passed from int to long while the processing carried out is the same as some higher line.

**Comment by evanchooly** [comment]
Ok.  I have that ironed out now, i think.  Jenkins is currently building a 1.6.0-SNAPSHOT build if you want to try it out.  Instructions on how to use that build on on https://morphia.dev.  Or if you'd like to work around it without updating the morphia version, you could simply call `inc()` with the negative value on your own.
