### ISSUE TITLE
Do not store className on embedded objects

### ISSUE THREAD

**Issue by ksenia0822** [MorphiaOrg/morphia#1407]
Morphia 0.108 allowed both `@Entity(noClassnameStored = true)` and `@Embedded` annotations at a class level and we used them on embedded objects not to store their class names, like so:

```
public class MyClass {
    private final Map<String, MyEmbeddedAbstractClass> embeddedClass;
}

@Entity(noClassnameStored = true)
@Embedded
public abstract class MyEmbeddedAbstractClass {
 
}
```
After upgrading to 1.5.8 we started getting an error `Cannot have both @Entity and @Embedded annotation at class level`. After removing `@Entity(noClassNameStored = true)` from `MyEmbeddedAbstractClass`, the className gets stored on the embedded class. 

How can we tell morphia not to store `className` on embedded objects?

Driver Version: 3.10.1
Morphia Version: 1.5.8

**Comment by evanchooly** [comment]
Currently that is not possible in 1.x.  In 2.x, this becomes much more configurable but that is still some time off (though getting much, much closer every day).  What you can try as a workaround is to simply not annotate with `@Embedded` at all.  I'm not 100% sure that will work but it's worth a shot.
