### ISSUE TITLE
How to do projections with version 2.0.0-ALPHA2? 

### ISSUE THREAD

**Issue by nickel-bert** [MorphiaOrg/morphia#1408]
I have been playing around with version 2.0.0-ALPHA2 in order to see how much work we would need to put into the migration.
It turns out that it actually isn't much - but i do have a problem with projections. 

_Query#project()_ has been deprecated in favour of  _FindOptions#projection()_.

But _FindOptions#projection()_ only offers me these methods: 
- knownFields()
- map(final Mapper mapper, final Class type)

More promising methods are unfortunately package-private: 
- FindOptions#include(final String... fields)
- FindOptions#exclude(final String... fields)

Is this still incomplete / a bug? 
Or am I not using the new Projections as intended?

**Comment by evanchooly** [comment]
first, thanks for taking a look at the alpha.  Feedback is always welcome.  and that is *definitely* an oversight.  those should be public.  I'll take a look at the tests and see why they haven't been updated accordingly.  Perhaps my next step step will simply be to remove all usage of deprecated items in the tests.  At any rate, i'll clean this up for the next alpha.  Thanks for the catch.

**Comment by evanchooly** [comment]
OK.  I'm back in front of my actual IDE and not just a web browser.  Here's how you would do projections in 2.0:

```java
getDs().find(MyEntity.class)
       .execute(new FindOptions()
                    .projection().include("name", "rank", "serial_number")
                    .projection().exclude("_id"))
```

**Comment by evanchooly** [comment]
if this answered your question, i'll close it out.

**Comment by nickel-bert** [comment]
👍
