### ISSUE TITLE
4.0 Java driver compatibility

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#1411]
The 4.0 release of the Java driver is imminent.  There is at least one change that breaks binary compatibility: the insert methods on MongoCollection now return InsertResult instead of void.  Anyone who wants to use a 4.x Java driver along with Morphia will need a Morphia release that has been compiled against the a 4.x Java driver.

I'm opening this issue to start a discussion about how to manage this transition for users of Morphia.

**Comment by evanchooly** [comment]
I'm currently building the 2.x branch against 3.11/12.  Are there 4.0 snapshots I could build against?

**Comment by jyemin** [comment]
Yes, there are.  A new one was published a few days ago that has all the API changes in it.

**Comment by jyemin** [comment]
And I plan to publish a beta by the end of the week.

**Comment by evanchooly** [comment]
fantastic!  i'm wrapping up the aggregation API and then i'll update to that and do a new alpha/beta release.  upgraded to server 4.2 and i'm getting "too many files" errors on the server now so i'm a bit hamstrung.  might just be a windows/WSL issue.  i'll test that later today.

**Comment by jyemin** [comment]
4.0.0-beta1 has been released

**Comment by evanchooly** [comment]
I'll have a few tweaks (for visibility) i've been sitting on until 4.0 snapshots showed up so I'll need to file that PR soon.  but one breaking change i've already noticed that seems to be undocumented is `com.mongodb.AggregationOptions` seems to have vanished.  It was not deprecated in 3.12.0 but is gone in 4.0.0.  My new aggregation API doesn't use it but the old one does.  I *could* just drop the old API altogether in 2.0 as the new one is far superior but I was hoping to at least provide a migration period.

**Comment by jyemin** [comment]
It's still there: https://github.com/mongodb/mongo-java-driver/blob/r4.0.0-beta1/driver-legacy/src/main/com/mongodb/AggregationOptions.java

Make sure you're depending on the right artifacts.  it's in mongodb-driver-legacy.  Note that we're no longer publishing the uber jars so there is no longer a mongo-java-driver artifact.

**Comment by evanchooly** [comment]
Oh. Right. Of course.  I'll add that as a dep.  That could be a good way to prune APIs actually as I don't want to need both jars.

**Comment by evanchooly** [comment]
There are 4 or 5 files I'll need bumped to public but otherwise, I've managed to vastly reduce the changes I'd been looking at.
