### ISSUE TITLE
Access parent object from embedded?

### ISSUE THREAD

**Issue by Joi3432** [MorphiaOrg/morphia#1413]
Following example model:
```
@Entity
class Page {
    String name;
    List<Comment> comments;
    
    @Embedded
    class Comment {
        String author;
        String content;
    }
}
```
Imagine that I only have a Comment, is it possible to access the related Page with Morphia Features? What would otherwise be the best approach to achieve this?

Thanks!

    Server Version: 4.2.2
    Driver Version: 3.12.0
    Morphia Version: 1.5.8

**Comment by evanchooly** [comment]
If you want that, you can manually track the parent reference:

```java
@Transient Page page;
```

Then just pass the parent page reference in to Comment's constructor, e.g.

**Comment by Joi3432** [comment]
Thanks.
That means when I e.g. load a Page from the Datastore I have to loop through all comments and set the page reference? I've tried an Constructor which only takes the Page instance in parallel to an empty constructor, but then the page value is null.

**Comment by evanchooly** [comment]
Ah, yes.  It *would* mean that.  if it's not transient you'd end up in a cycle and that'd overflow the stack.  Generally, you shouldn't need that upward reference like that.  You'd already have a reference to the page anyway in most scenarios.
