### ISSUE TITLE
minDistance of geoNear aggregation is missing

### ISSUE THREAD

**Issue by heyarny** [MorphiaOrg/morphia#1414]
https://docs.mongodb.com/v3.6/reference/operator/aggregation/geoNear/

=> `minDistance`

Is there going to be a new version in near future or do we have to build our own forks?

**Comment by evanchooly** [comment]
I've been madly working on 2.0 as it happens:  https://github.com/MorphiaOrg/morphia/commits/2.0-dev

**Comment by heyarny** [comment]
@evanchooly is there a snapshot on maven repository available somewhere?

**Comment by evanchooly** [comment]
add this to your pom:

```xml
<repository>
  <id>sonatype</id>
  <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
</repository>
```

I have 2 more issues to fix and i'll do another preview release.  probably an `ALPHA3` as I'm not sure I'm quite ready for `BETA` and certainly not `RC` releases.
