### ISSUE TITLE
change artifact id name in pom.xml

### ISSUE THREAD

**Issue by dinosavings** [MorphiaOrg/morphia#1416]
**Is your feature request related to a problem? Please describe.**
I finally migrated to the 1.4.1 and noticed a potential issue with the pom definition:

```
<dependency>
            <groupId>dev.morphia.morphia</groupId>
            <artifactId>core</artifactId>
            <version>1.4.1</version>
        </dependency>

```
Having an artifactId named core means that maven will include a jar file named core-1.4.2.jar into the war. Issue one: hard to tell that this jar file is morphia and two there could be a potential conflict if another library uses a generic name like this (actually there is one from com.google.zxing, it's definition is 
```
<dependency>
	    <groupId>com.google.zxing</groupId>
	    <artifactId>core</artifactId>
	    <version>3.2.1</version>
        </dependency>

```
**Describe the solution you'd like**
```
<dependency>
            <groupId>dev.morphia.morphia</groupId>
            <artifactId>morphia-core</artifactId>
            <version>1.4.1</version>
        </dependency>

```

**Comment by evanchooly** [comment]
I realized that too late to change it in 1.4.  In the 2.0 release, I've corrected that oversight.  I'm unsure about changing the artifact *again* in the 1.x releases...

**Comment by dinosavings** [comment]
Got it. I will simply close this ticket.
