### ISSUE TITLE
Support insert() and replace() operations in addition to save()

### ISSUE THREAD

**Issue by wheezil** [MorphiaOrg/morphia#1421]
**Summary**
In our app, we want to perform a "create new" operation, which rejects duplicate keys, in addition to a "replace" operation, which requires that the target entity already exists.  If I understand correctly, the save() method is essentially upsert(), which covers the general case but isn't always a perfect fit.

While this can be emulated using multiple steps, it loses atomicity, especially in a micro-service environment where you might have several instances of a service attempting the same operation simultaneously.

Hopefully I've just missed a feature that already exists?

**Proposed solution**
Add the following methods to Datastore:

*insert new entity, requiring uniqueness in key*
insert(T entity)
insert(Iterable&lt;T> entities)
insert(T entity, WriteConcern wc)
insert(Iterable&lt;T> entities, WriteConcern wc)

*replace existing entity, requiring that it exists*
replace(T entity)
replace(Iterable&lt;T> entities)
replace(T entity, WriteConcern wc)
replace(Iterable&lt;T> entities, WriteConcern wc)

**Describe alternatives you've considered**
Currently I check existence by attempting to query the key before doing the save().  This has performance penalties and is not atomic.

**Comment by evanchooly** [comment]
`insert()` already exists on `AdvancedDatastore` and is being bumped up to `Datastore` in 2.0.  With all the efforts put in to reducing the surface area of the API in 2.0, I'm not convinced that adding a `replace()` is a good idea.  Can you elaborate on how you see that being different than `save()`?

**Comment by wheezil** [comment]
Thanks for following up on this.  Good to know the insert() exists.  I
assume it fails on unique key violations?
The need for replace() is similar to insert() -- atomically validate an
implicit assumption of exist/notexist, which is hard to do otherwise.

The insert() case is admittedly more common and useful, because it supports
optimistic locking strategies on sequences.  The replace() case is perhaps
rare, but can deal with race conditions of integrating parallel source
deltas that collide, and if you service one delete and one update you want
the delete to win.

**Comment by evanchooly** [comment]
I was wondering if that'd be the case for `replace()`.  It's *almost* worth just deprecating `save()` altogether and breaking it out in to the atomic `insert()`/`replace()` like you're talking about here.  It would remove a fair bit of complicated logic trying to suss out how to deal with entities in `save()`.  I think the driver might have done something similar but i seem to recall a `save()`, too.  But that might be on `DBCollection` which morphia no longer uses.  

I'll dig in to that and see what's what.  I'm trying to align Morphia's terminology with the driver's for easier transitions anyway.  I'll keep you posted.  :)
