### ISSUE TITLE
Get a document as java object

### ISSUE THREAD

**Issue by sergioluc** [MorphiaOrg/morphia#1422]
Hello,
How can I get retrieve the document stored in the database as java object. My code is shown below:
`@Entity(value="finger", noClassnameStored=true)
public class RecordFinger {
    @Id private ObjectId id;
    @Property private String name;
    @Embedded private FingerprintTemplate fingertemp;
    public RecordFinger(){

    }
    public RecordFinger(String name)
    {
        this.name=name;
    }
    public ObjectId getId() {
        return id;
    }

    protected void setId( final ObjectId id ) {
        this.id = id;
    }
    public FingerprintTemplate getTemplate(){
        return template;
    }
    public void setTemplate(FingerprintTemplate template){
        this.template=template;
    }
`
and the document structure is like this:
`"Name":"XXX",
 "Fingertemplate":{ "immutable" : { "size" : { "x" : 388 , "y" : 374} , "minutiae" : [ ............`

So I wanna retrieve the document as java object then extract the fingerprint template object to match it with another fingerpirnt template object

    Server Version:MongoDb 4.2.3
    Driver Version: mongodb-driver 3.12.0
    Morphia Version: 0.107

**Comment by evanchooly** [comment]
The version you're using is years out of date.  please upgrade to 1.5.8 and see https://morphia.dev for reference materials.

**Comment by evanchooly** [comment]
closing this for now.  if you have more specific questions, we can deal with them then.
