### ISSUE TITLE
Missing dev.morphia.morphia:util:pom:2.0.0-BETA1

### ISSUE THREAD

**Issue by diogocarleto** [MorphiaOrg/morphia#1424]
Trying to build a project using:
`<dependency>
        <groupId>dev.morphia.morphia</groupId>
        <artifactId>morphia-core</artifactId>
        <version>2.0.0-BETA1</version>
      </dependency>`

I've got the error
Failure to find dev.morphia.morphia:util:pom:2.0.0-BETA1 in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository,

I've inspected the pom.xml from morphia-core and there is the dependency declared:
`<dependency>
            <groupId>dev.morphia.morphia</groupId>
            <artifactId>util</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>`

The dev.morphia.morphia:util doesn't exists on maven repo.

**Comment by evanchooly** [comment]
Curious.  It would seem all my tests have run on machines where I also build morphia.  I have that fixed now on master but in the meantime, you can simply excluded that dependency from the `morphia-core` dependency and everything should work fine.  If you're not sure how to do that let me know and I'll get you sorted.

Sorry for the glitch and thanks for giving the beta a try.

**Comment by Vinarnt** [comment]
In gradle I fixed it like this:
`    implementation 'dev.morphia.morphia:morphia-core:2.0.0-BETA1'
    implementation('dev.morphia.morphia:util:1.4.1') {
        force = true
    }`

**Comment by evanchooly** [comment]
@Vinarnt you should just exclude `util` but yes `bytebuddy` is required.  I should just push a -BETA2 to clean that up.

**Comment by Vinarnt** [comment]
Yes you are right.

`
    implementation('dev.morphia.morphia:morphia-core:2.0.0-BETA1') {
        exclude group: 'dev.morphia.morphia', module: 'util'
    }
    implementation group: 'net.bytebuddy', name: 'byte-buddy', version: '1.10.8'
`
