### ISSUE TITLE
2.0-BETA?

### ISSUE THREAD

**Issue by MaxxQc** [MorphiaOrg/morphia#1431]
Hey guys,
I've been trying to find an answer online but I didn't find anything. I'm trying to use Morphia 2.0.0-BETA1 on intellij but I always get some errors. It works fine using the 1.5.8 version though, I just wanted to upgrade.

Thanks in advance

**Comment by evanchooly** [comment]
Well, what are the errors?

**Comment by MaxxQc** [comment]
Actually it's looking for morphia in one of my repository even though morphia is present on the central. And if I remove my repository and try it says "Could not find artifact dev.morphia.morphia:util:pom:2.0.0-BETA1 in central (https://repo.maven.apache.org/maven2)"

**Comment by evanchooly** [comment]
Yeah, there were some [packaging issues](https://github.com/MorphiaOrg/morphia/issues/1424) that have been cleaned up in master.  Note the addition of `bytebuddy` in the comments.

**Comment by MaxxQc** [comment]
So, is there any fix available?

**Comment by evanchooly** [comment]
The fix is described in the issue I linked.

**Comment by MaxxQc** [comment]
I just don't know how to excluse something from an artifact

**Comment by evanchooly** [comment]
like so:

```xml
<dependency>
    <groupId>dev.morphia.morphia</groupId>
    <artifactId>morphia-core</artifactId>
    <version>2.0.0-BETA1</version>
    <exclusions>
        <exclusion>
            <groupId>dev.morphia.morphia</groupId>
            <artifactId>util</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>net.bytebuddy</groupId>
    <artifactId>byte-buddy</artifactId>
    <version>1.10.1</version>
</dependency>
```
The first part will include `2.0.0-BETA1` and exclude the `util` module (which is only required by the morphia build and will also include `bytebuddy` wasn't included but should have been.

**Comment by MaxxQc** [comment]
Thanks!

**Comment by MaxxQc** [comment]
Sorry to bother once again, is it normal that I cannot create an instance of Morphia? 
'Morphia()' has private access in 'dev.morphia.Morphia'
