### ISSUE TITLE
JDK mismatch causing compilation error

### ISSUE THREAD

**Issue by Pugabyte** [MorphiaOrg/morphia#1438]
Hi, I'm trying to build a jdk 1.8 project with Morphia 2.0.0-SNAPSHOT and i'm getting the following error:
```
[ERROR] /home/griffin/git/BNCore/src/main/java/me/pugabyte/bncore/models/MongoService.java:[3,19] cannot access dev.morphia.Datastore
[ERROR]   bad class file: /home/griffin/.m2/repository/dev/morphia/morphia/morphia-core/2.0.0-SNAPSHOT/morphia-core-2.0.0-SNAPSHOT.jar(dev/morphia/Datastore.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
```

Searching around I found out that this is caused by the mismatch in jdk versions, but I found [this comment](https://github.com/MorphiaOrg/morphia/issues/1317#issuecomment-458676146), so I'm not sure if something is configured wrong on my platform maybe? Some guidance would be greatly appreciated. Thank you

**Comment by evanchooly** [comment]
The minimum JDK version is 11.  https://morphia.dev/2.0.0-BETA2/getting-started/installation-guide/

**Comment by Pugabyte** [comment]
I've updated my JDK to Java 11 to experiment how it works within my environment, however I'm getting this error when shading morphia into my project: 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.1.1:shade (default) on project BNCore: Error creating shaded jar: Problem shading JAR /home/griffin/.m2/repository/dev/morphia/morphia/morphia-core/2.0.0-SNAPSHOT/morphia-core-2.0.0-SNAPSHOT.jar entry dev/morphia/mapping/experimental/SingleReference.class: java.lang.IllegalArgumentException -> [Help 1]
```

**Comment by evanchooly** [comment]
What's with the `-SNAPSHOT` reference there?  is this project on github that I can look at?

**Comment by Pugabyte** [comment]
![image](https://user-images.githubusercontent.com/12417961/78736250-b28e4400-791a-11ea-8fdb-3915ac86bdae.png)
I pulled the version from here. I wasnt sure which to use. I'll switch it to beta2. However my preliminary tests with jdk 11 are not looking good. Is there a reason JDK 11 is required? I think 8 is still widely popular and supporting JDK 8 may be worth looking into.

**Comment by Pugabyte** [comment]
After a lot more testing I was able to get JDK 11 working with my environment. I still believe Morphia would benefit from supporting JDK 8, but I digress. 

However, after getting it working, and being really pleased with how much better it was working than 1.5, I started running into issues. 

At just before midnight, everything was working extremely smoothly. Then this error appeared: https://paste.bnn.gg/gipiw
I didnt pay attention to it because I was focused on something else, and when I restarted the server these two errors appeared: https://paste.bnn.gg/azahi.groovy and https://paste.bnn.gg/letov.stylus
After this, I couldn't get anything to work again. I've restarted multiple times, I don't know what's causing it, I've tried dozens of different suggestions on google. Do you have any idea what could be happening?

**Comment by evanchooly** [comment]
You need to put either `@Entity` or or `@Embedded` on that type.  That's why it can't find a codec for it.  You need to tell Morphia to register it and map a codec for it.

As for the UUID bit, a few versions ago, the java driver stopped configuring a default UUID scheme to use so if you bring your own `MongoClient` to Morphia, you need to configure it like what is done [here](https://github.com/MorphiaOrg/morphia/blob/master/morphia/src/main/java/dev/morphia/Morphia.java#L35).

The null pointer i'll have to dig in to but try fixing these two first and see if the NPE persists.

**Comment by evanchooly** [comment]
All better?
