### ISSUE TITLE
beans with lazy loaded references are not serializable via ObjectOutputStream

### ISSUE THREAD

**Issue by tobiaskohlbau** [MorphiaOrg/morphia#1439]
**Describe the bug**
Serialization of Objects with lazy loaded reference fails. It fails with error:
```
Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: dev.morphia.DatastoreImpl
```

**To Reproduce**
1. Enable lazy loading on references.
2. Use Morphia to load Object from DB and deserialize it.
3. Try to serialize this loaded object with ObjectOutputStream.
4. See error: No MongoCodec for DatastoreImpl.

**Expected behavior**
Serialization via ObjectOutputStream without errors.

** Please complete the following information: **
 - Server Version: 4.2.5
 - Driver Version: 3.11.2
 - Morphia Version: 1.5.8

**Additional context**
I searched a bit through the source code and found the underlying issue that's causing the shown error. If the reference has lazyloading enabled and the reference isn't fetched/unwrapped before serialization(OOT) of the object the error is caused by the following line:  https://github.com/MorphiaOrg/morphia/blob/c1769d11bf7348e1aeb3a1e9e0cb7b8d7c1e8990/morphia/src/main/java/dev/morphia/mapping/lazy/proxy/AbstractReference.java#L21. This line tries to serialize a Datastore within the ObjectOutputStream which is not possible and throws an NotSerializableException exception. 

This looks like a regression changed within 1.1.x branch as before that the implementation had a `DatastoreProvider` which is presumably serializable where as the `Datastore` introduced within 1.1.x does not have this capability. If needed I could try to assemble a minimal example.

### 1.0.x
https://github.com/MorphiaOrg/morphia/blob/00c9a442054bea50a934c1257868a6fee7aa1413/morphia/src/main/java/org/mongodb/morphia/mapping/lazy/proxy/AbstractReference.java#L19-L24
### 1.1.x
https://github.com/MorphiaOrg/morphia/blob/dc927ce210686605c24d5890a192e21267b52087/morphia/src/main/java/org/mongodb/morphia/mapping/lazy/proxy/AbstractReference.java#L19-L24

If you could point me to the right direction to solve this I'm more than happy to contribute. I thought about making the field `transient` as it shouldn't be serialized at all. Then I'm not aware how this object would be deserialized as the Datastore wouldn't be filled.

**Comment by evanchooly** [comment]
I had to dig through a number of versions to refamiliarize myself with all that as that feature went away years ago.  It was decommissioned for a number of reasons, however, and there are no plans to revive it.  Especially on the cusp of a cutover to a 2.0 release train with a vastly different internal architecture.  I would recommend using a DTO-style solution if you find yourself needing to serialize your entities.  I am sorry for the impact on your project but this feature is dead and all but buried at this point.
