### ISSUE TITLE
Consider a 1.6 release of the driver that is compatible with the 4.x Java driver

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#1440]
**Is your feature request related to a problem? Please describe.**
We would like to upgrade to a 4.x Java driver release but are not able to because there is not yet a Morphia release that is compatible with it.  And even after Morphia 2.0 is released, it could be a substantial amount of work to port our applications to it. For example, one internal application that uses Morphia has several hundred Morphia-related deprecation warnings that would need to be addressed before even starting to test against Morphia 2.0.

**Describe the solution you'd like**
Please consider doing a 1.6.0 minor release of morphia that depends on a 4.x release of the Java driver.   We've done some initial investigation and the work seems tractable.  The main incompatibility we've found is due to the removal of support for modifiers in `com.mongodb.client.model.DBCollectionFindOptions`, but it seems like it could be worked around.

**Describe alternatives you've considered**
We've considered forking Morphia privately and maintaining a branch off of 1.5.x that is compatible with the 4.x Java driver series, but we think that this work would be appreciated by the larger Morphia community.

**Comment by evanchooly** [comment]
I'm not sure i'm following.  This feels like it's part of a conversation from somewhere else.  I'm guessing that "a 1.6.0 minor release of the driver that depends on a 4.x release" means a morphia release though i'm not sure who the "we" is in all that.  the 1.5.x release should already work with a 4.0 driver provided the correct artifacts are included in the pom.  but i'll double check that at least.

**Comment by jyemin** [comment]
Yes, I meant a Morphia release.  The 1.5.x release doesn't quite work with the 4.0 driver, though it doesn't seem like it's too far off.

**Comment by jyemin** [comment]
Also, sorry, Justin, if the description is confusing.  Although I maintain the MongoDB Java driver, other teams at MongoDB build products implemented in Java that rely on both the driver directly _and_ on Morphia.  It's the maintainers of those products who I'm attempting to represent in this request. 

I'd be more than happy to discuss further if you'd like.

**Comment by evanchooly** [comment]
Yeah, that'd be great.  I'm trying to isolate any unavoidable breakages and provide migration paths to prep.  A 1.6 had been on my mind to provide a clean "if you compile here 2.0 should be an easy transition" kinda thing.   Apart from the `modifiers` change it would certainly help to know of any breaks they're running in to.  I should have most of them covered but there's a lot of cruft I'm trying to clean up so I could very well have missed a few here and there.
