### ISSUE TITLE
How to move embedded indexes to the recommended parent entity

### ISSUE THREAD

**Issue by stzanakis** [MorphiaOrg/morphia#1441]
Hi there!

I'm getting the following error when connecting to my db:
dev.morphia.IndexHelper:164 [main] - Embedded index generation is being removed from 2.0.  Please migrate any index definitions you need to the parent entity to ensure these indexes continue to be generated in future versions.

The structure of my classes looks something like this:
```
@Entity
class A{
private List<AbstractB> items = new ArrayList<>();
}

@Embedded
abstract class AbstractB{
@Indexed
String id
}
```

How can I move to the "new" way, to prepare the code for version 2.0?

I have tried, without success(The index is not created on ensureIndexes):

```
@Entity
@Indexes({@Index(fields = {@Field("items.id")})})
class A{
private List<AbstrctB> items = new ArrayList<>();
}

@Embedded
abstract class AbstractB{
String id
}
```

Version information:
Server Version:3.6.15
Driver Version:3.9.1
Morphia Version:1.5.8

**Comment by evanchooly** [comment]
Indexes aren't generated for abstract classes.  If you explicitly map the subclasses for that abstract class or map the entire package containing those classes, you should see you indexes show up.

**Comment by stzanakis** [comment]
Hi and thanks for the reply.

I do indeed _morphia.map();_ the subclasses of that abstract class and I do have the indexes created in the db, so the creation of the indexes is not the issue.
What I'm trying to figure out is how can I fix the warning, that I'm getting from morphia about embedded indexes, I mentioned above.. 

> dev.morphia.IndexHelper:164 [main] - Embedded index generation is being removed from 2.0. Please migrate any index definitions you need to the parent entity to ensure these indexes continue to be generated in future versions.

How can I fix this and comply to what morphia is telling me?

**Comment by stzanakis** [comment]
Defining the indexes on the parent entity worked finally, with the test I tried initially..
Not sure why it didn't work before, perhaps some building mismatch..
So I'm closing this issue
