### ISSUE TITLE
Sorting on tail is not allowed

### ISSUE THREAD

**Issue by svenkubiak** [MorphiaOrg/morphia#1451]
I am trying to debug an

> WARN dev.morphia.query.MorphiaQuery - Sorting on tail is not allowed. 

I am following one of the unit tests as followed:

```
  List<Rectangle> results = getDs().find(Rectangle.class).iterator(new FindOptions()
   .sort(descending("myfield")))
   .toList();
```
which outputs the warning above and as a result sorting does not work.

Update:
So from the code and documentation it looks like .iterator(FindOptions ...) is afaik the only way to set sorting for queries. But once done, the second validation in prepareCursor (MorphiaQuery) is

```
 if (findOptions.getCursorType() != NonTailable && (findOptions.getSort() != null)) {
            LOG.warn("Sorting on tail is not allowed.");
        }
```

However, you to set sorting any other way?

** Please complete the following information: **
    Server Version: 4.2.7
    Driver Version: 2.0.0-RC1
    Morphia Version: 2.0.0-RC1

**Comment by evanchooly** [comment]
I think the problem here is that default value for the cursor type is actually *null* so that first check fails of course.  I'll do some tests to confirm (and see why/if that doesn't show up in the test logs).

**Comment by ryanwlb** [comment]
use order teplace sort?
