### ISSUE TITLE
how to set print?

### ISSUE THREAD

**Issue by ryanwlb** [MorphiaOrg/morphia#1452]
** Please ask your question and provide whatever background or supporting information you think might be relevant: **
how to set print nosql at my idea console window?like mybatis sql，I don't how to set,I set <logger level="DEBUG" name="org.mongodb.morphia"/> at my log4j2.xml but it can't print
** Please complete the following information: **
    Server Version:
    Driver Version:3.4.2
    Morphia Version:1.3.2

**Comment by evanchooly** [comment]
There isn't anything like that on that version, especially.  What you can do is to add a comment on the query (via the options, iirc) and then check the logs on the server for that.
