### ISSUE TITLE
Extra unwanted backslash in Morphia Query object

### ISSUE THREAD

**Issue by sahar922** [MorphiaOrg/morphia#1453]
I'm using Morphia 1.5.8 (Java 8) MongoDB (V4.x), trying to use [Search for a phrase](https://docs.mongodb.com/manual/reference/operator/query/text/#search-for-a-phrase), so my code looks like :

`datastore.find(myEntity).disableValidation().search("\\\"" + textToFilter + "\\\"");`

Debug looks good, but in running time the query is being sent with the three backslashes instead of just one, and the query return 0 results.

What am I missing? thanks!

actual generated query: `"$text" : { "$search" : "\\\"filteredText\\\"" }`

1. Create a TEXT index
2. Try search by text with `\"` prefix and suffix
3. execute

**Expected behavior**
The query should be `\"filteredText\"
`
** Please complete the following information: **
 - Server Version: 4.X
 - Morphia Version: 1.5.8

**Comment by evanchooly** [comment]
try this:

```java
datastore.find(myEntity).disableValidation().search("\"" + textToFilter + "\"");
```

Though i have to ask, are you searching for that text wrapped in quotes?  i.e. are you trying to find `"something"` or just `something`?  If it's the latter then you can simply pass `textToFilter` to `search()`.

**Comment by sahar922** [comment]
thanks, @evanchooly ,
already tried, didn't work.

I am trying to search using TEXT index (not regular regexp) but I want to search for the whole praise without tokenizing my phrase to search.
e.g "myEmail@gmail.com" without the `/"` prefix and suffix will be tokenized to **myEmail OR Gmail OR com**

according to MongoDB - it is possible to search by the whole phrase using this prefix and suffix, and it is working for me when I'm trying to query the Mongo directly.

I do think it is a bug because it does not seem like JAVA issue, I have many places which I use special characters and it is working well.

somehow - the Query object does not encode the \\\ well.

thanks again,

**Comment by sahar922** [comment]
Thanks @evanchooly , can't believe I missed it!
