### ISSUE TITLE
explore UUID type conflicts

### ISSUE THREAD

**Issue by evanchooly** [MorphiaOrg/morphia#1454]
details:  https://jira.mongodb.org/browse/JAVA-3759

**Comment by evanchooly** [comment]
confirmed type 3 UUIDs can be persisted and loaded.

**Comment by arushi-dhunna** [comment]
Hi @evanchooly 
Issue was not with UUID type 3, but with type 4.
We are getting Binary insteadof UUID type 4 which is causing mapping exception and we are forced to add decodingHook

**Comment by evanchooly** [comment]
Type 4 has always been supported. There are unit tests to verify those.
