### ISSUE TITLE
bad class file: DeleteOptions

### ISSUE THREAD

**Issue by JohannesFluegel** [MorphiaOrg/morphia#1455]
My build.gradle contains
```
compile 'dev.morphia.morphia:morphia-core:2.0.0-RC1'
```
When I perform the gradle task `compileJava`, I will get the error
```
> Task :compileJava FAILED
C:\...\MyClass.java:14: error: cannot access DeleteOptions
import dev.morphia.DeleteOptions;
                  ^
  bad class file: C:\...\.gradle\caches\modules-2\files-2.1\dev.morphia.morphia\morphia-core\2.0.0-RC1\...\morphia-core-2.0.0-RC1.jar(dev/morphia/DeleteOptions.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

FAILURE: Build failed with an exception.
``` 
What can I do about it?

**Comment by evanchooly** [comment]
Are you compiling with a Java 11 JDK?  That's the minimum required version for 2.0.0.

https://morphia.dev/2.0.0-RC1/getting-started/installation-guide/

**Comment by JohannesFluegel** [comment]
Hi @evanchooly, thanks for your answer. Now I understand the error message: we use Java 8, and therefore 11 - 8 = 55.0 - 52.0 = three missing versions.
