### ISSUE TITLE
How to improve performance while building objects

### ISSUE THREAD

**Issue by Piskel** [MorphiaOrg/morphia#1457]
Hi,

So I have a large mongo database with heavy documents, and building the objects with `.find().toList()` is my biggest bottleneck right now and I couldn't find a way to improve it. Unfortunately I can't use projections to get only the field I need because I need all the fields, apart from linked objects.

The time it takes to build 120K items (which are quite big) is around 80 seconds and it's too long for my application. (I'm trying to replace an ObjectId with another, everywhere where it might be used)

Is there any way you're aware of that could help us get better performances?

I'm using 1.5.3

Thank you.

**Comment by evanchooly** [comment]
`toList()` will pull them all in to memory first.  Why not "stream" the results through and process as you iterate?  Right now you're iterating at least twice over all the returned results.

What change are you trying to make exactly?  Could it be done with an update directly in the server rather than pulling in all the objects in to memory to manipulate?

**Comment by Piskel** [comment]
Thank you, i will try the "stream" approach tomorrow but it seems difficult considering the problem.

What I'm trying to do is to replace all occurences of say, `ObjectID(a)` in a collection by `ObjectId(b)`. The problem is that this ObjectId(a) could be in several fields (I don't know how many, but it's a lot) so that's why I'm doing it in Java.

**Comment by Piskel** [comment]
I'm closing the issue because I've been able to solve my problem by not building all the objects -- I'm first selecting only the objects that actually have the value I want to change in them.

> Could it be done with an update directly in the server rather than pulling in all the objects in to memory to manipulate?

I would still be interested in knowing if you can actually do this in mongoDB. I know you can do this on text fields by indexing all the fields but as far as I know, you can't do it directly in mongo for ObjectIds

Thank you for your time.

**Comment by evanchooly** [comment]
You can change any field in a document via an update except the `_id` field.  So an update should work.  If you're updating multiple fields, you might need to do it in multiple updates so that your query matches limit the documents being updated but it should be doable.
