### ISSUE TITLE
Maven central missing latest versions

### ISSUE THREAD

**Issue by Javabien** [MorphiaOrg/morphia#1459]
I would like to use the latest version of this library, but in maven central, the latest version is 1.3.2 (added 3 years ago):
https://repo.maven.apache.org/maven2/org/mongodb/morphia/morphia/

Any reason why versions up to 1.5.8 are missing?

**Comment by Javabien** [comment]
I found the answer:
```xml
<dependencies>
    <dependency>
        <groupId>dev.morphia.morphia</groupId>
        <artifactId>core</artifactId>
        <version>1.5.8</version>
    </dependency>
</dependencies>
```

Just not sure the difference, from version 2.0 the artifact name is `morphia-core` and there's also a `morphia` artefact, so many renaming, it's kind of confusing.
```xml
<dependencies>
    <dependency>
        <groupId>dev.morphia.morphia</groupId>
        <artifactId>morphia-core</artifactId>
        <version>2.0.0-RC1</version>
    </dependency>
</dependencies>
```

**Comment by evanchooly** [comment]
With 1.4 morphia was moved out of MongoDB's control to the community project which necessitated the need for a GAV change.  It was noted after that was done that `core` alone led to a `core.jar` in a project which, if say, put in war file might conflict with any other artifact named simply `core`.  To avoid those kinds of conflicts, the artifact was renamed in 2.0 to be more unique.

**Comment by Javabien** [comment]
@evanchooly Thanks for the explanations!
