### ISSUE TITLE
datastore.save(List<T> entities) cause no initial value on `@Version` field

### ISSUE THREAD

**Issue by wilnguyen** [MorphiaOrg/morphia#1464]
**Describe the bug**
Create new entities with datastore.save(List<T> entities) cause no value generated on `@Version` field.
It's caused by the method save(List<T> entities) using bulkUpdate without initial `@Version` value.

**To Reproduce**
1. Create some new entities with unseted value on `@Version` field.
2. Run datastore.save(List<T> entities)
3. Make some update with the returned entities or use datastore.find(clazz).first() to fetch it.
4. Save the edited entities with datastore.save(entity)
5. See error `Exception in thread "main" java.util.ConcurrentModificationException: Entity of type com.domain.Customer (id=5f091547069f4f29c6fe6e14) was concurrently modified.
	at dev.morphia.DatastoreImpl.tryVersionedUpdate(DatastoreImpl.java:561)`

**Expected behavior**
. Method datastore.save(List<T> entities) should take care of `@Version` field as datastore.save(T entity)

** Version affected: **
 - Driver Version: mongo-java-driver:3.12.6
 - Morphia Version: morphia-core:2.0.0

**Work around**
Currently, I use `@PrePersist` to set version to default value if null because Morphia do not allow to set  initial value on version field. `
    @PrePersist
    void onSave() {
        this.version = defaultIfNull(this.version, 1l);
    }`

**Comment by evanchooly** [comment]
I'm reasonably sure there's a test case for this already.  Could you create a [reproducer](https://github.com/MorphiaOrg/reproducer) for me and I'll take a look?

**Comment by wilnguyen** [comment]
Sure  @evanchooly . Please take a look on my[ fork repo](https://github.com/wilnguyen/reproducer)
I added my db configuration in the test so you can have more detail of my case.

**Comment by evanchooly** [comment]
I'll try to take a look this weekend.

**Comment by evanchooly** [comment]
*sigh*.  found it.  the "save many" path doesn't check for versioning.  it just hand off to the driver to save.  The save one path *does* check.  Guess which path is tested?
