### ISSUE TITLE
LoggerFactory not being instantiated 

### ISSUE THREAD

**Issue by nolawnchairs** [MorphiaOrg/morphia#1465]
Hi,

I created a Logger instance using the MorphiaLoggerFactory, and it's not working:

```
static {
    MorphiaLoggerFactory.reset();
    MorphiaLoggerFactory.registerLogger(MorphiaLoggerFactoryImpl.class);
}

public static class MorphiaLoggerFactoryImpl implements LoggerFactory {
    @Override
    public Logger get(Class<?> aClass) {
        // a class implemented by me
        return new MongoLogger();
    }
}
```

Before I upgraded from `1.3.2` to `1.5.8`, things worked fine - but now my logger isn't getting instantiated. I put a breakpoint in my debugger where `return new MongoLogger();` is, and it never gets hit. Is this not working now?

I'd like to turn off warnings, as I'm getting serious logging spam like this:
```
WARN  d.morphia.mapping.Mapper converted [] to null
WARN    d.m.query.FieldEndImpl Specified an empty list/collection with the 'associateId' criteria
```

It would be nice to turn these off, as my application works fine and I only care about errors at this point. Not sure if these are new warnings or it's a symptom of my logger not being used. It's still using my log4j binding.

** Please complete the following information: **
 - Server Version: 4.2
 - Driver Version:  
 - Morphia Version: 1.5.8

**Comment by evanchooly** [comment]
Well, there are two points to discuss here:

1.  the Morphia logger stuff is officially gone in 1.6.0 and morphia relies on slf4j for its logging, so
2.  You can simply configure whichever logger you prefer to exclude that package.  The tests log4j2 with an entry that looks like this:

```xml
<logger name="dev.morphia" level="warn">
            <AppenderRef ref="Console"/>
</logger>
```

I would suggest bumping up to 1.6.0 and seeing if that gets you the logging you'd want.  I don't know offhand why that logging broke on 1.5.x but chances are you won't need it.
