### ISSUE TITLE
Non Id ObjectIds not saving?

### ISSUE THREAD

**Issue by iron-59** [MorphiaOrg/morphia#1466]
** Please ask your question and provide whatever background or supporting information you think might be relevant: **

** Please complete the following information: **
    Server Version: 4.2
    Driver Version: 4.2
    Morphia Version: 1.6.0-RC1

I'm interested to know if saving an ObjectId inside of a class (not the Id) is supported. I'm using an ObjectId for the Users Id, and one for another Object I may need to reference. Whenever I load in the User from morphia, the other ObjectId is not set (it is not the users Id).

**Comment by evanchooly** [comment]
That shouldn't be a problem at all.  can you use the [reproducer](http://www.github.com/MorphiaOrg/reproducer) to recreate it for me and i'll take a look?

**Comment by iron-59** [comment]
> That shouldn't be a problem at all. can you use the [reproducer](http://www.github.com/MorphiaOrg/reproducer) to recreate it for me and i'll take a look?

ive never used it before but I could try

**Comment by evanchooly** [comment]
Any progress?

**Comment by iron-59** [comment]
Its fixed, sorry for not responding!
