### ISSUE TITLE
Migrate to 2.0.0 - Embedded annotation only for class now?

### ISSUE THREAD

**Issue by Peter0x48** [MorphiaOrg/morphia#1467]
Hi,

I'm updating my projects to Morphia 2.0 and I stumbled across the Embedded annotation because in the previous version I used that annotation on fields of an entity to Embed instances of my own project but also from other libraries where I cannot add the Embedded annotation to the class.

The [documentation](https://morphia.dev/2.0.0/guides/annotations/) for Embedded says:
> This annotation can be applied to the class of the embedded type **or on the field** holding the embedded instance.

Is that part of the documentation not updated? If yes, how can I now use instances of other libraries in my Entities?

Thanks!

**Comment by evanchooly** [comment]
I'm sorry.  I meant to respond days ago.  This is a use case that, honestly, i overlooked.  I made `@Entity` and `@Embedded` required to eliminate a number of bugs and complicated code paths with scanning packages.  However, it's a simple matter to map classes regardless if they are explicitly passed to `map()`.  I can add this in 2.1 and backport it as a bug fix for a 2.0.1.

**Comment by Peter0x48** [comment]
Hi,

Is this really fixed? In 2.1.4 die Annotation is not applicable to fields.

Thanks!
