### ISSUE TITLE
do we have anything like @JsonUnwrapped?

### ISSUE THREAD

**Issue by chenchenyangll** [MorphiaOrg/morphia#1469]
Hi, I wonder if we have anything like [@JsonUnwrapped](https://www.baeldung.com/jackson-annotations#3-jsonunwrapped)

**Comment by evanchooly** [comment]
The closest thing is `@Embedded` but it won't flatten in to the enclosing document like that.

**Comment by evanchooly** [comment]
I'm going to close this for now since the matter seems to be answered.
