### ISSUE TITLE
@embedded issue in version 2.0.0?

### ISSUE THREAD

**Issue by c4bles** [MorphiaOrg/morphia#1479]
Newbie to Morphia and have been trying to use latest Version 2.0.  It would appear @embedded is not working as expected in this release - using sample code (below) but getting an error "the annotation @embedded is disallowed for this location". Yet it works just fine using Version 1.6. 

Apologies if I'm missing something here.

@Entity
public class Hotel
{
    @Id
    private ObjectId    id;

    private String        name;
    private int            stars;

    public Hotel() {}

    public Hotel( String name, int stars )
    {
        this.name = name;
        this.stars = stars;
    }

    @Embedded
    private ArrayList< Location >    locations;

    public ObjectId getId() { return id; }
    public void setId( ObjectId id ) { this.id = id; }

    public String getName() { return name; }
    public void setName( String name ) { this.name = name; }

    public int getStars() { return stars; }
    public void setStars( int stars ) { this.stars = stars; }

    public ArrayList< Location > getLocations() { return locations; }
    public void setLocations( ArrayList< Location > locations ) { this.locations = locations; }

    public String toString()
    {
        String string = this.name + ", " + this.stars + " stars " + "[" + this.id + "]\n";

        for( Location location : this.locations )
            string += "    " + location.toString() + "\n";

        return string;
    }
}

    Server Version: 4.2.8
    Driver Version: 4.1.0
    Morphia Version: 2.0.0

**Comment by evanchooly** [comment]
`@Embedded` is only allowed on types in 2.0 so you'd declare that on your class.  It allow for mapping a type without requiring an `@Id` annotated field.
