### ISSUE TITLE
Docs consistency with deprecated status of createUpdateOperations

### ISSUE THREAD

**Issue by ppartarr** [MorphiaOrg/morphia#1482]
`createUpdateOperation` is marked as deprecated in Morphia 2.0.0 but is still used in all the Updating section of the docs: https://morphia.dev/2.0.0/guides/updating/

The `update` method on a `Datastore` shown in the docs for 2.0.0 throws an `UnsupportedOperationException`. If I understand correctly, `update` should now be used on a `Query`

Can you update the docs to show the idiomatic way of performing an update (as seen in the [quick tour](https://morphia.dev/2.0.0/getting-started/quick-tour/))?

**Comment by evanchooly** [comment]
I thought I'd gotten all those.  It's all cleaned up now.  In my mind, the API is simple enough to not warrant *too* much documentation but if you find it's too sparse, I'd be happy to round it out.    I didn't want to ramble on aimlessly so if there's something that's unclear to someone unfamiliar with the code and API, I'd love to document those pieces more clearly.
