### ISSUE TITLE
Migrating from createQuery() to find() doesn't work as expected

### ISSUE THREAD

**Issue by ppartarr** [MorphiaOrg/morphia#1488]
**Please ask your question and provide whatever background or supporting information you think might be relevant:**
Hi @evanchooly, I'm in the process of migrating from v1.6 to v2.0 and I'm having some trouble re-writing queries from `createQuery()` to `find()` because of some counter-intuitive behaviour

## Code snippets
When using 1.6 the following simple mongo query would work:
```
               PricingVersion potential = datastore.createQuery(PricingVersion.class).order("-createdAt").get();
               // null check and logging
              return potential;
```

In 2.0 this becomes:
```
               return datastore.find(PricingVersion.class)
                               .iterator(new FindOptions()
                                               .sort(descending("createdAt")))
                               .next();
```

However the MongoCursor throws a NoSuchElementException.

## Logs
After some digging in the logs I found that the mongo command has changed from (v1.6):
```
{"find": "PricingVersion", "sort": {"createdAt": -1}, "limit": 1, "$db": "datahub_v", ... }
```

to (v2.0):
```
{"find": "pricingVersion", "filter": {"_t": {"$in": ["PricingVersion"]}}, "sort": {"createdAt": -1}, "$db": "datahub_v", ...}
```

I would expect `{"find": "PricingVersion"}`

After reading through the source code I found I could workaround this issue by using `find(final String collection, final Class<T> type)` [from here](https://github.com/MorphiaOrg/morphia/blob/master/morphia/src/main/java/dev/morphia/DatastoreImpl.java#L219). My code became 

```
               return datastore.find("PricingVersion", PricingVersion.class)
                               .iterator(new FindOptions()
                                               .sort(descending("createdAt")))
                               .next();
```

But this still throws a NoSuchElementException...

Here is the mongo request log:
```
{"find": "PricingVersion", "filter": {"_t": {"$in": ["PricingVersion"]}}, "sort": {"createdAt": -1}, "$db": "datahub_v", ...}
```

How can I properly retrieve the list of PricingVersions from mongo in morphia v2.0?

## Additional info
In the migration to morphia v2.0, a field was removed in the PricingVersion class:
```
        # deprecated price curve
	@Reference
	@JsonAlias("curves")
	private Map<String, Curve> oldcurves = new HashMap<>();
```

On top of being deprecated, this field also caused problem in morphia 2.0 because the `@ Reference` annotation requires Map to have an id.

Is this related to the fact the query above is returning a NoSuchElementExceptionand not the list of pricing versions as expected?

## Aside - refactoring
In https://github.com/MorphiaOrg/morphia/blob/master/morphia/src/main/java/dev/morphia/query/MorphiaQuery.java#L62 you might want to change the order of the parameters from 
```
MorphiaQuery(final Datastore datastore, final String collectionName, final Class<T> clazz)
```
to 
```
MorphiaQuery(final Datastore datastore, final Class<T> clazz, final String collectionName)
``` 
to match the [overloaded constructor just below](https://github.com/MorphiaOrg/morphia/blob/master/morphia/src/main/java/dev/morphia/query/MorphiaQuery.java#L79) which looks like 
```
MorphiaQuery(final Datastore datastore, final Class<T> clazz, final Document query)
```

It makes it slightly more readable and less confusing when reading [this if statement](https://github.com/MorphiaOrg/morphia/blob/67e062219ec1ed1d7501b817daa10f87a370ef1f/morphia/src/main/java/dev/morphia/query/DefaultQueryFactory.java#L21)

Thanks for reading this far! 😄

**Comment by evanchooly** [comment]
What you're running in to is, well, two things:  a change in the default behavior and lack of sufficient documentation.  How are you building your `MapperOptions`?  *Are* you explicitly building a `MapperOptions`?  In 1.6 `dev.morphia.mapping.MapperOptions#builder()` was deprecated in favor of `dev.morphia.mapping.MapperOptions#legacy()` because some defaults were going to change.  If you don't use `MapperOptions` directly, you're getting the new defaults automatically.  

One of those changes is the ability to set collection/field naming strategies.  In the case of collections that is now `camelCase` which is what you're seeing.  If update your code to use `dev.morphia.mapping.MapperOptions#legacy()` when creating your `Mapper`, you'll get the "correct" class name.  You can also use `dev.morphia.mapping.MapperOptions#builder()` directly and just update the naming strategy to your personal preference.

This is a gap in the [migration docs](https://morphia.dev/2.0.0/getting-started/migration/) which I'll update shortly to correct.

And yes, that constructor order is annoyingly inconsistent.  :)

**Comment by ppartarr** [comment]
Thanks, I've updated the datastore creation to include the MapperOptions:
```
		MapperOptions mapperOptions = MapperOptions.builder()
				.collectionNaming(NamingStrategy.identity())
				.build();
		return Morphia.createDatastore(mongoClient, dbName, mapperOptions);
```

And now the Mongo command is using the correct collection naming strategy. However I'm still getting a NoSuchElementException. The resulting mongo query log is shown below:
```
# v2.0 with identity naming strategy
{"find": "PricingVersion", "filter": {"_t": {"$in": ["PricingVersion"]}}, "sort": {"createdAt": -1}, "$db": "datahub_v", ...}

# here is the v1.6 log as a refresher
{"find": "PricingVersion", "sort": {"createdAt": -1}, "limit": 1, "$db": "datahub_v", ... }
```

I am sure that the PricingVersion collection contains documents:
```
C:\Users\Philippe>mongo --port 27000 -u $username -p $password --authenticationDatabase $dbName
MongoDB shell version v4.2.1
...
rs0:PRIMARY> use datahub_v
switched to db datahub_v
rs0:PRIMARY> db.PricingVersion.count()
18
```

There are 3 differences between the v1.6 & v2.0 query:
1. v2.0 has a filter on the discriminator
2. PricingVersion class changed when upgrading morphia to v2.0
3. v1.6 has a limit

I think the NoSuchElementException is due to a combination of 1 & 2 but I'm not sure how to investigate this further.

For completeness, heres is the query:
```
               return datastore.find("PricingVersion", PricingVersion.class)
                               .iterator(new FindOptions()
                                               .sort(descending("createdAt")))
                               .next();
```

and the PricingVersion class:
```
@Entity
@JsonInclude(JsonInclude.Include.NON_NULL)
public class PricingVersion {

	@Id
	@JsonIgnore
	private ObjectId id;

	@JsonView(Views.Public.class)
	@JsonDeserialize(using = CreatedAtInstantDeserializer.class)
	private Instant createdAt;

	@JsonView(Views.Public.class)
	private String identifier;

        // REMOVED WHEN UPGRADING TO MORPHIA v2.0
	// @Reference
	// @JsonAlias("curves")
	// private Map<String, Curve> oldcurves = new HashMap<>();

	// todo comment back in when upgrading to morphia 2.0.1 or 2.1.0: https://github.com/MorphiaOrg/morphia/issues/1467
	// @Embedded
	private List<Curve> curvesList = new LinkedList<>();

	public PricingVersion() {
	}

	public ObjectId getId() {
		return id;
	}

	public void setId(ObjectId id) {
		this.id = id;
	}

	public Instant getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(Instant createdAt) {
		this.createdAt = createdAt;
	}

	public String getIdentifier() {
		return identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	@Deprecated
	@JsonIgnore
	public Map<String, Curve> getCurves() {
		return curvesList.stream().collect(Collectors.toMap(c -> Curve.encodedName(c.getName()), Function.identity()));
	}

	public List<Curve> getCurvesList() {
		return curvesList;
	}

	public void setCurvesList(List<Curve> curvesList) {
		this.curvesList = curvesList;
	}

        // REMOVED WHEN UPGRADING TO MORPHIA v2.0
	// @JsonIgnore
	// @Deprecated
	// public Map<String, Curve> getOldCurves() {
	//	return oldcurves;
	// }
}
```

Do you have any ideas where I'm going wrong?

**Comment by evanchooly** [comment]
What do your documents look like in the database?  It's probably the discriminator that's throwing things off.

**Comment by ppartarr** [comment]
### Here's an example PricingVersion document:
![pricingVersion](https://user-images.githubusercontent.com/16687219/93486844-eecfc280-f904-11ea-8ae3-075c558712a3.PNG)

### The embedded curve is a list of objects, each with a date and value. Here it is fully expanded:
![expanded](https://user-images.githubusercontent.com/16687219/93487084-38b8a880-f905-11ea-82a1-a0153248853e.PNG)

I'm guessing I have to specify the discriminator to be `com.mmxlabs.lngdataservice.pricing.model.PricingVersion` rather than just `PricingVersion`?

**Comment by evanchooly** [comment]
Yeah.  The simplest thing for you to do is to use [MapperOptions#legacy()](https://morphia.dev/1.6.0/javadoc/dev/morphia/mapping/MapperOptions.html#legacy()) when creating your `Datastore`.  There perks to using the modern configuration but it does involve data migrations when you have existing data.

I'm currently updating the migration docs to reflect all this but I'm battling hardware issues, too, so it's taking a bit longer.

**Comment by ppartarr** [comment]
I'll stick to `MapperOptions#legacy()` for now then. I'll keep an eye out on the docs and start planning the migration. Thanks for your help! 👍
