### ISSUE TITLE
Compatibility of Morphia 1.3.2 with mongoldb 4.x

### ISSUE THREAD

**Issue by a-panchenko** [MorphiaOrg/morphia#1490]
Hi. I've got quite a lot of legacy services that use Morphia 1.3.2 and mongodb 3.x
Now I need to migrate MongoDB to 4.x version. The thing is, I couldn't find any information if I can use Morphia 1.3.2 with MongoDB 4.x. Is it possible or I have to migrate to Morphia 2.0.0?

**Comment by evanchooly** [comment]
Chances are that it's not.  I don't remember the changes I had to make but part of the 1.6 release was a specific request from a team at MongoDB to support the 4.0 driver.  I would suggest upgrading to 1.6 as that change is far smaller.  It will get you to the 4.0 driver and you can baby step your way to 2.0 by cleaning up deprecations at your own pace.

**Comment by a-panchenko** [comment]
Ok, thanks.

**Comment by a-panchenko** [comment]
So, I've tried to use 1.6 release but I've got an exception:
```
java.lang.NoClassDefFoundError: com/mongodb/internal/binding/ReadWriteBinding
```
and it happens on the following line of code:
```
com.mongodb.MongoClient mongo = new com.mongodb.MongoClient("localhost", mongoDBPort);
```
Do you have an idea what I could to resolve the issue?

**Comment by evanchooly** [comment]
What do you have in your pom for the driver?  Here's what Morphia has in its pom:

```xml
<dependency>
   <groupId>org.mongodb</groupId>
   <artifactId>mongodb-driver-sync</artifactId>
   <version>${driver.version}</version>
</dependency>
<dependency>
   <groupId>org.mongodb</groupId>
   <artifactId>mongodb-driver-legacy</artifactId>
   <version>${driver.version}</version>
</dependency>
```

**Comment by a-panchenko** [comment]
I've got the same, driver version I've tried is 4.1.0

**Comment by evanchooly** [comment]
Odd.  Can you try to isolate that behavior in a [reproducer](https://github.com/MorphiaOrg/reproducer) and I'll take a look after these issues I'm working?

**Comment by a-panchenko** [comment]
Here's a fork https://github.com/a-panchenko/reproducer

So the problem seems to be 
```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.2.RELEASE</version>
</parent>
```
If I remove it then everything works like a charm.

**Comment by evanchooly** [comment]
It sounds like you're squared away.  If so, can we close this one out?

**Comment by a-panchenko** [comment]
Actually I don’t understand why adding spring boot as parent leads to such a problem and I still need spring boot. Ao the problem isn’t solved.

**Comment by evanchooly** [comment]
OK.  I'll play with the reproducer then and see if anything pops.

**Comment by evanchooly** [comment]
That version of spring-boot-starter-parent is bringing in a 3.11 dep on the mongodb classes.  bumping to `2.3.4.RELEASE` seems to fix your issue.

**Comment by a-panchenko** [comment]
Indeed, it fixed the problem. Thanks @evanchooly !
