### ISSUE TITLE
any hints at getting the depedency to kick in on intellij.. all annotation optiosn set.. maven pom all set.

### ISSUE THREAD

**Issue by johnda98** [MorphiaOrg/morphia#1493]
** Please ask your question and provide whatever background or supporting information you think might be relevant: **

@Entity not pulling in the dependency .. tried re-start.. pom has it..  setting have annotation all set .. compiler etc..
** Please complete the following information: **
    Server Version:
    Driver Version:
    Morphia Version: latest on the dev site.

**Comment by evanchooly** [comment]
Can you show your pom?  It only needs the one entry as shown on the website.  If your IDE isn't importing automatically, you might need to manually tell it to rescan the pom.

**Comment by johnda98** [comment]
I know lombok n springboot fairly well and annotations switches in intellij
setup etc..  Yep.. Reloaded maven.. Have the pom from the .dev site install
docs..

Ill send pom.. Bone simple .. Rebooted etc.. Usual ide tricks

Id hate to have to use eclipse.

Really dont want to use springboot w mongo on this new proj.

**Comment by johnda98** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.crob</groupId>
    <artifactId>modsim</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>11.0.2</version>
        </dependency>

        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>11.0.2</version>
        </dependency>


        
        <dependency>
            <groupId>org.mongodb.morphia</groupId>
            <artifactId>morphia</artifactId>
            <version>1.3.2</version>
        </dependency>



    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <release>11</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.4</version>
                <configuration>
                    <mainClass>org.crob.App</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>




PS I also tried the dev sites's 


<dependencies>
    <dependency>
        <groupId>dev.morphia.morphia</groupId>
        <artifactId>morphia-core</artifactId>
        <version>2.0.1</version>
    </dependency>
</dependencies>

**Comment by johnda98** [comment]
ok had to add to the module.. will try it for 
<dependencies>
    <dependency>
        <groupId>dev.morphia.morphia</groupId>
        <artifactId>morphia-core</artifactId>
        <version>2.0.1</version>
    </dependency>
</dependencies>


ok solved ! :-)
