### ISSUE TITLE
Guys n Gals.. can't you provide Examples of the new queries API  Query.. filter(Filters. .. etc there is NO documentation of examples

### ISSUE THREAD

**Issue by johnda98** [MorphiaOrg/morphia#1495]
Guys n Gals.. can't you provide Examples of the new queries API  Query.. filter(Filters. .. etc there is NO documentation of examples  .. except the following..  and even then you dont show the Object retrieved.. just counts etc.

I need to simply get the bloody object from the filter(filters) and the APi documentation on these new libs is very thin.. a few examples of simply how to get a single object ie a singleton from a collection  would be sooo nice.. not much on s/overflow or google

thanks
cheers

        Query<Employee> query = datastore.find(Employee.class);
        final long employees = query.count();

        Assert.assertEquals(3, employees);

        long underpaid = datastore.find(Employee.class)
                                  .filter(lte("salary", 30000))
                                  .count();
        Assert.assertEquals(1, underpaid);

        final Query<Employee> underPaidQuery = datastore.find(Employee.class)
                                                        .filter(lte("salary", 30000));
        final UpdateResult results = underPaidQuery.update(inc("salary", 10000))
                                                   .execute();

** Please complete the following information: **
    Server Version:
    Driver Version:
    Morphia Version:

**Comment by evanchooly** [comment]
https://morphia.dev/2.0.1/guides/querying/

Let me know if anything is missing but that should cover it.

**Comment by johnda98** [comment]
Not really useful examples.. What about getting 1 object? And all its
relayed objects.. Like a many to many

**Comment by evanchooly** [comment]
There's a `first()` method (working from memory as I don't have morphia on this machine).  As for many-to-many, the references guide should help:  https://morphia.dev/2.0.1/guides/references/.  Typically references aren't recommended when using MongoDB but there are cases where they're useful still.  But your model should avoid them if you can.

**Comment by johnda98** [comment]
Thnks this is excellent!!  Example.

**Comment by johnda98** [comment]
thanks yes I see now the new API and the disadvantages of Reference - thanks guys
