### ISSUE TITLE
Please Add Version Class to judge Morphia Version

### ISSUE THREAD

**Issue by ztechstack** [MorphiaOrg/morphia#1496]
Please Add a Version Class in Morphia, so I can compatible with 1.x and 2.x.

**Comment by evanchooly** [comment]
Are you talking about the [annotation](https://morphia.dev/2.0.1/javadoc/dev/morphia/annotations/Version.html)?

**Comment by ztechstack** [comment]
I want auto initialize different version of morphia bean using spring @ConditionalOnClass or @ConditionalOnMissingClass.

**Comment by evanchooly** [comment]
I don't understand what that means.

**Comment by ztechstack** [comment]
Here is an example:

    @Bean
    @ConditionalOnClass(dev.morphia.MorphiaV2.class)
    public Datastore datastore(MongoClient mongoClient, MongoProperties mongoProperty) {
        log.info("init morphia datastore");
        return Morphia.createDatastore(mongoClient, mongoProperty.getDatabase());
    }

    @Bean
    @ConditionalOnMissingClass(dev.morphia.MorphiaV2.class)
    public Datastore datastore(MongoClient mongoClient, MongoProperties mongoProperty) {
        Morphia morphia = new Morphia();
        morphia.mapPackage("xxx.xxx.xxx");
        return morphia.createDatastore(mongoClient, mongoProperty.getDatabase());
    }

**Comment by evanchooly** [comment]
I think I understand.  If you want to do that today, you can always switch on `MorphiaQuery.class` which is new 2.0.  There's a risk there that it's an internal class and might go away but it would work today at least.

Would this work as an enum?

```java
public enum MorphiaVersion {
  v160,
  v200,
  v201,
  v210,
  ...
}
```

Would that suffice?

**Comment by evanchooly** [comment]
Or would it be better to have classes scoped to a version that would vanish on the next release?

e.g.,  `Morpha160` in 1.6.0 gets renamed to `Morphia161` in 1.6.1 and then `Morphia200` in 2.0.0 etc.  ?

**Comment by evanchooly** [comment]
Note:  add a test to make sure the class get renamed according to current version in maven so that each release gets the appropriate indicator class.
