### ISSUE TITLE
No examples of how to Create, Update Delete  for 20. .. even the documented "UpdateOperations ops = datastore     .createUpdateOperations(Hotel.class)     .. does NOT exist .. it is 'UpdateOperators' ? instead ?

### ISSUE THREAD

**Issue by johnda98** [MorphiaOrg/morphia#1499]
sooooo.. MorphiaReference.wrap(entity obj) ;  will  create the relationship ?

UpdateOperations ops = datastore
    .createUpdateOperations(Hotel.class)
    .set("name", "Fairmont Chateau Laurier");
datastore.update(updateQuery, ops);

UpdateOperations class does not exist ?? moreover how does one create a new entity ? ie instantiate ? especially how does a user know what to use list,set,map ??

**Comment by evanchooly** [comment]
What version of Morphia are you using?

**Comment by evanchooly** [comment]
I'm not entirely sure what you're trying to ask here.

**Comment by johnda98** [comment]
the 2.0 in the dev dependency .. but I think we'll just go back to 1.4
until we get used to it.

Justin.. thanks alot for kind quick respond..   its a neat abstract.. we're
just under pressure to climb the learn curve quickly here.  ps. will
comment out other references here and try the .first() fetch again with
lazy true and other not used references commented out.. as a test.

yes first() was'nt hanging it when we had fewer or no references and we
saved them AFTER the object .. oops..

just couldnt find much documentation examples out there for 2.0 or 1.4 ..
the docs are good but its Examples that enables quick implement for
polyglot techs

*John D Allen.*


*T +1 417 849 0705 ** CST  | john.allen@leveridgesystems.com
<john.allen@leveridgesystems.com>  | https://www.leveridgesystems.com
<https://www.leveridgesystems.com> | linkedin.com/in/johndallen1
<http://linkedin.com/in/johndallen1> | skype john.allen_67
https://www.yourhashgraphtoken.com <https://www.yourhashgraphtoken.com>*


 Leveridge Systems INC. Reg Missouri Charter #01082460.  The information
contained in this email and any attached files is confidential and intended
solely for the addressee(s). The email may be legally privileged or
prohibited from disclosure and unauthorized use. If you are not the
named addressee you may not use, copy, or disclose this information to any
other person. If you received this message in error please notify the
sender immediately and permanently delete it from your system.

**Comment by johnda98** [comment]
closing
