### ISSUE TITLE
Reference error

### ISSUE THREAD

**Issue by dkulesevic** [MorphiaOrg/morphia#1500]
After switching to 2.0 i encountered a problem with references. Getting this error:
java.lang.IllegalStateException: unknown type for bson mapping: class com.mongodb.DBRef
	at dev.morphia.mapping.codec.reader.DocumentReader.getBsonType(DocumentReader.java:347)

I checked the DB and the previous version of morphia would map reference with something like this:
```
            "mediaItem" : {
                "$ref" : "MediaItem",
                "$id" : {
                    "className" : "some UID type of class",
                    "uuid" : "xxxxxxxxxxxxxxxxxxx"
                }
            }
```
and now when testing dummy class with the same type reference I get following in DB:
```
    "mediaItem" : {x
        "uuid" : "xxxxxxxxxxxxxxxxxxx"
    }
```

Was there a change how @Reference annotation is handled/saved?

**Comment by evanchooly** [comment]
In theory, no, nothing has changed.  Though I did, iirc, try to unify how the two reference implementations work internally so that might have introduced some drift.  I'll dig in to it.

**Comment by evanchooly** [comment]
If you could retry your test with 2.1.0-SNAPSHOT, i think i've fixed your problem.  If that works, i can backport and release a 2.0.2 with the fix.  you probably don't want to wait for 2.1.0 with this tripping you up.

**Comment by dkulesevic** [comment]
Hi,
I tried with 2.1.0-SNAPSHOT and I still got the same error and still see the same document created in the db with dummy class, no $ref information just the id. 
But maybe there are more things that could affect my testing, not sure what other changes 2.1.0-SNAPSHOT has.

**Comment by evanchooly** [comment]
could you attach the documents as seen by the mongo shell?  (`db.collection.find({...}).pretty()`) of just one of each type of entity.  I want to make sure I'm working with the correct document shape and it doesn't appear that I'm quite there yet.

**Comment by dkulesevic** [comment]
I will try to provide with simple case using 2.1.0, two entity classes:

```
@Entity(value = "Dummy", useDiscriminator = false)
public class Dummy {
    @Id
    private final Uid id;

    @Reference(value = "dummyRef", ignoreMissing = true)
    private final DummyRef dummyRef;

    protected Dummy() {
        id =null;
        dummyRef = null;
    }

    public Dummy(Uid id, DummyRef dummyRef) {
        this.id = id;
        this.dummyRef = dummyRef;
    }

    public Uid getId() {
        return id;
    }

    public DummyRef getDummyRef() {
        return dummyRef;
    }
}
```
```
@Entity(value = "DummyRef", useDiscriminator = false)
public class DummyRef {
    @Id
    private final Uid id;

    protected DummyRef() {
        id =null;
    }

    public DummyRef(Uid id) {
        this.id = id;
    }

    public Uid getId() {
        return id;
    }
}
```
After saving DummyRef first and than Dummy I get this in DummyRef:
```
{
    "_id" : {
        "uuid" : "54d98682-b686-4ded-9e80-d8fa92a8355b"
    }
}
```
and this in Dummy collection
```
{
    "_id" : {
        "uuid" : "d2b4839a-cba9-4551-a300-e6905c785de5"
    },
    "dummyRef" : {
        "uuid" : "54d98682-b686-4ded-9e80-d8fa92a8355b"
    }
}
```

It works in a such way that with newly saved documents, I can access the DummyRef after reading the Dummy object but the structure is different so our old documents throw the error I put in my original message.
java.lang.IllegalStateException: unknown type for bson mapping: class com.mongodb.DBRef

**Comment by dkulesevic** [comment]
If it may help, I'm testing locally with mongodb version 4.0.19

**Comment by evanchooly** [comment]
I'm having no luck recreating the issue.  My theory is that perhaps the driver simply isn't encoding the `DBRef` like it used to.  I can' play around with dropping the driver version back to 3.something and see.  But in the meantime, if you could look this over and see if I'm missing something that'd be really helpful.  Thanks.

**Comment by evanchooly** [comment]
I went as far back as 3.10 on the driver and 1.4 of morphia with no luck.  It still stores `Dummy` like this:

`{ "_id" : BinData(3,"dks7hJvAUYr0gPEBN9szrA=="), "dummyRef" : DBRef("DummyRef", BinData(3,"dks7hJvAUYr0gPEBN9szrA==")) }`

**Comment by dkulesevic** [comment]
Hi,
That is really strange. I'm using driver version 4.0.5.

**Comment by evanchooly** [comment]
Pfft.  forgot to link the repo:  https://github.com/evanchooly/dbRefs  That's what I get for working late nights.  :)  Anyway, if you could look at *that* and see what I'm missing...

**Comment by dkulesevic** [comment]
I tested your project and you are right, I don't see the error java.lang.IllegalStateException: unknown type for bson mapping: class com.mongodb.DBRef.

I also played with your tests a little bit, instead of new version of morphia reading the old version of morphia generated db I copied the generator part of test into new morphia version module and basically created two dbs, one generated by old morphia version and one generated by new morphia version (changed the db name of the old morphia version db to 'morphia_test_old). 
That way you can compare the documents created by two versions and you will see the difference, at least I see it. Now, maybe that is not a problem and that is what you expect from new version.

Second test I did was trying to generate a documents in the same db by both new and old versions and you still see the difference but now it is in the same collection, two documents with different reference look saved inside the same collection.
Reading is possible for both documents with the new version of morphia which is good.

```
/* 1 */
{
    "_id" : LUUID("764b3b84-9bc0-518a-f480-f10137db33ac"),
    "dummyRef" : {
        "$ref" : "DummyRef",
        "$id" : LUUID("764b3b84-9bc0-518a-f480-f10137db33ac")
    }
}

/* 2 */
{
    "_id" : LUUID("764b3b84-9bc0-518a-f580-f10137db33ac"),
    "dummyRef" : LUUID("764b3b84-9bc0-518a-f680-f10137db33ac")
}
```

Third test is something close to what we have, we don't use UUID as our ID class but we have our own, I will post simplified version for 1.6 and 2.1. I changed the id classes for Dummy and DummyRef to use that class.
1.6:
```
import java.util.UUID;

public class Uid {
    final String uuid;

    /**
     * Constructor. Simply creates a random UUID.
     */
    public Uid() {
        this.uuid = UUID.randomUUID().toString();
    }

    public Uid(String uuid) {
        this.uuid = uuid;
    }

    public String getUuid() {
        return uuid;
    }

    public boolean equals(Object obj) {
        boolean eq;
        if (this == obj) {
            eq = true;
        } else if (obj instanceof Uid) {
            Uid that = (Uid)obj;
            eq = that.uuid.equals(this.uuid);
        } else {
            eq = false;
        }

        return eq;
    }

    public int hashCode() {
        return this.uuid.hashCode();
    }
}
```

2.1:
```
import dev.morphia.annotations.Embedded;
import java.util.UUID;

@Embedded(useDiscriminator = false)
public class Uid {
    final String uuid;

    /**
     * Constructor. Simply creates a random UUID.
     */
    public Uid() {
        this.uuid = UUID.randomUUID().toString();
    }

    public Uid(String uuid) {
        this.uuid = uuid;
    }

    public String getUuid() {
        return uuid;
    }

    public boolean equals(Object obj) {
        boolean eq;
        if (this == obj) {
            eq = true;
        } else if (obj instanceof Uid) {
            Uid that = (Uid)obj;
            eq = that.uuid.equals(this.uuid);
        } else {
            eq = false;
        }

        return eq;
    }

    public int hashCode() {
        return this.uuid.hashCode();
    }
}
```
Saved documents by 1.6 version looks like this:

DummyRef
```
{
    "_id" : {
        "uuid" : "8a51c09b-843b-4b76-ac33-db3701f180f5"
    }
}
```

Dummy
```
{
    "_id" : {
        "uuid" : "8a51c09b-843b-4b76-ac33-db3701f180f4"
    },
    "dummyRef" : {
        "$ref" : "DummyRef",
        "$id" : {
            "className" : "com.foo.Uid",
            "uuid" : "8a51c09b-843b-4b76-ac33-db3701f180f5"
        }
    }
}
```

Try to read it via morphia version 2.1 and didn't get the exception but didn't get the reference object either, it was null, morphia didn't find it. Now maybe the combination of what we are doing is not correct, I don't know.
I hope this extra information helps.

**Comment by evanchooly** [comment]
I tried scanning this but it's a bit much to take in just now with $dayJob swirling but it looks promising at least.  I'll try to take a look tonight.  I can give you commit rights to that project if you'd like and we can massage things in to place to recreate this.

**Comment by evanchooly** [comment]
I just added you as a collaborator to that repro project.  if you could put your changes there it'd be a lot easier for me to walk through.  I have some vague ideas but seeing the code would help.

**Comment by dkulesevic** [comment]
I have pushed new branch 'inconsistent_behavior' I hope it will help. In that branch you should see both how saved documents look like with new and old version and the case where new version of morphia is able to read the document saved with the new version but fails to pick the reference document saved with the old version.
Now, maybe something in my setup is wrong. Still couldn't reproduce the error.

**Comment by evanchooly** [comment]
Just got back to this.  but yeah even your branch still works.  super frustrating.  I'm going to drop this from the 2.1 milestone largely for bookkeeping reasons as I'm getting close to ready to release 2.1.  But this is still very much on my mind.  Don't read too much in to that change.

**Comment by DanielForniessoria-TomTom** [comment]
Hi Evan, is there any update on what release version this fix could be into?
Otherwise we might need to start thinking on replacing all DBRefs with IDs and changing our code to compensate for it.

**Comment by evanchooly** [comment]
I'll add this to the 2.1.4 milestone so I don't lose track of it.  I'll see if I can figure out the missing pieces.

**Comment by evanchooly** [comment]
side note:  ID only is "better" if those references are to one type or to types that share a collection.  (Avoids needing to track the type/collection to query).  But I know if you have existing data with `DBRef` that change probably isn't trivial.

**Comment by evanchooly** [comment]
i've found the issue.  pondering the proper fix. should be today/tomorrow depending on how deep this rabbit hole goes.

**Comment by evanchooly** [comment]
OK.  Deeper hole than I expected but I think I've tracked it all down.  I pushed some slight tweaks to the test repo showing what I hope is that it's solved your issue.  I tweaked the 2.1 version to successfully load the 1.6 version.  If you could take a look and confirm that I'm seeing things correctly and whether or not there were any other oddities you want to discuss on this one.  Barring that I think we're finally close to putting this one to bed.  There's a 2.1.4-SNAPSHOT build already available that should have the fix so the test repo should be ready to run once you pull the updates.

**Comment by dkulesevic** [comment]
Hi,
I tested both the test repo and our own project. The issue looks fixed. I'm running into some other problems but the test repo is able to read old records and in our project I no longer see:
java.lang.IllegalStateException: unknown type for bson mapping: class com.mongodb.DBRef
at dev.morphia.mapping.codec.reader.DocumentReader.getBsonType(DocumentReader.java:347)
Thank you very much for your work. For now the issue looks fixed.

**Comment by iAmcR** [comment]
Hi @evanchooly I'm having a similar issue trying to migrate some documents using version 2.1.3 and the recent 2.1.4-SNAPSHOT. I didn't get any exceptions thrown, however, the @Reference documents didn't resolve. 

The references currently look like this in mongo shell: 

DBRef("collection_name", ObjectId("aaaabbbbccccddddeeee"))

Any ideas, what could be happening here? Could you please point to me where you do the actually reference resolution?

**Comment by evanchooly** [comment]
@iAmcR  Can you create a [reproducer](https://github.com/MorphiaOrg/reproducer) that shows the problem so i can dig in to what's happening?

**Comment by iAmcR** [comment]
@evanchooly No need. I was able to go back through my code and found where the error was. Happy to report this works both for morphia 2.1.3 and 2.1.4-SNAPSHOT. 

Thank you.

**Comment by iAmcR** [comment]
@evanchooly One thing that I see as a sort of regression, is the support for the @Id annotation in super classes like: 

```
@Reference
SuperModel referencedItem;
``` 

I'm getting the following exception: 

```
Caused by: dev.morphia.mapping.validation.ConstraintViolationException: Number of violations: 1 
ReferenceToUnidentifiable complained about com.foo.Parent.referenceChild : com.foo.Parent#referenceChild is annotated as a @Reference but the com.foo.SuperModel class is missing the @Id annotation
	at dev.morphia.mapping.validation.MappingValidator.validate(MappingValidator.java:69)
```

I know this was supported in previous versions, but now when the `@Reference` annotation is on a field with the super class as a type it doesn't realize that there is indeed an `@Id` annotation. 
 
I did a reproducer here to illustrate the issue: https://github.com/iAmcR/reproducer.git

Thank you.

**Comment by evanchooly** [comment]
Open a new issue please and I'll try to take a look over the weekend.  Thanks.

**Comment by iAmcR** [comment]
Ok will do
