### ISSUE TITLE
Is this the ONLY way to add a new Book to a List of Book for Author in 2.0.1 example

### ISSUE THREAD

**Issue by johnda98** [MorphiaOrg/morphia#1503]
see below this is a crazy way to add a new book to a list of books for author.. to read in the whole list then send the whole list to setList ??????    because when i do a single .add it pukes..

"  author1.getList().add(book1);

        datastore.save(author1);"

it pukes with null pointer exception.. SO i HAVE to do a full list set..    must be missing something here surely this cant be so..

     Query<Author> getauth = datastore.find(Author.class);

        Author foundauth = getauth.first();

        System.out.println("found .. " + foundauth.toString());

        List<Book> booksofauth = foundauth.getList();

        for (Book bookstring : booksofauth) {
            System.out.println(" book .. " + bookstring.toString());
        }

       // ok now lets add a book to the list

        final Book newbook= new Book("dogs of war");
        
         booksofauth.add(newbook);
         
         foundauth.setList(booksofauth);
         
         datastore.save(foundauth);

**Comment by evanchooly** [comment]
You have to initialize any Java reference before you can call methods on it.  So in `Author.addBook()`, I would simply check if `books` was null and init it before adding the new book.  it would be transparent outside the class and you needn't worry about it anywhere else.  But this actually isn't a Morphia issue either way.  It's just how Java works.

**Comment by johnda98** [comment]
Thanks, yes I should have included the code further up in my original post above.. yes the objects all instantiated and added successfully to mongo.. ignore the comments '/*'   that code was run first ie to populate mongo.. worked well (of course having to add books as a List.. thats fine on load-up.. but in a query and then a dd to the Books List .. the .add to the getter returns a null pointer.. so I have to use setList ie pull the entire List.. add 1, then use setList to add the List back just to add a single new book..  see it ?  thanks.    in the example on the Morphia site it shows well for 1.4.1 'elmer.getDirectReports().add(daffy); ... sooooooo.. I do the same to try and add to my Books list .. and null pointer EVEN though all objects instantiated.     Evan/Justin.. I can't see the Author.addBook() method in your example ?https://morphia.dev/2.0.1/guides/references/

 MongoConnectiontest conn = MongoConnectiontest.getInstance();

        conn.init();

        Datastore datastore = conn.getDatastore();

        // test MorphiaReference on Author and Book 1:M  to test my morpha class loader etc

        // create author and 2 books
/*
        final  Author author1 = new Author("Jane");

        datastore.save(author1);

        final  Author author2 = new Author("Bob");

        datastore.save(author2);

        // create 2 books by Jane

        final Book book1 = new Book("Jane's dog");

        datastore.save(book1);

        final Book book2 = new Book("Jane's cat");

        datastore.save(book2);



        // save the relation.. set the auth for all books

        book1.setAuthor(author1);
        datastore.save(book1);
        book2.setAuthor(author1);
        datastore.save(book2);
        //  AND have to fill the list up in author !

        List<Book> booksforthisauth = Arrays.asList(book1, book2);
        author1.setList(booksforthisauth);

        // the below DOES NOT work.. null pointer  BTW cant understand why I'm calling a getter to set ??
        // as per elmer.getDirectReports().add(daffy); !!
        // so this line below is junk.. i can only add a full list to add a new single book ??
        author1.getList().add(book1);

      // author1.getList().add(book2) returns null pointer.. error in morphia code

        datastore.save(author1);

*/


        // ok query Jane's book .. jeeeezus  get her first !

        Query<Author> getauth = datastore.find(Author.class);

        Author foundauth = getauth.first();

        System.out.println("found .. " + foundauth.toString());

        List<Book> booksofauth = foundauth.getList();

        for (Book bookstring : booksofauth) {
            System.out.println(" book .. " + bookstring.toString());
        }

       // ok now lets add a book to the list

        final Book newbook= new Book("dogs of war");

         booksofauth.add(newbook);

         foundauth.setList(booksofauth);

         datastore.save(foundauth);

/*

**Comment by johnda98** [comment]
author1.getList().add(book1);   returns null pointer .. but author1 is instantiated and so is the book1 prior to this call

final Author author1 = new Author("Jane");

and so is    final Book book1 = new Book("Jane's dog");

both saved to datastore prior to the .add call 


yes I am simply seeing if there is a way to add a new book to the List in Author .. without having to getList the entire list of Books to the main code and then call .add  and then write it back using setList..   seems high overhead.      I used .getList.add(newbook) yes was  instantiated before when using 1.4 and it was fine.   Cant see why the .add fails as I have the instances all happy and there

**Comment by johnda98** [comment]
Trying to add a new method to Author Entity so I can add a single book to the end of the List 

 // add a single book beta
    
    public void addBooktolist(final Book addbook) {
        list. ??????? (no .add)


    }
    

no joy..   ".add" doesnt come up for the list as it is a MorphiaReference

**Comment by johnda98** [comment]
amazed that Morphia does not update the Parent Objects List automatically when the Child Object has its object set.  ie new book belongs to existing author.. thats fine.. but THEN manually have to read the full Author's Book List and then set the entire Authors Book list ..   thought morphia would abstract that and add the Book automatically to that author's Book list once the author was set in the new Book object.

  // ok query Jane's book .. jeeeezus  get her first !

        Query<Author> getauth = datastore.find(Author.class);

        Author foundauth = getauth.first();

        System.out.println("found .. " + foundauth.toString());

        List<Book> booksofauth = foundauth.getList();

        for (Book bookstring : booksofauth) {
            System.out.println(" book .. " + bookstring.toString());
        }

       // ok now lets add a book to the list

        final Book newbook= new Book("dogs of war II");

        // wow.. set author.. to be expected.. which Morphia should also
        // as an abstraction.. update the List of that author under the covers.
        // but it appears not to

        newbook.setAuthor(foundauth);

        // then save

        datastore.save(newbook);

        // add it to internal List

         booksofauth.add(newbook);
         
        // set the new list (in its entirerity!)
        
         foundauth.setList(booksofauth);

        // save author .. with new list

         datastore.save(foundauth);

         

         // finally get list to see if its added new book

        List<Book> booksofauth2 = foundauth.getList();

        for (Book bookstring : booksofauth) {
            System.out.println(" book .. " + bookstring.toString());
        }

**Comment by johnda98** [comment]
public Author(String name) {
        this.name = name;
    }

needed for https://morphia.dev/2.0.1/guides/references/

**Comment by johnda98** [comment]
?

**Comment by richarddd** [comment]
@evanchooly please close this

**Comment by evanchooly** [comment]
Yeah.  This one's been addressed.
