### ISSUE TITLE
Why is deprecated code for 2.0.1 still in the 2.0.1 example docs on the site ?  not helping.. 

### ISSUE THREAD

**Issue by johnda98** [MorphiaOrg/morphia#1505]
see attached pic  createQuery is deprecated and yet is in the sample code ?

for the life ?? how on earth do you put a results set of many objects from a Query into a List<> ?  again .. no examples of a common query.. just exotic ones

pls help- thanks guys..   more example of 2.0.1 without the old code
![Screenshot from 2020-10-06 14-46-21](https://user-images.githubusercontent.com/13384285/95252825-25ea1300-07e3-11eb-9a23-e218b0d9714c.png)

**Comment by johnda98** [comment]
wow.. we found MorphiaCursor toList .. no examples of course.. cool

**Comment by evanchooly** [comment]
A `Query` is actually an `Iterable` so it can be iterated directly without needing to convert to a `List`, necessarily.  And, of course, `toList()` is there if you really need it but it's not necessarily recommended especially with large query results.  I'll definitely take a look at the examples, though.

**Comment by richarddd** [comment]
> wow.. we found MorphiaCursor toList .. no examples of course.. cool

@johnda98 This library is open-sourced and free to use. Feel free to submit a PR if you want improvements of any kind and be more professional in your issues. I would also recommend doing some proper investigation on how to submit issues/bug reports before submitting ones like this.
