### ISSUE TITLE
Cascading Generics are not correctly mapped

### ISSUE THREAD

**Issue by Homer1991** [MorphiaOrg/morphia#1506]
**Describe the bug**
Similar to https://github.com/MorphiaOrg/morphia/issues/1481

When having cascaded generics the type is not correctly mapped.

**To Reproduce**
See code example under *Additional context*

**Expected behavior**
UUID is mapped to UUID instead of Binary

 - Server Version: 4.0.17
 - Driver Version: 4.0.5
 - Morphia Version: 2.0.1

**Additional context**
```java
@Entity
public class GenericEntity<T> {
	@Id
	protected T id;
	protected T test;
	protected UUID test2;

	public T getId() {
		return id;
	}

	public void setId(T id) {
		this.id = id;
	}

	public T getTest() {
		return test;
	}

	public void setTest(T test) {
		this.test = test;
	}

	public UUID getTest2() {
		return test2;
	}

	public void setTest2(UUID test2) {
		this.test2 = test2;
	}
}
```

```java
@Entity
public class SpecificEntity<ID> extends GenericEntity<ID> {
	private long number;

	public long getNumber() {
		return number;
	}

	public void setNumber(long number) {
		this.number = number;
	}
}
```

```java
@Entity
public class MoreSpecificEntity extends SpecificEntity<UUID> {
	private long number2;

	public long getNumber2() {
		return number2;
	}

	public void setNumber2(long number2) {
		this.number2 = number2;
	}
}
```

```java
	public static void main(String[] args) {

		CodecRegistry codecRegistry = CodecRegistries.fromRegistries(
				CodecRegistries.fromProviders(new UuidCodecProvider(UuidRepresentation.STANDARD)),
				MongoClientSettings.getDefaultCodecRegistry());

		final Datastore datastore = Morphia.createDatastore(
				MongoClients.create(MongoClientSettings.builder()
						.applyConnectionString(new ConnectionString("mongodb://127.0.0.1/"))
						.uuidRepresentation(UuidRepresentation.STANDARD).codecRegistry(codecRegistry).build()),
				"morphia_example");

		datastore.getMapper().mapPackage("de.test");

		datastore.ensureIndexes();

		MoreSpecificEntity beforeDB = new MoreSpecificEntity();
		beforeDB.setId(UUID.randomUUID());
		beforeDB.setTest(UUID.randomUUID());
		beforeDB.setTest2(UUID.randomUUID());
		beforeDB.setNumber(13);
		beforeDB.setNumber2(14);
		datastore.save(beforeDB);

		MoreSpecificEntity fromDB = datastore.find(MoreSpecificEntity.class).filter(Filters.eq("_id", beforeDB.getId()))
				.first();

		System.out.println(fromDB);

		datastore.getDatabase().getCollection("specificEntity").deleteMany(new BasicDBObject());
	}
```

![image](https://user-images.githubusercontent.com/1589934/95342133-5e5b2100-08b7-11eb-8d7d-7a2f63460bc6.png)

**Comment by evanchooly** [comment]
This actually like it might be related to changes i made trying to fix #1500.  Can you give 2.1.0-SNAPSHOT a try and see if that fixes your issue?

**Comment by Homer1991** [comment]
@evanchooly 
Unfortunately it also doesn't work with 2.1.0-SNAPSHOT
![image](https://user-images.githubusercontent.com/1589934/95439734-4e474e00-0958-11eb-8d7d-5934deab5b05.png)

**Comment by evanchooly** [comment]
Piffle.  Ok.  I'll dig in to it.  Thanks.

**Comment by Homer1991** [comment]
@evanchooly
do you know when you will investigate this bug?

**Comment by evanchooly** [comment]
I've been working it pretty hard the last several nights.  I had a nice clean fix but it made test runs 5x slower.  So I'm taking the lessons learned and trying a simpler fix.  Hopefully the next day or two will set it done.

**Comment by Homer1991** [comment]
thanks for the quick update ;)

**Comment by Homer1991** [comment]
@evanchooly 

For some reason its broken again :/

I've tried `2.1.0`, `2.1.0-SNAPSHOT` and `2.2.0-SNAPSHOT` non of them are working right now for me.
But i know that `2.1.0-SNAPSHOT` was working at some point with my code, i'm not sure if the problem now is on my side or if there still is a bug.

![image](https://user-images.githubusercontent.com/1589934/99402806-09fd8500-28ea-11eb-8a61-16ef431899b8.png)

**Comment by evanchooly** [comment]
Hrm.  that's odd.  pretty sure there's a test for that but i'll try to double check it tonight.

**Comment by Homer1991** [comment]
yes i've also seen the test. thats why i'm not sure if the problem is in my code example

**Comment by evanchooly** [comment]
everything in that image looks ok from here at least

**Comment by Homer1991** [comment]
the missing part on top is just:
```
public class Test {
	public static void main(String[] args) {

		CodecRegistry codecRegistry = CodecRegistries.fromRegistries(
				CodecRegistries.fromProviders(new UuidCodecProvider(UuidRepresentation.STANDARD)),
				MongoClientSettings.getDefaultCodecRegistry());

		final Datastore datastore = Morphia.createDatastore(
				MongoClients.create(MongoClientSettings.builder()
						.applyConnectionString(new ConnectionString("mongodb://10.9.1.235/"))
						.uuidRepresentation(UuidRepresentation.STANDARD).codecRegistry(codecRegistry).build()),
				"morphia_example");

...
```

dont know if there is something missing configuration wise

**Comment by evanchooly** [comment]
That test definitely still works on master.  Can you look [here](https://github.com/MorphiaOrg/morphia/blob/4d5e31372804adb3c85e825b2adefb683b838b31/core/src/test/java/dev/morphia/test/mapping/codec/pojo/EntityModelTest.java#L51) and see if anything leaps out at you?  The one thought I had was your doing codec configuration you probably don't need to.  If you're using the [legacy](https://morphia.dev/2.1.0/guides/configuration/#legacy), you'll need to additionally configure *that* to use the `STANDARD` setting but otherwise Morphia will set that for you.  So you might try ditching (potentially) all of that configuration and letting Morphia set it up for you and see what happens.

**Comment by Homer1991** [comment]
Yeah the Codec thing was from my old troubleshooting.
When i remove all the Configuration i get the error that the UUID Representation is not set so i now have:
```java
final Datastore datastore = Morphia.createDatastore( //
   MongoClients.create( //
      MongoClientSettings.builder()
         .applyConnectionString(new ConnectionString("mongodb://10.9.1.235/"))
         .uuidRepresentation(UuidRepresentation.STANDARD).build() //
   ), "morphia_example", MapperOptions.DEFAULT);
```

I also now have all the `@Entity`s as inner classes. For the Driver i'm using the one that come as a dependency from mophia itself so `org.mongodb:mongodb-driver-sync:4.0.5`
DB is still on Version `4.0.17`

But i still get `Object` instead of `UUID`

-------------------------------------------

The whole thing:
```java
public class Test {
   public static void main(String[] args) {

      final Datastore datastore = Morphia.createDatastore( //
            MongoClients.create( //
                  MongoClientSettings.builder()
                        .applyConnectionString(new ConnectionString("mongodb://10.9.1.235/"))
                        .uuidRepresentation(UuidRepresentation.STANDARD).build() //
            ), "morphia_example", MapperOptions.DEFAULT);

      datastore.getMapper().mapPackage("de.code.common.morphia.test");
//      datastore.getMapper().addInterceptor(new EntityInterceptor() {
//         @Override
//         public void preLoad(Object ent, Document document, Mapper mapper) {
//            System.out.println("test");
//         }
//      });

      datastore.ensureIndexes();

      EntityModel model = datastore.getMapper().map(GenericEntity.class).get(0);
      Class<?> idType = model.getField("id").getType();
      Class<?> testType = model.getField("test").getType();
      Class<?> test2Type = model.getField("test2").getType();

      model = datastore.getMapper().map(SpecificEntity.class).get(0);
      idType = model.getField("id").getType();
      testType = model.getField("test").getType();
      test2Type = model.getField("test2").getType();

      model = datastore.getMapper().map(MoreSpecificEntity.class).get(0);
      idType = model.getField("id").getType();
      testType = model.getField("test").getType();
      test2Type = model.getField("test2").getType();

      MoreSpecificEntity beforeDB = new MoreSpecificEntity();
      beforeDB.setId(UUID.randomUUID());
      beforeDB.setTest(UUID.randomUUID());
      beforeDB.setTest2(UUID.randomUUID());
      beforeDB.setNumber(13);
      beforeDB.setNumber2(14);
      datastore.save(beforeDB);

      MoreSpecificEntity fromDB = datastore.find(MoreSpecificEntity.class).filter(Filters.eq("_id", beforeDB.getId()))
            .first();

      System.out.println(fromDB);

      datastore.find(MoreSpecificEntity.class).delete(new DeleteOptions().multi(true));
   }

   @Entity
   private static class GenericEntity<T> {
      @Id
      protected T id;
      protected T test;
      protected UUID test2;

      public T getId() {
         return id;
      }

      public void setId(T id) {
         this.id = id;
      }

      public T getTest() {
         return test;
      }

      public void setTest(T test) {
         this.test = test;
      }

      public UUID getTest2() {
         return test2;
      }

      public void setTest2(UUID test2) {
         this.test2 = test2;
      }
   }

   @Entity
   private static class SpecificEntity<ID> extends GenericEntity<ID> {
      private long number;

      public long getNumber() {
         return number;
      }

      public void setNumber(long number) {
         this.number = number;
      }

   }

   @Entity
   private static class MoreSpecificEntity extends SpecificEntity<UUID> {
      private long number2;

      public long getNumber2() {
         return number2;
      }

      public void setNumber2(long number2) {
         this.number2 = number2;
      }
   }
}
```

-------------------------------------------

BTW in this [line](https://github.com/MorphiaOrg/morphia/blob/4d5e31372804adb3c85e825b2adefb683b838b31/core/src/test/java/dev/morphia/test/mapping/codec/pojo/EntityModelTest.java#L70) it should be:
```java
getDs().find(MoreSpecificEntity.class).delete(new DeleteOptions().multi(true));
```
or `"moreSpecificEntity"` instead of `"specificEntity"`

I just noticed this in my code ^^

**Comment by Homer1991** [comment]
Ok weird i copied the whole Test class into the morphia project itself and there its working just fine.
So it must be a dependency issue i guess

**Comment by Homer1991** [comment]
@evanchooly 

I now have a complete empty project with nothing except the Test in it and it's not working. I also put it on github:
https://github.com/Homer1991/morphia-test

When i try this inside the morphia project it does work but as soon as i use morphia as a dependency the mapping doesn't work.

**Comment by evanchooly** [comment]
fascinating.  i'll poke around.  thanks.

**Comment by Homer1991** [comment]
@evanchooly

FYI: I'm 90% sure that it was working with one of the SNAPSHOTs.

**Comment by evanchooly** [comment]
When I just open the project and run the `main()` (after updating the connection string) it runs with no errors.  what am I supposed to be seeing happen here?

**Comment by evanchooly** [comment]
ok.  i had to fix the `toString()`.  I see it.  pretty sure this was working, too.  disappointing.  i'll dig further.

**Comment by evanchooly** [comment]
hrm.  it autoclosed.  whatever.  i just pushed something to master that seems to close this out for good.  if you can give [2.2.0-SNAPSHOT](https://morphia.dev/morphia/2.2/index.html) a try that'd be great.  if that works, i'll back port that change to a 2.1.1 and push that release.

**Comment by Homer1991** [comment]
@evanchooly it does work with the new snapshot :) Thanks 👍

**Comment by evanchooly** [comment]
Great.  Then I'll backport it and push a 2.1.1.

**Comment by evanchooly** [comment]
2.1.1 is live, fwiw.  finally got it pushed early this morning.

**Comment by Homer1991** [comment]
nice thanks :) 👍

**Comment by evanchooly** [comment]
Apologies for the misfire in the first "fix."  It really looked like we'd gotten it.
