### ISSUE TITLE
MorphiaQuery.java:326 -> java.lang.NullPointerException

### ISSUE THREAD

**Issue by ktonder** [MorphiaOrg/morphia#1516]
**Describe the bug**
Just upgraded from 1.6.0 to 2.0.2, in 1.6.0 I annotated the Document class with @Document(collection = "userservice") (from sping data). As the getMappedClass function on line 340 has hardcoded "false" (allowUnannotated) classes I presume that the new version are forcing @Entity annotation to the document classes.

If you dont annotate the classes with @entity the MorphiaQuery will throw an unexpected nullpointer exception. To figure out why this happens I had to read trough the code etc.

**To Reproduce**
1. Create a DataStore 
2. Create a Document Class (MyEntity) without @Entity annotation.
3. datastore.getMapper().map(MyEntity.class)
4. datastore.getDatastore().find(MyEntity.class).forEach(d -> { System.out.println(d) });
5. Getting the following stack:

```
Caused by: java.lang.NullPointerException
	at dev.morphia.query.MorphiaQuery.prepareCursor(MorphiaQuery.java:326)
	at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:202)
	at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:197)
	at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:42)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
```

**Expected behavior**
I would have expected that the code throws a NullPointer exception earlier that points out that MyEntity without @Entity are not allowed?

It might be an idea to make an validater in the mapper class or so.

** Please complete the following information: **
 - Morphia Version: 2.0.1 and 2.0.2

**Comment by evanchooly** [comment]
Can you share your code or perhaps use a [reproducer](https://github.com/MorphiaOrg/reproducer)?  I'm not quite following how you got there.  If `T` is parameterized type, `T.class` shouldn't be possible.

**Comment by ktonder** [comment]
Thanks for your response, this is absolutely not a big issue but it can help others as it's a bit confusing. If you have a look at the forked repo: https://github.com/ktonder/reproducer you see that the test does not pass as it throws an NullPointerException.

Sorry about the confusion regarding the T.class, I have updated "To reproduce" to be more correct now as well.

**Comment by evanchooly** [comment]
OK.  I've finally gotten a chance to look at this.  The fix is simple:  add `@Entity` to your type.  `@Entity` is required for top level entities.  There's a gap in the validation of your entity that let this slip through that I'll have to think through how best to correct.  There's a conflict between the goal of requiring `@Entity` or `@Embedded` on all types with the option of mapping external classes without source for use in embedded scenarios.  I'll have to rethink how to support that second case but adding that annotation will get you going in the meantime.
