### ISSUE TITLE
on 2.0.1 example page https://morphia.dev/2.0.2/guides/updating/  "UpdateOperations" does NOT exist

### ISSUE THREAD

**Issue by johnda98** [MorphiaOrg/morphia#1517]
its deprecated ..  UpdateOperation exists..  but not "UpdateOperations"  it looks like example in the Reference Docs on the site for 2.0.1 show the old methods fro 1.4 etc.. some of them

for new users it makes it so much harder to quickly implement when the examples are not current or on the right page for the right version

just a kind fyi

so in our code we get these options for 2.0.1.. fine if one knows the morphia new SDK well..   not so fast for new comers.  

" datastore.find(DataHolonType.class)
                            .update(UpdateOperation) instanceof  ? (() datastore.find(DataHolonType.class)
                            .update(UpdateOperation)) : null;
              

any example of a bone simple instance Update using 2.0.1 ?   the world would spin so much faster then.

workaround for an update would just be a datastore.save presumably.

well.the deprecated works.. just be nice to use 2.0.1
  dhtypes.get(counter2).setName(metadatafield1.getText());
                    dhtypes.get(counter2).setDescription(metadatafield2.getText());

                   datastore.find(DataHolonType.class).modify((UpdateOperations<DataHolonType>) dhtypes.get(counter2)).execute();
![Screenshot from 2020-10-24 11-30-50](https://user-images.githubusercontent.com/13384285/97087021-8d2e0280-15ec-11eb-9c3b-6c1d589518ba.png)

see image attached.. which does not work.. it creates a new object with new Objectid and does not update
![Screenshot from 2020-10-24 11-34-57](https://user-images.githubusercontent.com/13384285/97087102-2ceb9080-15ed-11eb-81d9-ca9efb4e54f5.png)

just a kind fyi - as attached.. any clues I presume String Operator is the new value for that field of that new Object ?

I see its said its use is 'highly discouraged' ?  so how on earth , by example, is a simple Object update done on a entity ? 

Welcome an example -thanks or a documentation link that has 2.0.1 Classes in it not the older ones.. thanks guys ! :-)

![Screenshot from 2020-10-24 11-45-03](https://user-images.githubusercontent.com/13384285/97087317-d54e2480-15ee-11eb-8930-f46719ca8a8b.png)

**Comment by evanchooly** [comment]
there's a small example in the getting started guide:  https://morphia.dev/2.0.2/getting-started/quick-tour/#updates

**Comment by richarddd** [comment]
@johnda98 please read docs before submitting issues.
@evanchooly please close this ;)

**Comment by johnda98** [comment]
There are no examples on how to update an entity in 2.0.1. UpdateOperator
yes not UpdateOperations which is deprecated but is still used in the 2.0.1
examples on the site..

Guys please show a 2.0.1 update example with non deprecated classes..  Just
a simple example & i'll go away.

Thnks indeed.

**Comment by evanchooly** [comment]
https://github.com/MorphiaOrg/morphia/issues/1517#issuecomment-714802853

**Comment by johnda98** [comment]
@richarddd  in kindness.. yes read the docs..  thats the point.. there are no examples in the docs..  the one that is there references UpdateOperations ..  (with an s - plural )NOT UpdateOperation    which is what my depenencies tell me..  we are hazarding a guess at how to update using Updateoperation

"" datastore.find(DataHolonType.class)
.update(UpdateOperation) instanceof ? (() datastore.find(DataHolonType.class)
.update(UpdateOperation)) : null;

**Comment by johnda98** [comment]
The docs are good .. just not many examples of code for 2.0.1 .. and the IDE from mvn 2.0.1 pulls in Classes etc that are not references in the Documentation examples - currently.   I only have a depreacted UpdateOperations selection. 

thanks guys.. yep run me a few Update examples for 2.0.1 and I will crawl away happy..  its a neat abstraction and it would be a shame to have to code down to driver level for the update function.. just doing the basics cruds here, thats all.

**Comment by evanchooly** [comment]
again, https://morphia.dev/2.0.2/getting-started/quick-tour/#updates

**Comment by johnda98** [comment]
https://morphia.dev/2.0.2/getting-started/quick-tour/#updates   nice !  so thats a new doc page thanks guys :-)  I'll try it now !. will advise.

got kinda close earlier with        UpdateOperator op = new UpdateOperator(metadatafield1.getText().toString(),"name",dhtypes.get(counter2));
                    datastore.find(DataHolonType.class).update(op).execute();

**Comment by johnda98** [comment]
> again, https://morphia.dev/2.0.2/getting-started/quick-tour/#updates

ok.. implemented..

"   final Query<DataHolonType> forupdate = datastore.find(DataHolonType.class)
                            .filter(Filters.eq("id", dhtypes.get(counter2).getId()));

                    final UpdateResult results = forupdate.update()
                            .inc("name", metadatafield1.getText())
                            .inc("description", metadatafield2.getText())
                            .execute();

"

BUT .. the update()  method it says it cannot resolve method 'update()'

final UpdateResult results = underPaidQuery.update()
                                           .inc("salary", 10000)
                                           .execute();

**Comment by johnda98** [comment]
I guess I import 2.0.2 .. pom grabbing 2.0.1 presently

**Comment by johnda98** [comment]
@Entity("employees")
@Indexes(
    @Index(value = "salary", fields = @Field("salary"))
)
class Employee {
    @Id
    private ObjectId id;
    private String name;
    @Reference
    private Employee manager;
    @Reference
    private List<Employee> directReports;
    @Property("wage")
    private Double salary;
}

is there an update() method for this example ?  thanks.. presume it includes a Morphia class as it can't just be a regular entity class attribute setter

**Comment by johnda98** [comment]
nope.. its looking for UpdateOperator updateOperator

**Comment by johnda98** [comment]
![Screenshot from 2020-10-24 12-29-53](https://user-images.githubusercontent.com/13384285/97088181-c8ccca80-15f4-11eb-9ab2-87ed2991c462.png)

**Comment by johnda98** [comment]
yep same prob w 2.0.2 .. upgraded the pom..  refreshed mvn.... update() still seeking UpdateOperator for constructor.

your example cut/pasted..   welcome any advisement
![Screenshot from 2020-10-24 14-03-48](https://user-images.githubusercontent.com/13384285/97091483-c755cf00-1601-11eb-8ee8-2810f0597fd0.png)

**Comment by johnda98** [comment]
tried to workaround the update, by simply finding existing object and delete.. (based on your example but without multi.. and no joy..      so a simple find..delete and then save the new object (not much good later on as now I have a new objectId )

  DataHolonType newdoc = new DataHolonType();
                    newdoc = dhtypes.get(counter2);
                    // remove old
                    System.out.println("trying to delete " + newdoc.toString());
                    datastore.find(DataHolonType.class)
                            .filter(Filters.eq("name", "jdaname2"))
                            .delete();
                    // save new
                    newdoc.setName(metadatafield1.getText());
                    newdoc.setDescription(metadatafield2.getText());
                    datastore.save(newdoc);
![Screenshot from 2020-10-24 14-33-52](https://user-images.githubusercontent.com/13384285/97092058-41885280-1606-11eb-82ce-58c8338e7ce9.png)

**Comment by johnda98** [comment]
not even this deletes the Object, which is a valid instance of DataHolonType object  .. dhtypes.get(counter2)



   DataHolonType newdoc = new DataHolonType();
                    newdoc = dhtypes.get(counter2);
                    // remove old
                    System.out.println("trying to delete " + newdoc.toString());
                   // datastore.find(DataHolonType.class)
                   //         .filter(Filters.eq("name", "jdaname2"))
                   //         .delete();

                    datastore.delete(dhtypes.get(counter2));
                    // save new
                    newdoc.setName(metadatafield1.getText());
                    newdoc.setDescription(metadatafield2.getText());
                    datastore.save(newdoc);

**Comment by evanchooly** [comment]
Updated a typo that listed the wrong class to find update operators on.  the docs have been updated and pushed to the website.

**Comment by johnda98** [comment]
Thanks guys.  I guess the site changes take time to propo
![Screenshot from 2020-10-29 09-35-25](https://user-images.githubusercontent.com/13384285/97588408-73b10000-19ca-11eb-9216-10016999690c.png)
![Screenshot from 2020-10-29 09-33-44](https://user-images.githubusercontent.com/13384285/97588410-74499680-19ca-11eb-90b9-e504dd8be6eb.png)

gate..   quick pics of our code with examples from both 2.0.2 doc pages on the site (pre-changes presumably)

**Comment by johnda98** [comment]
Presume chaps :-)  that the website updates take time to propagate ?

We tried an example from 

datastore
    .find(Hotel.class)
    .update(UpdateOperators.set("address.city", "Ottawa"))
    execute();

https://morphia.dev/2.0.2/guides/updating/

![Screenshot from 2020-10-29 09-55-24](https://user-images.githubusercontent.com/13384285/97591307-7a8d4200-19cd-11eb-925b-6475d1307606.png)
![Screenshot from 2020-10-29 09-55-03](https://user-images.githubusercontent.com/13384285/97591309-7b25d880-19cd-11eb-80ba-e9bdd0661b26.png)

**Comment by johnda98** [comment]
will await updates to propgate
![Screenshot from 2020-10-29 10-01-00](https://user-images.githubusercontent.com/13384285/97591578-c17b3780-19cd-11eb-9d34-f46784e1ec36.png)
 - thanks guys .. yep as below

**Comment by johnda98** [comment]
Here is nice juicy example  and it works ! .. put this on the site as an example

  datastore.find(DataHolonType.class).filter(Filters.eq("_id",dhtypes.get(counter2).getId()))
                           .update(UpdateOperators.set("name",metadatafield1.getText()),
                                   UpdateOperators.set("description",metadatafield2.getText()),
                                    UpdateOperators.set("inactive",newinactiveflag))
                            .execute();

**Comment by johnda98** [comment]
![Screenshot from 2020-10-29 10-30-11](https://user-images.githubusercontent.com/13384285/97595824-1325c100-19d2-11eb-9e5a-2b97609784eb.png)

**Comment by evanchooly** [comment]
what changes are you expecting to propagate?
