### ISSUE TITLE
2.0.1 there are Zippo entity Update Examples ??  UpdateOperations is deprecated.. madness there are no examples on the site 

### ISSUE THREAD

**Issue by johnda98** [MorphiaOrg/morphia#1518]
ok cool I see we use UpdateOperator.. but it is "highly discouraged"

UpdateOperator op = new UpdateOperator()    ?????? but WHAT ? goes in the constructor ??
then we feed that into datastore.find(entity.class).update(op)

I mean what is the point of a excellent library if there is no documentation on the 2.0.1 and 2.0.2 ..   I had enough probs trying to get the deprecated version to work.

Can the Planet have at LEAST 1 example of how to update an entity .. without the coder having to find.. then delete then re-add the object himself with a .save

**Comment by evanchooly** [comment]
I have said elsewhere that I would update the docs when I wrap up what I'm working on.  and I'm trying to get there.  it just takes time.  I promise, I'm getting there.
