### ISSUE TITLE
2.0.2.. image attached.. :-)  how about a slight clue ? for https://morphia.dev/2.0.2/javadoc/dev/morphia/query/experimental/updates/UpdateOperator.html

### ISSUE THREAD

**Issue by johnda98** [MorphiaOrg/morphia#1519]
thanks team.. we are guessing the 'operator' string for constructor for OperatorUpdate is.......  well.. who knows ? its nowhere to be found in the docs

** Please complete the following information: **
    Server Version:
    Driver Version:
    Morphia Version: 2.0.2  maven sourced depedency
![Screenshot from 2020-10-28 12-34-46](https://user-images.githubusercontent.com/13384285/97474355-06459680-191a-11eb-80ea-677c8ec9cac6.png)

**Comment by evanchooly** [comment]
fixed. see #1517
