### ISSUE TITLE
How to annotate classes that represent aggregation results? (2.0.2)

### ISSUE THREAD

**Issue by DefiantCatgirl** [MorphiaOrg/morphia#1525]
When using `pipeline.aggregate()` with an end result that is not an entity per se, Morphia throws `dev.morphia.mapping.MappingException: (...)$CompanyFacetResponse is not a mappable type. Mappable types need to be annotated with either @Entity or @Embedded.` 

However, this class is neither embedded nor an entity, but just a result of the aggregation (e.g. in this case it has some metadata and an array of entities). Should there perhaps be an annotation specifically for results of aggregations, or maybe a possibility to map classes without having to use the `@Embedded` annotation in general?

    Server Version: 3.6
    Driver Version: 4.0.5
    Morphia Version: 2.0.2

**Comment by evanchooly** [comment]
That's a good question and one that was obviously missed.  All the tests either use mapped types or aggregate to `Document` just to test the document shape.  In 2.1, there is a `mapExternal()` that could be used but obviously you can't use that just yet.  Right now, I would just mark them with `@Embedded` to get things working.  `@Embedded` is feeling increasingly poorly named, semantically speaking, but it carries with it the entire history of Morphia.  Seems like some rethinking needs to happen there.

**Comment by evanchooly** [comment]
I'm going to close this out if this answers your question.  I'll file the `@Entity`/`@Embedded` discussion under a new issue.
