### ISSUE TITLE
delete throws UnsupportedOperationException when using legacy options

### ISSUE THREAD

**Issue by ppartarr** [MorphiaOrg/morphia#1527]
**Describe the bug**
When attempting to delete an entity using legacy options, [DatastoreImpl#delete()](https://github.com/MorphiaOrg/morphia/blob/r2.0.2/morphia/src/main/java/dev/morphia/DatastoreImpl.java#L248) calls   [Query#filter()](https://github.com/MorphiaOrg/morphia/blob/r2.0.2/morphia/src/main/java/dev/morphia/query/Query.java#L206) which throws an UnsupportedOperationException 

**To Reproduce**
1. Use morphia legacy options as shown below
```java
MapperOptions mapperOptions = MapperOptions.legacy().build();
```
2. Create an `@Entity`, and save it in a datastore with legacy mapper options
3. call `datastore.delete(entity)`
4. See stack trace below
```
Caused by: java.lang.UnsupportedOperationException: This operation is not available to the legacy query implementation.
	at dev.morphia.query.Query.filter(Query.java:206)
	at dev.morphia.DatastoreImpl.delete(DatastoreImpl.java:248)
	at dev.morphia.DatastoreImpl.delete(DatastoreImpl.java:232)
	at com.mmxlabs.lngdataservice.scenarios.services.SharedWorkspaceService.remove(SharedWorkspaceService.java:85)
	at com.mmxlabs.lngdataservice.scenarios.services.SharedWorkspaceServiceTest.lambda$testStoreData_Parallel$2(SharedWorkspaceServiceTest.java:117)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 6 more
```

**Expected behavior**
I'd expect `DatastoreImpl#delete()` to work, even with legacy options enabled. 

**Please complete the following information:**
 - Morphia Version: 2.0.2

**Comment by evanchooly** [comment]
What was the issue?  Is there something that could use better docs, for example?

**Comment by ppartarr** [comment]
I was using `datastore.delete()` which calls [DatastoreImpl#delete](https://github.com/MorphiaOrg/morphia/blob/r2.0.2/morphia/src/main/java/dev/morphia/DatastoreImpl.java#L248) which in turn calls [Query#filter](https://github.com/MorphiaOrg/morphia/blob/r2.0.2/morphia/src/main/java/dev/morphia/query/Query.java#L206) and rightfully throws an UnsupportedOperationException.

Since I'm using legacy mapper options, I just replaced `Datastore#delete` with `Query#delete`

**Comment by evanchooly** [comment]
Fair enough.  There might be something to do to clean that up, though.  If it trips up more folks, I'll dig in to it.  Thanks for clarifying for me.

**Comment by ppartarr** [comment]
I've changed the title back to the original to help people find this issue in case they run into the same problem 😄
