### ISSUE TITLE
Filters.eq().not() is not applying the negation (2.0.2)

### ISSUE THREAD

**Issue by DefiantCatgirl** [MorphiaOrg/morphia#1528]
When building a query such as
```kotlin
.filter(eq("isDeleted", true).not())
```
the resulting query to the database is `isDeleted: true` and not `$not: {isDeleted: true}`. I know `$ne` exists so this kind of query shouldn't normally be used in the first place, but I accidentally had some in the codebase.

Presumably because this instantiation ignores checking the `not` in the overridden function.
```java
    public static Filter eq(final String field, final Object val) {
        return new Filter("$eq", field, val) {
            @Override
            public void encode(final Mapper mapper, final BsonWriter writer, final EncoderContext context) {
                writer.writeName(field(mapper));
                writeUnnamedValue(getValue(mapper), mapper, writer, context);
            }
        };
    }
```

 - Server Version: 3.6
 - Driver Version: 4.0.5
 - Morphia Version: 2.0.2

**Comment by evanchooly** [comment]
you're exactly right.  I'm going to mark this as a 2.1 since that should be out in a few days and I'm trying to avoid a 2.0.3.  But I can backport if a 2.0.3 is needed.  thanks.
