### ISSUE TITLE
Support GridFS [moved]

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#153]
This is [Issue 153](http://code.google.com/p/morphia/issues/detail?id=153) moved from a Google Code project.
Added by 2010-11-02T17:41:54.000Z by [scotthernandez](http://code.google.com/u/scotthernandez/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, Milestone-Release1.0
### Original description

```
There are two ways I can see supporting gridfs.
1.) Add a special type/annotation that can be used as a reference to a gridfs file (by path or _id)

class HasAFileRef {
@Id ObjectId id;
@GridFS OutputStream/GridFSDBFile/byte[] gridFsFile;
...
}

2.) Wrap a class as the gridfsfile.metadata fields.

@GridFsFile
class IsAFile {
@Id ObjectId id;
String field1; // maps to metadata.field1
...
[GridFSFile gfsFile;]
}
```

**Comment by heruan** [comment]
Plus one for way 1: support for large file should be transparent for POJOs, which would see a NIO stream/channel to read/write bytes.

**Comment by heruan** [comment]
Any chance to have GridFS support in 1.1.0 milestone?

**Comment by evanchooly** [comment]
The Java driver will soon have a new GridFS spec implemented.  When that's done, we can integrate with that API in Morphia.  That API is scheduled for 3.1 and therefore before the end of the quarter.  So you can expect Morphia support some time after that.

**Comment by schmitzhermes** [comment]
are there any updates on this?

**Comment by SoltauFintel** [comment]
Access to GridFS is so easy.

```
	private MongoClient client;
	private final GridFSBucket bucket;
...
	client = new MongoClient();
	bucket = GridFSBuckets.create(client.getDatabase(dbname), collection);

	ObjectId save(File in, String filename) throws IOException {
		try (FileInputStream fis = new FileInputStream(in)) {
			return bucket.uploadFromStream(filename, fis);
		}
	}

	... load(ObjectId id, File saveTo) throws IOException {
		try (FileOutputStream fos = new FileOutputStream(saveTo)) {
			bucket.downloadToStream(id, fos);
		} catch (MongoGridFSException e) {
			// file not found or any other trouble ...
		}
	}
...
	client.close();
```

**Comment by evanchooly** [comment]
I've put together some design options [here](https://github.com/MorphiaOrg/morphia/blob/master/design/GridFS.adoc).  Comments (here) welcome.

**Comment by evanchooly** [comment]
The driver actually has a `GridFSFileCodec` to save references to gridfs content which seems Good Enough(tm) for now.  Absent a concrete use case to design around, I'm going to consider this close enough.  We can revisit this in the future should something come up that's no covered by the driver support.

**Comment by heruan** [comment]
Hey! Sorry for joining late to the party. Where do I find documentation on how to map GridFS files to entities?

**Comment by evanchooly** [comment]
The driver itself has pretty good support for gridfs entries so I would start that.  Looking at what the driver offered, I didn't see any obvious improvements that Morphia could offer.  At least not without a specific use case from a user.  I'm not opposed to doing something more advanced in Morphia than the driver offers but i wasn't comfortable trying to speculate on user needs.  If you use the driver types and find some gaps  that might be worth filling, I'd be more than happy to discuss those needs.

**Comment by heruan** [comment]
Thanks! I misinterpreted your last message as if Morphia had already some support to map files to entities. This is the use case I have right now:

```java
class Attachment {
    String id;
    String name;
    Blob data;
}
```
This is a JPA-mapped entity which uses the `Blob` type to read from database, i.e. `data.getBinaryStream()` which reads from the database (without loading all the bytes in memory).

I'm moving from JPA to Morphia and I don't really know how to migrate this last bit of logic!

It would then be used like:

```java
InputStream downloadAttachment(String id) {
    return repository.find(id).getData().getBinaryStream();
}
```
