### ISSUE TITLE
How to translate collation({ locale: "en" }) to morphia api

### ISSUE THREAD

**Issue by lfzCarlosC** [MorphiaOrg/morphia#1532]
**Describe the bug**
We want to set locale to en so that name(a property) can be sorted following that locale. I am not sure how to write it in morphia using its java api.

**To Reproduce**

`db.collection.find({}).collation({ locale: "en" }).sort({ name: 1 })`
But not sure how to write in morphia. The collation() method is deprecated, even if I use deprecated, there is no way to set locale.

**Expected behavior**

** Please complete the following information: **
 - Server Version:
 - Driver Version:
 - Morphia Version: morphia-1.3.2.jar

**Additional context**
Any example models, queries, and executable test cases you can supply will greatly help debugging your issue:

**Comment by evanchooly** [comment]
That version of Morphia doesn't support collations if I remember correctly.  It's really old at this point.  Newer versions have collation related methods on `FindOptions` that can be passed in as part of the query execution.

**Comment by evanchooly** [comment]
closingthis seems to be resolved so i'll close it out. feel free to reopen or open a new one if something comes up.
