### ISSUE TITLE
VersionMisuse check is not Compatible with Kotlin Data classes

### ISSUE THREAD

**Issue by soemeier** [MorphiaOrg/morphia#1533]
**Is your feature request related to a problem? Please describe.**
I tried to use a Versioned Entity with Kotlin Data Classes that have not nullable Fields. Unfortunetly does the `VersionMisuse` check try to create a class with just null values.

**Describe the solution you'd like**
As a quick fix it would be nice if the Annotation could have a property to disable this field check.

**Describe alternatives you've considered**
Of course I could change all properties to allow nullable Fields but I think that would be a nasty workaround because I would have to adapt my code in several other places.

If you would agree with my proposed solution I would be happy to provide a Pull Request.

**Comment by evanchooly** [comment]
Did you try init'ing to 0?

**Comment by soemeier** [comment]
Well that won't help. The problem is that a new Object is created here: 

https://github.com/MorphiaOrg/morphia/blob/8ebfdfe7a4c315a81b910b8c088b722cd3f3b29d/core/src/main/java/dev/morphia/mapping/validation/fieldrules/VersionMisuse.java#L38

If any of the fields are not nullable the object cannot be created. So the problem is not with the version field itself but the with other non nullable fields.
