### ISSUE TITLE
External Mapping is broken

### ISSUE THREAD

**Issue by BlackReloaded** [MorphiaOrg/morphia#1541]
**Describe the bug**
The function `mapExternal` in `dev.morphia.mapping.Mapper` does not work correctly. If i add a class i get an exception `org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class`.

**To Reproduce**
1. Make a new `dev.morphia.Datastore`
2. Register an external class that have no @Embedded annotation
3. Write a bean to the database
4. Get exception `org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class`

**Expected behavior**
Save the bean to the database without exception.

** Please complete the following information: **
 - Server Version: 4.4.2
 - Driver Version: 4.0.5
 - Morphia Version: 2.1.3

**Additional context**
I found one solution for this probmen in `dev.morphia.mapping.codec.MorphiaCodecProvider`: 
```java
    @Override
    @SuppressWarnings("unchecked")
    public <T> MorphiaCodec get(Class<T> type, CodecRegistry registry) {
        MorphiaCodec codec = (MorphiaCodec) codecs.get(type);
        if (codec == null && mapper.isMappable(type)) {
            codec = new MorphiaCodec(datastore, mapper.getEntityModel(type), propertyCodecProviders,
                mapper.getDiscriminatorLookup(), registry);
            codecs.put(type, codec);
        }

        return codec;
    }
```

It uses the funktion `isMappable` which tests again for the annotations. I think you wanted to use `isMapped` with looks at the already mapped entities. I test this on my computer and it works fine.

**Comment by evanchooly** [comment]
Did you follow the steps in the [documentation](https://morphia.dev/morphia/2.1/mapping.html#_external_types)?

**Comment by BlackReloaded** [comment]
Yes i added the external class with:
```java
mapper.mapExternal(EmbeddedBuilder.builder(), ExternalClass.class);
```
after that, the query validator is happy but not codec mapper.

**Comment by evanchooly** [comment]
OK, thanks.  i'll try to fix that tonight.
