### ISSUE TITLE
Are Morphia's driver dependencies correct?

### ISSUE THREAD

**Issue by pioorg** [MorphiaOrg/morphia#1544]
One of the points listed in https://mongodb.github.io/mongo-java-driver/4.1/upgrading/ says:

> The mongo-java-driver and mongodb-driver “uber-jars” are no longer published. Applications that reference either of these artifacts must switch to either mongodb-driver-sync or mongodb-driver-legacy, depending on which API is being used. Care should be taken to ensure that neither of the uber-jars are included via a transitive dependency, as that could introduce versioning conflicts.

Whereas in [Morphia's POM](https://github.com/MorphiaOrg/morphia/blob/a617095788382c6cc86b90ff89719270ee15aee8/core/pom.xml#L180) one can find:

            <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongodb-driver-sync</artifactId>
            <version>${driver.version}</version>
        </dependency>
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongodb-driver-legacy</artifactId>
            <version>${driver.version}</version>
        </dependency>

I'm a bit confused. Could it be clarified somehow?

**Comment by evanchooly** [comment]
They are.  `sync` gets us the new API whereas `legacy` gets us some of the old  `DBObject` related methods still the for compatibility.

**Comment by pioorg** [comment]
I see. Thanks!
