### ISSUE TITLE
Impossible to add life cycle methods to entities having UUID fields

### ISSUE THREAD

**Issue by pioorg** [MorphiaOrg/morphia#1545]
**Impossible to add life cycle methods to entities having UUID fields**
If an `@Entity` has UUID-based fields (e.g. `@Id`), it's impossible to add life cycle methods, like `@PreLoad` and friends.
This manifests in 

```
java.lang.IllegalStateException: unknown type for bson mapping: class java.util.UUID

	at dev.morphia.mapping.codec.reader.DocumentReader.getBsonType(DocumentReader.java:347)
	at dev.morphia.mapping.codec.reader.ReaderState.getCurrentBsonType(ReaderState.java:97)
	at dev.morphia.mapping.codec.reader.DocumentReader.getCurrentBsonType(DocumentReader.java:43)
````
It seems it's because the DocumentReader's `TYPE_MAP = new BsonTypeMap()` doesn't contain UUID.

**To Reproduce**
```
@Entity()
class UUIDKeyed {
	@Id UUID id;
	@PreLoad void preLoad(Document doc) {
		System.out.printf("Going to load [%s].%n", doc.get("_id", UUID.class));
	}
}

public class UUIDLifecycleCheck {
	@Test
	void checkLifecycleForUuid() {

		MongoClientSettings settings = MongoClientSettings.builder()
			.applyConnectionString(new ConnectionString("mongodb://localhost:27017"))
			.uuidRepresentation(UuidRepresentation.STANDARD)
			.build();

		MongoClient mongoClient = MongoClients.create(settings);

		MapperOptions options = MapperOptions.builder().build();
		final Datastore datastore = Morphia.createDatastore(mongoClient, "morphia_example", options);
		datastore.getMapper().map(UUIDKeyed.class);

		var example = new UUIDKeyed();
		example.id = UUID.randomUUID();

		datastore.save(example);
		var loaded = datastore.find(UUIDKeyed.class).first();
		System.out.println(loaded.id);
	}
}

```

**Expected behavior**
Loading entities having both life cycle method(s) and `UUID` field(s).

** Please complete the following information: **
 - Server Version: 4.2.11
 - Driver Version: 4.1.1
 - Morphia Version: 2.1.3

**Comment by pioorg** [comment]
Hi @evanchooly 
I'm not sure how this should be addressed. Is there a BsonType to put to the `TYPE_MAP` (apart from `BINARY`)? I could try implementing a fix, provided it's really a bug. ;-)
Thanks!

**Comment by evanchooly** [comment]
It probably is a bug.  😀  UUIDs have been a pain sine the 4.0 driver switch.  I've fixed a handful of similar bugs so I have an idea of what it might be.  I can take a look soon.

**Comment by pioorg** [comment]
Thanks for a prompt reply. For time being I'm bypassing this with a custom `Codec`. ;-)

**Comment by evanchooly** [comment]
I'm pretty sure it has to do with getting the right codec registry to the right place since there is already a UUID code in the driver.  Its just not in the mix by default in the driver apparently. I doubt I get to it today as it's my birthday but probably this weekend hopefully.

**Comment by pioorg** [comment]
Yes, because in that case codecs are picked by the BsonType. I'm not sure if that's optimal choice for DocumentReader, since it can operate on other types as well. UUID being an example here.
And again, Happy Birthday!

**Comment by evanchooly** [comment]
OK.  so that wasn't quite the problem I expected but the fix is still rather small in spite of my initial panic.  :)
