### ISSUE TITLE
Could not load ByteArray

### ISSUE THREAD

**Issue by BlackReloaded** [MorphiaOrg/morphia#1548]
**Describe the bug**
While trying to load an json with an byte array i get an `java.lang.ClassCastException: class org.bson.types.Binary cannot be cast to class org.bson.BsonBinary`

**To Reproduce**
1. Create Class with bytearray
```java
@Entity
public class A {
	@Id private ObjectId id;
	private byte[] data;
}
```
2. Create a json
```json
{
 "_id": {
    "$oid": "59580ebf36218c7edf155044"
 },
 "data": {
      "$binary": {
          "base64": "",
          "subType": "00"
      }
  }
}
```
2. Trying to load that Json:
```java
Document doc = Document.parse(json);
dataStore.getMapper().fromDocument(A.class, doc)
```
3. Get the Exception java.lang.ClassCastException

**Expected behavior**
Load the json into an object.

**Please complete the following information:**
 - Morphia Version: 2.1.3

**Additional context**
I think i found the problem, the file [https://github.com/MorphiaOrg/morphia/blob/master/core/src/main/java/dev/morphia/mapping/codec/reader/DocumentReader.java#L52-L59](https://github.com/MorphiaOrg/morphia/blob/master/core/src/main/java/dev/morphia/mapping/codec/reader/DocumentReader.java#L52-L59) needs an extra case: 
```java 
if(value instanceof Binary) {
    var b = (Binary)value;
    return new BsonBinary(b.getType(), b.getData());
}
```
because of [BsonTypeMap.java](https://github.com/MorphiaOrg/morphia/blob/0ec886ef481ff061241e084f43661a9dc0421a56/core/src/main/java/dev/morphia/mapping/codec/BsonTypeMap.java#L34) that uses `org.bson.types.Binary` for $binary.

**Comment by evanchooly** [comment]
I literally ran in to that last night (with a slightly different context) before going to bed.  I'll clean it up.

**Comment by evanchooly** [comment]
While fixing another bug I rebroke this one (*sigh*) and I'd like to ask how you got `$binary` representation?  when I save a `byte[]` it shows up as `[ 1, 2, 3, ... ]`.

**Comment by BlackReloaded** [comment]
Hi, i got the json from a system with the old morphia (version 1.5.8), with actual version (2.1.4) i get the same result as us.

Is this change wanted?

**Comment by evanchooly** [comment]
OK.  This is the piece that was missing.  I couldn't actually recreate it with Morphia itself.  Knowing what versions are in the mix will help.  I'll try to recreate it and come up with a solution.  the new codecs might save it in a new format, but morphia should be able to load the old one, too.  I just created #1557 to track this.
