### ISSUE TITLE
Expected @Reference format in database

### ISSUE THREAD

**Issue by pioorg** [MorphiaOrg/morphia#1549]
Hi!

I'd like to ask you a question (perhaps related to #1500) about Morphia 2.+.
In general: what's the expected format of documents, if the root document keeps a set of `@Reference`s to other `@Entity`ies?

Is this supposed to be something like this:
```
{
    "_id" : UUID("91d165e4-55b3-4d19-a637-750ec4d29e38"),
    "aSet" : [ 
        {
            "_id" : UUID("eaf4473d-29d9-4eb4-8cf4-ab9b005d0358")
        }, 
        {
            "_id" : UUID("17181a06-c30c-44a8-954e-fdd44180cc23")
        }
    ]
}
```
Or this:
```
{
    "_id" : UUID("91d165e4-55b3-4d19-a637-750ec4d29e38"),
    "aSet" : [ 
        UUID("eaf4473d-29d9-4eb4-8cf4-ab9b005d0358"),
        UUID("17181a06-c30c-44a8-954e-fdd44180cc23"),
    ]
}
```
Thanks in advance!

**Comment by evanchooly** [comment]
With `idOnly=true` I'd expect the second.  The first looks like it's trying to embed the entities rather than reference them.

**Comment by pioorg** [comment]
Hi @evanchooly 
Thanks for the answer. I thought so. ;-)

I'm afraid this might mean there's a bug and the fix is really simple, but I guess it'll break backward compatibility.
