### ISSUE TITLE
@Reference and @Id Annotation Support for Super Classes

### ISSUE THREAD

**Issue by iAmcR** [MorphiaOrg/morphia#1554]
@evanchooly One thing that I see as a sort of regression, is the support for the @Id annotation in super classes like: 

```
@Reference
SuperModel referencedItem;
``` 

I'm getting the following exception: 

```
Caused by: dev.morphia.mapping.validation.ConstraintViolationException: Number of violations: 1 
ReferenceToUnidentifiable complained about com.foo.Parent.referenceChild : com.foo.Parent#referenceChild is annotated as a @Reference but the com.foo.SuperModel class is missing the @Id annotation
	at dev.morphia.mapping.validation.MappingValidator.validate(MappingValidator.java:69)
```

I know this was supported in previous versions, but now when the `@Reference` annotation is on a field with the super class as a type it doesn't realize that there is indeed an `@Id` annotation. 

The expected behavior is that it would have resolved the referenced entity to its correct concrete type and object/model at runtime. 
 
I did a reproducer here to illustrate the issue: https://github.com/iAmcR/reproducer.git

Thank you.

**Comment by evanchooly** [comment]
looks like you didn't push all the relevant details there (the test is empty) but I can probably recreate the rest...

**Comment by evanchooly** [comment]
`@Entity` and `@Embedded` are [required](https://morphia.dev/morphia/2.1/mapping.html#_classes) in order to be mapped as of 2.0.  Adding `@Entity` to `SuperModel` fixes this failure.

**Comment by iAmcR** [comment]
Thank you for looking into this. I'll check that out in a bit.
