### ISSUE TITLE
byte[] saved format changed

### ISSUE THREAD

**Issue by evanchooly** [MorphiaOrg/morphia#1557]
**Describe the bug**
Prior to 2.0, a `byte[]` can end up with a `$binary` document in the database.  Using lifecycle events, `DocumentReader` fails to read the old format.

**To Reproduce**
Save a `byte[]` field using 1.5.8 and then try loading with a 2.x application.

**Expected behavior**
The data should be properly loaded in to the field.

See #1548 for more details

**Comment by BlackReloaded** [comment]
I have done a little bit of research on this topic. I think this change was not intended.
Morphia add support for arrays in `MorphiaTypesCodecProvider` see: https://github.com/MorphiaOrg/morphia/blob/85f0c84060e16d36da5a16d5faebb16340d348d1/core/src/main/java/dev/morphia/mapping/codec/MorphiaTypesCodecProvider.java#L43-L50

The error is, that byte[] is a special type and must be encoded as $binary in mongodb. The mongo driver has a codec for that, so if you remove the line 44: https://github.com/MorphiaOrg/morphia/blob/85f0c84060e16d36da5a16d5faebb16340d348d1/core/src/main/java/dev/morphia/mapping/codec/MorphiaTypesCodecProvider.java#L44

All works as expected.
