### ISSUE TITLE
Error with storeNull=false and update Document

### ISSUE THREAD

**Issue by BlackReloaded** [MorphiaOrg/morphia#1558]
**Describe the bug**
If storeNull is false, the Datastore.save method does not unset properties that are now null. In version before 2 this works.

**To Reproduce**
1. Create a Datastore with storeNull set to false
1. Create a Bean 
```java
@Entity
public class A {
   @Id
   private ObjectId id;
   private String a2;
}
```
2. Save Object 
```java
var a = new A();
a.a2 = "Test";
dataStore.save(a)
a.a2 = null;
dataStore.save(a)
```
3. See in database that a2 has the value of "Test"

**Expected behavior**
The field "a2" should be removed from the database. This changed to Version 1.6.

** Please complete the following information: **
 - Server Version: 4.4.2
 - Driver Version: 4.0.5
 - Morphia Version: 2.1.4

**Additional context**
The problem is in DatastoreImpl: https://github.com/MorphiaOrg/morphia/blob/85f0c84060e16d36da5a16d5faebb16340d348d1/core/src/main/java/dev/morphia/DatastoreImpl.java#L578

This line uses the codecs to create the $set command but if storeNull=false only fields with a value will be updated. For every field with the value null, there musst be a unset command or do i miss anything?

**Comment by evanchooly** [comment]
I'm sorry I let this one sit for so long.  I missed it somehow.  At any rate, yes, if you have `storeNull` set to false it won't be passed along in a save and the old field will remain.  In those cases, you'll want that explicit `unset` update statement.

**Comment by BlackReloaded** [comment]
This is a strange behavior. If i set a Field to null in an embedded Object, it will be removed. But if i set a Field to null in top level it will remain and i have to unset myself. In my opinion this is a bad design.

**Comment by pioorg** [comment]
Hello
2 cents from me, maybe that will help future visitors.
As in version 2.1.4 I don't see this bug. Meaning: setting `storeNulls(true)` in `MapperOptions` sends nulls in all places I checked. However, this might be an overhead for some people, when there are a lot of null fields.
In this aspect the pre2 versions of Morphia used to work differently, as they weren't using the `$set` operator for updates, but sent all the replace document, it seems (https://docs.mongodb.com/manual/reference/method/db.collection.update/#update-method-replacement-document). I'm far from judging that, but maybe behaviour might have been better though, especially that `storeNulls` is `false` by default.
I understand there might be people relying on this mechanism for data processing in general. However, for an ORM not clearing null model fields by default seems to be somewhat odd...
Thanks!

**Comment by BlackReloaded** [comment]
@pioorg I'm sorry for the confusion but the title was wrong. The error is with `storeNull(false)` and it is still in 2.1.4 and main.

**Comment by pioorg** [comment]
Hi @BlackReloaded 
Yeap, it might be somewhat confusing, but (as I was describing in the previous post) I'm not quite convinced that `datastore.save` performing `$set` update is the best option for an ORM. Maybe things will change if/when `datastore.insert` and `datastore.update` are introduced (I think I saw another ticket on that). Anyway, without proxy objects and tracing `$set: {field: null}` I somehow don't see incremental updates. Maybe my vision is somehow broken, sorry ;-)

**Comment by BlackReloaded** [comment]
@pioorg You are right, but morphia actual uses a $set command on `datastore.save` and not a replace (prev 2.0 it uses a replace), look at DatastoreImpl.java:

- L403 calls  private <T> void save(MongoCollection collection, T entity, InsertOneOptions options) (L536)
- L541 calls  private <T> boolean tryVersionedUpdate(T entity, MongoCollection collection, InsertOneOptions options) (L569)
- L596-L603 performs a update command with $set and not a replace.

At the root level if a field is null the serializier will ignore the field, so it is not possible to remove or set it to null. I think it should be possible to null a field if i call save with an entity.

IMHO: Morphia should use the replace method (https://docs.mongodb.com/manual/reference/method/db.collection.replaceOne/) to save an entity.

**Comment by pioorg** [comment]
Hi @BlackReloaded 
Thanks for the analysis, this time I didn't dig into the sources. I found examining the Mongo client logs enough ;-)
I was thinking about this during last few days... And it seems that `$unset` is not an option too, because a missing field is different than a null field. Besides, how to track them easily without proxies? So in NoSQL ORM things are trickier than in a SQL one.
I'm also not going to say what Morphia should, the replace document seems the approach to go with `save`, but there might be reasons which made this shift towards `$set` take place of which I'm basically not aware. There might be reasons to favour `$set`.
I just wanted to share my thoughts that not nullifying fields by default seems somewhat odd to me, that's all.

**Comment by evanchooly** [comment]
`$set` is used in `save()` only for versioned updates due to how concurrent changes to versioned entities is handled.  Non-versioned entities are saved using `replaceOne()` on `MongoCollection`.

**Comment by pioorg** [comment]
Hi @evanchooly
Thanks for clarification. I haven't spotted other ones as almost all entities we have are versioned.
I saw that `updates` contains `"$inc": {"version": 1}` and `$set` with all other fields, of course.
If the version is checked in the query part, e.g. `{"_id": id_goes_here, "version": 15}`, let me ask naively: why the update can't set "version" : 16 in the replacing document?
Thanks!

**Comment by evanchooly** [comment]
It could.  `$inc` was just simpler way back in the day.

**Comment by evanchooly** [comment]
So I haven't abandoned this issue.  It's still on my mind i've just been focusing on other things.  I did run across something that might just resolve this for you:  [Datastore.merge()](https://morphia.dev/morphia/2.1/javadoc/dev/morphia/Datastore.html#merge(T)).

**Comment by evanchooly** [comment]
related #1579

**Comment by evanchooly** [comment]
actually, i'll close this one in favor of the other.  I'm thinking we'll end up with an option on `InsertOneOptions` to do the additional `$unset` operations when calling `merge()`.
