### ISSUE TITLE
morphia fails to decode null value into array

### ISSUE THREAD

**Issue by tobiaskohlbau** [MorphiaOrg/morphia#1560]
**Describe the bug**
As a result of #1558 we enabled _storeNull_ to workaround that issue. After enabling said setting, morphia is unable to decode such null value into for e.g. a string array. It crashes with an _NullPointerException_, resulted by the following unchecked access to _value_:
https://github.com/MorphiaOrg/morphia/blob/85f0c84060e16d36da5a16d5faebb16340d348d1/core/src/main/java/dev/morphia/mapping/codec/ArrayFieldAccessor.java#L31-L38

I've checked the call chain and found that the `EntityDecoder` decodes the null value and calls that function. 
https://github.com/MorphiaOrg/morphia/blob/85f0c84060e16d36da5a16d5faebb16340d348d1/core/src/main/java/dev/morphia/mapping/codec/pojo/EntityDecoder.java#L49-L70

I'm not sure whether the right fix for this is, to either fix the _ArrayFieldAccessor_ by adding an additonal null check or by returning after reading the _nullValue_ from the BSON within the EntityDecoder itself.

**To Reproduce**
1. Create an Object which contains a string array.
2. Store that object with that string array equal to null within the database.
3. storeNull preserves that null value within mongo itself.
4. Try to load same object via morphia.
5. NullPointerException within _ArrayFieldAccessor_.

**Expected behavior**
Morphia should not crash and handle the null value correctly.

** Please complete the following information: **
 - Server Version: 4.4.2
 - Driver Version: 4.0.5
 - Morphia Version: 2.1.4

**Additional context**

```
@Entity
public class A {
   @Id
   private ObjectId id;
   private String[] test;
}
```

Enable _storeNull_ within the morphia mapping setting.

If additonal context or informations are needed to debug/find this issue let me know.

**Comment by evanchooly** [comment]
can you retry with 2.1.5-SNAPSHOT?  i fixed another bug last night that looks *exactly* like this one.

**Comment by evanchooly** [comment]
considering this one fixed then.
