### ISSUE TITLE
Deserialization fails with java.sql.Timestamp as field in model.

### ISSUE THREAD

**Issue by ptwohig** [MorphiaOrg/morphia#1561]
**Describe the bug**
When a type has a ```java.sql.Timestamp``` as any of its fields, it results in an exception when de-serializing the model object. I suspect that what happens is that when serializing the java.sql.Timestamp, the driver saves it as if it was saving a ```java.util.Date``. When fetching back out of the database, the driver seems to construct a ``java.util.Date```which won't work when ```NoArgCreator.set()``` passes the value direct to ```Field.set``` resulting in an exception.

**To Reproduce**
1. Define any model type which has ```java.sql.Timestamp``` as a field (eg ```class MyTest { private Timestamp ts; }
2. Create an instance of the object.
3. Assign a value to the object's Timestamp field
4. Assign an id.
5. Fetch object by Object ID.

**Expected behavior**
There should be no exception when fetching the object from the database.

 - Server Version: db version v3.6.8
 - Driver Version: 4.2.0. I've also tested on 
 - Morphia Version: master, 2.1.3

**Additional context**
Have a look at the testcase:
- https://github.com/ptwohig/morphia/tree/bug/deserialization-fails-java-sql-timestamp
- https://github.com/ptwohig/morphia/blob/bug/deserialization-fails-java-sql-timestamp/core/src/test/java/dev/morphia/test/models/ModelWithTimestamp.java
- https://github.com/ptwohig/morphia/blob/bug/deserialization-fails-java-sql-timestamp/core/src/test/java/dev/morphia/test/TestModelWithTimestamp.java

**Comment by evanchooly** [comment]
discussed on irc...
