### ISSUE TITLE
How to implement custom Converter since 1.6

### ISSUE THREAD

**Issue by fgoulhot** [MorphiaOrg/morphia#1562]
** Please ask your question and provide whatever background or supporting information you think might be relevant: **
As MappedField has been deprecated, what is the appropriate way to build custom converter now?

** Please complete the following information: **
    Server Version:
    Driver Version:
    Morphia Version: 1.6.1

**Comment by evanchooly** [comment]
For 1.6, a `Converter` is still the right answer.  In 2.x such a role would be fulfilled by a `Codec`.

**Comment by evanchooly** [comment]
does this answer your question or do you need more information?

**Comment by fgoulhot** [comment]
Yes. So I'm stuck with the deprecated warning until I migrate.
However, I cannot find the codec documentation. Do you have the link?

**Comment by evanchooly** [comment]
this is probably far too delayed (I apologize for that) but for anyone else who comes looking, documentation on codecs can be found [here](https://mongodb.github.io/mongo-java-driver/4.3/bson/codecs/)
