### ISSUE TITLE
Unset fails on deleted references

### ISSUE THREAD

**Issue by janknobloch** [MorphiaOrg/morphia#1569]
**Describe the bug**

`datastore.find(Entity.class).filter(Filters.eq("_id", entityId)).update(UpdateOperators.set("child", child)).execute();`

works fine, adding a child reference to the parent.

using the following to remove the child reference:
`datastore.find(Entity.class).filter(Filters.eq("_id", entityId)).update(UpdateOperators.unset("child")).execute();`

Is actually deleting the child object in the child collection but not the reference on the parent object.
Child in my scenario is a referenced field using  ` @Reference(lazy = true)`

**To Reproduce**
Steps to reproduce the Behavior:
1. Create two entity objects (Parent, Child) whereas child is refered inside parent
2. Do an set operation setting the child
3. do an unset operation removing the child 

**Expected behavior**
Delete / Unset the parent.child reference not removing the child in the different collection

** Please complete the following information: **
 - Server Version: MongoDB 4.4.2 Community
 - Driver Version: 3.11.0
 - Morphia Version: 2.1.4

**Additional context**

I had to do a workaround like this to make it work which is kind of ugly.

```
parentToDeleteFrom = datastore.find(Entity.class).filter(Filters.eq("_id", entityId)).first();
        parentToDeleteFrom.setChild(null);
        datastore.save(parentToDeleteFrom);
```

Edith:

It seems the unset operation is actually deleting the referenced child, but keeping the child refererence in place, the NPE occurs due to Im trying to delete the child afterwards which can not be found anymore.

**Comment by evanchooly** [comment]
Can you put together a [reproducer](https://github.com/MorphiaOrg/reproducer) so I can take a look?

**Comment by janknobloch** [comment]
@evanchooly for sure here you go:

https://github.com/janknobloch/reproducer

**Comment by evanchooly** [comment]
looks like you forgot to commit some changes.  I don't see any actual test.

**Comment by janknobloch** [comment]
I swapped the simple main as a test hope this test does what it should do if not please look at the assert statement.

**Comment by evanchooly** [comment]
ah.  of course.  i should've looked there.  I'll tackle this tonight/this weekend.  thanks.

**Comment by janknobloch** [comment]
No worries my bad. i haven't looked in the test folder either.. :-) @evanchooly i updated my fork and hope this helps.
I can reproduce the NPE in the reproducer, however while running in my environment right now its actually removing the referenced object from its own collection but keeps the reference on the other object.

let me know if i can be of assistance.

**Comment by evanchooly** [comment]
I ran it briefly before turning to $dayJob and saw the error so I think I have what I need for now.  thanks.

**Comment by janknobloch** [comment]
these $dayJobs these days.. ;-) looking forward to see this fixed which bugs me using save instead of update and forcing a lot of extra logic :-). Have a great day.
