### ISSUE TITLE
Unresolved reference in ReferenceCodec results in infinite loop calling database

### ISSUE THREAD

**Issue by TnTGamesTV** [MorphiaOrg/morphia#1576]
**Describe the bug**
An unresolved reference (in this case [SingleReference](https://github.com/MorphiaOrg/morphia/blob/21bda5e417a889b5ce1370c361c2f41dc1c286f1/core/src/main/java/dev/morphia/mapping/experimental/SingleReference.java) results in an infinite loop.

The reason for this is the call of `reference.get(...)` in [ReferenceCodec:315](https://github.com/MorphiaOrg/morphia/blob/21bda5e417a889b5ce1370c361c2f41dc1c286f1/core/src/main/java/dev/morphia/mapping/codec/references/ReferenceCodec.java#L315) immediately after creating it in [ReferenceCodec:311](https://github.com/MorphiaOrg/morphia/blob/21bda5e417a889b5ce1370c361c2f41dc1c286f1/core/src/main/java/dev/morphia/mapping/codec/references/ReferenceCodec.java#L311) using [ReferenceCodec#readSingle](https://github.com/MorphiaOrg/morphia/blob/21bda5e417a889b5ce1370c361c2f41dc1c286f1/core/src/main/java/dev/morphia/mapping/codec/references/ReferenceCodec.java#L358).

As the reference is not resolved it will try to resolve itself (see [SingleReference#get](https://github.com/MorphiaOrg/morphia/blob/21bda5e417a889b5ce1370c361c2f41dc1c286f1/core/src/main/java/dev/morphia/mapping/experimental/SingleReference.java#L76)) which will call the database again.

Another reference is created which is also not resolved and will try to resolve itself as well.

**Edit**: The problem is that MorphiaReference#resolve is not getting called (as an example see [SingleReference:44](https://github.com/MorphiaOrg/morphia/blob/21bda5e417a889b5ce1370c361c2f41dc1c286f1/core/src/main/java/dev/morphia/mapping/experimental/SingleReference.java#L44)). 

See [Log](https://pastebin.com/wZpMxsLD) for details.

**To Reproduce**
~~Request a single object from the database using .first() (should theoretically work with all types of queries)~~

Use [this reproducer](https://github.com/TnTGamesTV/reproducer). It will request a single object with a circular reference.

**Expected behavior**
~~As the value is already given in [ReferenceCodec#fetch](https://github.com/MorphiaOrg/morphia/blob/21bda5e417a889b5ce1370c361c2f41dc1c286f1/core/src/main/java/dev/morphia/mapping/codec/references/ReferenceCodec.java#L297) the reference should already be marked as resolved.~~

The infinite loop is not expected behavior.

**Please complete the following information:**
 - Server Version: 4.4.1
 - Driver Version: 4.2.0 (also tested with 4.0.2)
 - Morphia Version: 2.0.2 (also tested with 2.1.4)

**Comment by evanchooly** [comment]
I'm not quite following the description here.  Can you build a [reproducer](https://github.com/MorphiaOrg/reproducer) so i can see it in action?

**Comment by TnTGamesTV** [comment]
I have created a [reproducer](https://github.com/TnTGamesTV/reproducer). I am using ObjectIds as identification. MyEntity and TestEntity both have a reference to each other.

The reproducer also has a [branch](https://github.com/TnTGamesTV/reproducer/tree/variant-multiple) for finding multiple instances.

The issue is still that the MorphiaReference (tested for a single instance and a list of instances) is not getting resolved.
The call to `entityModel.getType().isInstance(id)` in [SingleReference:39](https://github.com/MorphiaOrg/morphia/blob/21bda5e417a889b5ce1370c361c2f41dc1c286f1/core/src/main/java/dev/morphia/mapping/experimental/SingleReference.java#L39) (as an example) is returning false.

**Comment by evanchooly** [comment]
I apologize it took so long to get to this but I've been unexpectedly busy lately.  At any rate, after stepping through the reproducer and the code, what you're actually up against here is an infinite loop as both entities reference the other.  You'll need to mark up at least one of those with `lazy = true` in the `@Reference` annotation and everything should load as expected.
