### ISSUE TITLE
Aggregation & Projection

### ISSUE THREAD

**Issue by sterd71** [MorphiaOrg/morphia#1577]
Hi,

Server Version: 4.2.8 Community
Driver Version: 4.0.3
Morphia Version: 1.6

I need to join two documents using an aggregation and then project just the items I want from both documents.

e.g.
I want to process a list of books and their authors (where author in Book is the _id of Person), and list the book title, author name and age.

    Book = {
        _id,
        title,
        author,
        isbn
    }

    Person = {
        _id,
        name,
        age,
        website
    }

This is what I’ve got to just dump the values into json strings:

    Iterator bookAggregate = datastore.createAggregation(Book.class)
                    .sort(descending("title"))
                    .lookup("Person", "author", "_id", "bookAuthor")
                    .project(projection("_id"),
                             projection("title"),
                             projection("bookAuthor.name"),
                             projection("bookAuthor.age"))
                    .aggregate(Book.class);

    while (bookAggregate.hasNext()){
                ObjectMapper om = new ObjectMapper();
                try {
                  json = om.writerWithDefaultPrettyPrinter().writeValueAsString(bookAggregate.next());
                  System.out.println(json);
                } catch (Exception ex) {
                }
            }

The json string, only includes items from Book.  Values from Person (e.g. name & age) are not there. 

I expected the aggregation to produce something like:

    {
        _id,
        title,
        name, 
        age
    }

Apologies if this is a poor example, but how do I include items from the “joined” table in an aggregation?

Thanks
Steve

**Comment by evanchooly** [comment]
Well, you're aggregating in to a `Book` so it's only going to have available whatever fields are on a `Book`.   You could try `.aggregate(Document.class)` instead and then you can just use `Document.toJson()` and see how close that gets you to what you want.

**Comment by sterd71** [comment]
Hi evanchooly,

Thanks for that, it's got me a bit closer to what I want.  The bookAuthor items have come out contained in an array element.

I'll keep playing.
Thanks for your suggestion.
Steve

**Comment by evanchooly** [comment]
this seems to be resolved so i'll close it out.  feel free to reopen or open a new one if something comes up.
