### ISSUE TITLE
morphia.dev website is unusable on mobile devices

### ISSUE THREAD

**Issue by hoat4** [MorphiaOrg/morphia#1578]
The pages change layout when window width becomes less than 1024 pixels, but that mobile layout has many glitches, so no pages are accessable beyond the landing page and the Getting Started page. 

See attached screenshots. When I click on the hamburger icon at the top left corner on the Getting Started page, it goes back to the "landing" page, instead of providing a navigation menu. 

![morphia dev_landing_index html(Pixel 2)](https://user-images.githubusercontent.com/5830175/108994596-4afcf680-769c-11eb-9ba2-072e40509f52.png)
![morphia dev_morphia_2 1_index html(Pixel 2)](https://user-images.githubusercontent.com/5830175/108994610-4e907d80-769c-11eb-92fd-9356937a6a59.png)

**Comment by evanchooly** [comment]
Thanks for the reminder.  There are some oddities in the antora libs that generate that html.  I'll see what fixes are available and if I can fix it otherwise.

**Comment by evanchooly** [comment]
still not quite what I want but it seems to render better now.
