### ISSUE TITLE
Support for Composite id

### ISSUE THREAD

**Issue by himnaz** [MorphiaOrg/morphia#1583]
Hi,
Could you please let me know if morphia supports composite id for mongodb collections?

For example support for the following document types.

{"_id":{"owner_id":{"$numberLong":"1"},"pro_id":{"$numberLong":"289"}}, "address": "123 Main Street"}

** Please complete the following information: **
    Server Version: 3.6
    Driver Version: 3.12.8
    Morphia Version: 1.6.1

**Comment by evanchooly** [comment]
It does.  See [this test](https://github.com/MorphiaOrg/morphia/blob/a5526094d889ee7c561b68c313a9fc706a4a321e/legacy-tests/src/test/java/dev/morphia/mapping/CompoundIdTest.java) for an example.

**Comment by himnaz** [comment]
Superb! very helpful thank you.

**Comment by himnaz** [comment]
Hi
 I am getting  " by: dev.morphia.mapping.validation.ConstraintViolationException" for the composite key entity. Should the composite keyid class be created without the @Entity? . I have uploaded the classes and the full error stack
Thank you for your support.
[composite_id_error.zip](https://github.com/MorphiaOrg/morphia/files/6250640/composite_id_error.zip)

**Comment by evanchooly** [comment]
I'm so sorry.  I missed this update.  But yes, the type should have `@Embedded` on it as well.

**Comment by evanchooly** [comment]
seems this has been resolved.  feel free to reopen if something comes up.
