### ISSUE TITLE
Using Morphia in Wildfly 22

### ISSUE THREAD

**Issue by himnaz** [MorphiaOrg/morphia#1591]
** Please ask your question and provide whatever background or supporting information you think might be relevant: **
Hi I am getting the following error when trying to connect to the database from Wildfly 22 application server. Could you please tell me how you should configure the morphia in the wildfly project.
I have uploaded the full error file, pom and the class which is creating the connection.
Caused by: java.lang.NoClassDefFoundError: Failed to link com/mongodb/DBObjectCodec (Module "deployment.ROOT.war" from Service Module Loader): org/bson/codecs/OverridableUuidRepresentationCodec

** Please complete the following information: **
    Server Version: 3.6
    Driver Version:
    Morphia Version:2.1.4
[error.txt](https://github.com/MorphiaOrg/morphia/files/6237853/error.txt)
[pom.txt](https://github.com/MorphiaOrg/morphia/files/6237862/pom.txt)

[MorphiaDriverConnection.txt](https://github.com/MorphiaOrg/morphia/files/6237872/MorphiaDriverConnection.txt)

**Comment by evanchooly** [comment]
it sounds like your war file is missing the driver jar for some reason.  Can you confirm it's in your war file?

**Comment by himnaz** [comment]
I have tried including the following dependency for the mongodb driver, but still getting the error. 
<mongodb.driver.version>3.12.8</mongodb.driver.version>
<dependency>
			<groupId>org.mongodb</groupId>
			<artifactId>mongo-java-driver</artifactId>
			<version>${mongodb.driver.version}</version>
		</dependency>


I have attached the dependency tree and  full error stack and the pom in the attachment.
[error_details.zip](https://github.com/MorphiaOrg/morphia/files/6244078/error_details.zip)

**Comment by evanchooly** [comment]
Morphia 2.x requires at least version 4.0 of the driver so that's the first thing to fix.  The tests, e.g., won't even start with an older driver than that.

**Comment by himnaz** [comment]
Used the driver 4.0.5 the issue got resolved.
