### ISSUE TITLE
Morphia in JDK 1.8

### ISSUE THREAD

**Issue by DeserRC** [MorphiaOrg/morphia#1592]
I would like to know if there is any way for me to make Morphia work in version 1.8 of the JDK

**Please complete the following information:** 
    Server Version: 4.4.4
    Driver Version: 4.2.2
    Morphia Version: 2.2-SNAPSHOT

**Comment by evanchooly** [comment]
Morphia 1.6 works on Java 8.  2.0 and newer all use Java 11, however.
