### ISSUE TITLE
In 2.x can not use project(field, true) on Query

### ISSUE THREAD

**Issue by Alexander-Nalbandyan** [MorphiaOrg/morphia#1595]
According to this guide we should still be able to use [projections](https://morphia.dev/morphia/2.1/querying-old.html#_projections) with legacy method but the project method is not found. Please suggest how I can use it?
Thanks

**Comment by evanchooly** [comment]
That looks like a docs bug actually.  that method was deprecated in 1.6 and removed in 2.0.  I'll do an audit of those docs and get them up to ... well, code, I suppose.

**Comment by evanchooly** [comment]
the milestone says 2.2 just so it shows up on my current todo list.  i'll backport the update to al the 2.x versions.
