### ISSUE TITLE
Mappable types error

### ISSUE THREAD

**Issue by mluizaa00** [MorphiaOrg/morphia#1596]
Hello, I'm currently using Morphia on a Java EE application with Wildfly as the server, the error is the following:

`com.luizaprestes.store.model.Author; is not a mappable type. Mappable types need to be annotated with either @Entity or @Embedded.`

The author object already has the **Entity** and **Id** annotation. Embedded is **deprecated in 2.2** so I'm not using that.
Does someone had the same error? If yes, what possible causes could be that?

**Information:**
  Server Version: 4.4.4
  Driver Version: 4.2.2
  Morphia Version: 2.2-SNAPSHOT

  Java: JDK 11
  Wildfly: 23.0.0

**Comment by evanchooly** [comment]
Can you share your Author class definition?  And can you try using 2.1.4 since that is the latest.  2.2 should work just fine but it *is* a snapshot release so relying on it isn't advisable.  2.2 is some time out from being released.

**Comment by mluizaa00** [comment]
Here is the Author class, please ignore the Storable interface as it is from another framework, it worked fine with Morphia so that's not really the problem.

I will get a response for you about changing the Morphia version tomorrow.

```
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity(value = "website_authors")
public class Author implements Storable<Author> {

  @Id
  private UUID id;
  private String name;

}
```

**Comment by evanchooly** [comment]
Sorry, i got sidetracked with stuff.  are you sure that's *Morphia's* `@Entity` and not, say, Hibernate's?

**Comment by mluizaa00** [comment]
Just checked in the model, and the current import is Morphia @Entity not Hibernate's.

**Comment by mluizaa00** [comment]
This issue is no longer needed.
