### ISSUE TITLE
Polymorphic entities with lifecycle: child entity lifecycle methods are not invoked 

### ISSUE THREAD

**Issue by renat-nosto** [MorphiaOrg/morphia#1608]
**Describe the bug**
https://github.com/MorphiaOrg/morphia/issues/1589 being incomplete port of https://github.com/MorphiaOrg/morphia/pull/1587 in a respect that it doesn't respect ChildEntity lifecycle methods

**To Reproduce**
```java
    @Entity(value = "entity")
   class BaseEntity {
        @Id
        ObjectId id;

        @PostLoad
        void audit() {
        }
    }

   class ChildEntity extends BaseEntity {
        String value;

        @PostLoad
        void childAudit() {
        }

    }
```

```java
ChildEntity childEntity = new ChildEntity();
ds.save(childEntity);
BaseEntity saved = ds.find(BaseEntity.class).filter(Filters.eq("_id", childEntity.id)).first();
```
in version 2.1.5 `childAudit` is not called as `EntityModel` for `BaseEntity` is used for calling lifecycle methods (through `morphiaCodec.getEntityModel()` in `EntityDecoder.decodeWithLifecycle` instead of newly resolved `model`)

**Expected behavior**
`childAudit` is invoked 

** Please complete the following information: **
 - Server Version: 4.2.6
 - Driver Version: 4.0.5
 - Morphia Version: 2.1.5

Only applies to 2.1.5, not 2.2

**Comment by evanchooly** [comment]
That's really interesting that it works on 2.2 but not 2.1.5.  I hadn't thought that part changed all that much.  I'll try to take a look at this tomorrow.
