### ISSUE TITLE
Please could you create 2.1.6 release with 1599 ?

### ISSUE THREAD

**Issue by rozky** [MorphiaOrg/morphia#1613]
Hi Justin,

sorry for a shameless ask but is there any chance you could create  2.1.6 release with #1599 ?

Thanks,
Michal

**Comment by evanchooly** [comment]
I surely can.  I'd hoped to just roll it in to 2.2.0 but that one's taking a little longer than I'd hoped to get out the door.  I'll try to push that tonight.

**Comment by rozky** [comment]
You are a hero, thanks a lot

**Comment by evanchooly** [comment]
just pushed the bits.  You should be able to see them now on central.  if not wait a few hours but looking at the directory, i see a 2.1.6 folder there.

**Comment by rozky** [comment]
Nice, I can see it, thanks a lot
