### ISSUE TITLE
Add Java module-info

### ISSUE THREAD

**Issue by BlackReloaded** [MorphiaOrg/morphia#1616]
**Is your feature request related to a problem? Please describe.**
Actual morphia does not support for the java modules system.

**Describe the solution you'd like**
Add `module-info.java` with all needed requirement and exports to the source.

**Describe alternatives you've considered**
It is possible to declare a automatic module name in the manifest

**Additional context**
Morphia is already build with jdk 11, so a modules file should not be a problem.

**Comment by evanchooly** [comment]
this has already been filed #1502.

**Comment by BlackReloaded** [comment]
Sorry i had used the wrong keywords.

**Comment by evanchooly** [comment]
no worries.  it's on my radar but it's been low-priority so far.  it'll be the first thing i do in 2.3 so I can iron out any wrinkles.
