### ISSUE TITLE
Inheritance not working

### ISSUE THREAD

**Issue by davidribeirofhp** [MorphiaOrg/morphia#1617]
**Describe the bug**

I have a superclass mapped to a collection and multiple subclasses of that. I cannot query this collection and get data mapped to these subclasses. If I use superclass in find, a filter is automatically added to the query to match the _t field (or className if using legacy) to this superclass, filtering all data of these subclasses. If I use one subclass in find, it still adds the filter for the superclass. Also tried using the collection name in find, in this case, a warning is logged saying there are multiple classes mapped to this collection. The automatic filter is still added.

**To Reproduce**

Consider the following classes:

```java
@Entity("mycollection")
public class MySuperClass {
  @Id private UUID id;
  private String a, b;
...
}

public class MySubClass1 extends MySuperClass {
  private String c;
...
}

public class MySubclass2 extends MySuperClass {
  private String c;
...
}
```

Data is inserted for each of those subclasses then try querying it:
```java
datastore.find(MySuperClass.class).iterator().toList();
datastore.find(MySubclass1.class).iterator().toList();
datastore.find("mycollection").iterator().toList;
```

**Expected behavior**
The data for the MySuperClass as well as the subclasses should be returned by these queries. An automatic filter by the _t field / className should not be added to the query.

** Please complete the following information: **
 - Server Version: Irrelevant
 - Driver Version: Irrelevant
 - Morphia Version: 2.1.6

**Additional context**
I am in the process of migrating from 1.3.2 into Morphia's latest version, the old subclassing mechanism is currently unsupported.

**Comment by evanchooly** [comment]
I just noticed, too, that this is not really documented in the docs so if this change fixes your problem (which i'm sure it will) I'll update the docs to highlight this method.

**Comment by davidribeirofhp** [comment]
Thank you for the quick response @evanchooly, that indeed solves my problem! I could not find that method in the documentation, it may be particularly useful in the migration to 2.0 as well.
