### ISSUE TITLE
How to build a list of updates?

### ISSUE THREAD

**Issue by bulldozer75** [MorphiaOrg/morphia#1621]
Is there a way to add update operators one by one, like the following?

```
Boolean field1, field2;
// [...]
List<UpdateOperator> ops = new ArrayList<>();
if (field1 != null)
    ops.add(UpdateOperators.set("field1", field1));
if (field2 != null)
    ops.add(UpdateOperators.set("field2", field2));
q.update(ops).execute();
```
The code above doesn't work because there is only `update(UpdateOperator, UpdateOperator, ...)`, and there is no `update(List)`. So, I have to provide all update operators together, which is inconvenient for complex updates.

In 1.5.4 I could achieve that by adding `UpdateOperations` one by one similarly to my code above, but the support of `UpdateOperations` was removed at some point.

 Morphia Version: 2.1.6

**Comment by bulldozer75** [comment]
Found a workaround:

```
Boolean field1, field2;
// [...]
List<UpdateOperator> ops = new ArrayList<>();
if (field1 != null)
    ops.add(UpdateOperators.set("field1", field1));
if (field2 != null)
    ops.add(UpdateOperators.set("field2", field2));
q.update(ops.get(0), ops.toArray(new UpdateOperator[0])).execute();
```

**Comment by evanchooly** [comment]
Yeah, the goal was to syntactically enforce at least one update operation but it's turned out to be more awkward than I'd hope.  More people are building their list of operations "externally" like you are and it means a super awkward invocation.  I'll clean that up.
