### ISSUE TITLE
Update operation $set does not work with a whole map as an argument when the key of the map has a non-String type

### ISSUE THREAD

**Issue by burdeynyy** [MorphiaOrg/morphia#1622]
Hi!
When trying to update a whole map with a non-String key I get the following error:
```
java.lang.ClassCastException: class com.test.repository.model.TestMapWithEnumKey$TestEnum cannot be cast to class java.lang.String (com.test.repository.model.TestMapWithEnumKey$TestEnum is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at org.bson.codecs.MapCodec.encode(MapCodec.java:112)
	at org.bson.codecs.MapCodec.encode(MapCodec.java:40)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at dev.morphia.aggregation.experimental.codecs.ExpressionHelper.value(ExpressionHelper.java:95)
	at dev.morphia.query.OperationTarget.lambda$encode$0(OperationTarget.java:74)
	at dev.morphia.aggregation.experimental.codecs.ExpressionHelper.document(ExpressionHelper.java:35)
	at dev.morphia.query.OperationTarget.encode(OperationTarget.java:74)
	at dev.morphia.query.Operations.toDocument(Operations.java:84)
	at dev.morphia.query.UpdateBase.toDocument(UpdateBase.java:76)
	at dev.morphia.query.Update.execute(Update.java:45)
	at dev.morphia.query.Update.execute(Update.java:35)
...

```
Reproducible example:

```
@Data
@Entity
public class TestMapWithEnumKey {

    @Id
    private ObjectId id;

    private Map<TestEnum, EmbeddedObjTest> map;

    @Embedded
    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    public static class EmbeddedObjTest {
        private String name;
        private String value;
    }

    public enum TestEnum {
        ANYVAL, ANOTHERVAL
    }
}
```

```
    @Test
    public void testUpdateMap() {
        final Map<TestEnum, EmbeddedObjTest> map =
                Map.of(TestEnum.ANYVAL, new EmbeddedObjTest("name", "value"));
        datastore.find(TestMapWithEnumKey.class)
                .update(UpdateOperators.set("map", map))
                .execute();
    }
```
So I wanted to know if it is by design or it is a bug.
Thank you. 

    OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
    Server Version: 4.2.8
    Driver Version: 4.0.5
    Morphia Version:2.1.6

**Comment by evanchooly** [comment]
I've been on the road so I'm just now sitting down to this one.  Any time you see an exception like that it's definitely a bug and probably in Morphia.  Even if it's in your code, morphia should not validate that mapping at a minimum.  I'll dig in to this and see what's happening.

**Comment by evanchooly** [comment]
closed via 95e3263e969a0977d2baf3bac3c833af897b1870 et al

**Comment by evanchooly** [comment]
Can you try using 2.1.7-SNAPSHOT just to confirm before I push out that release?  Instructions on how to do that can be found [here](https://morphia.dev/morphia/2.1/index.html)

**Comment by kirill-burdeynyy-immoviewer** [comment]
@evanchooly it works as expected now, thank you! May I ask you to add this fix to 2.2.x version too?

**Comment by burdeynyy** [comment]
@evanchooly it works as expected now, thank you! May I ask you to add this fix to 2.2.x version too?

**Comment by evanchooly** [comment]
yep.  now that it's confirmed outside of unit tests, i'll forward port that.

**Comment by ugljesas** [comment]
I would just like to point out that this is still (as of 2.2.2) throwing the same exception if the map is created with new HashMap() or Maps.newHashMap() from Guava. It does work with Map.of(k,v) and Maps.newEnumMap(enumClass).

It appears to be using dev.morphia.mapping.codec.MorphiaTypesCodecProvider$HashMapCodec for HashMaps instead of dev.morphia.mapping.codec.MorphiaMapCodec.

**Comment by evanchooly** [comment]
curious.  can you provide a reproducer and i'll take another look?

**Comment by ugljesas** [comment]
The test provided here and in the latest merges should fail if 
final Map<TestEnum, EmbeddedObjTest> map = Map.of(TestEnum.ANYVAL, new EmbeddedObjTest("name", "value"));
is replaced with
final Map<TestEnum, EmbeddedObjTest> map = new HashMap()
map.put(TestEnum.ANYVAL, new EmbeddedObjTest("name", "value"));
