### ISSUE TITLE
Test packages included in the release JAR

### ISSUE THREAD

**Issue by ctmay4** [MorphiaOrg/morphia#1623]
Upgrading to 2.2.0, I started getting this error from Gradle.

```
Execution failed for task ':bootJar'.
> Entry BOOT-INF/lib/jquery-3.5.1.jar is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.0.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```

When I look at the dependencies I see this:

```
+--- dev.morphia.morphia:morphia-core:2.2.0
|    +--- org.mongodb:mongodb-driver-sync:4.2.2 -> 4.1.2
|    |    +--- org.mongodb:bson:4.1.2
|    |    \--- org.mongodb:mongodb-driver-core:4.1.2
|    |         \--- org.mongodb:bson:4.1.2
|    +--- org.mongodb:mongodb-driver-legacy:4.2.2 -> 4.1.2
|    |    +--- org.mongodb:bson:4.1.2
|    |    +--- org.mongodb:mongodb-driver-core:4.1.2 (*)
|    |    \--- org.mongodb:mongodb-driver-sync:4.1.2 (*)
|    +--- io.github.classgraph:classgraph:4.8.78 -> 4.8.83
|    +--- net.bytebuddy:byte-buddy:1.10.2 -> 1.10.22
|    +--- org.slf4j:slf4j-api:1.7.30
|    +--- org.jetbrains:annotations:13.0
|    +--- com.github.spotbugs:spotbugs-annotations:3.1.9
|    |    \--- com.google.code.findbugs:jsr305:3.0.2
|    \--- org.testng:testng:7.4.0
|         +--- com.beust:jcommander:1.78
|         \--- org.webjars:jquery:3.5.1
```

Why would the release JAR have "testng" as part of it?  I checked the prior version and it did not include JQuery.

The reason I am getting an error is because I use the NPM webjar which is different than the one you are including.

```
implementation 'org.webjars.npm:jquery:3.5.1'
```

I could exclude the testng dependency but it seems like it shouldn't be there, right?

**Comment by evanchooly** [comment]
huh.  yeah.  looks like a case of `depMgmt` assuming the child poms would do it and the child poms assuming the opposite.  I've fixed.  My apologies for the slip.  The last big push was getting all the `legacy-test` code audited and either moved over or removed as redundant.  Looks like that dep got mangled in the process.  At any rate, any 2.2.1 will *not* have that and you can exclude it for now.  If it's bothersome, I can look at putting a 2.2.1 together.  Maybe I should.  Releases are cheap and that's an annoying gaffe.

Ok.  you talked to me in to it.  I'll push a 2.2.1 and clean that.  Thanks for the heads up.  I'd have never noticed that probably.

**Comment by evanchooly** [comment]
ok.  2.2.1 is on central.  should be all cleaned up.  :/

**Comment by ctmay4** [comment]
Just tested and all working great now. Thanks for such a quick fix!
