### ISSUE TITLE
Doc with deprecated methods

### ISSUE THREAD

**Issue by Duduxs** [MorphiaOrg/morphia#1635]
I'm following the documentation to create some examples and I see some example methods to do X or Y, however when I use it in my project it's deprecated and I have to look for another alternative on the internet to make it more up-to-date.

PS: I'm looking for the most up-to-date documentation.

It would be interesting to update the site with the most current examples, or even talk about the documentation of that method which we should use when it gets deprecated

**Comment by evanchooly** [comment]
i'll scan through and see what I can find that's still showing the deprecated bits but if you have specific examples that'd really help out. Thanks.

**Comment by Duduxs** [comment]
Yes, like method execute() at morhpia 2.3 or below version in the [quick tour](https://morphia.dev/morphia/2.3/quicktour.html)

**Comment by evanchooly** [comment]
Great.  Thanks.  I'll clean that up.

**Comment by newk5** [comment]
@evanchooly can you clarify what should be used instead of .execute()?
I'm was migrating an old app from 1.3.2 to 2.3 but I stopped for now until I know for sure which methods I should use, the docs got me a bit confused as they suggest to use deprecated methods and everything else I try to use seems to be marked as deprecated aswell, are there more updated docs somewhere I can follow?

**Comment by evanchooly** [comment]
I'm in the process of updating the docs now (trying and failing to get antora includes to work) but here's the short version.  A `Query` is also an `Iterable` so you could simply include the query as part of a for loop, e.g., and iterate the results.  If you explicitly want a list then you just need to call `.iterator().toList()` and you'll get a `List` with all the results of the query.  This, obivouly, can run in to memory issues so you'll want to be careful with that route.

**Comment by newk5** [comment]
I see what you mean, Thanks.

**Comment by newk5** [comment]
One more question, .field(fieldName).doesNotExist() is deprecated, what should I use instead?

**Comment by evanchooly** [comment]
uses of `field()` can be done using `filter()` instead.  you can enable the "legacy" query API by using `MapperOptions.legacy()`.  This will give you 1.x style behavior.  `startsWith()` is done via a regex filter.  You can find the replacement methods on the javadoc for these methods.

**Comment by newk5** [comment]
- Yep I know about the filter() method, what I'm saying is: there is no "doesNotExist()" method inside Filters, how do I use "doesNotExist()" with the new API?
- So utility methods like "doesNotExist" "startsWith", "endsWith", "containsIgnoreCase", "endsWithIgnoreCase" have all been removed from the new API?

**Comment by evanchooly** [comment]
- You'd use `Filter.exists().not()`
- for the others, you'd use regex patterns:  `regex("keywords").pattern("^ralph").not()` for words beginning with ralph, e.g.  `regex()` supports the options and flags as shown in the [mongodb docs](https://docs.mongodb.com/manual/reference/operator/query/regex/)

**Comment by newk5** [comment]
>     * for the others, you'd use regex patterns:  `regex("keywords").pattern("^ralph").not()` for words beginning with ralph, e.g.  `regex()` supports the options and flags as shown in the [mongodb docs](https://docs.mongodb.com/manual/reference/operator/query/regex/)
I see, thats unfortunate. I know about the mongodb $regex operator but I was hoping to use those utility methods rather than having to write a regex every time, they're more user friendly in my opinion and were very useful shortcuts that I used in all my apps back in 1.3.2. I hope you consider adding them in the upcoming versions :stuck_out_tongue:

**Comment by evanchooly** [comment]
Well, the good news is, that it's just a `Filter` at the end of the day so you could just encapsulate that in a method call.  One of the goals of 2.x has been to simplify the API a bit as during it's long run in 0.x and 1.x, Morphia had accumulated a lot of convenience methods.  That led to a large, inconsistent API that I'm hoping to correct.  I won't say "never," but ... I guess we'll see.  :)

**Comment by shubhangi-bawanthade** [comment]
why in 1.x api is faster then 2.x i used 2.3.5 version
