### ISSUE TITLE
Problem getting aggregate lookup joining two collections to retrieve joined documents

### ISSUE THREAD

**Issue by Luthien-in-edhil** [MorphiaOrg/morphia#1636]
We're having a problem retrieving the results of an Aggregate lookup query with Morphia. 

The idea was to improve performance of what was before two separate queries, where the first retrieves the original documents (collection Original) and the second one the translations (collection Translation).

The documents are joined on three columns (dsId, lcId and pgId), and the MongoDB query works fine:

```
db.Original.aggregate([
   {  $match: { query parameters } },
   {  $lookup:
     {
       from: "Translation",
       let: { "origDsId": "$dsId", origLcId: "$lcId", "origPgId": "$pgId" },
       pipeline: [
          { $match:
             { $expr:
                { $and:
                   [
                     { $eq: [ "$dsId",  "$$origDsId" ] },
                     { $eq: [ "$lcId",  "$$origLcId" ] },
                     { $eq: [ "$pgId",  "$$origPgId" ] }
                   ]
                }
             }
          },
          { $project: { dsId: 0, _id: 0 } }
       ],
       as: "translations"
     }
}])
```

Trying to get this working in Morphia, I added a field to the Original entity object:
`private List<Translation> translations;` (plus getter and setter)

And added a query method:

```
public List<Original> findOriginalPagesWithTranslations(String datasetId, String localId) {
    Aggregation<Original> query = datastore.aggregate(Original.class)
               .match(eq(DATASET_ID, datasetId), eq(LOCAL_ID, localId))
               .lookup(Lookup.lookup(Translation.class)
                     .let("origDsId", value("$dsId"))
                     .let("origLcId", value("$lcId"))
                     .let("origPgId", value("$pgId"))
                     .pipeline(Match.match(expr(Expressions.of()
                           .field("$and",
                                  array(Expressions
                                        .of().field("$eq",
                                               array(field("dsId"),
                                                     value("$$origDsId"))),
                                        Expressions
                                        .of().field("$eq",
                                               array(field("lcId"),
                                                     value("$$origDsId"))),
                                        Expressions
                                        .of().field("$eq",
                                               array(field("pgId"),
                                                     value("$$origPgId"))))))))
                     .as("translations"));
    return query.execute(Original.class).toList();
}
```
I derived the syntax of the pipeline above [from this unit test](https://github.com/MorphiaOrg/morphia/blob/master/core/src/test/java/dev/morphia/test/aggregation/experimental/TestAggregation.java), but whatever we try, the translations List remains empty. Debugging the actual MongoDB query that the above method produces shows that it is the same as what I tried manually in MongoDB; so I guess there is something not quite right with the mapping, but I can't imagine what that might be - in fact, I thought about annotating the translations field, but I'm not sure if that would cause the query to persist the outcome to the database ;)

Do you maybe have any suggestions where we might look?

Thanks!

    Server Version: MongoDB v. 4.4.3
    Driver Version: 4.0.5 (Spring-Boot-Starter-Mongodb, v 2.3.4-RELEASE)
    Morphia Version: 2.2.1

**Comment by evanchooly** [comment]
this has likely aged out of relevance.  my apologies for not getting to it sooner.  please reopen this or create a new discussion if you'd still like to discuss it.
