### ISSUE TITLE
It seems Date types and lifecycles do not play along well

### ISSUE THREAD

**Issue by Pr-Pierre** [MorphiaOrg/morphia#1639]
**Describe the bug**

I skimmed through the bugs, but I did not find any covering my issue (https://github.com/MorphiaOrg/morphia/issues/1218 is close but not exactly the same thing), so here comes the description. I am very sorry if it is a duplicate or if it is a misconfiguration on my side.

On a non-UTC system, when Dates and lifecycle hooks are used together with a Morphia instance configured to store date with SYSTEM_DEFAULT, it seems part of Morphia use dateStorage configuration whereas other uses hardcoded UTC value.

In my case, with a system set to Europe/Paris Summertime, date time of 2021/10/10 10:00:00 will be stored as 2021/10/10 08:00:00.

**To Reproduce**

Here is a test running on 2.x branch code. System TZ is +2Hours.

```
public class DateWithLifecycleTest extends TestBase {
    @Test
    public void ensureDateConfigurationIsAppliedEverywhere() {

        Datastore ds = Morphia.createDatastore(getMongoClient(), getDatabase().getName(),
            MapperOptions.builder().dateStorage(DateStorage.SYSTEM_DEFAULT).build());

        SimpleBean simpleBean = new SimpleBean();
        simpleBean.setId(ObjectId.get());
        simpleBean.setLdt(LocalDateTime.now());
        simpleBean.setDate(new Date());

        ds.save(simpleBean);

        SimpleBean reloaded = ds.find(SimpleBean.class).first();

        Assert.assertEquals(reloaded.getDate(), simpleBean.getDate());
        Assert.assertEquals(reloaded.getLdt().getHour(), simpleBean.getLdt().getHour());
    }

    @Entity
    private static class SimpleBean {
        @Id
        private ObjectId id;
        private LocalDateTime ldt;
        private Date date;

        @PostPersist
        void postPersist() {
            // This @PostPersist method ensures DocumentWriter is used during persistance.
            // The method dev.morphia.mapping.codec.DocumentWriter.writeDateTime(long) uses the hardcoded Zone UTC
        }

        public ObjectId getId() {
            return id;
        }

        public void setId(ObjectId id) {
            this.id = id;
        }

        public LocalDateTime getLdt() {
            return ldt;
        }

        public void setLdt(LocalDateTime ldt) {
            this.ldt = ldt;
        }

        public Date getDate() {
            return date;
        }

        public void setDate(Date date) {
            this.date = date;
        }
    }
}
```

**Expected behavior**

In my opinion, tests should be ok.

** Please complete the following information: **

 - Server Version: 4.4.3
 - Driver Version: 4.2.3
 - Morphia Version: 2.1.5, but all 2.x should be affected

**Additional context**

DocumentWriter, which is used when lifecycles hooks are executed, has a hardcoded UTC configuration. I _guess_ this class could use the date storage configuration, but I do not know all the ins and outs of this class, and that would be a breaking change for those who built upon this behaviour.

**Comment by evanchooly** [comment]
OK.  I think i have this fixed based on a slight alteration of your test case.  If you would like to try the snapshot build to confirm, i would greatly appreciate it.  there's one other issue i might hold 2.2.2 for but i haven't yet dug in to that one just yet but a proper release should happen in the next few days I hope.

**Comment by Pr-Pierre** [comment]
Thanks @evanchooly, it works great on our use case.
