### ISSUE TITLE
'Morphia()' has private access in 'dev.morphia.Morphia'

### ISSUE THREAD

**Issue by alvileg** [MorphiaOrg/morphia#1642]
** Please ask your question and provide whatever background or supporting information you think might be relevant: **
For some reason, when I try to just create a Morphia object, exactly as it is seen on the docs, I get the following error:
```'Morphia()' has private access in 'dev.morphia.Morphia'```

This is the line:
``` Morphia morphia = new Morphia();```

Any ideas why this happens, or is it intended behaviour?

** Please complete the following information: **
    Morphia Version: 2.2.1

**Comment by evanchooly** [comment]
Because it's not meant to be used that way.  It has factory methods for creating `Datastore` instances which are what you should be using.  See the [quick tour](https://morphia.dev/morphia/2.2/quicktour.html) for details.
