### ISSUE TITLE
Queries don't return data created by previous version of Morphia

### ISSUE THREAD

**Issue by gmitelman1** [MorphiaOrg/morphia#1651]
Hi.  I just swithced from Morphia 0.99 to 2.2.1.  Spent considerable amount of time converting all classes/queries just to get everything to compile.  Finally got to trying to just run the simplest query using datastore.find(AccessRoleData.class).iterator().toList();
It kept returning nothing.  I decided to try saving a new document and noticed what happens.  New Morphia puts classname (without the package) into field called "_t".  But old version put classname (with the package name) into "className" field.  I think that's why the new version can't find the data.  I'm not sure how to fix that.  Please help.

    Server Version: 3.6.12
    Driver Version: 4.3.3
    Morphia Version: 2.2.1

**Comment by evanchooly** [comment]
No worries.  Just making sure you were squared away.
