### ISSUE TITLE
How to store byte[] as a Binary rather than storing it as Array in MongoDB

### ISSUE THREAD

**Issue by himnaz** [MorphiaOrg/morphia#1653]
Hi I have the following class which has image stored inside a byte[], when saving this entity in the database using Morphia it stores it as a Array rather than storing it as a binary. Is there any way I can configure Morphia to store the image as Binary?

I am using the following MongoDB and Morphia
<mongodb.driver.version>3.12.8</mongodb.driver.version>
<morphia.driver.version>2.1.4</morphia.driver.version>

@Entity(useDiscriminator=false, value="Content")
public class Content implements Serializable {

    @JsonSerialize(using = ToStringSerializer.class)
    @Id
    private ObjectId id;
    private String fileName;
    private long fileSize;
    private Date createdDate;
    private Date updatedDate;
    //immediate parent
    private long parentRef;

    //Grand Parent Referrence
    private long gParentRef;
    private String fileDescription;
    private byte[] bytes;
    public Content() {
    }

}

**Comment by evanchooly** [comment]
Can you try 2.2?  The unit test for `byte[]` fields creates a `BinData` field in the database.  Is that what you're looking for?

**Comment by evanchooly** [comment]
i'm closing this for now as I think it's fixed and there's been no response.  feel free to reopen or open a new one if the problem persists.
