### ISSUE TITLE
Exception on Datastore.insert with versioned objects

### ISSUE THREAD

**Issue by DerNamenlose** [MorphiaOrg/morphia#1657]
**Describe the bug**
When adding a new versioned object with `Datastore.insert(T)` an exception is thrown from `setInitialVersion(...)`.

```
Exception in thread "main" dev.morphia.query.ValidationException: When versioning entities, the version properties must not be manually given values.
        at dev.morphia.DatastoreImpl.setInitialVersion(DatastoreImpl.java:588)
        at dev.morphia.DatastoreImpl.insert(DatastoreImpl.java:473)
        at dev.morphia.DatastoreImpl.insert(DatastoreImpl.java:286)
        at dev.morphia.DatastoreImpl.insert(DatastoreImpl.java:275)
        ....
```

**To Reproduce**

`App.java`
```java
package test;

import com.mongodb.client.MongoClients;

import dev.morphia.Morphia;

public class App {
    public static void main(String[] args) {
        var mongoClient = MongoClients.create(
                "..");

        var ds = Morphia.createDatastore(mongoClient, "reference-test");
        ds.getMapper().map(Entity1.class);

        final Entity1 e = new Entity1();
        ds.insert(e);
    }
}
```

`Entity1.java`
```java
package test;

import dev.morphia.annotations.Entity;
import dev.morphia.annotations.Id;
import dev.morphia.annotations.IdGetter;
import dev.morphia.annotations.Version;

@Entity
public class Entity1 {

    @Id
    private String _id;

    @Version
    private long version;

    @IdGetter
    public String getId() {
        return _id;
    }
}
```

**Expected behavior**

The document should be inserted with the initial version set to 1.

**Versions**
 - Server Version:5.0.2
 - Driver Version: 4.2.2
 - Morphia Version: 2.2.2

**Additional context**
I think the issue is due to the following line https://github.com/MorphiaOrg/morphia/blob/a803503f31c513f1437306a8569caecd49b0a688/core/src/main/java/dev/morphia/DatastoreImpl.java#L686  
`Long.equals(0)` cannot return true, because `0` is an `Integer` and not a long. The line probably should be along the lines of `.equals(0L)`. 

Related to that: there are two different ways to insert an item into the database: `ds.insert(...)` (which triggers the error) and `ds.save(...)` (which doesn't because `setInitialVersion` is not called on that code path). Which one is the intended way to go about this?

**Comment by evanchooly** [comment]
You're absolutely right about that check.  And I was confused because I was 100% sure I had a test with `long` version field.  And, indeed, I do.  But that test uses `save()` and not `insert()`.  So I'll clean this up.  `save()` vs `insert()` has long rankled me and I'm not sure both should be there.  Not needing to know if an entity has been inserted or not is a good thing.

**Comment by evanchooly** [comment]
I just pushed 2.2.3 with this fix.  It should be available Real Soon Now whenever the sync to central finishes.
