### ISSUE TITLE
Field level converters [moved]

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#167]
This is [Issue 167](http://code.google.com/p/morphia/issues/detail?id=167) moved from a Google Code project.
Added by 2010-11-22T16:41:02.000Z by [jej2...@gmail.com](http://code.google.com/u/116895926805721615729/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low
### Original description

What version are you using? (Morphia 0.97/MongoDB 2.3)

Currently it seems that Converters are registered at the class level and all instances of a particular type are handled by any converters which support the type.  In other examples of systems which support custom type converters (JAX-B for instance) converters are registered on fields such that fields of the same type can be converted with different converters.  Is there any plan to implement something like this?  My issue is that I have a field for storing geometry information which is currently a String (typically a WKT Geometry) but to take advantage of MongoDBs geospatial capability it must be stored as an array of doubles as is detailed at http://www.mongodb.org/display/DOCS/Geospatial+Indexing.  I don't see a way to handle this currently given the current Converter architecture.  Am I missing something?

**Comment by evanchooly** [comment]
this is another ancient bug with seemingingly limited appeal.  I'm going to defer this until someone else has a similar need.
