### ISSUE TITLE
Inconsistency between published Maven package and GitHub release 2.2.3

### ISSUE THREAD

**Issue by DerNamenlose** [MorphiaOrg/morphia#1708]
**Describe the bug**
The GitHub release 2.2.3 seems to point to a commit that is inconsistent with the actual released version 2.2.3 of the package. This is especially tricky because the dependencies changed. While the release commit refers  to `org.mongodb.mongodb-driver-sync:4.3.3`, the package on https://search.maven.org/artifact/dev.morphia.morphia/morphia/2.2.3/pom refers to version 4.2.2. This is a bit of an issue because the one is officially compatible with MongoDB 5, the other not. 

**Expected behavior**

The two sources should be identical, preferably referring the newer driver version.

** Please complete the following information: **
 - Server Version: 5.0.2
 - Driver Version: 4.2.2
 - Morphia Version: 2.2.3

**Comment by evanchooly** [comment]
That's definitely odd as those are generated at the same time.  I'll try to take a look tonight.  4.2 doesn't work with 5.0, then?  I haven't bumped my tests to include 5.0 yet which is should...

**Comment by DerNamenlose** [comment]
It does work, it's just not officially supported as per https://docs.mongodb.com/drivers/java/sync/current/compatibility/. I've use it quite happily on my dev machine at work for a few months now, but bringing the thing to production does require an officially supported combination. 

In any way, the difference between the repo and the package is odd. Is there a way to see exactly which commit got picked up when building the package? I usually do this manually for my private projects and am actually not all that well versed in terms of best practices for Java libraries.

**Comment by evanchooly** [comment]
The pom in maven central is correct:  https://repo1.maven.org/maven2/dev/morphia/morphia/morphia/2.2.3/morphia-2.2.3.pom and matches what is in git.  The release on the github page *was* pointing to a random git hash but i've updated to reference the tag itself.  I'm guessing there's a race condition with the release and CI processes.  I'll have to dig in to it.  Thanks for pointing that out.

**Comment by DerNamenlose** [comment]
Cool. Thx for the quick reaction. Any idea when there might be a release with the newer drivers included?

**Comment by evanchooly** [comment]
2.3 will support the latest driver.  There's only a handful of issues left there.
