### ISSUE TITLE
Lazy intialization in EntityModel.getLifecycleMethods can create ConcurrentModificationExceptions

### ISSUE THREAD

**Issue by timowestnosto** [MorphiaOrg/morphia#1720]
**Describe the bug**
The lazy initialization of EntityModel.lifecycleMethods can create ConcurrentModificationExceptions in case this happens from multiple threads at the same time
https://github.com/MorphiaOrg/morphia/blob/2775801c87acceeba459c70e8a7b8efe54ee6b23/core/src/main/java/dev/morphia/mapping/codec/pojo/EntityModel.java#L208-L222

As a workaround we are initializing the lifecycleMethods of all our EntityModels at application startup.

**To Reproduce**
* Define lifecycle methods in our models
* Attempt to use them from multiple threads at the same time

**Expected behavior**
Either concurrency safe collections or outer synchronization should be used to avoid this behaviour.
Alternatively eager initialization of lifecycle methods could be considered as well.

**Please complete the following information:**
 - Server Version:
 - Driver Version:
 - Morphia Version: 2.1.5, happens in master as well

**Additional context**
Any example models, queries, and executable test cases you can supply will greatly help debugging your issue:

**Comment by evanchooly** [comment]
I think the simplest solution is for me to just make your workaround official at least for now.  I have some rearchitecting plans that will obviate it all but in the meantime this should resolve this.
