### ISSUE TITLE
HashMap not getting query correctly

### ISSUE THREAD

**Issue by hswhsw610** [MorphiaOrg/morphia#1722]
**Describe the bug**
example code

`
public class Item {

    @Id
    ObjectID id;
    String name;
    HashMap<String, Price> prices;

    public static class Price {
        Material material;
        int amount;
    }

}
`
so, for example, lets say i query a lot of items.
and later, i need to get price of one item.
but any price i get(ex. item.prices.get("normal")) points to price of last queried item

ok lets explain that again
(since im not native english speaker, its really hard to explain)
1. i query two items which has name "one", "two"
2. i want to get price of "one" item so i do one.prices.get("normal")
3. but what i get is the price of "two"

**Expected behavior**
explained above

** Please complete the following information: **
 - Server Version: latest
 - Driver Version: 
 - Morphia Version: 2.2.3

**Additional context**
Any example models, queries, and executable test cases you can supply will greatly help debugging your issue:
please tell me if you dont understand
i have been struggling hours for this..

**Comment by hswhsw610** [comment]
Ok nvm i was stupid enough to not putting empty constructor to Price class

**Comment by evanchooly** [comment]
Might be worth my time to add a Validation for that.

**Comment by hswhsw610** [comment]
> Might be worth my time to add a Validation for that.

well it would be nice and others will not act stupid like me anymore
it should throw exception instead of just getting weird object, you know.
