### ISSUE TITLE
Converting a BasicDBObject to a POJO?

### ISSUE THREAD

**Issue by newk5** [MorphiaOrg/morphia#1729]
Is there a way to convert a BasicDBObject to a POJO with morphia?

Server Version: 3.0.7
Driver Version: 4.3.4 
Morphia Version: 2.2.3

**Comment by evanchooly** [comment]
Morphia 2.x does not work with the older `DBObject` based APIs.  You'll want to perform your queries and aggregations with Morphia directly if you want to take advantage of the mapping capabilities properly.

**Comment by newk5** [comment]
What if I had a org.bson.Document instead of a DBObject ? Would it be possible then?

**Comment by evanchooly** [comment]
There is not a public API for that, no.  I think there might be something visible if you dig hard enough but it's not considered a public API and is subject to change which is why I don't recommend or encourage its use.  How are you getting data such that Morphia is only just now entering the picture?

**Comment by newk5** [comment]
Well the use case here is to migrate existing, non-morphia applications. This is for an old legacy project that is currently not using morphia. It uses the mongo driver directly and there's tons of DBObject's being passed around the whole application. In some cases entities being built manually without any POJO's and using BasicDBObject#put directly. It's a big mess and unfortunately I inherited the project.

I proposed we switch to using morphia for obvious reasons. Unfortunately the project is pretty big and we can't migrate to morphia all at once, so the idea was to tackle some of the more "ugly" places for now. For places in the app where we have some loose DBObjects being passed around, we'd use morphia's excelent mapper to convert them to proper POJO's. And then slowly start creating morphia queries and using the morphia AP, until everything is converted to morphia.

This used to be possible back in the day with old morphia. I've done this exact same approach many many times with other apps back in morphia 1.x. I used the old morphia#fromDBObject internal method to quickly buy me some type safety by converting my DBObjects to POJO's, then slowly over time, rewrote everything to use morphia and removed the code using  morphia#fromDBObject. Even though it was an internal method and its usage was discouraged it always worked flawlessly for all my use cases.

I'd gladly settle with an internal method even if it's subject to change, this is only a temporary measure anwyay, even if its for Document instead of DBObject that would be fine since conversion between both is trivial.

**Comment by evanchooly** [comment]
OK.  So this is really down in the muck but let's see if this works.  There is a type inside Morphia used for lifecycle events called `DocumentReader`.  You can use this type with the codecs to deserialize in to the type you want.

```java
YourType entity = datastore.getCodecRegistry().get(YourType.class)
                                             .decode(new DocumentReader(document), DecoderContext.builder().build());
```

This should get you back an entity based on that document.  You can of course loop over however many documents you might have and deal with them accordingly.  Let's start with that and see if that gets you what you need.  Just be aware that all of that is very much internal implementation details and might not work a year from now.  :)

**Comment by newk5** [comment]
Thank you! That worked nicely. I think you meant to type datastore.getDatabase() btw :)

Is there an equivalent to go from POJO to Document? I tried this this but I'm not getting it right, maybe I'm passing the wrong things to the methods:
```java
    CodecRegistry codecs = datastore.getDatabase().getCodecRegistry();
    DocumentWriter docWriter = new DocumentWriter(new Mapper(datastore, codecs, MapperOptions.DEFAULT));
    Document doc = codecs.get(myPojo.getClass()).encode(docWriter, myPojo, EncoderContext.builder().build());
```
Netbeans tells me:
```
incompatible types: Object cannot be converted to CAP#1
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Object from capture of ? extends Object
```
When I pass in "myPojo". I'm not sure what should I be passing there. Any idea?

**Comment by newk5** [comment]
Ok, I just noticed encode doesn't actually return anything, the document is written into the document writer. Leaving my code here if anyone coming from morphia 1.x needs it:
This worked for me: 
```java
public Document toDocument(Object obj){
    CodecRegistry codecs = datastore.getDatabase().getCodecRegistry();
    DocumentWriter docWriter = new DocumentWriter(new Mapper(ds, codecs, MapperOptions.DEFAULT));
    Codec codec = codecs.get(obj.getClass());
    codec.encode(docWriter, obj, EncoderContext.builder().build());
    
    return docWriter.getDocument();
}

public toObject(Document doc, Class klass){
   return datastore.getDatabase()
   .getCodecRegistry().get(klass)
   .decode(new DocumentReader(doc), DecoderContext.builder().build());
}
```
Thank you for the help :)

**Comment by evanchooly** [comment]
> Thank you! That worked nicely. I think you meant to type datastore.getDatabase() btw :)
> 
> Is there an equivalent to go from POJO to Document? I tried this this but I'm not getting it right, maybe I'm passing the wrong things to the methods:
> 
> ```java
>     CodecRegistry codecs = datastore.getDatabase().getCodecRegistry();
>     DocumentWriter docWriter = new DocumentWriter(new Mapper(datastore, codecs, MapperOptions.DEFAULT));
>     Document doc = codecs.get(myPojo.getClass()).encode(docWriter, myPojo, EncoderContext.builder().build());
> ```
> 
> Netbeans tells me:
> 
> ```
> incompatible types: Object cannot be converted to CAP#1
>   where CAP#1 is a fresh type-variable:
>     CAP#1 extends Object from capture of ? extends Object
> ```
> 
> When I pass in "myPojo". I'm not sure what should I be passing there. Any idea?

No, i meant `datastore.getCodecRegistry()`.  At least that's how it works in master.  Perhaps that's shifted from 2.2.x.  I did some refactoring to separate out `Mapper` from `Datastore` so that a `Mapper` can be shared between them so that might be the discrepancy there.

**Comment by evanchooly** [comment]
Happy that's working for you.  Note that, as I mentioned in the last comment, that's likely to break with 2.3 when it comes out in a few weeks.

**Comment by newk5** [comment]
Ah I see. Yea since I'm on 2.2.3 the datastore doesn't have that method. I understand being an internal method it's subject to change, but it's ok, I'm not going to rely on these methods forever, just until we fully migrate all of the app to morphia. I can stay on 2.2.3 until then. Or maybe if 2.3 is similar, that code might still work with a few minor adjustments, I'll look into it when when 2.3 is released.
