### ISSUE TITLE
Support parameterized classes in fields [moved]

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#175]
This is [Issue 175](http://code.google.com/p/morphia/issues/detail?id=175) moved from a Google Code project.
Added by 2010-12-01T06:30:32.000Z by [scotthernandez](http://code.google.com/u/scotthernandez/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Milestone-Release1.0
### Original description

```
Support fields like this:

@Entity
class MyEntity {
   @Id ObjectId id;
   MyClass<String> s;
}

Currently you must create a concrete class like this:

class MyClassString extends MyClass<String> {...
```

**Comment by evanchooly** [comment]
works with 2.0's mapping code

**Comment by evanchooly** [comment]
fixed by the previous commit
