### ISSUE TITLE
Inheritance queries not working if the filtering criteria doesn't include the _id field

### ISSUE THREAD

**Issue by CMOW5** [MorphiaOrg/morphia#1773]
**Describe the bug**
This is related to #1617 

When doing inheritance-related queries, the result is always **null** if the filtering criteria **doesn't** include the **_id** field.
We're using a custom mapper with the option **enablePolymorphicQueries​(true)**, but it doesn't work.

```
AbstractSuperClass entity = datastore.find(AbstractSuperClass.class)
                                      .filter(Filters.eq("name", "client1Name"))
                                      .first();
```
**To Reproduce**
```
MapperOptions mapper = MapperOptions.builder()
                                 .discriminatorKey("className")
                                 .discriminator(DiscriminatorFunction.className())
                                 .enablePolymorphicQueries(true)
                                 .build();
                                 
Datastore datastore = Morphia.createDatastore(mongo, database.getName(), mapper)

AbstractSuperClass entity = datastore.find(AbstractSuperClass.class)
                                      .filter(Filters.eq("name", "client1Name"))
                                      .first();
```

This is the record in mongo
```
{
 "_id": 1,
 "className": "com.foo.SubClassA",
 "name":"client1Name"
}
```

abstract super class
```
@Entity("test_inheritance")
public abstract class AbstractSuperClass {

    @Id
    private long id;
    
    private String name;
    
    // constructor, getters and setters
}    
```

and the Subclass 
```
public class SubClassA extends AbstractSuperClass {
  // 
}
```

**Expected behavior**
It should return an **Entity of type SubClassA**, but we're getting **null**

**Additional context**
This is the link to our reproducer: https://github.com/CMOW5/reproducer-morphia-inheritance

**Important:** You'll notice that in our reproducer we need to **re-initialize the datastore in the test to reproduce the actual issue**. If we previously save an entity and then use the same datastore to query for it, **it will actually work** (maybe the datastore is caching the entities??)

Not sure if that's another issue. here's an example:

```
// arrange data for tests
datastore.save(new SubClassA(1L, "client1Name")

// this query will actually work. Maybe datastore has the previously saved entity cached ???
AbstractSuperClass entity = datastore.find(AbstractSuperClass.class)
                                      .filter(Filters.eq("name", "client1Name"))
                                      .first();
```

** Please complete the following information: **
 - Server Version: irrelevant 
 - Driver Version: irrelevant
 - Morphia Version: 2.2.1
 - JDK: Java11

**Comment by evanchooly** [comment]
Thanks for this.  i'll take a look in the next few days and get back to you.

**Comment by CMOW5** [comment]
Hi @evanchooly. Thank you! 
I can confirm that adding `mapPackageFromClass` works.

Thanks for your quick answer. I really appreciate it.
