### ISSUE TITLE
NPE while trying to save entity having reference (lazy, idOnly, ignoreMissing) to no-longer-existing entity

### ISSUE THREAD

**Issue by h-arlt** [MorphiaOrg/morphia#1811]
**Describe the bug**
Saving an entity that references another entity - field is annotated with `@Reference(lazy=true, idOnly=true, ignoreMissing=true)` - that does not exist in DB anymore causes a `NullPointerException` to be thrown.

Stack Trace:
```
 java.lang.NullPointerException
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
	at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
	at java.base/java.lang.reflect.Field.get(Field.java:418)
	at dev.morphia.mapping.codec.FieldAccessor.get(FieldAccessor.java:31)
	at dev.morphia.mapping.codec.pojo.PropertyModel.getValue(PropertyModel.java:162)
	at dev.morphia.mapping.Mapper.getId(Mapper.java:325)
	at dev.morphia.mapping.codec.references.ReferenceCodec.encodeId(ReferenceCodec.java:110)
	at dev.morphia.mapping.codec.references.ReferenceCodec.collectIdValues(ReferenceCodec.java:283)
	at dev.morphia.mapping.codec.references.ReferenceCodec.encode(ReferenceCodec.java:242)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.writeValue(EntityEncoder.java:103)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.encodeValue(EntityEncoder.java:93)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.lambda$encode$0(EntityEncoder.java:46)
	at dev.morphia.aggregation.experimental.codecs.ExpressionHelper.document(ExpressionHelper.java:36)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.encode(EntityEncoder.java:33)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.encode(MorphiaCodec.java:126)
```

**To Reproduce**
1. Store two entities in DB where one references the other by having the field annotated as described above.
2. Delete the referenced entity.
3. Modify the root entity and save it.

**Expected behavior**
No exception is thrown while saving the entity since the ID of the referenced entity is known and reference itself is marked w/ `ignoreMissing`. Optionally, the reference value might be stored as `null` since the referenced entity has gone.

** Please complete the following information: **
 - Server Version: 3.6.23
 - Driver Version: 4.2.2
 - Morphia Version: 2.2.3

**Additional context**
Sample demo testcase:
```java
package dev.morphia.test.mapping.lazy;

import static dev.morphia.query.experimental.filters.Filters.eq;

import org.bson.types.ObjectId;
import org.testng.annotations.Test;

import dev.morphia.Datastore;
import dev.morphia.annotations.Reference;
import dev.morphia.test.mapping.ProxyTestBase;
import dev.morphia.test.models.TestEntity;

@Test(groups = "references")
public class TestLazyIdOnlyIgnoreMissing extends ProxyTestBase
{
    public void testSaveAfterReferentIsGone() 
    {
        checkForProxyTypes();

        RootEntity root = new RootEntity();
        root.setBar("foo");
        final ReferencedEntity reference = new ReferencedEntity();
        reference.setFoo("bar");

        root.setR(reference);
        
        final Datastore datastore = getDs();
        final ObjectId id = datastore.save(reference).getId();
        datastore.save(root);
        
        root = datastore.find(RootEntity.class)
                        .filter(eq("_id", root.getId()))
                        .first();

        final ReferencedEntity p = root.r;

        assertIsProxy(p);
        assertNotFetched(p);
        p.getFoo();
        assertFetched(p);
        
        datastore.delete(reference);
        
        // Re-Fetch root entity from DB
        root = datastore.find(RootEntity.class)
            .filter(eq("_id", root.getId()))
            .first();

        root.setBar("baz");
        datastore.save(root);
    }
    
    
    public static class RootEntity extends TestEntity {
        @Reference(idOnly = true, lazy = true, ignoreMissing = true)
        private ReferencedEntity r;
     
        private String bar;

        public String getBar() {
            return bar;
        }

        public void setBar(String bar) {
            this.bar = bar;
        }

        public ReferencedEntity getR() {
            return r;
        }

        public void setR(ReferencedEntity r) {
            this.r = r;
        }
    }

    public static class ReferencedEntity extends TestEntity {
        private String foo;
        
        public String getFoo() {
            return foo;
        }
        
        public void setFoo(String string) {
            foo = string;
        }
    }
}

```

**Comment by h-arlt** [comment]
Just for a better understanding of the code: Why is the object passed to `PropertyModel#getValue(Object)` unwrapped in case it's an instance of `MorphiaProxy`? As the proxy class inherits from the class of the referenced entity, getting the value of a field should be possible without unwrapping.  Maybe I'm missing something here ;)
Anyway, some kind of special handling for ID properties might be necessary in `PropertyModel#getValue(Object)` as the ID might be known but the referenced entity has gone in the meanwhile.

**Comment by evanchooly** [comment]
This could probably use better messaging (though getting the context in the right place might be tricky) but referenced entities have to be saved first (or at last have a user supplied ID set) before trying to use them as in a reference.

**Comment by h-arlt** [comment]
The referenced entity did exist when the root entity was saved. This issue is about when the referenced entity does not exist anymore but the ID is known and reference is marked as ignore-missing.On Jan 28, 2022 18:52, Justin Lee ***@***.***> wrote:
This could probably use better messaging (though getting the context in the right place might be tricky) but referenced entities have to be saved first (or at last have a user supplied ID set) before trying to use them as in a reference.

**Comment by evanchooly** [comment]
hrm.  ok.  i'll play with the reproducer and see what pops.
