### ISSUE TITLE
Native query with morphia 2.x?

### ISSUE THREAD

**Issue by newk5** [MorphiaOrg/morphia#1823]
How can I make a native query with morphia 2.x?

Server Version: 3.0.7
Driver Version: 4.3.4
Morphia Version: 2.2.3

**Comment by evanchooly** [comment]
It depends on what you mean by "native."  if you mean cutting and pasting a query document in to morphia code, no, there isn't a supported way to do that.

**Comment by newk5** [comment]
I mean if I have a org.bson.Document (which is used to make queries with the mongodb java driver), can I pass that document to morphia or convert that to morphia query somehow? This was possible with morphia 1.x. Was this also another thing that was removed in 2.x?

**Comment by newk5** [comment]
@evanchooly Any news on this? 

We have an app running with morphia 1.x that allows the user to write mongodb queries on a "query builder" sort of UI and we were then using BasicDBObject.parse to convert it to DBObject and then passing that to morphia and getting a morphia query in return. It was a very useful feature back in 1.x, I'd like to update our app to use  morphia 2.x. but if this feature is missing then that application will be forever stuck on morphia 1.x :disappointed: 

Any thoughts on possibly re-introducing this feature?

**Comment by evanchooly** [comment]
I've been thinking about this a fair bit actually and it'll go back in with 2.3.  I just keep forgetting to schedule an issue for it.  I'm not sure what form it will take but probably something like:  `ds.find(Foo.class).query("...")`.  Once that query gets passed in probably any other operation other than executing will result in an error but I'll have to see how that works in practice.

**Comment by newk5** [comment]
It would be useful to be able to modify the query after it's built but I understand if that might be too complex to implement. As for the syntax, I like that approach you mentioned.

**Comment by evanchooly** [comment]
because of how the query is built up via the API that can get *very* complicated.  but it's also something that can be opened up later if a viable solution is found.

**Comment by evanchooly** [comment]
So this was easier than I expected *and* you can add filters after the fact.  Turns out it was already implemented for a not so public feature (query by example) so it was just a matter of overloading `Datastore#find()` to take a `Document`.

**Comment by newk5** [comment]
Great! Thanks for adding it back in 😀
