### ISSUE TITLE
Don't throw VersionMismatchException in case of index violations?

### ISSUE THREAD

**Issue by jowerner** [MorphiaOrg/morphia#1831]
Imagine an entity with a String attribute and a unique index on that attribute. When using `Datastore.save()` to persist this entity and there is already another entity with the very same attribute value, we will get different exceptions depending on whether or not the entity has a `@Version` attribute.

Not versioned:
```
com.mongodb.MongoWriteException: Write operation error on server local:27017. Write error: WriteError{code=11000, message='E11000 duplicate key error collection: xxx.Issue index: issue_1 dup key: { issue: "issue1645522906810" }', details={}}.
```

Versioned:
```
dev.morphia.VersionMismatchException: Entity of type foo.Issue (id=6214afaa3473a979b452e7ac) was not persisted. Either it was modified by another process or was improperly initialized.  See the versioning documentation for more details. 
```

Since in both cases the underlying problem is a unqiue index violation, I would expect the original MongoDB exception to be thrown for the versioned entity as well. Also, a `VersionMismatchException` may lead you on the wrong track here as the entity was not concurrently updated at all. What do you think? Thanks!

Server Version: 5.0.5
Driver Version: 4.4.1
Morphia Version: 2.2.3

**Comment by evanchooly** [comment]
hrm.  I'd have to look at the code to be sure but this might be a case of catching too "high" of an exception.  I'll add a quick test case and see what I can do to fine tune that error.
