### ISSUE TITLE
Obscure Java error when connecting to Database

### ISSUE THREAD

**Issue by vigenere23** [MorphiaOrg/morphia#1837]
**Describe the bug**

I followed the simple connection steps provided by the documentation, and get the follwing error :

```
Exception in thread "main" java.lang.ArrayStoreException: dev.morphia.mapping.codec.PrimitiveCodecRegistry
	at dev.morphia.mapping.Mapper.<init>(Mapper.java:96)
	at dev.morphia.DatastoreImpl.<init>(DatastoreImpl.java:70)
	at dev.morphia.Morphia.createDatastore(Morphia.java:49)
	at dev.morphia.Morphia.createDatastore(Morphia.java:60)
```

**To Reproduce**

```java
Morphia.createDatastore(MongoClients.create(), "any_db_name");
```

**Expected behavior**

It should start smoothly without errors. 

**Additional context**

- Local mongodb instance is running
- Connected manually throught mongo CLI and worked
- Maven : 3.6.3
- Morphia (dev.morphia.morphia.morphia-core) : 2.2.3
- mongodb Driver (org.mongodb.mongo-java-driver) : 3.12.10

The following error is also visible from the "source code" (downloaded from IntelliJ) : 

![morphia-bug](https://user-images.githubusercontent.com/32545895/155991877-5949ef24-f084-4617-a4a9-e652637f5cc3.png)

**Comment by evanchooly** [comment]
That driver version is pretty old.  The oldest driver version actively tested against is 4.0.6.  There were driver changes in the 4.0 line that make supporting older driver versions problematic.  Try upgrading and see what you get.

**Comment by vigenere23** [comment]
This seems to be the latest available version from Maven. Maybe I'm not using the right artifact? There are actually 4 artifacts to choose from :
- `mongodb-java-driver`
- `mongodb-driver-sync`
- `mongodb-driver-core`
- `mongo-db`

After more research, I think that the latest version is 4.5.0 from the artifact `mongodb-driver-sync`. I will give that a try, thanks :+1:

**Comment by vigenere23** [comment]
I was definitly using the wrong library. Using `mongodb-driver-sync` version 4.5.0 works. Thank you!
