### ISSUE TITLE
Multiple similar filters can lose the existing filter in 2.2.5

### ISSUE THREAD

**Issue by adevvv** [MorphiaOrg/morphia#1854]
I tried today if the problem is fixed with morphia 2.2.5, but there still seems to be a problem.
STEP 1:

```
final Query<Event> q = dbs.getDatastore().find(Event.class);
q.filter("customerId", customerId);
		q.filter(
				Filters.or(
						Filters.exists("status").not(),
						Filters.eq("status",0
				)
		);
log.info("Q1: " + q);
```
Q1: MorphiaQuery[clazz=Event, query=Document{{customerId=5ca0c24a4ac35d7748610e68, $or=[Document{{status=Document{{$exists=false}}}}, Document{{status=0}}]}}]

STEP 2:

```
			q.filter(
					Filters.or(
							Filters.exists("belongsToContentId").not(),
							Filters.and(
								Filters.exists("belongsToContentId"),              
								Filters.eq("showAtGuideLevel", Boolean.TRUE)
							)
					));
log.info("Q2: " + q);
```
Q2: MorphiaQuery[clazz=Event, query=Document{{customerId=5ca0c24a4ac35d7748610e68, $or=[Document{{belongsToContentId=Document{{$exists=false}}}}, Document{{$and=[Document{{belongsToContentId=Document{{$exists=true}}}}, Document{{showAtGuideLevel=true}}]}}]}}]

BUG: The filter of status from before is gone?

I also added this comment at the closed bug at https://github.com/MorphiaOrg/morphia/issues/1814 - But I do not know how I can reopen the closed bug, because it apperantly is still existing, so I created a new bug, so it's definitely seen by you. Please feel free to delete this bug if doubled, thanks!

**Comment by evanchooly** [comment]
That's *very* odd.  The test recreating this bug is [here](https://github.com/MorphiaOrg/morphia/blob/969332ee6cefbfbd499d66aba1c6a0c9a181ee7a/core/src/test/java/dev/morphia/test/query/TestQuery.java#L794).  Can you look over that test and your failing code and see if you can spot where maybe I messed something up?

**Comment by adevvv** [comment]
Thanks, for the link, but when I open it I get to this line, which does not have any of the Filters.exists, Filters.not, or maybe I did not see right, what you wanted me to check?
<img width="989" alt="Bildschirmfoto 2022-03-21 um 6 30 58 PM" src="https://user-images.githubusercontent.com/99043436/159309047-75059c04-b6da-40e5-b5a0-224f6eaa8018.png">

**Comment by adevvv** [comment]
I am really sorry, it fell over the oldest dev problem, that gets me since over 10years: The IntelliJ Rebuild did not work correctly, after a clean and rebuild it worked. The finder works now. 

However, strangly I have a new problem after upgrade to 2.2.5, that was not there in 2.2.3:

A big Query execution fails:

`MorphiaQuery[clazz=Event, query=Document{{customerId=5ca0c24a4ac35d7748610e68, $and=[Document{{$or=[Document{{contentId=5ca0c49d4ac35d7748610ed4}}, Document{{belongsToContentId=5ca0c49d4ac35d7748610ed4}}]}}, Document{{$or=[Document{{$or=[Document{{disabled=Document{{$exists=false}}}}, Document{{disabled=false}}]}}, Document{{$and=[Document{{disabled=true}}, Document{{createdByUserId=5ca7497a72a6220ffd6dceac}}]}}, Document{{$and=[Document{{disabled=true}}, Document{{$or=[Document{{contentId=5ca0c49d4ac35d7748610ed4}}]}}, Document{{belongsToContentId=5ca0c49d4ac35d7748610ed4}}]}}]}}, Document{{$or=[ { start: { $gte: 2022-03-20T23:00 } }, { $and: [ { start: { $lte: 2022-03-20T23:00 } }, { end: { $gte: 2022-03-20T23:00 } } ] } ]}}], $or=[Document{{start=Document{{$gte=2022-03-20T23:00}}}}, Document{{$and=[Document{{start=Document{{$lte=2022-03-20T23:00}}}}, Document{{end=Document{{$gte=2022-03-20T23:00}}}}]}}], start=Document{{$lte=2023-03-21T17:25:54.774}}}}] find options: FindOptions[allowDiskUse=null, batchSize=0, limit=10, maxTimeMS=0, maxAwaitTimeMS=0, skip=0, sort=Document{{start=1}}, cursorType=null, noCursorTimeout=false, oplogReplay=false, partial=false, collation=null, comment='null', hint=null, max=null, min=null, returnKey=false, showRecordId=false, readPreference=null, queryLogId='null', projection=null]`

with 

```
org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class dev.morphia.mapping.codec.writer.NameState.
	at org.bson.internal.CodecCache.lambda$getOrThrow$1(CodecCache.java:52)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.bson.internal.CodecCache.getOrThrow(CodecCache.java:51)
	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:64)
```

Or also: 

`MorphiaQuery[clazz=Event, query=Document{{customerId=5ca0c24a4ac35d7748610e68, primary=Document{{$ne=null}}, $and=[Document{{$or=[Document{{$or=[Document{{disabled=Document{{$exists=false}}}}, Document{{disabled=false}}]}}, Document{{$and=[Document{{disabled=true}}, Document{{createdByUserId=5ca7497a72a6220ffd6dceac}}]}}]}}, Document{{$or=[Document{{$or=[Document{{visibility=Document{{$exists=false}}}}, Document{{visibility=PUBLIC}}]}}, Document{{$and=[Document{{visibility=PRIVATE}}, Document{{createdByUserId=5ca7497a72a6220ffd6dceac}}]}}]}}, Document{{$or=[ { belongsToContentId: { $exists: false } }, { $and: [ { belongsToContentId: { $exists: true } }, { showAtGuideLevel: true } ] } ]}}], $or=[Document{{belongsToContentId=Document{{$exists=false}}}}, Document{{$and=[Document{{belongsToContentId=Document{{$exists=true}}}}, Document{{showAtGuideLevel=true}}]}}]}}]`

fails with

```
Can't find a codec for class dev.morphia.mapping.codec.writer.NameState.
org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class dev.morphia.mapping.codec.writer.NameState
```

Can you please help me understand what changed from 2.2.3 to 2.2.5 there?

**Comment by adevvv** [comment]
@evanchooly I commented in the bug https://github.com/MorphiaOrg/morphia/issues/1853 this blocking codec issue today. It seems to be still existent in Morphia 2.2.6 as I have updated the lib today in the project. Would be very grateful if you could look into this. Thanks!
