### ISSUE TITLE
Unsafe allocation creator is inadvertently cached

### ISSUE THREAD

**Issue by vigenere23** [MorphiaOrg/morphia#1858]
**Describe the bug**

When getting all data or filtering, it returns a list of the right size, but all the elements in the list are duplicates of the first (or last) element found. I've already read about a similar bug here (#854) and there (#932), but removing the `_id` field with a projection does not work either.

**To Reproduce**

```java
@Entity
class UserModel {
    @Id
    public final String id;
    public final String name;
   // ... other attributes
}

List<UserModel> users = datastore.find(UserModel.class).iterator().toList();
System.out.println(users);
```

output :

```shell
[UserModel@28a0fd6c, UserModel@28a0fd6c]
```

Output is the same with :

```java
List<UserModel> users = datastore.find(UserModel.class)
    .iterator(new Findoptions().projection.exclude("_id"))
    .toList();
System.out.println(users);
```

Printing the ids returns, for example, `["def", "def"]` instead of `["abc", "def"]`.

If i use the driver directly with :

```java
datastore.getDatabase()
    .getCollection("userModel")
    .find().forEach(doc -> {
            System.out.println(doc.toJson());
    });
```

I obtain the following :

```json
{"_id": "abc", "_t": "UserModel", "name": "John Doe", "bio": "A simple men", "birthDate": "2022-03-27", "createdAt": "2022-03-27T11:10:40.507233-04:00"}
{"_id": "def", "_t": "UserModel", "name": "John Doe", "bio": "A simple men", "birthDate": "2022-03-27", "createdAt": "2022-03-27T11:10:40.507256-04:00"}
```

**Expected behavior**

The returned items should all be different and return the same output than the driver.

**Additional information**

 - Server Version: 5.0 (local, ubuntu)
 - Driver Version: 4.5.0 (maven) (also 4.5.1)
 - Morphia Version: 2.2.6 (also on 2.2.3)

**Comment by vigenere23** [comment]
Solution found : The fields need to **NOT BE FINAL** because the default constructor will be used (probably related to Jackson's object mapping). Having no final fields makes the default constructor available and things now work.

**Comment by evanchooly** [comment]
Well, that's a fix to your issue in particular but it's actually a general issue as well though a rather niche one.  Thankfully it's a oneliner fix (inadvertent caching issue deep inside Morphia) so i'll patch that up for the next release.
