### ISSUE TITLE
ReferenceException while calling method on referenced entity that has gone despite ignoreMissing

### ISSUE THREAD

**Issue by h-arlt** [MorphiaOrg/morphia#1860]
**Describe the bug**
This issue is about calling a method on a referenced entity that has vanished from DB but still referenced by some other entity and the reference is annotated with` @Reference(lazy = true, ignoreMissing = true)`.

STR:
* create an entity `parent` having at least one reference annotated with `@Reference(lazy = true, ignoreMissing = true) `to another entity `child` and let `getChild()` be a public getter for this field
* store `child` and `parent` to DB
* remove `child` from DB
* fetch `parent` from DB and invoke some public method of `child`'s entity class on the value returned by `getChild()`
&rarr; ReferenceException

Invocation of any public instance method on the proxy instance returned by Morphia throws a `ReferenceException` in Morphia v2.
This is a significant change to Morphia v1 which simply returned `null` for any public instance method on the proxy instance in case the referenced entity does not exist in DB (anymore) and the reference is annotated with `@Reference(lazy = true, ignoreMissing = true)`.

**To Reproduce**
Run the following unit test:
```java
package dev.morphia.test.mapping.lazy;

import static dev.morphia.query.experimental.filters.Filters.eq;

import org.testng.Assert;
import org.testng.annotations.Test;

import dev.morphia.Datastore;
import dev.morphia.annotations.Reference;
import dev.morphia.test.mapping.ProxyTestBase;
import dev.morphia.test.models.TestEntity;

@Test(groups = "references")
public class TestLazyIgnoreMissing extends ProxyTestBase
{
    public void testReferentIsGone() 
    {
        checkForProxyTypes();

        RootEntity root = new RootEntity();
        root.setBar("foo");
        final ReferencedEntity reference = new ReferencedEntity();
        reference.setFoo("bar");

        root.setR(reference);
        
        final Datastore datastore = getDs();
        datastore.save(reference);
        datastore.save(root);
        
        root = datastore.find(RootEntity.class)
                        .filter(eq("_id", root.getId()))
                        .first();

        final ReferencedEntity p = root.r;

        assertIsProxy(p);
        assertNotFetched(p);
        p.getFoo();
        assertFetched(p);
        
        // delete the referenced entity
        datastore.delete(reference);
        // refresh root entity
        root = datastore.find(RootEntity.class)
            .filter(eq("_id", root.getId()))
            .first();

        Assert.assertNotNull(root.r);
        Assert.assertNotNull(root.getR());
        Assert.assertNull(root.r.getFoo());
    }
    
    
    public static class RootEntity extends TestEntity {
        @Reference(idOnly = true, lazy = true, ignoreMissing = true)
        private ReferencedEntity r;
     
        private String bar;

        public String getBar()
        {
            return bar;
        }

        public void setBar(String bar)
        {
            this.bar = bar;
        }

        public ReferencedEntity getR() {
            return r;
        }

        public void setR(ReferencedEntity r) {
            this.r = r;
        }

    }

    public static class ReferencedEntity extends TestEntity {
        private String foo;


        public String getFoo() {
            return foo;
        }

        public void setFoo(String string) {
            foo = string;
        }

    }
}

```

**Expected behavior**
Proxy object returned by Morphia honors `ignoreMissing` flag as was done in Morphia v1 and returns `null` as result for any public instance method invocation.

** Please complete the following information: **
 - Server Version: 5.0
 - Driver Version: 4.4.1
 - Morphia Version: 2.2.7-SNAPSHOT

**Comment by evanchooly** [comment]
actually i'm not so sure this isn't the correct behavior.  With your test if I run this code:

```java
Target ignoreMissing = getDs().find(Source.class).first().getIgnoreMissing();
```
If I call `ignoreMissing.getFoo()` what should happen there?  If i return `null` because the reference is gone/missing then it looks like `getFoo()` returns `null` rather than in the invoker simply return null because the referent doesn't exist.  `ignoreMissing` will always be a non-null reference proxy so that looks a value was returned back to user code.  The simplest way to check that it's a valid reference and not a referent-less proxy is this:

```java
MorphiaProxy proxy = (MorphiaProxy) ignoreMissing;
if (proxy.unwrap() != null) {
  ...
}
```
And leaks out mapping information in to application code which isn't necessarily a good idea.  By leaving the code as it was, you get a `ReferenceException` the moment you try to dereference that referent-less proxy giving you the exact problem (and solution) right where you need it.

Thoughts?

**Comment by h-arlt** [comment]
I just want to point out that the handling of lazy references marked as `ignoreMissing` has changed significantly from a users point of view: Morphia v1 just returned `null` when invoking any method on the returned proxy while Morphia v2 now throws an exception.

Our application makes heavy use of lazy references and some of them are marked as `ignoreMissing`. I know that the proposed solution isn't optimal and I agree on your point
> ignoreMissing will always be a non-null reference proxy so that looks a value was returned back to user code

However, it realigns the handling of missing references in Morphia v2 with that of Morphia v1 and prevents existing code to break.

Otherwise, we would have to wrap all of your method calls on the returned proxy with a try-catch just because the reference (that is marked as **ignoreMissing**) might have gone. That would effectively render the `ignoreMissing` flag obsolete.

Ideally, Morphia v2 would return `null` for all lazy references that have gone and are marked as `ignoreMissing`; maybe by using a proxy for all entities that are known to have lazy references marked as `ignoreMissing` or by manipulating the byte code of the entity's class. However, this would require much more changes but can be basically achieved by the using the code snipped you suggested:
```java
MorphiaProxy proxy = (MorphiaProxy) ignoreMissing;
if (proxy.unwrap() != null) {
  ...
}
```
IMHO this _magic_ should be performed by the framework and not the by the user - (s)he gave all necessary information about the reference so the framework should know how to handle it.

Let me know your thoughts on this. And thanks for your rapid feedback ;)

**Comment by h-arlt** [comment]
Yep, exactly. Doing it *lazy* is the tricky part here. That's why I considered to proxy the reference's owning entity instead of the reference itself. But I don't have enough insights on whether and how this would fit into your code.

**Comment by evanchooly** [comment]
that is like to be the right fix, honestly, and it won't be simple...

**Comment by evanchooly** [comment]
ok.  i've been gnawing on this bone for a while and I have an idea.  I'll keep you posted...

**Comment by evanchooly** [comment]
I just confirmed that in 1.6, on a single lazy reference, you would still get a non-null reference for the field's value and any attempts to dereference that proxied lazy reference would result in a `RuntimeException`.  You can see this test in action [here](https://github.com/MorphiaOrg/morphia/blob/54d59fe5f47cf73c5c3038e025c1f6ac8925d69e/morphia/src/test/java/dev/morphia/mapping/lazy/TestLazyWithMissingReferences.java#L36=).  Looking at the test, you can see that `getIgnoreMissing()` returns a valid reference and calling `.foo()` on the reference gives you the `RuntimeException`.  So at least on the single reference (i.e., not a `List` or a `Map`), the behavior looks largely the same.  I'll confirm the 2.x behavior but I think we're ok on that front.  for Maps/Lists we have a bit of leeway to slot in nulls for missing referenced entities.

**Comment by h-arlt** [comment]
Thanks for the update and the time you've spent on working on this.

> I just confirmed that in 1.6, on a single lazy reference, you would still get a non-null reference for the field's value and any attempts to dereference that proxied lazy reference would result in a `RuntimeException`.
Is the RuntimeException also thrown in case the reference has been marked as `ignoreMissing`? Because that's what causes our code to break as it expects the same behavior as in Morphia v1.

Up to now, we don't store references to collections, so I'm totally fine to have a working solution for "simple" references at least.

The test you mentioned does use a lazy reference that is marked as `ignoreMissing` **and** `idOnly`. Thus, I'm not sure whether we're talking about the same code paths here.

**Comment by evanchooly** [comment]
This behaves the same as in 1.6.x and given how references work, it *has* to work this way.  Since references are implemented via proxies at the field level, there *has* to be a nonnull value in that field even if the lazy reference points to a document that has gone away.  It *is* slightly incongruous with non-lazy references but technical limitations are the constraint here.  In the 3.0 timeline, we can explore proxying at the entity level and intercept the lazy reference at the method level instead where we can "correctly" return nulls for missing lazy references.

**Comment by evanchooly** [comment]
There's no difference in code paths.  The `idOnly` case gets the raw ID value wrapped up in a wrapper type and then both reference styles are resolved the same way.

**Comment by h-arlt** [comment]
I just found out that the test you mentioned will **not** throw an exception when you declare the method `foo` in class `Target` as well as both classes - `Source` and `Target` - as public. This seems to be the key point here.
Thus, my previous statement still holds about the change of behavior between Morphia v1.x and v2.x. Please note that I'm not questioning the correctness of the new behavior; at least it is consistent now. 

The main reason why I posted this issue is that the (undocumented) change in behavior causes our existing code to break and as long as there is no other way to ensure compatibility with v1, we'll have to use a self-hosted patch version of Morphia v2.

Looking forward to v3 where proxying at entity level will hopefully solve this issue.
