### ISSUE TITLE
Batch insert using .save(List<T> entities) performance issue

### ISSUE THREAD

**Issue by ball3t** [MorphiaOrg/morphia#1868]
DatastoreImpl.java
public <T> List<T> save(List<T> entities, InsertManyOptions options)
line 407, grouped.computeIfAbsent(getCollection(type), c -> new ArrayList<>())
since getCollection returned a new collection object each time, so the entities cannot be grouped into 1 list, instead it will be multiple list of 1 entity. causing running multiple times of insertMany later

    Server Version: 4.2
    Driver Version: 4.2
    Morphia Version: 2.2.6

**Comment by evanchooly** [comment]
Is this just your theory or are you seeing an actual issue?  The hash on the collection should be the only thing that matters.

**Comment by ball3t** [comment]
I am seeing the actual issue. I tried to set a break point in the IDE and looked at the Map "grouped". 
try to save 10 TestEntity object with id = null, you may refer to the scree cap below
[https://imgur.com/a/JADQENf](url)
