### ISSUE TITLE
Quicktour broken?

### ISSUE THREAD

**Issue by evanchooly** [MorphiaOrg/morphia#1871]
It compiles as part of a build but does it run?  See [here](https://stackoverflow.com/questions/71996828/migrating-to-morphia-from-hibernate-ogm/72002875#72002875) for details.

**Comment by NOTiFYcouk** [comment]
Have you any 'Unit' test I can run on 'src/test/java/dev/morphia/example/QuickTour.java'? Where I can run on various version of JDK, MongoDB & Morphia?

**Comment by evanchooly** [comment]
OK.  So the issue here is that 4.3.0 (it seems) of the driver introduced new method on the cursor type which require Morphia to add a method to various types in Morphia.  This breaks semver so that particular upgrade is included in the upcoming 2.3 release.  The 2.2.x branch is constrained to 4.2.x of the driver.

**Comment by NOTiFYcouk** [comment]
implementation("org.mongodb:mongodb-driver-core:4.2.3")
implementation("dev.morphia.morphia:morphia-core:2.2.6")

2 April 2022:
https://github.com/MorphiaOrg/morphia/blob/master/examples/src/test/java/dev/morphia/example/QuickTour.java

/Library/Java/JavaVirtualMachines/jdk-18.0.1.jdk/Contents/Home/bin/java -javaagent:/Applications/IntelliJ 

Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.String com.mongodb.connection.ClusterSettings.getDescription()'
	at com.mongodb.connection.DefaultClusterFactory.createCluster(DefaultClusterFactory.java:179)
	at com.mongodb.client.internal.MongoClientImpl.createCluster(MongoClientImpl.java:190)
	at com.mongodb.client.internal.MongoClientImpl.<init>(MongoClientImpl.java:57)
	at com.mongodb.client.MongoClients.create(MongoClients.java:112)
	at com.mongodb.client.MongoClients.create(MongoClients.java:99)
	at com.mongodb.client.MongoClients.create(MongoClients.java:83)
	at com.mongodb.client.MongoClients.create(MongoClients.java:40)
	at dev.morphia.example.QuickTour.main(QuickTour.java:20)

**Comment by evanchooly** [comment]
https://github.com/MorphiaOrg/morphia/runs/6275209470?check_suite_focus=true

something seems off somewhere.

**Comment by NOTiFYcouk** [comment]
Have migrated to JDK 17.0.2 & run your tests using mvn. Can't run it from IntelliJ. I'll have a think1 Thanks. 

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@76494737
Tests run: 713, Failures: 0, Errors: 0, Skipped: 30, Time elapsed: 125.656 sec

Results :

Tests run: 713, Failures: 0, Errors: 0, Skipped: 30

[INFO] 
[INFO] -----------------< dev.morphia.morphia:morphia-kotlin >-----------------
[INFO] Building morphia-kotlin 2.3.0-SNAPSHOT                             [5/7]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-cli) @ morphia-kotlin ---
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/apache/maven/surefire/surefire-testng/3.0.0-M5/surefire-testng-3.0.0-M5.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-testng/3.0.0-M5/surefire-testng-3.0.0-M5.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-testng/3.0.0-M5/surefire-testng-3.0.0-M5.jar (44 kB at 1.1 MB/s)
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/apache/maven/surefire/surefire-testng/3.0.0-M5/surefire-testng-3.0.0-M5.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-testng/3.0.0-M5/surefire-testng-3.0.0-M5.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-testng/3.0.0-M5/surefire-testng-3.0.0-M5.pom (4.1 kB at 164 kB/s)
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/apache/maven/surefire/surefire-providers/3.0.0-M5/surefire-providers-3.0.0-M5.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-providers/3.0.0-M5/surefire-providers-3.0.0-M5.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-providers/3.0.0-M5/surefire-providers-3.0.0-M5.pom (2.5 kB at 101 kB/s)
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/apache/maven/surefire/common-java5/3.0.0-M5/common-java5-3.0.0-M5.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-java5/3.0.0-M5/common-java5-3.0.0-M5.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-java5/3.0.0-M5/common-java5-3.0.0-M5.pom (2.6 kB at 97 kB/s)
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/apache/maven/surefire/surefire-testng-utils/3.0.0-M5/surefire-testng-utils-3.0.0-M5.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-testng-utils/3.0.0-M5/surefire-testng-utils-3.0.0-M5.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-testng-utils/3.0.0-M5/surefire-testng-utils-3.0.0-M5.pom (3.0 kB at 120 kB/s)
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/apache/maven/surefire/surefire-grouper/3.0.0-M5/surefire-grouper-3.0.0-M5.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-grouper/3.0.0-M5/surefire-grouper-3.0.0-M5.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-grouper/3.0.0-M5/surefire-grouper-3.0.0-M5.pom (3.1 kB at 130 kB/s)
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/testng/testng/5.10/testng-5.10.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/testng/testng/5.10/testng-5.10.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/testng/testng/5.10/testng-5.10.pom (2.1 kB at 88 kB/s)
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/mockito/mockito-core/2.28.2/mockito-core-2.28.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/mockito/mockito-core/2.28.2/mockito-core-2.28.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/mockito/mockito-core/2.28.2/mockito-core-2.28.2.pom (20 kB at 773 kB/s)
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/powermock/powermock-reflect/2.0.5/powermock-reflect-2.0.5.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/powermock/powermock-reflect/2.0.5/powermock-reflect-2.0.5.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/powermock/powermock-reflect/2.0.5/powermock-reflect-2.0.5.pom (7.2 kB at 265 kB/s)
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/assertj/assertj-core/3.9.1/assertj-core-3.9.1.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/assertj/assertj-core/3.9.1/assertj-core-3.9.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/assertj/assertj-core/3.9.1/assertj-core-3.9.1.pom (10 kB at 427 kB/s)
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/assertj/assertj-parent-pom/2.1.9/assertj-parent-pom-2.1.9.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/assertj/assertj-parent-pom/2.1.9/assertj-parent-pom-2.1.9.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/assertj/assertj-parent-pom/2.1.9/assertj-parent-pom-2.1.9.pom (15 kB at 673 kB/s)
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/easytesting/fest-assert/1.4/fest-assert-1.4.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/easytesting/fest-assert/1.4/fest-assert-1.4.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/easytesting/fest-assert/1.4/fest-assert-1.4.pom (2.4 kB at 113 kB/s)
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/easytesting/fest/1.0.8/fest-1.0.8.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/easytesting/fest/1.0.8/fest-1.0.8.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/easytesting/fest/1.0.8/fest-1.0.8.pom (12 kB at 484 kB/s)
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/easytesting/fest-util/1.1.6/fest-util-1.1.6.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/easytesting/fest-util/1.1.6/fest-util-1.1.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/easytesting/fest-util/1.1.6/fest-util-1.1.6.pom (1.6 kB at 71 kB/s)
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/apache/maven/surefire/common-java5/3.0.0-M5/common-java5-3.0.0-M5.jar
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/apache/maven/surefire/surefire-grouper/3.0.0-M5/surefire-grouper-3.0.0-M5.jar
Downloading from snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/apache/maven/surefire/surefire-testng-utils/3.0.0-M5/surefire-testng-utils-3.0.0-M5.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-grouper/3.0.0-M5/surefire-grouper-3.0.0-M5.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-java5/3.0.0-M5/common-java5-3.0.0-M5.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-testng-utils/3.0.0-M5/surefire-testng-utils-3.0.0-M5.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-grouper/3.0.0-M5/surefire-grouper-3.0.0-M5.jar (40 kB at 1.3 MB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-java5/3.0.0-M5/common-java5-3.0.0-M5.jar (16 kB at 477 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-testng-utils/3.0.0-M5/surefire-testng-utils-3.0.0-M5.jar (14 kB at 191 kB/s)
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running dev.morphia.test.TestKotlinMapping
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.149 s - in dev.morphia.test.TestKotlinMapping
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] ---------------< dev.morphia.morphia:morphia-validation >---------------
[INFO] Building morphia-validation 2.3.0-SNAPSHOT                         [6/7]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-cli) @ morphia-validation ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running dev.morphia.test.validation.TestMorphiaValidation
12:54:29.876 [main] INFO  org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 7.0.4.Final
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.182 s - in dev.morphia.test.validation.TestMorphiaValidation
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --------------------< dev.morphia.morphia:examples >--------------------
[INFO] Building examples 2.3.0-SNAPSHOT                                   [7/7]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-cli) @ examples ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Morphia 2.3.0-SNAPSHOT:
[INFO] 
[INFO] Morphia ............................................ SUCCESS [  0.213 s]
[INFO] build-plugins ...................................... SUCCESS [  0.455 s]
[INFO] util ............................................... SUCCESS [  0.003 s]
[INFO] morphia-core ....................................... SUCCESS [02:08 min]
[INFO] morphia-kotlin ..................................... SUCCESS [  5.213 s]
[INFO] morphia-validation ................................. SUCCESS [  2.029 s]
[INFO] examples ........................................... SUCCESS [  0.007 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:16 min
[INFO] Finished at: 2022-05-04T12:54:30+01:00
[INFO] ------------------------------------------------------------------------
