### ISSUE TITLE
Shard keys support

### ISSUE THREAD

**Issue by gnupinguin** [MorphiaOrg/morphia#1938]
**Is your feature request related to a problem? Please describe.**
I'm testing Morphia 2.2 and MongoDB 4.2. I'm using sharded Mongo cluster. Since 4.2 new behavior has been introduced: the shard key is required in a filter for upsert operations: [documentation](https://www.mongodb.com/docs/v4.2/release-notes/4.2-compatibility/#sharded-collections-and-replace-documents). It looks that only _id field is added to filter: [DatastoreImpl](https://github.com/MorphiaOrg/morphia/blob/cb3727a3cd2c53962fa42d219432ea5a3714223d/core/src/main/java/dev/morphia/DatastoreImpl.java#L653)

**Describe the solution you'd like**
Support annotation @ShardKey and add marked by annotation entity fields to the filter.  Another way is supporting the shard key in InsertManyOptions.

**Additional context**
Otherwise exception will be thrown:
`'Failed to target upsert by query :: could not extract exact shard key', details={}}
`

**Comment by evanchooly** [comment]
I think i've got you covered now. I have a sneaking suspicion there might be a case here or there where I'm not properly adding shard keys to filters but I've got the cases I know of corrected. I'm pretty sure I got them all but I always worry.  You can try a `2.3.0-SNAPSHOT` build to check it.
