### ISSUE TITLE
EntityEncoder writes a duplicated property to a document if an entity has a discriminatorKey matching a field in the entity.

### ISSUE THREAD

**Issue by burdeynyy** [MorphiaOrg/morphia#1949]
**The bug**
If a discriminator key name matches an existing field name, dev.morphia.mapping.codec.pojo.EntityEncoder#encode will try to write both to a document. Therefore the method dev.morphia.mapping.codec.writer.NameState#andTogether added in the commit https://github.com/MorphiaOrg/morphia/commit/8e24982523115d9df63f4d3d664cb1e456efb0d9 will be invoked and the attempt to convert the entity into a document will add the unexpected stage.

**Expected behavior**
The discriminator field should be written only once and without $and. 

 - Server Version: db version v4.2.8
 - Morphia Version: >= 2.2.5

```
@Data
@Entity(value = "TestCollection", discriminatorKey="type")
public class Parent {

    @Id
    protected ObjectId id;

    public Type type;

    public enum Type {
        ANY, SOME
    }

}

@EqualsAndHashCode(callSuper = true)
@Entity(value = "TestCollection", discriminatorKey="type", discriminator = "SOME")
@Data
public class Child extends Parent {
    public Child() {
        setType(Type.SOME);
    }
}

    @Test
    public void test() {
        Parent parent = new Child();

        final Document document = datastore.getMapper().toDocument(parent);

        System.out.println(document);
    }
```
Output: Document{{$and=[Document{{type=SOME}}, Document{{type=SOME}}]}}

**Comment by burdeynyy** [comment]
@evanchooly Could you please fix this issue?

**Comment by evanchooly** [comment]
I've been giving this one a lot of thought since it was initially raised.  I've decided that I'm not going to allow reuse of the discriminator field like this.  It was never meant to be reused like this and introducing this feature would create too many corner cases for my peace of mind.  In the end, it would simply be too complicated and expensive to maintain this behavior.

**Comment by burdeynyy** [comment]
@evanchooly Could you please suggest a workaround for this issue?
