### ISSUE TITLE
Indexes of nested objects are not auto created

### ISSUE THREAD

**Issue by jbellic** [MorphiaOrg/morphia#2056]
**Describe the bug**
- Indexes of nested objects are not created via ds.ensureIndexes() and also not via ds.ensureIndexes(ClassRef)
- Top level objects indexes are created successfully but the nested ones are missing
- Both top level and nested classes are already added to ds.getMapper.map() method
- Tried both class level @Indexes and property level @Indexed annotations with no luck
- The nested object property itself is indexable but not the properties within the nested object

**To Reproduce**

Top level entity:

```
 @Data
 @Builder
 @AllArgsConstructor
 @RequiredArgsConstructor
 @Entity("twitter_tweets")
 @Indexes(@Index(fields = {@Field(value = "hashtags", type = IndexType.TEXT), @Field(value = "renderedContent", type = IndexType.TEXT)}, options = @IndexOptions(name = "twitter_tweets_text_index", language = "tr")))
 public class TwitterTweet {
 
     @Id
     private String id;
 
     private TwitterTweetUser user;
 
     @Indexed(options = @IndexOptions(name = "twitter_tweets_reply_count_index"), value = IndexDirection.DESC)
     private Integer replyCount;
  
     ... 
 }
```

Nested entity:

```
    @Data
    @Builder
    @AllArgsConstructor
    @RequiredArgsConstructor
    @Entity("twitter_tweet_users")
    public static class TwitterTweetUser {

        @Indexed(options = @IndexOptions(name = "twitter_tweets_user_username_index"), value = IndexDirection.DESC)
        private String username;
     
        ...
     }
```

Mongo config:
```
        datastore.getMapper().map(
                TwitterTweet.class,
                TwitterTweet.TwitterTweetUser.class,
                ...
        datastore.ensureIndexes();
        datastore.ensureIndexes(TwitterTweet.TwitterTweetUser.class);
```

**Expected behavior**
Auto creation of all indexes

** Please complete the following information: **
 - Server Version: 6.0.1 CE
 - Driver Version: 4.6.1
 - Morphia Version: 2.2.8

**Additional context**
Workaround: Define index of nested object via class level Index definition in top level class:

```
@Index(fields = @Field(value = "user.username", type = IndexType.ASC), options = @IndexOptions(name = "twitter_tweets_user_username_index")),`
```

**Comment by evanchooly** [comment]
I thought this issue seemed [familiar](https://github.com/MorphiaOrg/morphia/issue/1316). As I recall there were conflicting needs on this particular issue and some odd/confusing errors when embedded indexes were allowed.  I'm not sure they're worth reviving but I can be convinced.  Does anything prevent you from moving those index definitions to the topmost type?

**Comment by jbellic** [comment]
Thanks for the fast response, workaround is fine for me.
It was a good decision to switch from Spring Data Mongo to Morphia, I'm happy so far :)

**Comment by evanchooly** [comment]
I'm thrilled to hear that.  :)  If you're good, then I'll close this one out.
