### ISSUE TITLE
setOnInsert update operator causes "Can’t find a codec for class Instant | LocalDateTime..."

### ISSUE THREAD

**Issue by metalpalo** [MorphiaOrg/morphia#2066]
**Configuration**
    Server Version: MongoDB 6.0.0 Community
    Driver Version: 4.6.0
    Morphia Version: 2.2.8

Hi,
I wanted to update existing document or insert new one(via upsert = true) when missing.

**Here is my document entity:**
```
@Data
@Builder
@Entity(value = "COLL_LoanAccountChange")
@Indexes({
        @Index(fields = @Field("technicalUid"), options = @IndexOptions(name = "idx_technical_uid", unique = true))
})
@EqualsAndHashCode(of = {"id"})
public class LoanAccountChange {

    @Id
    private ObjectId id;

    private String technicalUid;

    private String entityUid;

    private Instant createdAt;

    private Instant updatedAt;
}
```
**Dao operation method:**
```
public void save(LoanAccountChange entity) {
        final Instant timestamp = Instant.now();
        datastore
                .find(LoanAccountChange.class)
                .filter(eq("technicalUid", entity.getTechnicalUid()))
                .update(
                        UpdateOperators.setOnInsert(Map.of(
                                "entityUid", entity.getEntityUid(),
                                "createdAt", entity.getCreatedAt() != null ? entity.getCreatedAt() : timestamp)),
                        UpdateOperators.set("updatedAt", entity.getUpdatedAt() != null ? entity.getUpdatedAt() : timestamp)
                )
                .execute(new UpdateOptions().upsert(true));
    }
```
**What want I to achieve is following:**

1. update field **updatedAt** for existing document found by **technicalUid**
2. create new one document with fields: **technicalUid**, **entityUid**, **createdAt**, **updatedAt**

**What I found:**

1. When running it I got error regarding missing codec for Instant class related to **createdAt**:
_Can’t find a codec for class Instant_
2. When I ommited setOnIsert operator everyting works fine. UpdateOperator $set works and codec is available.
3. When I run following I see tht InstantCodec is registered for my dataStatore instance:
```
Codec<Instant> instantCodec = datastore.getMapper().getCodecRegistry().get(Instant.class);
```
4. It seems that problem caused that setOnIsert operator has only possibility to take Map(LinkedHashMap) and another resolution is used there. When debugging something like **MorphiaMapCodec**  is founded then **InstantCodec** is not available from **Jsr310CodecProvider**.

**My patch for this moment is to split entries from Map parameter setOnInsert, that means:**

1. overtaken source UpdateOperator in my code(classpath) and make public constructors:
2. rewrite my dao method like this:
```
public void save(LoanAccountChange entity) {
        final Instant timestamp = Instant.now();
        datastore
                .find(LoanAccountChange.class)
                .filter(eq("technicalUid", entity.getTechnicalUid()))
                .update(
                        new UpdateOperator("$setOnInsert", "entityUid", entity.getEntityUid()),
                        new UpdateOperator("$setOnInsert", "createdAt", entity.getCreatedAt() != null ? entity.getCreatedAt() : timestamp),
                        UpdateOperators.set("updatedAt", entity.getUpdatedAt() != null ? entity.getUpdatedAt() : timestamp)
                )
                .execute(new UpdateOptions().upsert(true));
    }
```

**My question:**
Is something incorrect in my code? Im totaly newbie regarding the using morphia and mongodb driver.
Thanks
brmetalpalo

**Comment by evanchooly** [comment]
I just pasted your code in to the unit tests and ran it and it worked just fine so there's something definitely off about your setup.  If you could put together a [reproducer](/morphiaorg/reproducer) I'd be happy to take a look and see.

**Comment by metalpalo** [comment]
Hmm.., maybe is a problem that I use morphia within the Spring boot application  2.7.0 and something is wrong configured?
All my configuration for morphia is following:

```
@Configuration
public class MorphiaConfiguration {

    @Autowired
    private MongoProperties mongoProperties;

    @Autowired
    private MongoClient mongoClient;

    @Bean
    public Datastore datastore() {
        Datastore datastore = Morphia.createDatastore(mongoClient, mongoProperties.getDatabase());
        datastore.getMapper().mapPackage("com.example.entity");
        datastore.ensureIndexes();
        return datastore;
    }
}
```

**Comment by evanchooly** [comment]
I'm pretty sure this is working but I would love to see a reproducer to be sure.

**Comment by evanchooly** [comment]
But maybe it's old enough that it's not an issue any more.  I'll close this on that assumption but feel free to reopen or to open a new one with more details.
