### ISSUE TITLE
setOnInsert() does not honor @Reference annotations

### ISSUE THREAD

**Issue by isaacrj** [MorphiaOrg/morphia#2085]
Given the classes:
```
@Entity("child")
public class Child {
     @Id
     private ObejctId id;
     
     @Property("name")
     private String name;
}

@Entity("parent")
public class Parent {

     @Id
     private ObejctId id;

      @Property("unique")
      private String unique;

      @Reference("child")
      private Child child;

}

```
doing an upsert like this:
```
db.datastore.find(Parent.class)
      .filter( Filters.eq("uid", "uniqueValue") )
      .modify( UpdateOperators.setOnInsert("uid", "uniqueValue"), UpdateOperators.setOnInsert("child", childInstance) )
      .execute( new ModifyOperations().upsert(true) )
```
results in a "Parent" document being written to database with "childInstance" as an embedded document, instead of a reference.

**Comment by evanchooly** [comment]
What version of Morphia are you using?  https://github.com/MorphiaOrg/morphia/issues/2001 smartened up that processing and may or may not affect this as well.

**Comment by isaacrj** [comment]
Hi, I was using 2.2.7 at the time. I have since updated to 2.2.9 but the code already has a workaround in place for this issue so I'm not sure if the bug is still there or not...
