### ISSUE TITLE
Field shadowing breaks mapping

### ISSUE THREAD

**Issue by filipemb** [MorphiaOrg/morphia#2114]
**Describe the bug**
The retrieve operation fails when the child class overrides attributes with the same name as the superclass but changes the Type to an extended Type of the Type in the superclass.

**To Reproduce**

1. Create a class hierarchy like:

Superclass:
```
@Entity(value = "ClassA")
public class ClassA {
 
  private Version schemaVersion = Version.V1_0;
  @Id
  private String id;
  private ClassB classB;

[... getter & setters]

}
```
Type B:
```
@Entity
public class ClassB {
 
 private String attribute;

[... getter & setters]

}
```

Childclass:
```
@Entity(value = "ClassA")
public class ClassAExtended extends ClassA {
 
 private ClassBExtended classB;

[... getter & setters]

}
```

Extension of Type in Superclass:
```
@Entity
public class ClassBExtended extends ClassB {
 
 private String anotherAttribute;

[... getter & setters]

}
```
    
2. Try to retrieve the entity
3. See error codec cannot be null.

**Expected behavior**
Expect to retrieve the ClassA with the anotherAttribute inside the child class.

** Please complete the following information: **
 - Server Version:  5.0.3
 - Driver Version: 4.4.0
 - Morphia Version: 2.2.3
 - JDK Version: 11

**Additional context**
From the local machine debug I tried 2 configurations:

**First Config using FIELDS**

1) Setup MapperOptions to MapperOptions.PropertyDiscovery.FIELDS;
2) While populating EntityModel the collections propertyModelsByMappedName and propertyModelsByName has distinct items (PropertyModels):
2.1) propertyModelsByMappedName: get the PropertyModel with TypeData from superclass
2.2) propertyModelsByName: get the PropertyModel with TypeData from childclass (the right one)
3) When decoding the method getProperty of EntityModel retrieves from propertyModelsByMappedName as the primary option and then from propertyModelsByName as default.
4) It retrieves the wrong PropertyType that has no cachedCodec() and this causes the exception: decoder can not be null

Analyzing this scenario I saw that FieldDiscovery convention first read child class properties then parent superclass, adding the fields to a list. Then, after EntityModelBuilder build() during an instantiation of EntityModel the constructor loops this list adding the PropertyModel to both maps. 
The point is that FieldDiscovery should ignore fields with the same name as the child while looping parent attributes. In this way, the field will not be in the list as it is done by the ConfigureProperties convention when it detects a @Transational annotation.

**Second Config using METHODS**
1) Setup MapperOptions to MapperOptions.PropertyDiscovery.METHODS;
2) EntityModel has the same PropertyModels in both collections pointing to the parent TypeData (wrong)
3) It decodes without the expected extended fields

Analyzing this scenario FieldDiscovery is replaced by MethodDiscovery, but as before it loads first from the child class and then from the parent superclass, and while mapping parent gets over the child method. 

I know that in java we should use methods to override types. But both corrections can be enabled by changing the order in which properties are read, starting from a parent class and then a child one.

**Comment by evanchooly** [comment]
I have mixed feelings about this one.  This is called (field) shadowing and is generally frowned up, in general, from an OO perspective.  This might cause a few nuanced issues but I'll see what I can do here.  If the compiler supports it, I generally try to make sure Morphia can work with it.

**Comment by filipemb** [comment]
I'm trying this workaround:

```
package your.package.here.convention;


import java.util.Iterator;

import dev.morphia.Datastore;
import dev.morphia.mapping.codec.pojo.EntityModelBuilder;
import dev.morphia.mapping.codec.pojo.PropertyModel;
import dev.morphia.mapping.codec.pojo.PropertyModelBuilder;
import dev.morphia.mapping.codec.pojo.TypeData;
import dev.morphia.mapping.conventions.MorphiaConvention;

public class FieldShadowingDiscovery implements MorphiaConvention {

    @Override
    public void apply(Datastore datastore, EntityModelBuilder modelBuilder) {
        Iterator<PropertyModelBuilder> iterator = modelBuilder.propertyModels().iterator();
        while (iterator.hasNext()) {
            final PropertyModelBuilder builder = iterator.next();
            if (isOverridedByChildShadowedField(builder, modelBuilder)) {
                iterator.remove();
            }
        }
    }

    private boolean isOverridedByChildShadowedField(PropertyModelBuilder item, EntityModelBuilder modelBuilder) {
        
        for (PropertyModelBuilder propertyModelBuilder : modelBuilder.propertyModels()) {
            //if there is more than one distinct field with the same name
            if(item.name().equals(propertyModelBuilder.name()) && item != propertyModelBuilder) {
                //get the typeData of the parent
                PropertyModel parentPropertyModel = modelBuilder.superclass().getProperty(item.name());
                TypeData<?> typeDataOfParentAttribute = parentPropertyModel.getTypeData();
                //verify if the item has the same type as the parent, then it should be removed 
                if(typeDataOfParentAttribute.equals(item.typeData())) {
                   return true; 
                }
            }
        }
        return false;
    }
}

```

Registering through:

```
MapperOptions.Builder mapperOptionsBuilder = MapperOptions.builder();
//default ones 
mapperOptionsBuilder.addConvention(new MorphiaDefaultsConvention());
mapperOptionsBuilder.addConvention(propertyDiscovery == FIELDS ? new FieldDiscovery() : new MethodDiscovery());
mapperOptionsBuilder.addConvention(new ConfigureProperties());
//custom one
mapperOptionsBuilder.addConvention(new FieldShadowingDiscovery());
```
