### ISSUE TITLE
Morphia saves Map<UUID, Object> as a String-keyed map in mongo, and then loads while silently failing

### ISSUE THREAD

**Issue by FerusGrim** [MorphiaOrg/morphia#2122]
**Describe the bug**
When Morphia saves a `Map<UUID, Object>` into mongo, it stores it as a [`string, object`](https://ferus.xyz/jM0DGv.png) relationship in the database. When it loads the data back into the application, it loads it properly as a `Map<UUID, Object>` mapping, but actually populates the Map with String keys, causing me quite a headache when I could not retrieve objects using a `Map#get` operation. It wasn't until I looped through the Map during a debug session that I discovered logs were inappropriate stopping. After investigation, I discovered a ClassCastException was occurring silently when the map attempted to provide me the key as a UUID.

**To Reproduce**
1. Save `Map<UUID, Object>` map using morphia.
2. Attempt to load the data.

**Expected behavior**
Saves (or, at the very least, loads) the data as a UUID keyed object in the database.

** Please complete the following information: **
 - Server Version: Ubuntu 20.04.4 LTS
 - Driver Version: sync-4.0.5
 - Morphia Version: 2.1.7
 - Shell Version: 4.4.15

**Additional context**
There is an issue which I believe is a parallel of mine #1461. However, the thread is rather old and the solutions (such as `@Converters`) are no longer available (or are deprecated) in my version of morphia.

I'm sure, given that this was a closed issue, that I'm missing something, but I can't for the life of me figure it out.

In the mean time, because I couldn't wait for a solution, I've just taken to altering the map at load-time, but I'd obviously love something a bit more official and less hacky.

**Comment by evanchooly** [comment]
I'm sorry it took so long to get to but I can confirm this is indeed broken in 2.1.x.  However, I can also confirm that it is fixed in 2.2.x so you should definitely update to 2.2.9.

**Comment by FerusGrim** [comment]
Can confirm that this works as intended in 2.2.9! Thanks so much for the response. I was pulling my hair trying to figure out what I was doing wrong. :)
