### ISSUE TITLE
Dynamic filter building

### ISSUE THREAD

**Issue by CycleMost** [MorphiaOrg/morphia#2134]
I'm using Filters for building queries, and it works great when you have a hard-coded set of conditions, but sometimes the conditions and logic need to be built programatically. The Filters class doesn't lend itself well to this, for example:

```
    List<Filter> orConditions = new ArrayList<>();
    // based on some app logic, random set of conditions
    orConditions.add(Filters.eq("model", "8DYX445"));
    orConditions.add(Filters.lt("price", 100));
     
    query.filter(Filters.or(orConditions.toArray(new Filter[] {})));
```
It gets even more complicated when you need to dynamically add and() and or() conditions.
It would be nice to have a helper/builder where you could build a document structure for the query. Or am I missing something?

**Comment by evanchooly** [comment]
I'm definitely interested in making the API more usable.  It's been a major focus over the last few releases.  In this, case what do you think would make it less awkward?  Maybe a cumulative method on `or` where clauses could be added individually?  e.g.,:

```java
var or  = Filters.or();
or.add(eq("model", "8DYX445"));
or.add(lt("price", 100));

query.filter(or);
```

Something like that?

**Comment by CycleMost** [comment]
Exactly. The filters that take multiple operands should be able to add/append conditions to them. I'm in the process of making a helper class to use in building dynamic queries, but it would be nicer it that wasn't needed. Thanks for considering this!

**Comment by evanchooly** [comment]
absolutely!  I'll acutally add that to 2.3.0 since it's a really easy fix.  that should be the final issue for 2.3.0 and once I clean up some upgrade docs/tools, I can push that release out soon.

**Comment by CycleMost** [comment]
awesome.
