### ISSUE TITLE
Problem applying $unset and $pull operations on nested entities

### ISSUE THREAD

**Issue by jonasnyberg** [MorphiaOrg/morphia#2145]
**Describe the bug**
We have queries doing various field operations on embedded objects in our system. Until now we have been using Morphia 1.5 without any issues. But we are currently migrating our system to Morphia 2.2.9 and encountered some problems, mainly with the `$unset` and `$pull` operators where they are not translated to their full paths (e.g. "parent.field").

**To Reproduce**
Lets say we have following Morphia query:
```
Query<CWOrg> query = ds.find(Entity.class).filter(eq("_id", someId));
query
	.update(
		UpdateOperators.unset("subscriptionDetails.syncAttempts"),
		UpdateOperators.set("subscriptionDetails.lastSyncDate", syncDate))
	.execute(new UpdateOptions().multi(true));
```

Morphia will translate the full path for the `$set` operator but only use the mapped field name for the `$unset` operator (found similar issues with `$pull`). So logging the native Mongo query results in below update. This means that only the `$set` operator applies as the `$unset` has incorrect path.

```
[
  {
    "q": {"_id": {"$oid": "637b48c5735ce247d5759634"}
	"u": {
	  "$unset": {"syncAttempts": ""}, 
	  "$set": {"subscriptionDetails.lastSyncDate": {"$date": "2022-11-21T09:45:41.514Z"}}
	}, 
	"multi": true
  }
]

```
**Expected behavior**
We would have expected that all operators are applied using their complete dot-notated path. But maybe we are misunderstanding something with the new APIs.

** Please complete the following information: **
 - Server Version: 4.2
 - Driver Version: 4.7
 - Morphia Version: 2.2.9

**Comment by pschmidt88** [comment]
I can verify that behaviour, we observe similar problems when executing `unset` updates.

Example:

```java
datastore.find(User.class)
                .filter(eq("_id", new ObjectId(userId)),
                        eq("providerAccessDetails.providerName", providerName.toString()))
                .update(UpdateOperators.unset("providerAccessDetails.lockedAt"))
                // this line doesnt work either
                .update(UpdateOperators.unset("providerAccessDetails.$.lockedAt"))
                .execute();
```

**Comment by jonasnyberg** [comment]
@pschmidt88 As a temporary workaround, I created a custom `UnsetOperator` (which extends Morphia's UnsetOperator), overriding the `toTarget(PathTarget pathTarget)` method like this:
```
@Override
public OperationTarget toTarget(PathTarget pathTarget) {
    return new OperationTarget(pathTarget, "") {
        @Override
        public Object encode(Mapper mapper) {
            return new Document(pathTarget.translatedPath(), "");
        }
    };
}
```
And then replace all calls to `UpdateOperators.unset(field)` with: `new CustomUnsetOperator(field)`. I'm not yet sure if it's a proper solution o but so far it seems to solve our issues at least.

**Comment by pschmidt88** [comment]
@jonasnyberg That saved some time debugging and finding out where it goes wrong, thank you!

**Comment by evanchooly** [comment]
I will try to take a look at this tonight/tomorrow.  I was on the verge of push 2.2.10 and this would be good to get in before then.

**Comment by jonasnyberg** [comment]
By the way, to solve the issue with `$pull` I added a custom `PullOperator` to modify these two (last) lines:
```
@Override
public OperationTarget toTarget(PathTarget pathTarget) {
    return new OperationTarget(pathTarget, value()) {
        @Override
        public Object encode(Mapper mapper) {
			...

            PropertyModel target = pathTarget.getTarget();
            return new Document(target != null ? target.getMappedName() : field(), writer.getDocument());
        }
    };
}
```
with this (last) line:
```
@Override
public OperationTarget toTarget(PathTarget pathTarget) {
    return new OperationTarget(pathTarget, value()) {
        @Override
        public Object encode(Mapper mapper) {
			...

			return new Document(pathTarget.translatedPath(), writer.getDocument());
        }
    };
}
```

**Comment by evanchooly** [comment]
OK.  Confirmed and fixed both failures.  After several attempts, I finally found a way to directly those in bulk and in various combos.  It's not pretty but gets the job done.  I'll try to push 2.2.10 tomorrow.

**Comment by evanchooly** [comment]
I just pushed 2.2.10.  It should be ready in maven central in an hour or two.

**Comment by jonasnyberg** [comment]
@evanchooly Thanks a bunch for the very quick response on it! Updated to 2.2.10 this morning and it seems to work great. 👏
