### ISSUE TITLE
Queries themselves should refuse to execute once query validation fails

### ISSUE THREAD

**Issue by mchiaffarelli6561** [MorphiaOrg/morphia#2174]
Hello,

I have some queries involving referenced objects that fail in the following way:
the first time I try to execute the query (or even just calling `toString()` on it) I get a `ValidationException` thrown, with a message saying `Could not resolve path 'ref.$id' against '[name of my class here]'.  Unknown path element: 'ref'.` (here `ref` is the name of the field holding the reference).
After the first attempt (in some cases after n attempts, for some unknown but apparently fixed n, depending on the particular query), every further attempts using the same query object succeed.

 - Server Version: 6.0.3 (also happening with 4.4)
 - Driver Version: 4.8.1 (also happening with the earlier driver version shipped by morphia)
 - Morphia Version: 2.3.0 (The bug was certainly present in morphia version 2.2.10 too. I think other earlier versions are affected too, but I cannot remember which one I tried).
 - Java Version: OpenJDK 17.0.2

This is a sample stacktrace I'm getting
```
	at dev.morphia.internal.PathTarget.failValidation(PathTarget.java:155)
	at dev.morphia.internal.PathTarget.resolve(PathTarget.java:176)
	at dev.morphia.internal.PathTarget.translatedPath(PathTarget.java:124)
	at dev.morphia.query.filters.Filter.path(Filter.java:167)
	at dev.morphia.query.filters.Filters$1.encode(Filters.java:217)
	at dev.morphia.query.MorphiaQuery.lambda$getQueryDocument$0(MorphiaQuery.java:353)
	at dev.morphia.aggregation.codecs.ExpressionHelper.document(ExpressionHelper.java:81)
	at dev.morphia.query.MorphiaQuery.getQueryDocument(MorphiaQuery.java:350)
	at dev.morphia.query.MorphiaQuery.toDocument(MorphiaQuery.java:257)
	at dev.morphia.query.MorphiaQuery.iterable(MorphiaQuery.java:316)
	at dev.morphia.query.MorphiaQuery.prepareCursor(MorphiaQuery.java:336)
	at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:220)
	at dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:197)
	at dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:192)
	at [my code calling query.first() here]
```

These simple unit tests are enough to reproduce the issue on my project, and they should clarify the issue I'm facing.

```
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import dev.morphia.Datastore;
import dev.morphia.Morphia;
import dev.morphia.annotations.Entity;
import dev.morphia.annotations.Id;
import dev.morphia.annotations.Reference;
import dev.morphia.query.Query;
import dev.morphia.query.ValidationException;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static dev.morphia.query.filters.Filters.eq;
import static org.junit.jupiter.api.Assertions.*;

class MorphiaReferenceBugTest {

	private static Datastore ds;
	private static ReferenceDocument ref;
	private static RootDocument doc;

	@Entity
	public static class RootDocument {
		@Id
		public int id;
		@Reference
		public ReferenceDocument ref;
	}

	@Entity
	public static class ReferenceDocument {
		@Id
		public int id;
	}

	@BeforeAll
	static void setUp() {
		String dbName = "TEST";
		String connectionString = "mongodb://localhost:27017/%s?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000".formatted(dbName);
		MongoClient mongoClient = MongoClients.create(connectionString);
		ds = Morphia.createDatastore(mongoClient, dbName);

		ref = new ReferenceDocument();
		ref.id = 2;
		ds.save(ref);

		doc = new RootDocument();
		doc.id = 1;
		doc.ref = ref;
		ds.save(doc);
	}

	@AfterAll
	static void tearDown() {
		ds.delete(doc);
		ds.delete(ref);
	}

	private Query<RootDocument> createQuery(String field) {
		return ds.find(RootDocument.class)
				.filter(eq(field, 2));
	}

	@ParameterizedTest
	@CsvSource({
			"ref.$id",
			"ref.id",
			"ref._id",
			"ref",
	})
	void stackTrace(String field) {
		var result = createQuery(field).first();
		assertNotNull(result);
		assertEquals(1, result.id);
	}

	@ParameterizedTest
	@CsvSource({
			"ref.$id",
			"ref.id",
			"ref._id",
			"ref",
	})
	void testFirst(String field) {
		var query = createQuery(field);

		// First call to query.first() fails.
		ValidationException e = assertThrows(ValidationException.class, query::first);
		assertEquals(
				"Could not resolve path '%s' against '%s'.  Unknown path element: 'ref'."
						.formatted(field, RootDocument.class.getName()),
				e.getMessage());

		// Then everything is fine
		var result = query.first();
		assertNotNull(result);
		assertEquals(1, result.id);
		result = query.first();
		assertNotNull(result);
		assertEquals(1, result.id);
	}

	@ParameterizedTest
	@CsvSource({
			"ref.$id",
			"ref.id",
			"ref._id",
			"ref",
	})
	void testToString(String field) {
		var query = createQuery(field);

		// First call to query.toString() fails.
		ValidationException e = assertThrows(ValidationException.class, query::toString);
		assertEquals(
				"Could not resolve path '%s' against '%s'.  Unknown path element: 'ref'."
						.formatted(field, RootDocument.class.getName()),
				e.getMessage());

		// Next everything is fine.
		assertNotNull(query.toString());
		var result = query.first();
		assertNotNull(result);
		assertEquals(1, result.id);
	}
}
```

Let me know if you need further clarifications.

**Comment by evanchooly** [comment]
`$id` isn't valid.  You'll want to use either the field name, `id`, or the document name `_id`.

**Comment by mchiaffarelli6561** [comment]
As far as I know, `$id` is the standard mongodb syntax for querying against reference ids.
And indeed on my project it is working on morphia too, after it fails a first time, as detailed above.
On the contrary, `id` and `_id` are not working at all. I've expanded a little bit the unit tests in the original report to testify this.

**Comment by evanchooly** [comment]
Actually, I think the solution is even simpler.  If you're trying to query against a reference, you just need to reference the field name of the reference, `ref`, against the value of the id:  `filter(eq("ref", id"))`.  Morphia should do all the mapping needed in regards to the `DBRef` in the database.

**Comment by evanchooly** [comment]
But, to be clear, it's Morphia failing to find a `$id` in the mapping of your entity that's failing and not anything with the server.  Morphia doesn't map the underlying `DBRef` like that.

**Comment by mchiaffarelli6561** [comment]
It appears that not even `filter(eq("ref", id))` is doing the job. It is not throwing any exception, but it is not matching the record it should match, thus the query returns no data. I have yet again expanded the unit tests in the original post adding this case.
If you says that Morphia does not support "ref.$id" as a field as in `filter(eq("ref.$id", id))` then I'm surprised that it is actually the only construct that is doing the job, even though not at first try, which fails as detailed above, but from the second try on.

**Comment by evanchooly** [comment]
the `$id` shouldn't work at all since when morphia tries to validate the path segments `$id` is not a part of the mapped `EntityModel`.  If you could wrap this up in a [reproducer](/morphiaorg/reproducer) I'd be happy to take a deeper look and see.

**Comment by mchiaffarelli6561** [comment]
I've just pushed some tests describing the issue in this reproducer repository https://github.com/mchiaffarelli6561/MorphiaReferenceQuery

I've run the tests with both JDK11 and JDK17 (17 is my target) and on morphia versions 2.2.3 and 2.3.0 (2.3.0 is my target, slight imports adjustment required to pass between the two morphia versions, as you'll know).

Hope this will help.

**Comment by evanchooly** [comment]
Sorry for the delay.  I'm in conference prep mode so my evenings are packed.  *But*, part of the mystery is solved at least.  The reason it doesn't fail that first time, at least, is that path segments that start with a `$` are ... glossed over because there are legitimate uses for those special case names (e.g., aggregations).  So when Morphia is validating the path you've given it, `ref.$id`, it sees that `$` and just nods and moves along.

Now why it suddenly starts complaining later is a bit of a mystery.  However it might have something to do with the fact that these paths are only resolved once so subsequent processing of those `Filters` might be hitting an odd code path.  There shouldn't be any validation after that first resolution.  I'll keep digging.

**Comment by evanchooly** [comment]
And, of course, right when I post that I start getting the *other* failure case.  This is one is cut and dry, though.  When querying against a reference field and there's a segment after the reference field name, validation will fail because paths down into a referenced object are explicitly failed.

**Comment by evanchooly** [comment]
I'm getting closer.  I think it boils down to debugging the code and executing the `toString()` which will resolve all the paths in a query.  In IDEA, where I should see the `toString()` value, I see the expected `ValidationException` where there should be a string.  Subsequent use of that query "works" because the validation error was swallowed by the IDE.  Running the tests without triggering that `toString()` works as expected.

So it would appear that Morphia is behaving as expected but interactions with your IDE are hiding/confusing the error states making it look like it's behaving inconsistently.  Does that help?

**Comment by mchiaffarelli6561** [comment]
Hi evan, thanks for your time.

> Sorry for the delay. I'm in conference prep mode so my evenings are packed. _But_, part of the mystery is solved at least. The reason it doesn't fail that first time, at least, is that path segments that start with a `$` are ... glossed over because there are legitimate uses for those special case names (e.g., aggregations). So when Morphia is validating the path you've given it, `ref.$id`, it sees that `$` and just nods and moves along.
> 
> Now why it suddenly starts complaining later is a bit of a mystery. However it might have something to do with the fact that these paths are only resolved once so subsequent processing of those `Filters` might be hitting an odd code path. There shouldn't be any validation after that first resolution. I'll keep digging.

I should mention that it's actually the reverse: the first interaction with the query fails (either by executing it or by calling `toString()` on it). All later executions run smoothly and if I were using `ref.$id` as fieldName I would alse the data I'm expecting. But I guess you already got this point.


> I'm getting closer. I think it boils down to debugging the code and executing the `toString()` which will resolve all the paths in a query. In IDEA, where I should see the `toString()` value, I see the expected `ValidationException` where there should be a string. Subsequent use of that query "works" because the validation error was swallowed by the IDE. Running the tests without triggering that `toString()` works as expected.
> 
> So it would appear that Morphia is behaving as expected but interactions with your IDE are hiding/confusing the error states making it look like it's behaving inconsistently. Does that help?

Indeed this is exactly the way I started to grasp the bug. I had some unit tests in my project failing due to the said `ValidationException`. When I started debugging it, I noticed that if I paused my debug right before executing, IDEA was failing to display the query object (showing me something like `ValidationException` as the value for the object), but then resuming the executing had my query working fine, encountering no errors. At this point I guessed that in debug mode IDEA was calling `toString()` to display my query, receiving the `ValidationException`, and that somehow this operation "saving the ship" behind the scenes.
The next thing I tried was changing my code so that it calls `toString()`, catches the `ValidationException` without rethrowing, and finally executes my query. This workaround allowed me to execute my query and get my records even outside of debug mode, and it is the thing that you see in the reproducer.

I should also mention: I phrased the reproducer so that it executes the workaround, with asserts detailing the various exceptions thrown and the data that are actually retrieved. Thus the reproducer test passes, confirming the odd behavior I'm experiencing.

To conclude, this to me smells like a bug: either `ref.$id` is not supported and should never work, or it is supported and it should always work. I part for the latter, as it parallels the native mongo query, but If you stand by the former (as you were suggesting at the beginning of this thread), I think you should a note in the documentation explicitely stating so. In that case, I would have another question for you: how should I translate into morphia the following query? 
`db.getCollection("RootDocument").find({"ref.$id": 2})`

Sorry for the long post, and thanks again for your time.

**Comment by mchiaffarelli6561** [comment]
Hi, thanks for taking the time analyzing this issue. Now that you've decided that you want to forbid later execution of queries that didn't pass validation, it remains to address the original reason that let me discover the issue and that I was mentioning at the end of my last post.
I need to run the following query
`db.getCollection("RootDocument").find({"ref.$id": 2})`
but the obvious way to implement it in morphia ( `datastore.find(RootDocument.class).filter(eq("ref.$id", 2)).whatever()`) do not pass validation. As a workaround, I was able to execute the query and get my desired result using this exact syntax and executing the query twice, since the validation was skipped the second time as per the bug we were talking about.
This bug assisted workaround will be forbidden by your fix, so can you point me to the intended way of implementing this query using morphia?
If I can offer a suggestion, as you already have a working solution which is also close to the native query in syntax, but which is forbidden in the validation step, you could simply lift this validation and allow the syntax `eq("ref.$id", 2)`.

**Comment by evanchooly** [comment]
Hrm.  I went to get the link to the docs where it talks about how to query references only to find that it apparently only exists in my head.  I'm certain I wrote that up somewhere but can't find it at the moment.  At any rate, you can just query that field by name and simply pass in the ID value as the query parameter.  You can see an example [here](https://github.com/MorphiaOrg/morphia/blob/8f3bdf72b0294fda190b08ca9bb65c07788d27f3/core/src/test/java/dev/morphia/test/query/TestQueriesOnReferences.java#L53).  I'll update the docs as part of this bug fix.  

i'm *know* i wrote that somewhere ...
