### ISSUE TITLE
EntityModel exception of ArrayIndexOUtOfBounds for polymorphic types with generics

### ISSUE THREAD

**Issue by daniel-exceed** [MorphiaOrg/morphia#2197]
in parameterized types building of entity model there can be an exception of IndexOutOfBounds due to not limiting the peek index while looping on it.

**To Reproduce**
https://github.com/daniel-exceed/entity-model-builder-index-out-of-bounds

**Expected behavior**
polymorphic types with generics are mapped correctly

 - Server Version: 6
 - Driver Version:4,7,2
 - Morphia Version:2.3.0

I have created a pull request to fix this:
https://github.com/MorphiaOrg/morphia/pull/2170

**Comment by evanchooly** [comment]
PR merged
