### ISSUE TITLE
Embedded entity with mixup of strings and long for the same attribute works till 2.2.X but not upon 2.3.X 

### ISSUE THREAD

**Issue by MichaBub** [MorphiaOrg/morphia#2200]
**Describe the bug**
Having an embedded entity annotated as entity can be properly mapped / read from DB with 2.2, but not with 2.3
Attention: The documents in mongo for this error can be either contain string or long values - this worked fine with 2.2, not with 2.3

e.g. Java class:

```
@Entity(useDiscriminator = false)
public class MyId implements Serializable {
    private static final long serialVersionUID = -1L;
    protected long myId;
    public MyId() {
    }
    public MyId(long myId) {
        this.myId = myId;
    }
    public MyId(String myId) {
        this.myId = Long.parseLong(myId);
    }
}
```

and data in mongo with mixup of long and string

```
{
    "_id" : {
        "identifier" : "1"
    },
	"blabla" : {
        "myId" : NumberLong(123)
    }
},
{
    "_id" : {
        "identifier" : "2"
    },
	"blabla" : {
        "myId" : "1234"
    }
}
```

will result in:
Caused by: dev.morphia.mapping.MappingException: The type 'xxx.xxx.MyId' can not be instantiated: Can not set long field xxx.xxx.myId to java.lang.String

**Comment by evanchooly** [comment]
Can you put together a [reproducer](/morphiaorg/reproducer)?  I'm not sure how that would work under 2.2 but not 2.3, either.

**Comment by MichaBub** [comment]
Hi @evanchooly 

I rather invested time in fixing this issue then writing the reproducer. 
Loading all documents from mongo, and deleting plus saving again every single document did the trick.

But I can tell you it works with 2.2 and the mixup of string/long/int fields in mongo with this trick:
This API just got removed in 2.3....

`            datastore.getMapper().mapExternal(null, aggregate);
`
see full implementation:

```
        MapperOptions mapperOptions = MapperOptions.builder()
                .collectionNaming(NamingStrategy.identity())
                .propertyNaming(NamingStrategy.identity())
                .build();
        datastore = Morphia.createDatastore(mongoClient, this.dbName, mapperOptions);

        Set<Class<?>> aggregates = loadAnnotatedWithEntity();
        for (Class aggregate : aggregates) {
            datastore.getMapper().map(aggregate);
            datastore.getMapper().mapExternal(null, aggregate);
            datastore.ensureIndexes(aggregate);
        }
    }

    public static Set<Class<?>> loadAnnotatedWithEntity() {
        Reflections reflections = new Reflections("com.mypackage");
        Set<Class<?>> classes = reflections.getTypesAnnotatedWith(Entity.class);
        return classes;
    }
```

**Comment by evanchooly** [comment]
that reproducer would really help.  Seeing what changes in the database would be useful to see.

**Comment by MichaBub** [comment]
Hi @evanchooly 

okay I wrote reproducer tests to compare

Morphia 2.2.3 - working
https://github.com/MichaBub/reproducer/tree/works_with_morphia_2_2_3

Morphia 2.3.0 - broken
https://github.com/MichaBub/reproducer/tree/broken_with_morphia_2_3

and the diff of changes:
https://github.com/MichaBub/reproducer/pull/5/files

you´ll get the error as described with 2.3 - with 2.2.3 all works fine.

```
dev.morphia.mapping.MappingException: The type 'com.foo.MyId' can not be instantiated: Can not set long field com.foo.MyId.myId to java.lang.String

	at dev.morphia.mapping.internal.ConstructorCreator.getInstance(ConstructorCreator.java:118)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:43)
```
