### ISSUE TITLE
Missing @Nullable on the value in Filters.eq

### ISSUE THREAD

**Issue by zenbones** [MorphiaOrg/morphia#2201]
Minor, but Jetbrains Idea reports Filters.eq("anAttribute", null) as annotated @NotNull. It's actually annotated with com.mongodb.lang.Nullable, so I suspect something is wrong with that annotation, which is probably not your problem, but it seems like just switching to the standard javax.annotation.Nullable would solve the issue.

**Comment by evanchooly** [comment]
It's actually missing an annotation on that field altogether.  By default, all parameters and return values are non-nullable unless otherwise annotated.  Since this parameter is missing that annotation, it gets the default from `package-info.java`.

**Comment by zenbones** [comment]
Thanks.
