### ISSUE TITLE
Can't find() a derived class in a collection of base class.

### ISSUE THREAD

**Issue by eheimburg** [MorphiaOrg/morphia#2204]
If I have class A, and class B which is derived from A *and stored in the same collection*, I can't find B's when searching.

This idiom worked in the past (possibly the *distant* past, as I'm updating from Morphia 0.111, but still). 

Simplest way to explain is to show some code, see below. 

I have also set up a reproducer here: https://github.com/eheimburg/morphiarepro

**Please complete the following information:**
 - Server Version: 4.2
 - Driver Version: 4.7.2
 - Morphia Version: 2.3.0

**Additional context**
Given these two classes:

```
@Entity
public class MyEntity {
    @Id public long id;
    @Indexed public String myName;

    public MyEntity() {}
}
```

```
@Entity(value="MyEntity")
public class MyPlayer extends MyEntity {
    public MyPlayer() { super(); }
}
```

This query should work, but doesn't:
```
    public void reproduce() {
        MyPlayer p = new MyPlayer();
        p.id = 1;
        p.myName = "Bob";
        datastore.save(p);

        MyEntity pp = datastore.find(MyEntity.class).filter(Filters.eq("myName", "Bob")).first();
        assertNotNull(pp);
        assertTrue(pp.myName.equals("Bob"));
    }
```
The first assertion, `assertNotNull(pp);`, fails.

**Comment by eheimburg** [comment]
I know this also doesn't work in 2.2.3, as that's the version the Reproducer automatically used. I've also tested in 2.3

**Comment by eheimburg** [comment]
Oddly, If I use the version of `find()` that takes a collection name (and provide the SAME collection name), I can query on the @Id variable, but no other variables (like myName). It's just odd that this works:

`        MyEntity pp = datastore.find("MyEntity", MyEntity.class).filter(Filters.eq("id", 1)).first();`

**Comment by eheimburg** [comment]
That was the problem, thanks!

This wasn't an option in the legacy 1.6 setup. Does it make sense to add a note about this to `migrating.adoc`? That's what I've been following. I'm imagining a sentence like this added to the **Legacy Configuration** section:

> If you use polymorphic queries (i.e. you have derived classes stored with base classes in the same collection) you should also add `.enablePolymorphicQueries(true)`

**Comment by evanchooly** [comment]
I added a section in the queries doc as that's probably a better long term home for it.
