### ISSUE TITLE
When saving a new document, @Id is filled in before @PrePersist is called

### ISSUE THREAD

**Issue by eheimburg** [MorphiaOrg/morphia#2225]
In the legacy system, I used an idiom where the @Id variable wasn't set on new objects until the @PrePersist function. But that doesn't seem to work anymore -- it looks like I'm being given an automatically-generated ObjectID for the ID field, BEFORE the lifecycle functions are called. I can fix this (by not using that idiom anymore) but wanted to make sure that I've understood this right -- am I misunderstanding something?

(I asked this in discord; posted as a question so it doesn't get lost.)

Additional info: when the @Id variable is an ObjectID, it gets initialized correctly. But a few of my classes use a Long for the @Id, and in those cases, trying to save crashes during a call to `dev.morphia.mapping.codec.pojo.MorphiaCodec.generateIdIfAbsentFromDocument()` . This is called before the @PrePersist function is called.

** Please complete the following information: **
    Server Version: 4.2
    Driver Version: 4.7.2
    Morphia Version: 2.3.0

**Comment by evanchooly** [comment]
I'm getting a null ID during prepersist.  If you could put together a [reproducer](/morphiaorg/reproducer) I can see what's different with my attempt to recreate this.  I'll keep poking around as I have an idea or two but other than that not having to guess at the exact scenario would be helpful.

**Comment by evanchooly** [comment]
Nope.  My idea didn't work out.  The ID is still null so I'll need that reproducer after all.  Thanks.

**Comment by eheimburg** [comment]
Here's the reproducer I was using to play around with it. (There's some extraneous configuration bits as I tried stuff out.)

https://github.com/eheimburg/morphiarepro

**Comment by evanchooly** [comment]
My apologies for taking so long.  I've been traveling for conferences but I did manage to dig in to this at the airport on the way home.  :)  Here's what's happening:  As part of the "serialized to documents" part of the codec workflow, an ID is generated for certain types.  Since the lifecycle process invokes that serialization, it attempts to generate an ID because the ID is null.  So your approach here isn't going to work.

In general, there are some historical oddities and inconsistencies with the lifecycles that I'm hoping to clean up/clarify in 3.0.  Not that it helps *now* ...

**Comment by evanchooly** [comment]
That being said, a simple check to make sure the type is `ObjectId` would "fix" this for you.  For those that don't supply an ID, the database will and then loads will break for the same reason but it'd get you where you need to be.  I'm reasonably sure I had written support for an `IdGenerator` for this very case but perhaps that was just a dream.  In any case, I'll add a check to skip generation in this case.

**Comment by jonasnyberg** [comment]
Hi @evanchooly  

I have a following up question to this fix. We use a custom composite ID in our application, called `EntityId<T>`, so we can pass around type-safe IDs in our methods. This object is wrapping an `ObjectId` and uses converters to convert it back/from the DB (so it's actually saved as an `ObjectId` in the DB).

Example code:

```
# EntityId.java:

public class EntityId<T> {
	private ObjectId id;
}

---

# MyEntity.java:

public class MyEntity {
	@Id private EntityId<MyEntity> id;
	
	public EntityId<MyEntity> getId() {
		return id;
	}
	
	public void setId(EntityId<MyEntity> id) {
		this.id = id;
	}
}
```
This has been working fine together with Morphia for several years. Normally when we save a new entity, we have always been able to do following:

```
MyEntity entity = new MyEntity();
datastore.save(entity);
assertNotNull(entity.getId());
```

However, with this commit the entity no longer contains an ID on that object after calling the `save()` method. It does seem to have an ID in the database but it's not set on the entity itself anymore. It's pretty fundamental part of our workflow and I'm kind of stuck here so wondering if you have any hints on how to solve this.

**Comment by evanchooly** [comment]
That's definitely concerning.  If you could put together a [reproducer](/morphiaorg/reproducer) I'd be happy to take a look. In the meantime, i'll try to recreate it locally.

**Comment by jonasnyberg** [comment]
Thanks for your response!

I ran a unit test in debugging mode and eventually found this change:

https://github.com/MorphiaOrg/morphia/commit/966af698781213cde3cb335e692243ae6445b2dc#diff-4253a82a97b92a3a999b1aff920949ba6afe31fa7b9e03dc13c32bb81ea2a9a8R93

As our `IdProperty.getType()` is of type `EntityId` it won't actually set the ID value anymore. In the DB, there will still be an ID set (I guess auto-generated by native Mongo?) but that ID is no longer attached to the entity being returned. If the list in that "if-statement" could be customizable somehow, that could solve it for us (then we could config it to check "EntityId") but I'm not sure I fully understand the change to begin with. 🙂

I found a workaround where I simple force set a new ID (`myEntity.setId(new EntityId<>())`) to my entity before calling `datastore.save()` and that seems to work. And maybe that is even the correct way of doing things? I was just a bit surprised as I've used Morphia for the last 8 years and it has always generated the ID for me up until that change.

**Comment by jonasnyberg** [comment]
Well, as the method itself ()`generateIdIfAbsentFromDocument(..)`) delegates the actual ID conversion to the generic method `dev.morphia.mapping.codec.Conversions.convert(...)`, I assumed it was meant to be able to handle other types as well:

```
idProperty.setValue(entity, convert(new ObjectId(), idProperty.getType()));
```
 
We have simply added a custom converter like this:

```
Conversions.register(ObjectId.class, EntityId.class, EntityId::new);
```

...And then it was able to properly convert the `ObjectId` to an `EntityId` and set it on our entity.

But if you think that the correct approach is in fact to just create the ID ahead of time then we will just make that change.

**Comment by evanchooly** [comment]
Ideally, you should be creating such IDs ahead of time.  The `Conversions` class is not part of the public API so relying on it might come back to bite you at some point.  And it's really only intended for "primitive" conversions.  Complex object types should have their own [codecs](https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/data-formats/codecs/).

**Comment by jonasnyberg** [comment]
Interesting. We do have an "EntityIdCodec" set up as well to be able to map the field between Document and Java POJO (and that is still needed). But after setting the ID ahead of time, like you suggested, it seems that we can now remove the `Conversions.register(..)` part. So we will go for that approach then.

Thanks a lot for your time! 🙏
