### ISSUE TITLE
Setting UpdateOptions.bypassDocumentValidation(true) does not keep Morphia from trying to validate paths and failing, despite the path being perfectly valid

### ISSUE THREAD

**Issue by zenbones** [MorphiaOrg/morphia#2228]
I have an entity with a map-like structure on a field...

@Property("items)
private Items items

...where Items is the map-like structure. Items has a codec which handles disassembly and writing to mongo, and reassembly and producing an Items instance. However, most changes are made via direct mongo updates, like...

 UpdateOperators.set("items.some.dot.notated.path", "aString")

...which is perfectly valid in mongo and the database will have no problem setting that value. Clearly, there's no way for Morphia to validate that path, as it has no clue what the structure of Items looks likes. I'm using bypassDocumentValidation, which evidently keeps the underlying mongo driver from trying to validate the paths, but Morphia itself ignores this and throws an error. The 1.3.x version of Morphia used to allow this by properly accepting the disabling of document validation. That was nice. Can we have that back? Can I help?

**Comment by evanchooly** [comment]
`bypassDocumentValidation` is a slightly different beast.  What you're looking for is disabling Morphia's validation which is done on the `Query` itself used to initiate the update operation.  There is a currently an [open issue](https://github.com/MorphiaOrg/morphia/issues/2198) on that one.

But it does raise a good point that perhaps these two notions should be merged.  `bypassDocumentValidation` is a much newer feature on the server but serves essentially the same need.  I'll dig in to that notion.

**Comment by zenbones** [comment]
Git it. Thank you. I'll close this as I do see the validation enable/disable on query.
