### ISSUE TITLE
Add support for Covered Indexes [moved]

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#224]
This is [Issue 224](http://code.google.com/p/morphia/issues/detail?id=224) moved from a Google Code project.
Added by 2011-02-03T15:31:59.000Z by [scotthernandez](http://code.google.com/u/scotthernandez/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Milestone-Release1.1
### Original description

Primarily this means having _id:0 and inclusion fields in Query.retrievedFields. Maybe a special method is best; Query.ignoreIdField().

It is kinda weird since the _id field is special and needed for references and internal use (save/delete/query-by-id).

**Comment by evanchooly** [comment]
7 years old and not a single other request for this.  I'm going to close this and if someone actually wants this, a new issue can be opened.
