### ISSUE TITLE
Error: Caused by: dev.morphia.query.ValidationException: Could not resolve path 'customParams.inventory.data' against <SOME_ENTITY_CLASS>.  Unknown path element: 'data'.

### ISSUE THREAD

**Issue by Hussain-Badshah** [MorphiaOrg/morphia#2253]
Hi all, I have morphia 2.2.3 version in my project and here's what the scenario is: 

I have a map of map field in my @Entity class like following: Map<String,Map<String,String>> map; and I am trying to update the value of  inner map's key, for example let's assume that in the existing document, map looks like following: 

map
{
"inventory"
{
"data":"123"
}
}

then I want to update the value against "data" key in the inner map "inventory" to let's say "456". Now, to update, below is the couple of lines of code I have in my project: 
 **Bson bsonUpdates = com.mongodb.client.model.Updates.combine(q.update(updateOperations).toDocument(), com.mongodb.client.model.Updates.set(LAST_UPDATED_TIME, LocalDateTime.now()));
            UpdateResult ur = mongoCollection.updateMany(q.toDocument(), bsonUpdates, new UpdateOptions().multi(true).upsert(false));**

From the first line above, from one of the nested calls from toDocument() method, from PathTarget#resolve() method following exception is getting thrown: **Error: Caused by: dev.morphia.query.ValidationException: Could not resolve path 'customParams.inventory.data' against 'com.harman.ignite.vehicleprofile.domain.VehicleProfile'.  Unknown path element: 'data'.**

In my test case the key that I am generating is "map.inventory.data" but if for the key: "map.inventory.123" or to say in general, for any such key: "map.inventory.<any_numeric_key>" the same test case is passing and the update operation is getting done successfully. 

I don't understand why only for a **literal String** at the end of the DB key it's failing. Am I doing anything the wrong way? Could you somebody please help me with this error/exception? We are totally blocked because of this issue, any suggestion/help would be really helpful.

**Comment by evanchooly** [comment]
Can you share your entity and the query code?

**Comment by Hussain-Badshah** [comment]
> Can you share your entity and the query code?

@evanchooly 
**Below is the entity class**: 

@Entity("ecallEvents")
public class ECallEvent extends AbstractIgniteEvent implements AuditableIgniteEntity {

    private static final long serialVersionUID = -1785142819686025246L;
    @Id
    private String ecallId;
    private long hits;
    private long dunks;
    @Property("testCounter")
    private long counter;
    private BytesBuffer bytesBuffer;
    private List<String> listAttr1 = new ArrayList<String>();
    private List<String> listAttr2 = new ArrayList<String>();
    private Set<String> setAttr1 = new HashSet<String>();
    private Set<String> setAttr2 = new HashSet<String>();

    private LocalDateTime lastUpdatedTime;

    private LocalDate localDate;

    private LocalTime localTime;

    private List<AuthUsers> authorizedUsers;
   
    private Map<String,Map<String,Integer>> customParams;
    
    private TestEntity entity;
    
    
    public void setMeta(Map<String,Map<String,Integer>> customParams) {
    	this.customParams = customParams;
    }
    
    public Map<String,Map<String,Integer>> getMeta(){
    	return this.customParams;
    }

    public LocalDate getLocalDate() {
        return localDate;
    }
    
    public void setEntity(TestEntity entity) {
    	this.entity = entity;
    }
    
    public TestEntity getEntity() {
    	return this.entity;
    }
    public void setLocalDate(LocalDate localDate) {
        this.localDate = localDate;
    }

    public LocalTime getLocalTime() {
        return localTime;
    }

    public void setLocalTime(LocalTime localTime) {
        this.localTime = localTime;
    }

    public List<AuthUsers> getAuthorizedUsers() {
        return authorizedUsers;
    }

    public void setAuthorizedUsers(List<AuthUsers> authorizedUsers) {
        this.authorizedUsers = authorizedUsers;
    }

    public String getEcallId() {
        return ecallId;
    }

    @Id
    public void setEcallId(String ecallId) {
        this.ecallId = ecallId;
    }

    @Override
    public List<IgniteEvent> getNestedEvents() {
        // TODO Auto-generated method stub
        return null;
    }

    public long getHits() {
        return hits;
    }

    public void setHits(long hits) {
        this.hits = hits;
    }

    public long getDunks() {
        return dunks;
    }

    public void setDunks(long dunks) {
        this.dunks = dunks;
    }

    public List<String> getListAttr1() {
        return listAttr1;
    }

    public void setListAttr1(List<String> strings) {
        this.listAttr1 = strings;
    }

    public Set<String> getSetAttr1() {
        return setAttr1;
    }

    public void setSetAttr1(Set<String> integers) {
        this.setAttr1 = integers;
    }

    public List<String> getListAttr2() {
        return listAttr2;
    }

    public void setListAttr2(List<String> listAttr2) {
        this.listAttr2 = listAttr2;
    }

    public Set<String> getSetAttr2() {
        return setAttr2;
    }

    public void setSetAttr2(Set<String> setAttr2) {
        this.setAttr2 = setAttr2;
    }

    public BytesBuffer getBytesBuffer() {
        return bytesBuffer;
    }

    public void setBytesBuffer(BytesBuffer bytesBuffer) {
        this.bytesBuffer = bytesBuffer;
    }

    public long getCounter() {
        return counter;
    }

    public void setCounter(long counter) {
        this.counter = counter;
    }

    @Entity
    public static class AuthUsers {
        private String userId;

        private String role;
        private String status;
        private LocalDateTime createdOn;
        private LocalDateTime updatedOn;

        public String getUserId() {
            return userId;
        }

        public void setUserId(String userId) {
            this.userId = userId;
        }

        public String getRole() {
            return role;
        }

        public void setRole(String role) {
            this.role = role;
        }

        public String getStatus() {
            return status;
        }

        public void setStatus(String status) {
            this.status = status;
        }

        public LocalDateTime getCreatedOn() {
            return createdOn;
        }

        public void setCreatedOn(LocalDateTime createdOn) {
            this.createdOn = createdOn;
        }

        public LocalDateTime getUpdatedOn() {
            return updatedOn;
        }

        public void setUpdatedOn(LocalDateTime updatedOn) {
            this.updatedOn = updatedOn;
        }

    }

    @Override
    public LocalDateTime getLastUpdatedTime() {
        return lastUpdatedTime;
    }

    @Override
    public void setLastUpdatedTime(LocalDateTime lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;

    }
    
    @Override
    public String toString() {
    	return "AbstractIgniteEvent [TestEntity = "+this.entity+", version=" + version + ", timestamp=" + timestamp + ", eventData=" + eventData + ", requestId=" + requestId
                + ", sourceDeviceId=" + sourceDeviceId + ", vehicleId=" + vehicleId + "]";
    }
}

Below are the couple lines through which I am trying to update the customParams field in my Entity class:

**Bson bsonUpdates = com.mongodb.client.model.Updates.combine(q.update(updateOperations).toDocument(), com.mongodb.client.model.Updates.set(LAST_UPDATED_TIME, LocalDateTime.now()));
UpdateResult ur = mongoCollection.updateMany(q.toDocument(), bsonUpdates, new UpdateOptions().multi(true).upsert(false));**

In above lines, **q**'s datatype is Query<ECallEvent> 

Please let me know if anything else is required.

**Comment by Hussain-Badshah** [comment]
@evanchooly maybe you can have a similar or the same entity class as ECallEvent in my previous comment and in it you can have a map of map type property and in your test case you can try updating only that particular field through morphia 2.2.3 or with any later version. 

Another thing I would like to bring to your attention is that the exact same use case of mine was working as expected with 1.6.1 morphia version. Below is how update was being done with 1.6.1 version: 

**UpdateResults ur = mongoDatastore.update(q, updateOperation);**

where, **mongoDatastore**'s type is **AdvancedDatastore**, **q**'s type is **Query** and **updateOperation**'s type is **UpdateOperations<T>**
Since the above update method was deprecated, we had to change our implementation to what I have mentioned in my previous comment. 

On a different note, do you have any reference to some document that explains how to update any field in an entity class using pure morphia library code, in version 2.2.3? If you do, can you please share? I will go through it and try to incorporate the same in my project.

**Comment by Hussain-Badshah** [comment]
@evanchooly as you suggested, tried updating through pure morphia code too, the below way: 

**UpdateResult ur = datastoreNew.find(entityClass).update(updateOperations).execute();** - Mentioned in the official morphia docs but this also resulted in the same exception. execute() internally calls a toDocument() method of UpdateBase, and there's something wrong in the flow from toDocument() onwards. After the control goes inside toDocument(), it fails with the aforementioned exception. 

Below is the stack trace for your reference: 

dev.morphia.query.ValidationException: Could not resolve path 'customParams.inventory.data' against '<entity.class.package.name>'.  Unknown path element: 'data'.
	at dev.morphia.internal.PathTarget.failValidation(PathTarget.java:137)
	at dev.morphia.internal.PathTarget.resolve(PathTarget.java:166)
	at dev.morphia.internal.PathTarget.getTarget(PathTarget.java:121)
	at dev.morphia.query.OperationTarget.encode(OperationTarget.java:48)
	at dev.morphia.query.Operations.toDocument(Operations.java:74)
	at dev.morphia.query.UpdateBase.toDocument(UpdateBase.java:88)
	at dev.morphia.query.Update.execute(Update.java:45)
	at dev.morphia.query.Update.execute(Update.java:35)
