### ISSUE TITLE
mapPackages() optional?

### ISSUE THREAD

**Issue by CycleMost** [MorphiaOrg/morphia#2263]
I've noticed that my app seems to work just fine without calling mapPackages(). The only effect I've seen is that the ensureIndexes() method won't do anything (and will show the warning "no packages mapped"). Aside from that, are there any drawbacks to not calling mapPackages()?

Full detail - I had some issues with class loading when I called mapPackages() using the mapSubPackages option, so I've turned it off for now.

thank you

**Comment by evanchooly** [comment]
Morphia will, typically, dynamically map a type when it encounters one.  However, if you're doing something like indexes or document validation, those won't operate on anything that's been mapped already.  So at startup, it's "better" to call map explicitly but if you're not using either of those two features, you're probably ok.

One area where it will silently violate expectations is if you use polymorphic queries.  Morphia won't know about your full class hierarchy without mapping all your entities up front.  There's a very good chance that the next version (3.0, that is) will require upfront mapping for this very reason.  The behavior can be subtly unexpected without it.  But I haven't committed fully to that notion just yet.

**Comment by CycleMost** [comment]
Thanks for the explanation and the heads-up about version 3.0

**Comment by evanchooly** [comment]
If there are no further questions, I'll close this one out as it seems you have your question answered.  Feel free to reopen or open a new one if that's not the case.
