### ISSUE TITLE
Reproducer Bug: exceptions in new bottlerocket version

### ISSUE THREAD

**Issue by eheimburg** [MorphiaOrg/morphia#2265]
**Describe the bug**
I noticed this when creating a new reproducer: if I create a new reproducer repo and run the empty `reproduce()` test, I get a cascade of exceptions. The core exception is this:

> java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.lang.Enum.name accessible: module java.base does not "opens java.lang" to unnamed module @43c3d622

Since I'd previously created a working reproducer, I compared it to the new one and poked at things until it worked. When I edited the pom to use `com.antwerkz.bottlerocket` version 0.14 instead of the new 0.41.0, the error disappeared.

**To Reproduce**
The reproducer for my other bug report can show this -- if you edit the pom in https://github.com/eheimburg/enumserializedbug to reference 0.41.0, instead of 0.14, you should see the errors.

**Expected behavior**
Empty test class should succeed out of the box

**Please complete the following information:**
 - Server Version:
 - Driver Version:
 - Morphia Version: 2.3.0

**Comment by evanchooly** [comment]
updated the reproducer template
