### ISSUE TITLE
Test containers dependency should not be leaked to the library users

### ISSUE THREAD

**Issue by cocorossello** [MorphiaOrg/morphia#2340]
**Describe the bug**
I just noticed that the test container dependency should be in the test scope (SNAPSHOT version).

**To Reproduce**

**Expected behavior**
Dependency should not be leaked

** Please complete the following information: **
 - Server Version:
 - Driver Version:
 - Morphia Version: SNAPSHOT

**Comment by cocorossello** [comment]
https://github.com/MorphiaOrg/morphia/pull/2341

**Comment by evanchooly** [comment]
fixed by PR
