### ISSUE TITLE
Add support for result transformers / projections [moved]

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#240]
This is [Issue 240](http://code.google.com/p/morphia/issues/detail?id=240) moved from a Google Code project.
Added by 2011-03-08T08:35:49.000Z by [martin.grotzke](http://code.google.com/u/martin.grotzke/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, Milestone-Icebox
### Original description

```
It would be great to be able to specify a resulttransformer for a subset of requested fields (retrievedFields) so that custom entities are created by morphia when returning the result.
```

**Comment by evanchooly** [comment]
This should be doable with `find(String, Class)`
