### ISSUE TITLE
ReferenceException within a transaction: Referenced entity could not be found during a fetch.

### ISSUE THREAD

**Issue by phitosoftware** [MorphiaOrg/morphia#2445]
A ReferenceException is thrown within a transaction.

```
public class Company
{
    String name;
}

public class User
{
    String email;
    @Reference
    Company company;
}

public void test(){
    Datastore datastore = Morphia.createDatastore(mongoClient, "test_database");
    Morphiasession session = datastore.startSession();
    session.startTransaction();

    // save company
    Company company = new Company();
    company.setName("test");
    company = session.save(company)

    // save user with reference to company
    User user = new User();
    user.setEmail("test@test.com");
    user.setCompany(company);
    session.save(user);

    // find all users
    List<User> users = session.find(User.class).iterator().toList(); // Exception
    ...
    session.commitTransaction();
}
```

The Exception is thrown in dev.morphia.mapping.experimental.SingleReference line 87:
`ReferenceException: Referenced 'Company' entity could not be found during a fetch.`

Resolving the company reference seems to take place outside the transaction and the newly created company is therefore still unknown.

How can the active transaction be taken into account when resolving the reference?

Our current version of morphia is 2.3.5.

**Comment by evanchooly** [comment]
I'm away at a conference but I'll try to take a look as soon as I can.
