### ISSUE TITLE
Null Map<> field when loaded from entity class with ctor that initializes it

### ISSUE THREAD

**Issue by christolis** [MorphiaOrg/morphia#2446]
**Describe the bug**
There was recently a user report where a `Map<>` object within an entity class would not get properly loaded from the database. When the entity class is saved, the `Map<>` is successfully persisted with its values. However, when it is loaded from the database, the `Map<>` becomes `null`. The issue is likely caused by the constructor in the entity class that re-initializes the values to empty values, overriding the values loaded from the database. Note that this might include field types that are different from `Map<>`.

**To Reproduce**
1. Create a new instance of an entity class that has a constructor which initializes fields, including one with the type of `Map<>` .
2. Make sure that the `Map<>` field is populated with some key-value pairs.
3. Save the object to the database.
4. Now load it again. The `Map<>` field should be null.

**Expected behavior**
The `Map<>` should have been populated with data from the database when the object would get loaded.

 - Driver Version: 4.10.1
 - Morphia Version: 2.3.5

**Comment by evanchooly** [comment]
I can't reproduce this locally and a workaround for the OP was found.
