### ISSUE TITLE
Fixes not merged to 2.3.x branch

### ISSUE THREAD

**Issue by h-arlt** [MorphiaOrg/morphia#2450]
It seems to me that several fixes - at least those for #1831 and #2340 but others might be affected too - were not merged to 2.3.x branch and are thus missing for releases v2.3.1 - v2.3.6.
Was this intended or did some merge broke?

**Comment by evanchooly** [comment]
This looks like an oversight and if they're not in 2.3.x, they're not in 2.4.0 either so it looks like a couple of rapid fire releases this weekend.

**Comment by evanchooly** [comment]
in the case of #2340, it looks like it went in to master but wasn't backported to 2.3.

**Comment by h-arlt** [comment]
Roger that. Thanks for the update and the quick fix!

**Comment by evanchooly** [comment]
2.3.7 and 2.4.1 are syncing to central now.
