### ISSUE TITLE
Missing conversions codecs across Morphia versions.

### ISSUE THREAD

**Issue by dnfeitosa** [MorphiaOrg/morphia#2576]
**Describe the bug**
Populating objects with `java.util.Date` fields fails when the date is stored as `Long` in Mongo.

After some debugging, I found the `Long` to `Date` conversion codec added in `2.2.x` is missing in Morphia `2.3.x`, `2.4.x`, and `master`.

**2.2.x**
https://github.com/MorphiaOrg/morphia/blob/2.2.x/core/src/main/java/dev/morphia/mapping/codec/Conversions.java#L53-L55

**2.3.x**
https://github.com/MorphiaOrg/morphia/blob/2.3.x/core/src/main/java/dev/morphia/mapping/codec/Conversions.java#L68-L69

**2.4.x**
https://github.com/MorphiaOrg/morphia/blob/2.4.x/core/src/main/java/dev/morphia/mapping/codec/Conversions.java#L68-L69

**master**
https://github.com/MorphiaOrg/morphia/blob/master/core/src/main/java/dev/morphia/mapping/codec/Conversions.java#L68-L69

**To Reproduce**
Sample code: https://gist.github.com/dnfeitosa/403dac9d37e705465c1049c055f598ed

Expected:
```
Date: Wed Sep 27 11:24:20 EDT 2023
Object saved:  MyModel{id='65144a11a6e99c58e9a572e7', someDate=Wed Sep 27 11:24:20 EDT 2023}
Object loaded: MyModel{id='65144a11a6e99c58e9a572e7', someDate=Wed Sep 27 11:24:20 EDT 2023}
```

Current:
```
Date: Wed Sep 27 11:24:20 EDT 2023
Object saved:  MyModel{id='65144a86bfcf39506d3a36ab', someDate=Wed Sep 27 11:24:20 EDT 2023}

dev.morphia.mapping.MappingException: The type 'dev.morphia.issue.DateConversionIssueTest$MyModel' can not be instantiated: Can not set java.util.Date field dev.morphia.issue.DateConversionIssueTest$MyModel.someDate to java.lang.Long

	at dev.morphia.mapping.internal.ConstructorCreator.getInstance(ConstructorCreator.java:118)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:49)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:76)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:53)
```

** Please complete the following information: **
 - Server Version: 5.0.21
 - Morphia Version: 2.2.x (working), 2.4.x (not working)

**Comment by evanchooly** [comment]
Doh.  found it.  I'd done some clean up in that class and missed that removal.  I'll add it back for 2.4.6.

**Comment by dnfeitosa** [comment]
@evanchooly thank you for the quick response and fix! It worked perfectly.
