### ISSUE TITLE
Issue with normalize() in PropertyModel

### ISSUE THREAD

**Issue by subhagho** [MorphiaOrg/morphia#2677]
**Describe the bug**
When detecting the entity type for `@Reference` field in an entity, it picks up the incorrect type if the field is a collection and component type is parameterized.

**To Reproduce**
1.  Nested entity: 
 
 `class N<K> {`
`@Id`
`private ObjectId id`
`...`
`}`

2.  Parent entity:  
 
`class P {`
`@Id`
`private ObjectId id;`
`...`
`@Reference`
`private List<N<String>> nested;`
`}`

**Expected behavior**
The expected extracted type from the `PropertyModel.normalize()` would be type(N). But the actual extracted type is type(String). Hence it throws a validation error `is annotated with @Reference but the class java.util.List is missing the @Id`.

** Please complete the following information: **
 - Server Version: 6.0
 - Driver Version: 4.9
 - Morphia Version: 2.4.7

**Additional context**
Any example models, queries, and executable test cases you can supply will greatly help debugging your issue:

**Comment by evanchooly** [comment]
[CI](https://github.com/MorphiaOrg/morphia/actions/runs/6842818031) for this is running now.  If that succeeds, there should be a 2.4.8-SNAPSHOT on the snapshot repo within an hour or so.  If you could give that a whirl and confirm it fixes your issue, I can push out a formal release.  if you can't test with it, I can just push the release anyway and take it from there.
