### ISSUE TITLE
Query is incorrect when DocumentState.andTogether method in package dev.morphia.mapping.codec.writer

### ISSUE THREAD

**Issue by RachelZ1** [MorphiaOrg/morphia#2764]
**Describe the bug**
Query is incorrect when a few "and" logical filters are added by DocumentState.andTogether method in package dev.morphia.mapping.codec.writer

**To Reproduce**
1. Create query with 2 conditions of the same field (like query.filter(Filters.gte(field1, "xxx"); query.filter(Filters.lt(field1, "xxxy"); ))
2. Add another 2 filter on another field (like query.filter(Filters.gte(field2, "aaa"); query.filter(Filters.lt(field2, "aaab"); )
3. print the query document
4. See the error: the second field have only the last filter ("$lt", "aaab") 
5. 

**Expected behavior**
The query has all of the filter clause...

** Please complete the following information: **
 - Server Version:
 - Driver Version:
 - Morphia Version: 2.3.4 but it happens also in 2.4.10

**Additional context**
Any example models, queries, and executable test cases you can supply will greatly help debugging your issue:
After I debugged Morphia code, I found the problem in 
codec.writer.DocumentState class andTogether method.
you remove the filter (extant) and not add it in case of add != null (line 43 )

**Comment by evanchooly** [comment]
I thought we'd vanquished the last of this ages ago.  :(

**Comment by evanchooly** [comment]
I just pushed a fix that should be making its way through CI right now.  If you can test the 2.4.11-SNAPSHOT just to confirm it also fixes your issue, I can push the final version.  If not, I can just push it and circle back if that's not quite the right fix.

**Comment by RachelZ1** [comment]
`  private Document andTogether(Document doc, String key, @Nullable Object additional) {
        if (additional != null) {
            Document newSubdoc = new Document(key, additional);
            var extant = doc.remove(key);
            List<Document> and = (List<Document>) doc.get("$and");
            if (and != null) {
                and.add(newSubdoc);
            } else {
                and = new ArrayList<>();
                and.addAll(of(new Document(key, extant), newSubdoc));
                doc.put("$and", and);
                return newSubdoc;
            }
        }
        return doc;
    }`

this is not good. 
After key removed from the doc, you need to add the 'extant' var also if and != null.

something like:
`  private Document andTogether(Document doc, String key, @Nullable Object additional) {
        if (additional != null) {
            Document newSubdoc = new Document(key, additional);
            var extant = doc.remove(key);
            List<Document> and = (List<Document>) doc.get("$and");
            if (and != null) {
                if (extant != null){ 
                      and.addAll(of(new Document(key, extant), newSubdoc));
                } else{
                    and.add(newSubdoc);
                }
            } else {
                and = new ArrayList<>();
                and.addAll(of(new Document(key, extant), newSubdoc));
                doc.put("$and", and);
                return newSubdoc;
            }
        }
        return doc;
    }`

**Comment by evanchooly** [comment]
Have you tried the snapshot? Because that method no longer exists and it should resolve your issue.
