### ISSUE TITLE
Query filters merged incorrectly

### ISSUE THREAD

**Issue by steffen-bobek** [MorphiaOrg/morphia#2824]
**Abstract**
When using several `or` filters, they are merged into a single `or` filter instead of being `and`-concatenated. 

**In Detail**
I just updated Morphia from 2.4.6 to 2.4.11 and now have a problem with queries.

Assuming A/B/C/D are any `eq` filters, I build a query as follows:

```java
query.filter(or(A, B));
query.filter(or(C, D));
```

In version 2.4.6, this was compiled into the following query:

`{ $and: [ $or: [ A, B ], $or: [ C, D ] ] }`

In version 2.4.11, however, it is now compiled into the following query:

`{ $or: [ A, B, C, D ] }`

The result of the query is something completely different. The change was introduced with the commit [afd698947fe3e7cd94a3add3917a1507f39f44f2](https://github.com/MorphiaOrg/morphia/commit/afd698947fe3e7cd94a3add3917a1507f39f44f2) from 3 January.

**Comment by evanchooly** [comment]
Yikes.  Kind of a subtle bug.  I had thought I correctly handled `$and` and `$or` but clearly not.  I just pushed a fix that should get you back to square.  It's currently percolating through CI but should be available in a `2.4.12-SNAPSHOT` in an hour so.  If you could give it a try to confirm it would be a huge help.  But if you can't, I'll just push it as is and look at a `.13` to clean up any remaining issues.
