### ISSUE TITLE
NullPointerException when using count()

### ISSUE THREAD

**Issue by faroflo** [MorphiaOrg/morphia#2844]
**Describe the bug**
Hi,
The following kind of invocation failed with a `NullPointerException`:
`dataStore.find(Simplistic.class).filter(Filters.eq("_id", "123")).count()`

Example entity:
```java
import dev.morphia.annotations.Entity;
import dev.morphia.annotations.Id;

@Entity
public class Simplistic {

    @Id
    private String id;

}
```

Error:
```
java.lang.NullPointerException: Cannot invoke "dev.morphia.Datastore.getCodecRegistry()" because the return value of "java.lang.ThreadLocal.get()" is null
	at dev.morphia.mapping.codec.pojo.PropertyModel.configureCodec(PropertyModel.java:374)
	at dev.morphia.mapping.codec.pojo.PropertyModel.specializeCodec(PropertyModel.java:274)
	at dev.morphia.query.filters.Filter.getValue(Filter.java:157)
	at dev.morphia.query.filters.Filters$1.encode(Filters.java:220)
	at dev.morphia.query.MorphiaQuery.lambda$getQueryDocument$0(MorphiaQuery.java:394)
	at dev.morphia.aggregation.codecs.ExpressionHelper.document(ExpressionHelper.java:81)
	at dev.morphia.query.MorphiaQuery.getQueryDocument(MorphiaQuery.java:391)
	at dev.morphia.query.MorphiaQuery.count(MorphiaQuery.java:114)
	at dev.morphia.query.MorphiaQuery.count(MorphiaQuery.java:108)
...
```

Datastore Setup:
```
CodecRegistry pojoCodeRegistry = fromRegistries(
                MongoClientSettings.getDefaultCodecRegistry(),
                fromProviders(PojoCodecProvider.builder().automatic(true).build()));

MongoClientSettings mongoClientSettings = MongoClientSettings
        .builder()
        .codecRegistry(pojoCodeRegistry)
        .applyConnectionString(connectionString)
        .retryReads(true)
        .build();
MongoClient mongoClient = MongoClients.create(mongoClientSettings);

MapperOptions mapperOptions =
          MapperOptions.builder()
                       .dateStorage(DateStorage.SYSTEM_DEFAULT)
                       .discriminatorKey(DISCRIMINATOR_KEY)
                       .discriminator(DiscriminatorFunction.className())
                       .collectionNaming(NamingStrategy.identity())
                       .propertyNaming(NamingStrategy.identity())
                       .enablePolymorphicQueries(true)
                       .mapSubPackages(true)
                       .build();

Datastore dataStore = Morphia.createDatastore(mongoClient, "dbname", mapperOptions);

```

Notes:
* The error appears to be related to https://github.com/MorphiaOrg/morphia/issues/2472
* The error only occurs if filters are defined.
* The cause appears to be that the `ThreadLocal` `holder` isn't set before it's accessed in `MorphiaQuery.count()` (see below).  
It's already required by `getQueryDocument()`, but only set inside `datastore.operations().countDocuments(...)` (so after it's accessed in `getQueryDocument()`). Note that the call to `getQueryDocument()` succeeds if _no_ filters were defined.  
The workaround to call `query.first()` (suggested in https://github.com/MorphiaOrg/morphia/issues/2472) works here as well.
```
public long count(CountOptions options) {
        MongoCollection<T> collection = datastore.configureCollection(options, this.collection);
        return datastore.operations().countDocuments(collection, getQueryDocument(), options);
}
```

**To Reproduce**
1. Create very simple entity with just an ID field
2. Invoke `dataStore.find(MyEntity.class).filter(Filters.eq("_id", "123")).count()`
3. Observe the error.

**Expected behavior**
The query should have returned the number of matching documents on the collection.

** Please complete the following information: **
 - Server Version: 7.0.5
 - Driver Version: 4.10.2
 - Morphia Version: 2.4.4

Thanks a lot for your support in advance, your efforts are very much appreciated!

**Comment by evanchooly** [comment]
This has been fixed in later versions.  Please try with 2.4.11.

**Comment by faroflo** [comment]
Hi @evanchooly,

I was under the impression 2.4.4 was the latest version, my bad.

Thanks for the quick response!
