### ISSUE TITLE
Ability to use a custom MorphiaInstanceCreator

### ISSUE THREAD

**Issue by agiannone** [MorphiaOrg/morphia#2934]
**Is your feature request related to a problem? Please describe.**
Currently each class associated with Morphia needs to have an empty constructor. I would like to avoid having empty constructors lying around and instead use Objenesis to create the objects. This was previously possible with the ObjectFactory.

**Describe the solution you'd like**
It would be great if we could provide a custom MorphiaInstanceCreator or supply our own NoArgCreator.

**Describe alternatives you've considered**
The only alternative I see manipulating each EntityModel to inject our own InstanceCreatorFactory which hurts my soul just to type :-)

**Comment by evanchooly** [comment]
Partial and full constructors are both supported so you shouldn't need to build custom anythings short of any functionality gaps/bugs.

**Comment by agiannone** [comment]
Is it possible to have a class with no constructor at all?

**Comment by evanchooly** [comment]
If you mean you don't write a constructor in your source, then yes. You'll get a default no arg constructor in the bytecode. But every class definition will have at least one constructor.

**Comment by agiannone** [comment]
Great, the idea was to not write a constructor in the source. Given that works then we can close this enhancement :-)
