### ISSUE TITLE
Update Operations do not work correctly for maps with ObjectId keys

### ISSUE THREAD

**Issue by danielmerchant** [MorphiaOrg/morphia#2936]
**Describe the bug**

I think I found a bug while trying to update documents that use `ObjectId` as a key in a map. I'm getting `ClassCastException`s from the Mongo Java Driver's `AbstractMapCodec` indicating that the value passed to the codec does not have a `String` key, which it expects - see the implementation [here](https://github.com/mongodb/mongo-java-driver/blob/master/bson/src/main/org/bson/codecs/AbstractMapCodec.java#L76-L88), and note the discrepancy between the method's type signature `M` and the definition of the `for` loop, which indicates that all entries in the map should have keys of type `String`.

I traced it back to the Morphia `ExpressionHelper`, which appears to retrieve a Codec (`MorphiaMapPropertyCodecProvider`) that is designed to handle this case, but because the codec does not implement the `PropertyHandler` interface, it is not applied in the `OperationTarget` code [here](https://github.com/MorphiaOrg/morphia/blob/master/core/src/main/java/dev/morphia/query/OperationTarget.java#L66-L68).

**To Reproduce**
1. Create a Morphia entity that contains a field of type `Map<ObjectId, ?>`
2. Use Morphia to write the document to the DB
3. Write an update operation that mutates the value of the field created in step 1
4. See `java.lang.ClassCastException: class org.bson.types.ObjectId cannot be cast to class java.lang.String (org.bson.types.ObjectId is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')`

**Expected behavior**

The entity is persisted correctly.

** Please complete the following information: **
 - Server Version: 4.0.20
 - Driver Version: 4.11.1
 - Morphia Version: 2.4.12

**Additional context**
Any example models, queries, and executable test cases you can supply will greatly help debugging your issue:

```java
@Entity
public class MyModel {
  private Map<ObjectId, String> data;
  // getters, setters, constructors, etc.
}

public class MyModelDAO {
  private final Datastore;

  // this throws a ClassCastException
  public void updateMyData(ObjectId modelId, Map<ObjectId, String> newData) {
      datastore.find(MyModel.class)
         .filter("_id", modelId)
         .update(new UpdateOptions(), UpdateOperators.set("data", newData));
    }
}

**Comment by danielmerchant** [comment]
Following up on this - I think this is also an issue for other types as well. I encountered the same stack trace when trying to update a map with an `enum`-based key. I'm wondering if it makes sense to use the `Conversions` API to attempt to convert the Object to a string when building the `UpdateOperator`s.

**Comment by evanchooly** [comment]
Have you tried this against 2.4.13?  I can't recreate this on the 2.4.x branch.  Maybe a full [reproducer](/morphiaorg/reproducer) might be useful.

**Comment by danielmerchant** [comment]
> Have you tried this against 2.4.13? I can't recreate this on the 2.4.x branch. Maybe a full [reproducer](/morphiaorg/reproducer) might be useful.

Still encountering this on 2.4.13. Will add a full reproducer.

**Comment by danielmerchant** [comment]
Found out what the issue was. The order in which my codecs were registered meant that the MongoClientSettings' default `AbstractMapCodec` was being used, rather than the Morphia Map codec.
