### ISSUE TITLE
New release of 1.6 branch with current mongo-driver

### ISSUE THREAD

**Issue by cdietze** [MorphiaOrg/morphia#3034]
**Is your feature request related to a problem? Please describe.**

We have a legacy application that uses morphia 1.6.1.
We need to move away from MongoDB to a SQL database.
So, we're looking to use [FerretDB](https://www.ferretdb.com/).
FerretDB requires at least MongoDB version 5.0 [which is supposed to be fine starting with mongo-driver 3.8](https://www.mongodb.com/docs/drivers/java/sync/current/compatibility/#mongodb-compatibility).
However, the mongo-driver in version 4.1.1 (used in morphia 1.6.1) still uses some incompatible commands.

**Describe the solution you'd like**

I'd like a new release of the 1.6 branch that uses the current (4.11.2) version of the mongo-driver.
I already tried it out locally, I can provide a PR if desired.

**Describe alternatives you've considered**

Upgrading to current morphia needs many adjustments, I would like to make as little changes to our code as possible.

**Comment by evanchooly** [comment]
Does it need any code changes or can you just explicitly declare a driver dependency on the version you need?

**Comment by evanchooly** [comment]
Unfortunately, an upgrade to a 5.0 driver is an incompatible change.  1.6 is effectively EOL and once 3.0 lands (hopefully later this year) will be officially unsupported.  Your best bet to migrate to 2.4.x.
