### ISSUE TITLE
why `Query#iterator` return `dev.morphia.query.internal.MorphiaCursor` instead of `dev.morphia.query.MorphiaCursor`

### ISSUE THREAD

**Issue by CoolLoong** [MorphiaOrg/morphia#3061]
** Please ask your question and provide whatever background or supporting information you think might be relevant: **
why `Query#iterator` return `dev.morphia.query.internal.MorphiaCursor` instead of `dev.morphia.query.MorphiaCursor`

** Please complete the following information: **
    Server Version: 7.0.9
    Driver Version: 4.11.2
    Morphia Version: 2.4.4

**Comment by CoolLoong** [comment]
`MapperOptions#Builder` is still tagged deprecated and forRemoval in `2.4.4`

**Comment by evanchooly** [comment]
Yes.  and the docs for that method list the new approach to use.

**Comment by evanchooly** [comment]
As for that return type, it was a mistake on the public API.  If you remove `internal` from the package name on your import, it should work just fine.  The `internal` version was moved to a public package.
