### ISSUE TITLE
When Adding @Deprecated please add alternatives to use.

### ISSUE THREAD

**Issue by BharathSurya219** [MorphiaOrg/morphia#3144]
**Is your feature request related to a problem? Please describe.**
When a method is @Deprecated please add alternatives or new methods so that is will be easy to update the existing usage in the method documentation.

**Comment by evanchooly** [comment]
Typically, there are alternatives or documentation with the deprecation.  if there's a specific example that perhaps is lacking either of those, I'd be happy to clean that up.  But as it is, this is too vague to do much with.  Are there specific cases you have in mind?
