### ISSUE TITLE
Lazy OneToMany reverse mapping [moved]

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#357]
This is [Issue 357](http://code.google.com/p/morphia/issues/detail?id=357) moved from a Google Code project.
Added by 2011-12-08T21:22:01.000Z by [nikfoun...@gmail.com](http://code.google.com/u/109131656467805960554/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low
## Original description

<b>What version are you using? (Morphia/Driver/MongoDB)</b>
Morphia: 0.99, Mongo Driver: 2.6.5, MongoDB: 2.0.0

Hi everyone,

I am relatively new to mongo - and morphia of course, but I'm quite fascinated by the schema-less, document database concept. I tried morphia recently and I would like to contribute to this ambitious project.
I've been using JPA (mainly hibernate) for quite some time, so inevitably I cannot avoid the comparison between morphia and JPA.

One thing that I would like to have in morphia is the OneToMany association of a parent entity towards its children, using reverse mapping. This would allow morphia to store only the child to parent reference inside the child collection, without having to store the children references inside the parent collection. When a parent entity is loaded from the db a lazy collection with children is prepared. When the collection of children is first accessed (by requesting size() for example) the lazy collection is filled with proxy references of child entities. Finally, each child is actually fetched upon the first usage. The benefit of this functionality is to avoid multiple save operations on the parent entity, after adding a child.

Actually what I have implemented so far is the following:

1) A custom proxy factory that provides a utility method to create the lazy collection on the parent entity: (Only List is supported for now)

``` java
public <T extends Collection> T createListProxy(Object parent, String mappedByFieldName, final T listToProxy, final Class referenceObjClass, final boolean ignoreMissing, final DatastoreProvider p) { ... }
```

The above snippet follows the principles of morphia's CGLibLazyProxyFactory class.

2) A custom implementation of the ProxiedEntityReferenceList interface similar to SerializableCollectionObjectReference except that it requires the parent entity and the child field name (mappedBy attribute) that holds the reference to this particular parent.

3) An EntityInterceptor implementation that uses the postLoad method to replace the actual children collection with the proxy list.

4) The parent class:

``` java
@Entity
public class Parent {
    @Id
    private ObjectId id;

    @Reference(lazy=true)
    @NotSaved
    //@OneToMany(mappedBy=&quot;parent&quot;)
    private List<Child> children;
...
}
```

5) The child class:

``` java
@Entity
public class Child {
    @Id
    private ObjectId id;

    @Reference(lazy=true)
    private Parent parent;
...
}
```

As a next step I was thinking to create a custom annotation @OneToMany or update the existing @Reference annotation and process it inside the ReferenceMapper class to achieve the above functionality.

If you find this issue interesting I could prepare a patch and submit it.

Best regards,
Nick

PS: What is the procedure to participate in the project?

**Comment by Eaiman** [comment]
is there any update on this issue? I mean, can we use one to many in morphia?

**Comment by evanchooly** [comment]
You can do a one-to-many relationship using a `@Reference List<Foo>` field.  What the OP wanted isn't ... nicely possible because it would require a join and mongo queries don't support that.
