### ISSUE TITLE
Add @EntityListeners [moved]

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#43]
This is [Issue 43](http://code.google.com/p/morphia/issues/detail?id=43) moved from a Google Code project.
Added by 2010-05-09T17:41:36.000Z by [scotthernandez](http://code.google.com/u/scotthernandez/).
Please review that bug for more context and additional comments, but update this bug.
 Closed (Fixed).

Original labels: Type-Enhancement, Priority-Low, Milestone-Release0.93
### Original description

```
Add @EntityListener support; works just like lifecycle methods but for 
another class.

@Entity
@EntityListeners(com.acme.AlertMonitor.class)
public class Account {
@Id long accountId;
}

public class AlertMonitor {
@PostPersist
public void newAccountAlert(Account acct) {
Alerts.sendMarketingInfo(acct.getAccountId(), acct.getBal-
ance());
}
}
```

**Comment by ravindra1986** [comment]
Hi,
I created a interface 
public interface ListnerInterface {}
and provide this interface to the one of my entity class like @EntityListeners(ListnerInterface .class)
and given the implementation of this interface to other folder eg:
public class ListnerUtilService implements ListnerInterface {}.
But it is not invoking this class.  why? please help me.
