### ISSUE TITLE
make Datasource accessible in @EntityListeners [moved]

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#439]
This is [Issue 439](http://code.google.com/p/morphia/issues/detail?id=439) moved from a Google Code project.
Added by 2012-11-02T15:47:24.000Z by [jmhed...@gmail.com](http://code.google.com/u/106058808180641141833/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Low
### Original description

```
What version are you using? 0.99

unfortunately, one isnt able to access the Datasource from within an EntityListener.
```

**Comment by evanchooly** [comment]
I looked in to this and even had it mostly working.  Unfortunately, it requires several changes to public APIs that can't be mitigated by simple overloads.  I'm afraid this one will have to wait.
