### ISSUE TITLE
Warnings while querying reference fields with a key

### ISSUE THREAD

**Issue by ismetozalp** [MorphiaOrg/morphia#483]
Hi!
I come to found a warning when i query reference fields with Key. I don't think it's necessary. But if it is, Is there way to suppress this warning. Let me explain the situation

I have a object

@Entity(noClassnameStored = true)
public class CrewLabel implements IsSerializable {

@Id
public ObjectId id;

@Reference
public Employee owner;
}

When i try to query it like this

Query query = createQuery();
query.field("owner").equal(new Key(Employee.class, ownerId));

I got the warning

WARNING: The type(s) for the query/update may be inconsistent; using an instance of type 'com.github.jmkgreen.morphia.Key' for the field 'com.statu.alarga.web.shared.model.CrewLabel.owner' which is declared as 's.model.Employee'
--@--com.statu.alarga.web.server.dao.CrewLabelDaoImpl.findLabelsOfCrew(CrewLabelDaoImpl.java:72)

What can we do about this?

Thank you.

Regards,
Ismet

[ pulled from https://github.com/jmkgreen/morphia/issues/65 ]

**Comment by lahong** [comment]
hi did this ever get resolved,im trying to do the same thing,
