### ISSUE TITLE
Add a getter for ValidatorFactory in ValidationExtension

### ISSUE THREAD

**Issue by jhooda** [MorphiaOrg/morphia#573]
Ideally one would want to catch all validation exceptions before "@PrePersist" and return a customized single message for all exceptions, so following will be a useful enhancement for someone to grab the --existing-- validatorFactory and perform validations on DOs. 

public Class ValidationExtension extends AbstractEntityInterceptor {
  // ....
  public ValidatorFactory getValidatorFactory() {
     return this.validationFactory;
  }
  // ...
}

**Comment by waqarabbas** [comment]
@evanchooly getValidatorFactory is been removed from morphia 2.x, Any specific reason ? if yes, what is the work around to get validationFactory object ?
