### ISSUE TITLE
Examples for creating Converter for ImmutableList, ImmutableMap, ImmutableSet?

### ISSUE THREAD

**Issue by darbie** [MorphiaOrg/morphia#601]
I have data objects that have the guava Immutable collections.  Is it possible to create a TypeConverter that will work for these classes?

**Comment by dklotz** [comment]
Has someone succeeded in this? I managed to do it for ImmutableList/Set of simple types (e.g. String), but for an embedded `ImmutableList<SomeCustomClass>`, my TypeConverter somehow isn't even called...

**Comment by evanchooly** [comment]
Please ask such questions on the [mailing list](https://groups.google.com/forum/#!forum/morphia).
