### ISSUE TITLE
No usable constructor for java.util.Currency

### ISSUE THREAD

**Issue by umbreak** [MorphiaOrg/morphia#617]
org.mongodb.morphia.mapping.MappingException: No usable constructor for java.util.Currency

Currency usses a factory method to create an instance of the object, and does not provide any constructor. Can you provide a mapping for it? Or I have to write my own converter?

Note that jackson and other JSON libraries do the marshalling/unmarshalling of Currency correctly and out of the box.

**Comment by evanchooly** [comment]
depends on #940
