### ISSUE TITLE
Validation Error on querying list element

### ISSUE THREAD

**Issue by jeremygirard** [MorphiaOrg/morphia#641]
I have an object with a list of ObjectId.

I need to make a query to retriever Obj containing an id in there ids list.

In version 0.107 my query was :
        Query<Obj> query = datastore.createQuery(Obj.class);
        query.field("ids").equal(id);

It works fine without validation warning.

Since 0.108 i've got the following message

WARN  [QueryValidator] The type(s) for the query/update may be inconsistent; using an instance of type 'org.bson.types.ObjectId' for the field 'xxx.bean.morphia.Obj.ids' which is declared as 'java.util.List'
WARN  [QueryValidator] Validation warnings: 
[Validation failed: 'Type java.util.List may not be queryable with value '53d8c51eda06cb13d550e814' with class org.bson.types.ObjectId']

I tried to rewrite my query this way

Query<Obj> query = datastore.createQuery(Obj.class);
        query.field("ids").hasThisElement(id);

but i have the same warning.

Thanks

**Comment by omervk** [comment]
Still happening as of 1.1.1.

**Comment by evanchooly** [comment]
Can't recreate on master.  If this issue persists on 1.2.1, please file a new issue with a test case to rereate it.
