### ISSUE TITLE
List<Interface> with custom converter does not work (converter ignored)

### ISSUE THREAD

**Issue by umbreak** [MorphiaOrg/morphia#658]
I have the following interface

```
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "className")
public interface InfoChartInformation {
    public String name();
}
```

And the following implementation (enum):

```
public class InfoChartSummary {    
    public static enum Immobilien implements InfoChartInformation {
        CITY, CONSTRUCTION_DATE;
    }
    public static enum Cars implements InfoChartInformation {
        POWER, MILEAGE;
    }
}
```

Then I use the following entity:

```
@Entity(noClassnameStored = true)
@Converters(InfoChartInformationMorphiaConverter.class)
public class TestEntity{
    @Id
    public ObjectId id;
    @Embedded
    public List<InfoChartInformation> order;
}
```

Jackson, in order to detect the type on the unmarshalling time, will add to every enum on the list the class.

I thought morphia would do the same, but there's no field className (or a full route to the enum, class.getName+"." +enum.name()) in the List of enum **and the unmarshalling cannot be done correctly**: `java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassCastException: java.lang.String cannot be cast to com.mongodb
.DBObject`

I guess the correct behaviour should be to save all the enum route, not only the enum name. So I created a custom converter, similar to the one [here](https://github.com/mongodb/morphia/blob/master/morphia/src/main/java/org/mongodb/morphia/converters/EnumConverter.java) but morphia is ignoring it:

```
public class InfoChartInformationMorphiaConverter extends TypeConverter{
    public InfoChartInformationMorphiaConverter() {
        super(InfoChartInformation.class);
    }
    @SuppressWarnings("unchecked")
    @Override
    public Object decode(Class targetClass, Object fromDBObject, MappedField optionalExtraInfo) {
        if (fromDBObject == null) {
            return null;
        }
        String clazz = fromDBObject.toString().substring(0, fromDBObject.toString().lastIndexOf("."));
        String value = fromDBObject.toString().substring(fromDBObject.toString().lastIndexOf(".") + 1);
        try {
            return Enum.valueOf((Class)Class.forName(clazz), value);
        } catch (ClassNotFoundException e) {
            return null;
        }
    }
    @Override
    public Object encode(final Object value, final MappedField optionalExtraInfo) {
        return value.getClass().getName() + "." + ((InfoChartInformation) value).name();
    }
}
```

Then, I added the converter information to morphia `morphia.getMapper().getConverters().addConverter(new InfoChartInformationMorphiaConverter());`. 

However, **when marshalling the object to save it into the database, the custom converter is not called and the Enum list is saved using the default Morphia converter** (only the enum name).

If I use in the `TestEntity` class only an **attribute `InfoChartInformation order;` instead of the `List<InfoChartInformation> order`, my customer converter will work**, but It does not for the List, which is what I need.

**Comment by evanchooly** [comment]
This involves deeper plumbing changes than I was hoping and more than I'm comfortable making in this cycle.  Bumping to post-1.0.

**Comment by evanchooly** [comment]
I know this is old but did #420 fix this one for you?

**Comment by wbijen** [comment]
Is this problem fixed? I'm still having problems with my converter.

It's converting the Object but not if I put it in a List.

**Comment by pioorg** [comment]
@wbijen Does your converter implement SimpleValueConverter? When writing collections, the items are encoded using their converter, provided the converter supports exactly their class and implements SVC.

**Comment by evanchooly** [comment]
Given the lack of response and that converters are going away in 2.0, I'm tempted to close this.  Any reason I shouldn't?

**Comment by evanchooly** [comment]
Closing this issue for now.  Hopefully 2.0's use of Codecs will make this a non-issue going forward.
