### ISSUE TITLE
Add support for global value naming convention

### ISSUE THREAD

**Issue by evanwong** [MorphiaOrg/morphia#677]
By default, it uses the field name as the value name which is pretty much camel case when you are doing Java. 
If you want to make it snake case, base on the example, you have to annotate the individual field:

``` java
@Property("my_integer")
private int myInt;
```

It will be better to make it a global config or provide an interface for people to implement for all fields instead of the need of annotating every fields manually.

**Comment by Mast3rPlan** [comment]
:+1:

**Comment by zgranik** [comment]
What is happening with this one? 
3 years to implement?
