### ISSUE TITLE
Add authentication [moved]

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#73]
This is [Issue 73](http://code.google.com/p/morphia/issues/detail?id=73) moved from a Google Code project.
Added by 2010-06-28T14:11:12.000Z by [darin%pl...@gtempaccount.com](http://code.google.com/u/106929007945936052056/).
Please review that bug for more context and additional comments, but update this bug.
 Closed (Fixed).

Original labels: Type-Enhancement, Priority-Low, Milestone-Release0.94
### Original description

```
Add authentication to DataStoreImpl
```

**Comment by duozhilin** [comment]
maybe you could use the following code:

        Morphia morphia = new Morphia();
        ServerAddress addr = new ServerAddress("host", 27017);
        List<MongoCredential> credentialsList = new ArrayList<MongoCredential>();
        MongoCredential credentia = MongoCredential.createCredential(
	        "username", "dbname", "password".toCharArray());
        credentialsList.add(credentia);
        MongoClient client = new MongoClient(addr, credentialsList);
        datastore = morphia.createDatastore(client, "dbname");
