### ISSUE TITLE
[enhancement] Support the new driver API

### ISSUE THREAD

**Issue by oallouch** [MorphiaOrg/morphia#749]
That might "just" involve a bridge between DBObjects and Documents, to get a Morphia.fromDocument() method for instance.

**Comment by RainoBoy97** [comment]
I'd also like to see this get implemented!

**Comment by ludjer** [comment]
Would be very nice to see this implemented.

**Comment by evanchooly** [comment]
What are you thinking this would look like?  Very little, if any, of the driver's types should be leaking into your application using Morphia.

**Comment by oallouch** [comment]
I only use morphia.toDBObject(obj) and I only need morphia.toDocument(obj)  .
Note that it's not that urgent, I can live with deprecated calls in my code.

**Comment by berus97** [comment]
Is there any estimate, when will be supported new 3.0 mongo java driver?
thanks.

**Comment by evanchooly** [comment]
I'm working on finishing up some 3.2 work for an internal project and then
plan/hope to tackle the next release of Morphia.

*--------------------------------*

*{ *name     : *"**Justin Lee**", *
  title    : *"*Software Engineer*"*,
  twitter  : *"*@evanchooly <http://twitter.com/evanchooly>*"*,
  web      : *[* "mongodb.com <http://www.mongodb.com>", *"*antwerkz.com*"*
*]*,
  location : *"*New York, NY*"* *}*

**Comment by evanchooly** [comment]
this is done in 2.0.  No more `DBObject` references anywhere.
