### ISSUE TITLE
Pattern not working for $in

### ISSUE THREAD

**Issue by singhcl** [MorphiaOrg/morphia#853]
Hi,
I need to search an array for a pattern but the query formed from Morphia in java does not return result while if I remove the quotes(") from resulted pattern, the query works in console.
e.g. { "effectiveSalts" : { "$in" : [ "/^PARA/"]}} -- Query from Morphia
{ "effectiveSalts" : { "$in" : [ /^PARA/]}} -- works in console

any help would be appreciated on this.

Thanks

**Comment by evanchooly** [comment]
Are you still fighting this one?  If you can post a test case, I'll see what I can do.

**Comment by evanchooly** [comment]
Rereading this it sounds like maybe you're trying to use `java.util.regex.Pattern` for the query which is currently supported.  I'll see what it'd take to make that work, though.

**Comment by evanchooly** [comment]
adding a new method in a patch releases breaks semver.  bumping to 1.4.0

**Comment by evanchooly** [comment]
Actually, the driver supports mapping `Pattern` objects.  The existing `in()` method should be suitable for this.  You'll just have to create `Pattern` instances and pass them in.  I'm going to close this for now but should a specific issue arise, please open a new issue and we'll take it from there.
