### ISSUE TITLE
Kotlin: Mapping exception when a field is delegated as NotNull

### ISSUE THREAD

**Issue by chaseberry** [MorphiaOrg/morphia#865]
``` Kotlin
var status: String by Delegates.notNull()
```

Morphia would throw an exception trying to inject a String into this field.

**Comment by evanchooly** [comment]
I know the why of this and the general shape of the how of the fix but it can't really be done until 2.0 where we're moving to a full Codec-based setup.

**Comment by evanchooly** [comment]
fixed in commits culminating with 175da2293c77c769bc1f0712d9ac32bda1965559
