### ISSUE TITLE
Trying to write and get a very basic object, everything works, but it throws warnings on pulling

### ISSUE THREAD

**Issue by MelonCode** [MorphiaOrg/morphia#877]
Doing everything exactly like in example code: http://habrahabr.ru/post/118783/
I'm 'recieving' object, everything works fine, but I'm getting warnings 

```
[03:45:18 WARN]: Class not found defined in dbObj: 
java.lang.ClassNotFoundException: test.TestItem
...
```

Getting with this code
`ds.find(TestItem.class).get();`

I'm using v. 1.0.1

**Comment by MelonCode** [comment]
I'm firgured out. feel free to contact me if you need help

**Comment by outman1234** [comment]
Class not found defined in dbObj: 
java.lang.ClassNotFoundException: com/server/entity/ClientInfo

How to solve this???
I met this problem Today,

**Comment by outman1234** [comment]
@MelonCode   see my

**Comment by MelonCode** [comment]
@outman1234 as I remember I was need to set custom object factory for morphia

You can do it like this
`morphia.getMapper().getOptions().setObjectFactory(new CustomMorphiaObjectFactory());`
And here's my 
[CustomMorphiaObjectFactory ] (https://gist.github.com/MelonCode/0d0ad8e07f2b1da8138860ec51bae975)
