### ISSUE TITLE
Configure the expireAfterSeconds annotation externally

### ISSUE THREAD

**Issue by raulgd** [MorphiaOrg/morphia#909]
Hi,

Most of Morphia's annotations are great time savers, but specifically the expireAfterSeconds property in the field annotation is not practical, because usually, depending on deployment capacity, I should be able to specify when to expire a certain document.

So, is there a way to externally specify expireAfterSeconds? As I see there is no way to execute queries to change such index, and also I see no way to dynamically specify that property in Morphia, like an external configuration file (in my case I use Spring Boot, so specify it in the application.properties file).

If someone has a suggestion on how to work around this would be great!

**Comment by evanchooly** [comment]
You can construct the index document directly and run `dbCollection.createIndex(DBObject, DBObject).`  e.g., the index created [here](org.mongodb.morphia.TestExpireAfterSeconds.ClassAnnotation) results in a call to `createIndex()` with two documents:  `{ "offerExpiresAt" : 1}` and `{ "expireAfterSeconds" : 5}`.

So depending on how you want that index to look, you can just create the appropriate `DBObject` structures and call `createIndex()` directly.

**Comment by evanchooly** [comment]
This verges on deployment concerns and is, at least for now, outside the scope of Morphia's concern.
