### ISSUE TITLE
Aggregation pipeline elements improvements

### ISSUE THREAD

**Issue by evanchooly** [MorphiaOrg/morphia#911]
#896 revealed some glitches in the aggregation API.  e.g., a Group's ID should like a list of expressions rather than a list of Groups.  Methods like `Projection.substract()` should probably be on an `Expression` class and return an `Expression` type.

**Comment by ravindra1986** [comment]
HI Evan,
i have situation like to implements compare entity before save entity to mongo DB.
How to achieve using morphia,spring and jersey.

**Comment by evanchooly** [comment]
this is cleaned up in the new aggregation api
