### ISSUE TITLE
Annotation to store long field as Date?

### ISSUE THREAD

**Issue by niccottrell** [MorphiaOrg/morphia#920]
I have a class with java.util.Date as a field, but I'd like to switch to using a long and unix datestamp inside the Java objects. Is there some way I can do this with Morphia annotations so that it marshalls them into the BSON date object time when saving?

**Comment by shils** [comment]
You should be able to do this with a combination of `PreSave`, `Transient` and `PreLoad` annotations. Rough idea: annotate your timestamp field with `Transient`, and have `PreSave` and `PreLoad` methods which set the date field in the DBObject prior to saving, and replace the date field in the DBObject with it's timestamp prior to loading.

**Comment by evanchooly** [comment]
As of 2.0, this can be done by simply providing a custom `Codec` when configuring the `MongoClient`.
