### ISSUE TITLE
Morphia does not uses registered Codec

### ISSUE THREAD

**Issue by viniciusfcf** [MorphiaOrg/morphia#935]
If I execute the follow code, mongodb store correctly UUID field: 
`
        CodecRegistry codecRegistry =  CodecRegistries.fromRegistries(CodecRegistries.fromCodecs(new UuidCodec(UuidRepresentation.STANDARD)), MongoClient.getDefaultCodecRegistry());

```
    // globally
    MongoClientOptions options = MongoClientOptions.builder()
        .codecRegistry(codecRegistry).build();
    MongoClient client = new MongoClient(new ServerAddress(), options);

    client.getDatabase("nomeDoBancoDependenteDoCliente").getCollection("App").insertOne(new Document("_id", UUID.randomUUID()));
```

`
However if If execute the follow code, the UUID is stored as LUUID (UUID old)
`

```
    CodecRegistry codecRegistry =  CodecRegistries.fromRegistries(CodecRegistries.fromCodecs(new UuidCodec(UuidRepresentation.STANDARD)), MongoClient.getDefaultCodecRegistry());

    // globally
    MongoClientOptions options = MongoClientOptions.builder()
        .codecRegistry(codecRegistry).build();
    MongoClient client = new MongoClient(new ServerAddress(), options);
```

Datastore ds = morphia.createDatastore(client, "nomeDoBancoDependenteDoCliente");
Application application = new Application(); //Application contains UUID field
        application.setName("APlicacao Fake main2");
        ds.save(application);`

Morphia shold respect my configuration.

source: http://mongodb.github.io/mongo-java-driver/3.2/driver/reference/crud/

Morphia version: 1.1.1
JDK version 1.8.0_91
Mongodb version: 3.2.4

![image](https://cloud.githubusercontent.com/assets/14058396/15347949/8b14c0c2-1c9c-11e6-9f64-4b5e7aaa397a.png)

![image](https://cloud.githubusercontent.com/assets/14058396/15347964/b2aeac4c-1c9c-11e6-97f6-c4f0a36f9b50.png)

**Comment by jyemin** [comment]
It's because Morphia is still built on top of the legacy DBCollection API, which does not use the registry.  See the Javadoc for [MongoClientOptions.Builder.codecRegistry](http://api.mongodb.com/java/current/com/mongodb/MongoClientOptions.Builder.html#codecRegistry-org.bson.codecs.configuration.CodecRegistry-)

So fixing this will require re-building Morphia on top of the standard MongoCollection API, which does use the codec registry.

**Comment by viniciusfcf** [comment]
Hi, thanks jyemin. Exists a workaround to save my entity ID in mongodb with UUID type 4? Or because  Morphia is still built on top of the legacy I can not use UUID type 4?

**Comment by jyemin** [comment]
It's not elegant, but adding this to the start of your application will do the trick:

````
      // Add a global encoding hook to transform a UUID into a Binary with subtype of 4   
      BSON.addEncodingHook(UUID.class, new Transformer() {
            @Override
            public Object transform(final Object objectToTransform) {
                UUID uuid = (UUID) objectToTransform;
                BsonDocument holder = new BsonDocument();

                // Use UUIDCodec to encode the UUID using binary subtype 4
                BsonDocumentWriter writer = new BsonDocumentWriter(holder);
                writer.writeStartDocument();
                writer.writeName("uuid");
                new UuidCodec(UuidRepresentation.STANDARD).encode(writer, uuid, EncoderContext.builder().build());
                writer.writeEndDocument();

                BsonBinary bsonBinary = holder.getBinary("uuid");
                return new Binary(bsonBinary.getType(), bsonBinary.getData());
            }
        });
```

This will ensure that the UUID is stored using the desired binary subtype, and the UUID decoder will ensure that its decoded properly.  

Give it a shot, but be careful that the encoding hook is always registered, in all of your applications.  Otherwise, you'll end up with a mix of encodings in the database.,

**Comment by pioorg** [comment]
Hello
Is there really no way to change the set of codecs used by Morphia?
Maybe org.mongodb.morphia.DatastoreImpl#saveDocument could pass an enhanced codec set (with encoder) in DBCollectionUpdateOptions?

**Comment by evanchooly** [comment]
Morphia isn't currently using the codec system at all (it uses the legacy API).  Work is underway to modernize that, however.

**Comment by evanchooly** [comment]
2.0 is using the codec system which fixes this issue.

**Comment by wheezil** [comment]
Greetings!  We're looking at morphia for a fall release, and would like the modern codec support.  I see that 2.0 Alpha was out in December.  Would it be wise for me to start using that now?

**Comment by evanchooly** [comment]
There's actually a BETA1 release out now and I would live some feedback on it.  Barring any massive rejection by users of the new APIs this is essentially the final form and should be stable enough to begin developing on and testing against.  All the tests pass so I'm comfortable as fast that goes but it could use some real world testing.

**Comment by wheezil** [comment]
Great!  Is there a maven repo I can reference for this?

**Comment by evanchooly** [comment]
Go to https://morphia.dev/ and select 2.0.0-BETA1.  I'm updating the docs but the docs under the 2.0.0 snapshot are partially updated.

**Comment by wheezil** [comment]
Ah, so I should build from source?  I was hoping to be lazy and just use a maven repo :-)

**Comment by evanchooly** [comment]
No the instructions are right there about how to update your pom.xml/build.gradle to pull the 2.0.0-BETA1 artifacts from maven central.  They're already built and ready to use.

**Comment by wheezil** [comment]
Uh, sorry, I must be having a stupid day...  The latest I can find on maven central is 1.5.8, and using 2.0.0-BETA1 or r2.0.0-BETA1 for <version> are failing maven.  A little help please?  I'm also getting a lot of 404s from morphia.dev links.
