### ISSUE TITLE
Possible to make Datastore serializable?

### ISSUE THREAD

**Issue by UlrichCech** [MorphiaOrg/morphia#937]
Hi,
I wanted to know, if it is possible to extend the datastore so that it is injectable into a Session-Scoped bean? Currently, you have to define the injection point as "transient", but this is of course not the solution ;-):
`@Inject
transient Datastore datastore;
`
RequestScoped, ApplicationScoped and Dependent-Pseudo-scope are fine, but SessionScoped produces the "WELD-000054: Producers cannot produce non-serializable instances for injection into non-transient fields of passivating beans"

Thanks in avdance,
Ulrich

**Comment by evanchooly** [comment]
The tricky thing here is that `Datastore` holds a reference to `MongoClient` which is not serializable.  I'm not sure what we can do from the Morphia end.  The idea or two I have are all breaking changes which aren't an option at this point.  Making `MongoClient` serializable would, at first glance, require pushing down serializability down through the `Codec` API which starts to get ugly pretty quickly.

I'm not entirely sure a session scoped `Datastore` is what you want anyway.  Using an application scoped `Datastore` is usually sufficient.  What is driving the requirement for session scope?

**Comment by UlrichCech** [comment]
It is not, that I need a session scoped Datastore... it is more the injection of the datastore into a session scoped bean... then the IDEs always complain about, that a non-serializable bean is injected into a serializable-scoped bean.
But you are right, the effort is not very easy here. So we can close the issue for now... or should we leave it open for the 'backlog'?

**Comment by evanchooly** [comment]
I'll close for now just to keep the backlog cohesive.  (I'm currently trying to triage all open tickets and bucketing in to milestones.)

**Comment by UlrichCech** [comment]
I just saw, that this is not only with SessionScoped, but also with ViewScoped, which is common in JSF-application development... so in summary: Usage of datastore in a Session- and ViewScoped-bean is not directly possible, which is a bit bad for concise development...

**Comment by evanchooly** [comment]
Hrm.  OK.  I have some ideas that might make this doable.  I'll target this for 1.3 and see what can be done.

**Comment by UlrichCech** [comment]
Perhaps, you can later tell me the key-points, and I can help with the implementation...

**Comment by evanchooly** [comment]
If `Morphia.createDatastore()` is overloaded to take a `MongoURI`, we can lazily connect in `getMongo()` and `getDB()`.  The `mongoClient` field would be marked serializable (as would `Datastore`).  This should allow us to reconnect after dehydration.  There are obvious performance implications, of course, but this is one approach.

**Comment by UlrichCech** [comment]
Some short workaround for web-applications at the moment without the enhancement could be to make the Producer-Method request-scoped:
```java
@Produces
@RequestScoped
public Datastore getDatastore() {
    return datastore;
}
```
Then, a 'normal' injection like this is possible:
```java
@Inject
Datastore datastore;
```
The IDEs do yet complain about the serialization/non-serialization-thing, but the CDI-container correctly analyzes, that the injected field is request scoped and need not not be serializable.

**Comment by evanchooly** [comment]
I know this is years out of date and probably not of interest at the point.  But I'm going to reclose this for a couple of reasons:

1.  It's technically near impossible and probably *actually* impossible without breaking someone, somewhere with the necessary API/config changes.  but more importantly,
2.  Datastore has no real state beyond the mongo client and the mapper reference.  This is something that could be injected via CDI, say, and managed externally.
