### ISSUE TITLE
Return single object instead of array with Lookup 

### ISSUE THREAD

**Issue by MiguelAngelLV** [MorphiaOrg/morphia#952]
Sometimes, when we use lookup use _id for external document, so it will return a single element. It is "boring" get a array and get the first element always.

Maybe the lookup stage would has a paramater "single" to get a single element instead of array.

**Comment by evanchooly** [comment]
Could you elaborate a little?  If you're referring to how `$lookup` works, that's defined by the server and there's nothing that morphia can do about that.

**Comment by PhilJay** [comment]
Have you tried the `{"$unwind": "$your_fieldname"}` argument in the pipeline?

**Comment by anuragpareek** [comment]
Yes we have tried "$unwind" but its really good if there is a parameter as "MiguelAngelLV" said.

**Comment by kallego** [comment]
I agree with MiguelAngelLVgree.

**Comment by daggett206** [comment]
up, it really makes sense

**Comment by PARAGJYOTI** [comment]
Yaa , that's makes sense . If the id field is not nested inside of an array , you can use $arrayElemAt but , if the result array is inside of an array  , you have to use $unwind . no other way .

**Comment by Amantel** [comment]
It would be super cool. $[arrayElemAt](https://docs.mongodb.com/manual/reference/operator/aggregation/arrayElemAt/) helps but, it is another operator.

**Comment by evanchooly** [comment]
It seems the solution here is to add a conditional stage that unwinds a single value or passes along the mutlivalue array.  i'm also not sure I want morphia to be responsible for providing that stage definition.  Given the age of this and how niche it is, I'm going to close this for now.

**Comment by githubSeb** [comment]
That would have been great to have a single example, ot to make $unwind works the way you described it. Its is painful !

**Comment by MahdadGhasemian** [comment]
I also use the `$arrayElemAt` but I agree with MiguelAngelLVgree.
