### ISSUE TITLE
Add T merge(T entity) method

### ISSUE THREAD

**Issue by pshadow** [MorphiaOrg/morphia#959]
Please add a method to return updated entity on merge method, so that user don't have to query again to get whole entity.

**Comment by evanchooly** [comment]
So, essentially, you'd like Morphia to make that query automtically, yes?

**Comment by pshadow** [comment]
@evanchooly yes I'd like to save a query, after mege I get a key, I need to use it query again to get modified entity. I think if "merge" can just return the modified entity would be great.

**Comment by evanchooly** [comment]
I can't change the return type of `merge()` because that would break everyone using it but I can introduce a new method...

**Comment by pshadow** [comment]
that would be great. Thank you!
