### ISSUE TITLE
Annotations for sharding [moved]

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#96]
This is [Issue 96](http://code.google.com/p/morphia/issues/detail?id=96) moved from a Google Code project.
Added by 2010-08-25T12:45:09.000Z by [rajesh.k...@gmail.com](http://code.google.com/u/109344903581321306501/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, Milestone-Icebox
### Original description

```
The database provides native commands to enable sharding on a certain database and the collection within that using enableSharding and shardCollection methods. It would be nice to have some annotations which will enable a database / collection for sharding much similar to the @Indexed annotation. Currently we will have to rely on the native database commands to enable this on every developer machine.
```

**Comment by jasondemorrow** [comment]
Maybe I'm misunderstanding, but it seems like relatively simple, minimal support could be added through an @ShardKey annotation. I agree that abstracting cluster-level operations is more the domain of a management tool than an ORM, but support for collection-level sharding indexes would be very nice to have.
