### ISSUE TITLE
Morphia does not recognize my @ID annotated field

### ISSUE THREAD

**Issue by rockydcoder** [MorphiaOrg/morphia#960]
I have a simple POSO `GroupACLTemplate` which I want to persist. It is subclassed from an abstract class. I have annotated it with `@Entity` and also have an `@Id`

```
@Entity("aclTemplate")
@SerialVersionUID(1L)
class GroupACLTemplate(@(Id@field) id: String, groupRoleAccess: Set[GroupRoleAccess]) extends AclTemplate(id) with Serializable
```

When I deploy my war, I am not seeing any collection of `GroupACLTemplate`. I also tried this

```
class GroupACLTemplate(@Id id: String, groupRoleAccess: Set[GroupRoleAccess]) extends AclTemplate(id) with Serializable
```

I added a test case and tried saving an object like this

```
@Inject
var aclTemplateRepository: AclTemplateRepository = _
aclTemplateRepository.save(aclTemplate.head)
```

The error says 

```
NoId complained about com.java.sample.acl.GroupACLTemplate. : No field is annotated with @Id; but it is required
```

Am I missing something here?

**Comment by evanchooly** [comment]
[Source](https://stackoverflow.com/questions/38246647/morphia-does-not-recognize-my-id-annotated-field)

**Comment by evanchooly** [comment]
Looks like this was self-solved.
