### ISSUE TITLE
WriteResult reports incorrect results for $pull array element operation

### ISSUE THREAD

**Issue by JamesDunne** [MorphiaOrg/morphia#987]
Morphia reports incorrect results for `$pull` array element operation in `WriteResult` because it uses older mongo client classes (`DB`, `DBCollection` etc.). The translation layer in the older mongo client classes is incorrect for `$pull` results. Please migrate Morphia to use the newer client classes (`MongoDatabase`, `MongoCollection`, etc.).

MongoDB shell 3.2.8 reports the following for a simple `$pull` array element operation (i.e. delete element from array where matching):

```
> db.coll.update({"opaqueId":{ $regex: /^ID$/i }},{"$pull":{"fromArray":{"whereId":"arrayElementId"}}})
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 0 })
```

Morphia 1.2.1 issuing the same command programmatically:

```
AdvancedDatastore datastore;
UpdateResults deleteResults = datastore.update(
  datastore.createQuery(DumbColl.class)
           .field("opaqueId").equalIgnoreCase("ID"),
  // Pull array element out by "type":
  datastore.createUpdateOperations(
    DumbColl.class,
    new BasicDBObject(
      "$pull",
      new BasicDBObject(
        "fromArray",
        new BasicDBObject("whereId", "arrayElementId")
      )
    )
  )
);
```

returns `UpdateResults` with `WriteConcern` having `n = 1` despite `nModified` being `0` (i.e. the array element did not exist to be deleted). The translation layer in the older mongo client classes does not consider `nModified` when calculating `n`.

**Comment by evanchooly** [comment]
This all should work.  I'm not aware of any issues with this bit of code.  Can extract a test case?  or some sample data and I can extrapolate from what you have here.  Also, there are `remove()` and `removeAll()` on `UpdateOperations` that might simplify your code.

**Comment by JamesDunne** [comment]
You can replicate on the simplest model, example below.

The error occurs when the array element to $pull does not exist. MongoDB shell correctly reports nModified as 0 but the mongo driver's WriteResult incorrectly reports 1 because it reads nMatched as 1 (ignoring nModified).

```
public class DumbColl {
  private String opaqueId;
  private List<DumbArrayElement> fromArray;
}
public class DumbArrayElement {
  private String whereId;
}
```

In mongo shell, create a single document with a single array element in `fromArray` first with a known `whereId` "key" to remove. Then run the update command:

```
AdvancedDatastore datastore;
UpdateResults deleteResults = datastore.update(
  datastore.createQuery(DumbColl.class)
           .field("opaqueId").equalIgnoreCase("ID"),
  // Pull array element out by "type":
  datastore.createUpdateOperations(
    DumbColl.class,
    new BasicDBObject(
      "$pull",
      new BasicDBObject(
        "fromArray",
        new BasicDBObject("whereId", "arrayElementId")
      )
    )
  )
);
```

and check the `UpdateResults`.

**Comment by evanchooly** [comment]
You're wanting the nModified value, but DBCollection only provides nMatched (which is what ’n’ always meant in getlasterror.  This is an [open ticket](https://jira.mongodb.org/browse/JAVA-1193) against this very thing.  So while Morphia is still on the legacy API, this will continue to be an issue.

I'd love to migrate Morphia to the newer API but that's a bigger and longer term issue than just this one area.  My current focus is wrapping up 1.3 and then turning my focus to 2.0 where larger changes like this one can be done.  I'm trying to make *that* happen as quickly as I can.

**Comment by evanchooly** [comment]
closing due to age.
