### ISSUE TITLE
Add support for $count aggregation stage

### ISSUE THREAD

**Issue by evanchooly** [MorphiaOrg/morphia#998]
[JAVA-2277](https://jira.mongodb.org/browse/JAVA-2277)

**Comment by email2liyang** [comment]
@evanchooly  any update on this? thanks

**Comment by evanchooly** [comment]
I left the company some months back and no longer have write access to this repository.  i can fork and submit a PR but I just haven't had the time.

**Comment by jyemin** [comment]
The $count stage is just syntactic sugar for:

    {$group:{_id:null, count:{$sum:1}}}

so you should be able to accomplish this with the existing aggregation support in Morphia.  See http://mongodb.github.io/morphia/1.3/guides/aggregation/ to get you started.

**Comment by email2liyang** [comment]
it works well, thanks!
